apache/brooklyn-server

core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, rest/rest-client/pom.xml, rest/rest-client/src/main/java/org/apache/brooklyn/rest/client/BrooklynApiUtil.java, rest/rest-client/src/test/java/org/apache/brooklyn/rest/client/BrooklynApiUtilTest.java
Useful methods for working with the Brooklyn API programatically.
Borne out of experiences with `brooklyn-maven-plugin` and `brooklyn-tosca`.
=> Brooklyn API utilities

core/src/main/java/org/apache/brooklyn/util/core/crypto/FluentKeySigner.java
- md5 use with certs has been disabled by default in Java 8u71+
- http://www.oracle.com/technetwork/java/javase/8u71-relnotes-2773756.html
self-signed certs generated by brooklyn observed to work in Chrome 48/Safari 9.0.3/Firefox 44 on OSX 10.11.3
```
Signature Algorithm: SHA-256 with RSA Encryption ( 1.2.840.113549.1.1.11 )
```
=> change cert signature hashing algorithm from md5 to sha256

launcher/src/main/java/org/apache/brooklyn/launcher/BrooklynLauncher.java, launcher/src/main/java/org/apache/brooklyn/launcher/BrooklynWebServer.java, launcher/src/main/java/org/apache/brooklyn/launcher/WebAppContextProvider.java
`WebAppContexts` for things running alongside `brooklyn.war` can be configured externally. This can be used to configure JSP support in certain contexts.
=> Inject WebAppContexts into BrooklynWebServer

core/src/main/java/org/apache/brooklyn/core/sensor/DurationSinceSensor.java, core/src/main/java/org/apache/brooklyn/core/sensor/http/HttpRequestSensor.java, core/src/test/java/org/apache/brooklyn/core/sensor/DurationSinceSensorTest.java, launcher/src/main/java/org/apache/brooklyn/launcher/WebAppContextProvider.java, policy/src/main/java/org/apache/brooklyn/policy/action/StopAfterDurationPolicy.java, policy/src/test/java/org/apache/brooklyn/policy/action/StopAfterDurationPolicyTest.java, utils/common/src/main/java/org/apache/brooklyn/util/time/Duration.java
Aka "the money saver".
`DurationSinceSensor` records the duration since it as added to an entity.
`StopAfterDurationPolicy` waits for an entity to reach a lifecycle, adds a duration-since sensor to it, waits for the duration to be greater than the configured lifetime, then stops the entity.
=> Add policy to stop applications after a period has elapsed

parent/pom.xml, software/base/pom.xml, software/winrm/pom.xml
Depends on org.slf4j 1.7.12 (via org.apache.cxf), whereas Brooklyn depends on 1.6.6
=> winrm4j: exclude slf4j transitive dependency

launcher/src/main/java/org/apache/brooklyn/launcher/BrooklynWebServer.java
wars passed to BrooklynLauncher get their context path stripped of the leading "/", resulting in empty string for root apps. The web server expects a "/" context path for a root war so it uses the default war instead.
/cc @sjcorbett
=> Pick up root wars when passed to BrooklynLauncher

core/src/main/java/org/apache/brooklyn/location/byon/ByonLocationResolver.java
Workaround for setting default winrm port for a Windows BYON location.
@aledsage can you review?
=> Fix WinRM default port for a BYON location

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/SpecParameterUnwrappingTest.java, core/src/main/java/org/apache/brooklyn/core/entity/AbstractApplication.java, core/src/main/java/org/apache/brooklyn/core/entity/StartableApplication.java, core/src/test/java/org/apache/brooklyn/entity/stock/BasicStartableTest.java
should fix https://issues.apache.org/jira/browse/BROOKLYN-203 and BasicStartableTest.testTransitionsThroughLifecycles (https://builds.apache.org/job/brooklyn-master-build/16/console) failure
=> Make destroy on stop configurable for apps

core/src/main/java/org/apache/brooklyn/core/mgmt/persist/BrooklynMementoPersisterToObjectStore.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/PeriodicDeltaChangeListener.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindCatalogItemTest.java
the persists and deletions run simultaneously; now, don't write things which are deleted.
also suppress the immediate delta write that was previously being done;
this may impact tests if there relying on an immediate checkpoint, but that's a bad test,
for in normal operation checkpointing should be started when the mgmt node starts and there should be nothing to persist.
if we support turning on persistence later that should trigger a full write not a delta write.
=> BROOKLYN-231 fix race where updating and deleting can cause deleted item not to be deleted

pom.xml, software/winrm/src/main/java/org/apache/brooklyn/location/winrm/WinRmMachineLocation.java, software/winrm/src/main/java/org/apache/brooklyn/util/core/internal/winrm/WinRmTool.java, software/winrm/src/main/java/org/apache/brooklyn/util/core/internal/winrm/winrm4j/Winrm4jTool.java
* Configurable  operationTimeout. 1 minute by default as the new winrm4j does regular status polling when a command is executed.
* WinRM set default execTries
This enables easier debugging and immidiate feedback when a problem occurs.
=> WinRM operationTimeout parameter

core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessSshDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/VanillaSoftwareProcessSshDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/lifecycle/MachineLifecycleEffectorTasks.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/lifecycle/ScriptHelper.java
the only vaguely interesting items:
* make `INSTALL_DIR` avail as a shell env var when doing customize and launch
* make `MachineInitTasks` transient, in case the outer class is ever serialized (it shouldn't be but it seems that it is)
=> minor code cleanup

software/base/src/test/java/org/apache/brooklyn/feed/jmx/JmxFeedTest.java, software/base/src/test/java/org/apache/brooklyn/feed/jmx/JmxHelperTest.java, software/base/src/test/java/org/apache/brooklyn/feed/jmx/RebindJmxFeedTest.java, utils/common/src/main/java/org/apache/brooklyn/test/http/TestHttpServer.java
see if this fixes failed PR builds on `ubuntu-us-1` eg as described at #47
=> for local address when used in tests, ports not contactable on some build machines; try loop back instead

core/src/main/java/org/apache/brooklyn/core/mgmt/persist/UnwantedStateLoggingMapper.java, core/src/main/java/org/apache/brooklyn/core/mgmt/persist/XmlMementoSerializer.java, core/src/test/java/org/apache/brooklyn/core/mgmt/persist/BrooklynMementoPersisterInMemorySizeIntegrationTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessPersisterInMemorySizeIntegrationTest.java
Certain types of objects could bring a lot of unwanted baggage with them when serialized.
* Check and warn if such objects are serialized
* Test that serializing SoftwareProcessDriverLifecycleEffectorTasks and MachineInitTasks is lean, doesn't lead to OOME
=> Make sure no unwanted state is serialized

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/SpecParameterUnwrappingTest.java, core/src/main/java/org/apache/brooklyn/core/config/ConfigKeys.java, core/src/main/java/org/apache/brooklyn/core/entity/AbstractApplication.java, core/src/main/java/org/apache/brooklyn/core/entity/StartableApplication.java, core/src/main/java/org/apache/brooklyn/entity/stock/BasicApplicationImpl.java, core/src/main/java/org/apache/brooklyn/entity/stock/BasicEntityImpl.java, core/src/main/java/org/apache/brooklyn/entity/stock/BasicStartable.java, core/src/main/java/org/apache/brooklyn/entity/stock/BasicStartableImpl.java, software/base/src/main/java/org/apache/brooklyn/entity/brooklynnode/BrooklynNodeSshDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessSshDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessWinRmDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/SoftwareProcess.java
Allows groups of components and applications to have their startup sequence controlled more easily. This includes only setting `service.isUp` to `true` on an `AbstractApplication` once it, and its children, have started. This is the same semantics as other entities, and allows a more consistent blueprint style.
Also reverts https://github.com/apache/brooklyn-server/commit/d7c3759a150f409d1674fdaf74117404d56a665d which prevents Clocker from re-using images.
=> Added start latch to BasicStartable and StartableApplication

locations/jclouds/pom.xml, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsSshMachineLocation.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsAddressesLiveTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/RebindJcloudsLocationLiveTest.java
* don't initialize hostname directly from the node
* correct lazy hostname initialization logic
According to [this comment](
https://github.com/apache/brooklyn-server/blob/master/locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsSshMachineLocation.java#L280-L283) we shouldn’t use `node.getHostname()`. But in practice that’s exactly what happens, because `hostname` is [initialized here]( 
https://github.com/apache/brooklyn-server/blob/master/locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsSshMachineLocation.java#L200) which is called both on location init and rebind.
=> Fix hostname resolving for jclouds locations

software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessPersisterInMemorySizeIntegrationTest.java
Seen a failure where 153397 bytes were written, increase maximum. The test is not deterministic.
=> Fix SoftwareProcessPersisterInMemorySizeIntegrationTest

launcher-common/src/test/java/org/apache/brooklyn/launcher/common/BrooklynPropertiesFactoryHelperTest.java
Windows doesn't support the expected file attributes, disable tests.
because of https://builds.apache.org/view/Brooklyn/job/brooklyn-master-windows/10
=> Disable tests on Windows

core/src/main/java/org/apache/brooklyn/core/entity/lifecycle/ServiceStateLogic.java, core/src/main/java/org/apache/brooklyn/enricher/stock/AbstractMultipleSensorAggregator.java
This is useful for apps that want to override the 
ComputeServiceIndicatorsFromChildrenAndMembers. For example, in 
clocker the app’s health depends on just two of the children (rather 
than all/one or quorum).
=> multi-sensor-aggregator: respect the EntityFilter

core/src/main/java/org/apache/brooklyn/core/location/BasicLocationRegistry.java, core/src/main/java/org/apache/brooklyn/location/localhost/LocalhostLocationResolver.java, core/src/test/java/org/apache/brooklyn/core/location/LocationRegistryTest.java, rest/rest-client/src/test/java/org/apache/brooklyn/rest/client/ApplicationResourceIntegrationTest.java, rest/rest-client/src/test/java/org/apache/brooklyn/rest/client/BrooklynApiRestClientTest.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/testing/BrooklynRestApiTest.java, rest/rest-server-jersey/src/test/java/org/apache/brooklyn/rest/testing/BrooklynRestApiTest.java
the location-add-wizard which @tbouron is working on will make it easy for users to do this, and there is no reason `localhost` should be added specially (and good reasons why it shouldn't as it is not representative and it is error-prone!)
i suggest this be tested and reviewed as part of @tbouron's WIP, and merged only at the same time as his.  (if this lands in time for 090 great but not needed.  probably confusing for a user to merge this PR without the wizard.)
we should also update the release notes with something like the following explaining the compatibility break:
```
6. The named location `localhost` is no longer automatically added by default on a fresh Brooklyn install.
Instead UI users are directed to a location wizard where they can configure their targets, including …
```
=> does not create a localhost named location automatically

core/src/main/java/org/apache/brooklyn/location/ssh/SshMachineLocation.java
Previously if a temporary location was created (i.e. using 
CREATE_UNMANAGED=true) then the cleanup task would execute immediately
and would close the ssh-connections-pool (potentially while the other 
thread tried to execute something).
=> Fix SshMachineLocation cleanup

software/base/src/main/java/org/apache/brooklyn/entity/software/base/SoftwareProcessImpl.java
Previously we'd collect the not-up-diagnostics when starting, even though we didn't expect the Entity to be up yet. Now we only call it when there is a genuine problem that would result in the entity being "on-fire".
=> NotUpDiagnostics: don’t collect if starting && !up

core/src/main/java/org/apache/brooklyn/core/location/AbstractLocation.java, core/src/main/java/org/apache/brooklyn/core/location/dynamic/DynamicLocation.java, core/src/main/java/org/apache/brooklyn/core/location/dynamic/LocationOwner.java, core/src/main/java/org/apache/brooklyn/core/mgmt/persist/XmlMementoSerializer.java, core/src/main/java/org/apache/brooklyn/core/objs/proxy/InternalLocationFactory.java, core/src/main/java/org/apache/brooklyn/util/core/task/BasicTask.java, core/src/test/java/org/apache/brooklyn/core/effector/EffectorBasicTest.java, software/base/src/main/java/org/apache/brooklyn/entity/machine/pool/ServerPool.java, software/base/src/main/java/org/apache/brooklyn/entity/machine/pool/ServerPoolImpl.java, software/base/src/main/java/org/apache/brooklyn/entity/machine/pool/ServerPoolLocation.java, software/base/src/main/java/org/apache/brooklyn/entity/machine/pool/ServerPoolLocationResolver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/SoftwareProcessImpl.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/clocker/ClockerDynamicLocationPatternRebindTest.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/clocker/ClockerDynamicLocationPatternTest.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/clocker/StubAttributes.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/clocker/StubContainer.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/clocker/StubContainerImpl.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/clocker/StubContainerLocation.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/clocker/StubHost.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/clocker/StubHostImpl.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/clocker/StubHostLocation.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/clocker/StubInfrastructure.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/clocker/StubInfrastructureImpl.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/clocker/StubInfrastructureLocation.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/clocker/StubResolver.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/clocker/StubResolverTest.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/clocker/StubUtils.java, software/base/src/test/java/org/apache/brooklyn/entity/machine/pool/AbstractServerPoolTest.java, software/base/src/test/java/org/apache/brooklyn/entity/machine/pool/ServerPoolLocationResolverTest.java, software/base/src/test/java/org/apache/brooklyn/entity/machine/pool/ServerPoolTest.java
This has (for testing only) a cut-down version of the Clocker entity and location structure, and some tests that it works - especially for rebind. The second commit shows how to fix https://github.com/brooklyncentral/clocker/issues/237, which motivated doing this.
(See javadoc in `StubInfrastructure` for a description of the Clocker code structure that this is testing).
=> Test clocker

api/src/main/java/org/apache/brooklyn/api/internal/AbstractBrooklynObjectSpec.java, core/src/main/java/org/apache/brooklyn/core/mgmt/persist/XmlMementoSerializer.java, core/src/test/java/org/apache/brooklyn/core/mgmt/persist/XmlMementoSerializerTest.java
As per @neykov 's comments in PR #59
=> XML SpecResolver: use context instead of thread-local storage

core/src/main/java/org/apache/brooklyn/core/objs/BasicSpecParameter.java
Support old-style persisted state, by implementing readResolve()
=> BasicSpecParameter: fix compatibility of persisted state

parent/pom.xml
When passed `-PIntegration` tests jars are not getting built on purpose. This causes build failures down the road where the missing tests-jar is a dependency in another module.
Initially introduced in https://github.com/apache/incubator-brooklyn/commit/dbda0be45531ba20085c1d082430b44aaca55231?w=1 without any details on why it's needed.
=> Don't skip tests jar generation during tests

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/EntitiesYamlTest.java, core/src/main/resources/org/apache/brooklyn/core/mgmt/persist/deserializingClassRenames.properties, core/src/test/java/org/apache/brooklyn/core/entity/hello/LocalEntitiesTest.java, core/src/test/java/org/apache/brooklyn/core/test/entity/TestEntity.java, core/src/test/java/org/apache/brooklyn/util/core/task/CompoundTaskExecutionTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/provider/AbstractJcloudsLocationTest.java, pom.xml, software/base/src/main/java/org/apache/brooklyn/entity/software/base/SoftwareProcessDriverLifecycleEffectorTasks.java, software/base/src/test/java/org/apache/brooklyn/feed/jmx/JmxFeedTest.java, software/base/src/test/java/org/apache/brooklyn/feed/jmx/JmxHelperTest.java
Also see the commit "softwareProcess.restart: even on error, set expected=running", and the details in that commit description.
=> Winrm4j upgrade

core/src/main/java/org/apache/brooklyn/util/core/osgi/Osgis.java
Without this change, if the predicate fails, the code flow just picks the next predicate to check,
when really we want to skip to checking the next bundle.
=> Skip to next bundle on predicate failure.

pom.xml, software/winrm/src/main/java/org/apache/brooklyn/location/winrm/WinRmMachineLocation.java, software/winrm/src/main/java/org/apache/brooklyn/util/core/internal/winrm/WinRmTool.java, software/winrm/src/main/java/org/apache/brooklyn/util/core/internal/winrm/winrm4j/Winrm4jTool.java
For some networks retries could be useful if user is able to configure high number of tries for connection failures.
Requires publishing new version of winrm4j.
=> WinRM Parametrize number of retries of network failures

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/softlayer/SoftLayerSameVlanLocationCustomizer.java
Builds on code from https://github.com/brooklyncentral/clocker/pull/138 to create a `JcloudsLocationCustomizer` that can be used to ensure all VMs in a specific application or other scope are created on the same VLAN. Use by configuring `customizers` on the location with an instance of this class.
=> SoftLayer VLAN customizer

karaf/itest/pom.xml, karaf/itest/src/test/java/org/apache/brooklyn/AssemblyTest.java, karaf/itest/src/test/java/org/apache/brooklyn/KarafTestUtils.java, karaf/itest/src/test/java/org/apache/brooklyn/rest/BrooklynRestApiLauncherTest.java, karaf/itest/src/test/java/org/apache/brooklyn/security/CustomSecurityProvider.java, karaf/itest/src/test/java/org/apache/brooklyn/security/CustomSecurityProviderTest.java, karaf/itest/src/test/java/org/apache/brooklyn/security/StockSecurityProviderTest.java, karaf/itest/src/test/java/org/apache/brooklyn/test/IntegrationTest.java, karaf/itest/src/test/resources/custom-security-bp.xml, karaf/pom.xml, rest/rest-resources/pom.xml, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/security/jaas/BrooklynLoginModule.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/security/jaas/ManagementContextHolder.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/security/jaas/SecurityProviderHttpSession.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/security/provider/DelegatingSecurityProvider.java, rest/rest-resources/src/main/resources/OSGI-INF/blueprint/service.xml, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/security/jaas/BrooklynLoginModuleTest.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/security/jaas/TestCallbackHandler.java
Depends on #15.
An implementation of a JAAS LoginModule, delegating to the SecurityProvider configured in brooklyn.properties. Used as the authentication mechanism for the REST API when running in Karaf.
Currently configured as a separate realm, used only for web.
=> [OSGi] JAAS LoginModule delegating to Brooklyn's SecurityProviders 

core/src/test/java/org/apache/brooklyn/core/mgmt/osgi/OsgiVersionMoreEntityTest.java, karaf/features/src/main/feature/feature.xml, pom.xml, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/util/ScannerInjectHelper.java, rest/rest-resources/src/main/resources/OSGI-INF/blueprint/service.xml, rest/rest-server-jersey/pom.xml, utils/rest-swagger/pom.xml, utils/rest-swagger/src/main/java/org/apache/brooklyn/rest/apidoc/RestApiResourceScanner.java
~~Note that this PR bumps the guava version, so might need wider community discussion!~~
=> [OSGi] Enable Swagger

core/src/main/java/org/apache/brooklyn/core/mgmt/ha/OsgiManager.java, core/src/main/java/org/apache/brooklyn/util/core/osgi/ContainerFramework.java, core/src/main/java/org/apache/brooklyn/util/core/osgi/Osgis.java, core/src/main/java/org/apache/brooklyn/util/core/osgi/SystemFrameworkLoader.java, core/src/main/resources/OSGI-INF/blueprint/blueprint.xml, core/src/test/java/org/apache/brooklyn/core/mgmt/osgi/OsgiStandaloneTest.java, karaf/features/src/main/feature/feature.xml, pom.xml, utils/common/src/main/java/org/apache/brooklyn/util/osgi/SystemFramework.java, utils/rt-felix/src/main/java/org/apache/brooklyn/rt/felix/EmbeddedFelixFramework.java, utils/rt-felix/src/main/java/org/apache/brooklyn/rt/felix/EmbeddedFramework.java, utils/rt-felix/src/main/resources/META-INF/services/org.apache.brooklyn.util.osgi.SystemFramework
Needs different implementations depending on whether running in Karaf or classical. Can't have EmbeddedFelixFramework loaded in Karaf because felix bundle doesn't export org.apache.framework packages, just generic OSGi ones.
Needs to be rebased on master after merging #65  for a successful build.
=> [OSGi] Make EmbeddedFelixFramework pluggable

karaf/init/pom.xml, karaf/init/src/main/java/org/apache/brooklyn/launcher/osgi/OsgiLauncher.java
Replicate classical launcher behaviour. Note that when accessing from localhost username will still be requested, but will accept any provider.
=> [OSGi] Generate random password if no security provider configured

core/src/main/java/org/apache/brooklyn/core/mgmt/persist/XmlMementoSerializer.java, core/src/main/java/org/apache/brooklyn/location/localhost/LocalhostMachineProvisioningLocation.java
When running `org.apache.brooklyn.qa.load.LoadTest`, I hit exceptions about serializing localhost machine location. I didn't try rebinding, but I presume the localhost machine's location object would not have been deserialised correctly (or not been available at all).
This PR fixes the two exceptions I hit.
=> Fix persisting localhost

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/CampInternalUtils.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlLocationTest.java
Fixes [BROOKLYN-246](https://issues.apache.org/jira/browse/BROOKLYN-246)
Was failing for byon locations where the host wasn't specified in the type.
For example the byon catalog location as shown in `testByonLocationHostsInConfig` had been failing due to `extractConfig` in the `ByonLocationResolver` throwing an `IllegalArgumentException` as no hosts were found.
=> pass brooklynConfig when making call to getLocationSpec

rest/rest-api/src/main/java/org/apache/brooklyn/rest/domain/LocationSpec.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/transform/LocationTransformer.java
LocationConfig contains null values which Guava's ImmutableMap rejects with a NullPointerException.
This fixes an error observed when deploying the "Template 1: Server" sample to localhost then running `br application <id>` with the CLI. The output from the CLI was "500 Server Error". The server logs contained:
```
java.lang.NullPointerException: null value in entry: byon.machineSpecs=null
at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33) ~[com.google.guava-guava-16.0.1.jar:na]
at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:135) ~[com.google.guava-guava-16.0.1.jar:na]
at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:206) ~[com.google.guava-guava-16.0.1.jar:na]
at …
```
=> Rest API location transformers use mutable map

server-cli/src/main/resources/brooklyn/default.catalog.bom, server-cli/src/main/resources/catalog.bom
When I use a "Template 2: Bash Web Server" with non-root user and password-less sudo, I've got a error because I don't have any python installed. We should use sudo command for installing python.
=> Fixed command for installing python via apt-get and yum by using sudo

core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogBomScanner.java, karaf/init/src/main/resources/OSGI-INF/blueprint/blueprint.xml
This change follows on from https://github.com/apache/brooklyn-server/pull/80.
With this change any catalog members that were added by scanning the bundle's
catalog.bom when the bundle started will be removed upon stopping the bundle.
=> Support removal of catalog entries from bundle BOM when the bundle is stopped.

core/src/main/java/org/apache/brooklyn/core/mgmt/entitlement/EntitlementManagerAdapter.java, core/src/main/java/org/apache/brooklyn/core/mgmt/entitlement/Entitlements.java, core/src/main/java/org/apache/brooklyn/core/mgmt/entitlement/PerUserEntitlementManager.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/ScriptApi.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ScriptResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ServerResource.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/entitlement/AbstractRestApiEntitlementsTest.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/entitlement/ActivityApiEntitlementsTest.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/entitlement/EntityConfigApiEntitlementsTest.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/entitlement/ScriptApiEntitlementsTest.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/entitlement/SensorApiEntitlementsTest.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/entitlement/ServerApiEntitlementsTest.java
`PerUserEntitlementManager` transforms the "user" keyword into an entitlement to everything but the most privileged actions (everything but `ROOT` and `SEE_ALL_SERVER_INFO`). Practically this means a user can do everything but: use `ScriptApi` to run any Groovy, stop the server, access management context configuration via `ServerApi`, reload Brooklyn properties and export persistence data.
I wasn't sure about the choice of "user" for the keyword. I wanted to indicate that it was a step down from "root". Other ideas people gave me include "manager" and "administrator", neither of which are hugely satisfactory to me. Suggestions welcome.
=> New PerUserEntitlementManager keyword: user

utils/common/src/main/java/org/apache/brooklyn/util/net/Networking.java, utils/common/src/test/java/org/apache/brooklyn/util/net/NetworkingUtilsTest.java
IP addresses with octets greater than 127 should be parsed as unsigned bytes, to prevent them being displayed with negative numbers.
=> Fix conversion of unsigned bytes to IP addresses

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/BrooklynCampPlatformLauncherAbstract.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AbstractYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ReferencedYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogOsgiVersionMoreEntityTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlAppTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlEntityTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlLocationTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlPolicyTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlTemplateTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/SpecParameterParsingTest.java
Speeds tests up a lot. Subclasses can enable OSGi by overriding `disableOsgi`.
Build of `camp-brooklyn` took 2:38 before and 1:40 afterwards on my relatively snappy laptop. The improvement should be more noticeable in Jenkins builds.
=> Use minimal management context in AbstractYamlTest

utils/common/src/main/java/org/apache/brooklyn/util/ssh/BashCommands.java
Deprecate `BashCommands.ifExecutableElse(String, List, List)` misleading name.
=> Deprecate BashCommands.ifExecutableElse(String, List, List)

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/transform/LocationTransformer.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/LocationResourceTest.java
Untyped config from the YAML is being pushed into flags rather than config, so rather than expose flags in the locations API (which we're moving away from to the catalog API), I'm now checking for the presence of a displayName parameter in flags and setting it in the LocationTransformer.
Tests added.
=> pull displayName from flags in LocationTransformer if present - fixes BROOKLYN-250

core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/RebindManagerImpl.java
Fixes issue where `forcePeristNow()` fails due to `persistenceRealChangeListener` being null
=> Fix NPE in forcePersistNow

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/AbstractJcloudsStubbedLiveTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsImageChoiceStubbedLiveTest.java
Fixes https://issues.apache.org/jira/browse/BROOKLYN-257.
To fix this, I was tempted to instead change `JcloudsLocation.buildTemplate` so that it ignored all null values, changing the code below:
```
for (Map.Entry<ConfigKey<?>, CustomizeTemplateBuilder> entry : SUPPORTED_TEMPLATE_BUILDER_PROPERTIES.entrySet()) {
ConfigKey<?> name = entry.getKey();
CustomizeTemplateBuilder code = entry.getValue();
if (config.containsKey(name))
code.apply(templateBuilder, config, config.get(name));
}
```
to:
```
for (Map.Entry<ConfigKey<?>, CustomizeTemplateBuilder> entry : SUPPORTED_TEMPLATE_BUILDER_PROPERTIES.entrySet()) {
ConfigKey<?> name = entry.getKey();
CustomizeTemplateBuilder code = entry.getValue();
if (config.containsKey(name) && config.get(name) != null)
code.apply(templateBuilder, config, …
```
=> BROOKLYN-257: allow nulling imageId in jcloudsLocation.obtain()

core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogBomScanner.java, core/src/main/resources/catalog.bom, karaf/apache-brooklyn/src/main/resources/etc/org.apache.brooklyn.core.catalog.bomscanner.cfg, karaf/init/src/main/resources/OSGI-INF/blueprint/blueprint.xml, karaf/itest/src/test/java/org/apache/brooklyn/core/catalog/internal/CatalogBomScannerTest.java, policy/src/main/resources/catalog.bom, server-cli/src/main/resources/catalog.bom, software/base/src/main/resources/catalog.bom, test-framework/src/main/resources/catalog.bom, utils/common/dependencies/osgi/entities/src/main/resources/catalog.bom, utils/common/dependencies/osgi/more-entities-v1/src/main/resources/catalog.bom, utils/common/dependencies/osgi/more-entities-v2-evil-twin/src/main/resources/catalog.bom, utils/common/dependencies/osgi/more-entities-v2/src/main/resources/catalog.bom, utils/common/src/main/java/org/apache/brooklyn/util/text/Strings.java, utils/common/src/test/java/org/apache/brooklyn/util/text/StringsTest.java
Note this PR depends on https://github.com/apache/brooklyn-server/pull/100 and should be merged after it.
It is desirable to have a config time mechanism to control what
bundles are allowed to present applications in the catalog and
what aren't.
This change adds a white/blacklist mechanism to the catalog.bom
bundle scanning. Each list takes the form of a CSV whitelist of
regexes to match against bundle symbolic ids.  A bundle will be
allowed to add an application (template) to the catalog if its
bundle id matches one of the regexes on the whitelist, and also
does not match one of the regexes on the blacklist.
The configuration keys and default values for the lists are:
brooklyn.catalog.osgi.application.whitelist=.*
brooklyn.catalog.osgi.application.blacklist=
(i.e. by default accept all …
=> Add catalog.bom application white/blacklists.

core/src/main/java/org/apache/brooklyn/core/server/BrooklynServerPaths.java, launcher/src/main/java/org/apache/brooklyn/launcher/BrooklynLauncher.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessDriver.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessSshDriverIntegrationTest.java, utils/common/src/main/java/org/apache/brooklyn/util/os/Os.java, utils/common/src/test/java/org/apache/brooklyn/util/os/OsTest.java
So blueprint writers can replace
```yaml
runtimeTemplates:
/path/to/source1: dest1
/path/to/source2: dest2
...
/path/to/sourceN: destN
```
With
```yaml
runtimeTemplates:
/path/to: dest
```
One minor difference: in the first example the two files end up in `runDir/` but in the second in `runDir/dest/`. If using the latter syntax I think this would be expected.
Each file is copied in a task so there's better visibility of what is in progress at any given point.
=> Driver copyResources walks the filesystem 

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, software/winrm/src/main/java/org/apache/brooklyn/location/winrm/WinRmMachineLocation.java
The problem this PR tries to solve is that In some clouds a restart could happen on a Windows Host 2 minutes after it is provisioned. This could be because of System Upgrade or other.
What particularly I experience is that this Blueprint fail:
```yaml
services:
type: org.apache.brooklyn.entity.software.base.VanillaWindowsProcess
pre.install.command: echo preInstallCommand
install.command: echo installCommand > C:\\install.txt
post.install.command: echo postInstallCommand
customize.command: echo customizeCommand
pre.launch.command: echo preLaunchCommand
launch.powershell.command: |
Start-Sleep -s 400
Write-Host Test Completed
post.launch.command: echo postLaunchCommand
checkRunning.command: echo checkRunningCommand
stop.command: echo stopCommand
```
When I login on the …
=> Wait to start windows parameter.

core/src/main/java/org/apache/brooklyn/core/internal/BrooklynProperties.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/LocalManagementContext.java, core/src/test/java/org/apache/brooklyn/core/config/BrooklynPropertiesBuilderTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/internal/LocalManagementContextTest.java, karaf/init/pom.xml, karaf/init/src/main/java/org/apache/brooklyn/launcher/osgi/ConfigSupplier.java, karaf/init/src/main/java/org/apache/brooklyn/launcher/osgi/OsgiLauncher.java, karaf/init/src/main/resources/OSGI-INF/blueprint/blueprint.xml, karaf/itest/src/test/java/org/apache/brooklyn/launcher/osgi/OsgiLauncherTest.java, launcher-common/src/main/java/org/apache/brooklyn/launcher/common/BrooklynPropertiesFactoryHelper.java, pom.xml
Load properties from:
* global brooklyn.properties
* local properties
* config admin's brooklyn PID
It's a one-way integration where changes in config admin will cause reloading the properties in brooklyn. Setting properties programmatically in brooklyn will not update config admin.
--
Since we are relying on config admin to read the configuration (which could be coming from multiple places) there's no check on the security attributes of the source.
=> [OSGi] Load properties from config admin

karaf/apache-brooklyn/pom.xml, karaf/commands/pom.xml, karaf/commands/src/main/java/org/apache/brooklyn/karaf/commands/cloud/explorer/AbstractCloudExplorerCommand.java, karaf/commands/src/main/java/org/apache/brooklyn/karaf/commands/cloud/explorer/BlobCommand.java, karaf/commands/src/main/java/org/apache/brooklyn/karaf/commands/cloud/explorer/DefaultTemplateCommand.java, karaf/commands/src/main/java/org/apache/brooklyn/karaf/commands/cloud/explorer/GetImageCommand.java, karaf/commands/src/main/java/org/apache/brooklyn/karaf/commands/cloud/explorer/ListContainerCommand.java, karaf/commands/src/main/java/org/apache/brooklyn/karaf/commands/cloud/explorer/ListContainersCommand.java, karaf/commands/src/main/java/org/apache/brooklyn/karaf/commands/cloud/explorer/ListHardwareProfilesCommand.java, karaf/commands/src/main/java/org/apache/brooklyn/karaf/commands/cloud/explorer/ListImagesCommand.java, karaf/commands/src/main/java/org/apache/brooklyn/karaf/commands/cloud/explorer/ListInstancesCommand.java, karaf/commands/src/main/java/org/apache/brooklyn/karaf/commands/cloud/explorer/TerminateInstancesCommand.java, karaf/pom.xml, launcher-common/pom.xml, launcher-common/src/main/java/org/apache/brooklyn/launcher/command/support/CloudExplorerSupport.java, server-cli/src/main/java/org/apache/brooklyn/cli/CloudExplorer.java
Refactors the CloudExplorer class into a core CloudExplorerSupport class
that does the work without knowing about any command line functionality,
plus a smaller CloudExplorer that does the command line handling and
invokes the CloudExplorerSupport to do the work.
Adds Karaf commands with the same names that use Karaf's command line
support to invoke the CloudExplorerSupport.
Adds the Karaf commands bundle as a boot feature so the commands are
readily available on startup.
=> Add Karaf equivalents of cloud commands.

software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/clocker/ClockerDynamicLocationPatternTest.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/clocker/StubHostLocation.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/clocker/StubInfrastructureLocation.java
See https://github.com/brooklyncentral/clocker/issues/290
This PR is testing how to fix that in Brooklyn, and to ensure that we continue to support that use-case in clocker.
Note the second commit (update for checkNotNull on rebind) is just to bring this code up-to-date with how Clocker actually does it. It is the first commit that is actually interesting here.
@grkvlt please review.
=> Fix clocker pattern: reload-properties listener

core/src/main/java/org/apache/brooklyn/entity/group/DynamicClusterImpl.java
Fixes `DynamicClusterTest.testServiceUpAfterStartingWithNoMembers`.
It feels like there should be a more general fix to this. But given that the DynamicCluster code is explicitly setting service.isUp to true, then it feels ok to also explicitly say that we know there are no service-not-up-indicators.
=> Fix BROOKLYN-268: DynamicCluster on-fire when initially empty

core/src/main/java/org/apache/brooklyn/core/objs/BasicSpecParameter.java, core/src/main/java/org/apache/brooklyn/enricher/stock/AbstractTransformer.java, core/src/main/java/org/apache/brooklyn/enricher/stock/Transformer.java, core/src/main/java/org/apache/brooklyn/enricher/stock/YamlRollingTimeWindowMeanEnricher.java, core/src/main/java/org/apache/brooklyn/enricher/stock/YamlTimeWeightedDeltaEnricher.java, core/src/test/java/org/apache/brooklyn/enricher/stock/TransformingEnricherTest.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/TestHttpCall.java
Some uses of the transformer want to be triggered by multiple sensor
events (e.g. when they will combine two sensor values). This change
allows us to subscribe to multiple sensors, and to trigger the
evaulation when any of those change.
The sourceSensor is now optional. You can use it in the same way as
previously, or you can use just triggerSensors, or you can combine the
two. If combined, then the triggerSensors will cause us to look up the
latest value of the sourceSensor and synthesise an event as though
the source sensor had just published.
=> Transformer enricher: support triggerSensors

rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/ApplicationResourceTest.java
This broke testDeleteApplicaiton, which had dependsOnMethods=...
that included the now-disabled testFetchApplicationsAndEntity
=> BROOKLYN-272: fix dependsOnMethods in ApplicationResourceTest

pom.xml
- XStream version bumped to 1.4.8 to avoid known bug.
See http://x-stream.github.io/jira/767/
Custom entities that hold serializable lambda expressions fail to rebind with XStream 1.4.7
=> Fix persistence for entities containing Java 8 lambdas

core/src/main/java/org/apache/brooklyn/core/entity/AbstractEntity.java, core/src/main/java/org/apache/brooklyn/core/mgmt/BrooklynTags.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/LocalEntityManager.java, core/src/main/java/org/apache/brooklyn/core/objs/proxy/InternalEntityFactory.java, core/src/test/java/org/apache/brooklyn/core/location/LocationManagementTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsLocationTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/test/location/SoftwareProcessLocationUnmanageTest.java
Only `MachineLocation` locations created by `SoftwareProcess` are unmanaged. Currently there's no owner for `LocationResolver` locations so there's no one to unmanage them.
The changes will mark locations created as part of bringing up a spec as owner by the entity where they are attached. When the entity is unmanaged the locations will be unmanaged as well.
=> Test and fix locations not being unmanaged

core/src/test/java/org/apache/brooklyn/core/sensor/DurationSinceSensorTest.java, policy/src/test/java/org/apache/brooklyn/policy/action/StopAfterDurationPolicyTest.java
Previously test failed in jenkins when asserting state was RUNNING, 
then STOPPED. Unclear if this re-write will fix that (!), but at least
we’ll get more info about what states it was in.
There was another race, which this fixes: the policy might shutdown the entity before we manage to assert it is RUNNING (if we were extremely unlucky with the main thread context switching!).
The failure was in https://builds.apache.org/job/brooklyn-server-pull-requests/org.apache.brooklyn$brooklyn-policy/460/testReport/junit/org.apache.brooklyn.policy.action/StopAfterDurationPolicyTest/testAppStoppedWhenDurationExpires/:
```
2016-05-27 20:39:41,707 INFO  TESTNG INVOKING CONFIGURATION: "Surefire test" - @BeforeMethod org.apache.brooklyn.core.test.BrooklynAppUnitTestSupport.setUp()
2016-05-27 …
```
=> Fix StopAfterDurationPolicyTest

test-framework/src/main/java/org/apache/brooklyn/test/framework/LoopOverGroupMembersTestCaseImpl.java
These minor changes were motivated by a jenkins test failure, when building an unrelated PR branch (https://builds.apache.org/job/brooklyn-server-pull-requests/org.apache.brooklyn$brooklyn-test-framework/463/testReport/junit/org.apache.brooklyn.test.framework/LoopOverGroupMembersTestCaseTest/testMultipleChildrenOneOfWhichFails/).
They will not actually fix the problem!
```
2016-05-28 00:12:23,277 INFO  TESTNG INVOKING CONFIGURATION: "Surefire test" - @BeforeMethod org.apache.brooklyn.test.framework.LoopOverGroupMembersTestCaseTest.setup()
2016-05-28 00:12:23,444 INFO  TESTNG PASSED CONFIGURATION: "Surefire test" - @BeforeMethod org.apache.brooklyn.test.framework.LoopOverGroupMembersTestCaseTest.setup() finished in 167 ms
2016-05-28 00:12:23,445 INFO  TESTNG INVOKING: "Surefire test" - …
```
=> Minor tidy to LoopOverGroupMembersTestCase

core/src/main/java/org/apache/brooklyn/core/objs/AbstractBrooklynObject.java, utils/common/src/main/java/org/apache/brooklyn/util/text/Identifiers.java
Needed to allow use of entity and application ids as part of DNS names, which
are case-insensitive. Extension to 10 characters gives equivalent amount of
randomness, so collision probability is unchanged.
=> Make entity ids lowercase

policy/src/test/java/org/apache/brooklyn/policy/loadbalancing/LoadBalancingPolicyConcurrencyTest.java
Same problem as in https://github.com/apache/brooklyn-server/pull/147
=> [BROOKLYN-272] disable more failing non-deterministic tests

core/src/main/java/org/apache/brooklyn/core/location/AbstractLocationResolver.java, core/src/main/java/org/apache/brooklyn/location/byon/ByonLocationResolver.java, core/src/main/java/org/apache/brooklyn/location/byon/FixedListMachineProvisioningLocation.java, core/src/main/java/org/apache/brooklyn/location/localhost/LocalhostLocationResolver.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsByonLocationResolver.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/AbstractJcloudsStubbedLiveTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsByonLocationResolverAwsLiveTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsByonLocationResolverStubbedRebindTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsByonLocationResolverStubbedTest.java
- Previously, it created locations every time the resolver was called
(even if that was just to query about what it would produce), which
caused us to leak locations.
- Now it defers creating the locations (though doing this with
LocationSpec is not practical because of the relationship between
the JcloudsLocation and the machines)!
- Adds FixedListMachineProvisioningLocation.initialMachinesFactory,
for deferring the machine-lookup until the byon location is really
being created.
=> BROOKLYN-259: Fix JcloudsByonLocationResolver

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/MapReferenceYamlTest.java, core/src/test/java/org/apache/brooklyn/core/config/MapConfigKeyAndFriendsMoreTest.java, core/src/test/java/org/apache/brooklyn/core/config/MapListAndOtherStructuredConfigKeyTest.java, core/src/test/java/org/apache/brooklyn/core/entity/EntityConfigTest.java, core/src/test/java/org/apache/brooklyn/core/test/entity/TestEntity.java, utils/common/src/main/java/org/apache/brooklyn/util/time/Durations.java
Part of #173 - please review + merge here, to decrease the size of PR #173 !
The previous name caused problems because there is also a
“confMapThing” of type MapConfigKey. That has special behaviour,
where it looks up any config with that prefix - so it picked up
any config defined against confMapThing.obj as well.
=> pr173/rename confMapThing.obj

locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/AbstractJcloudsStubbedLiveTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsByonLocationResolverStubbedRebindTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsByonLocationResolverStubbedTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsHardwareProfilesStubbedLiveTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsImageChoiceStubbedLiveTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsRebindStubTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/StubbedComputeServiceRegistry.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/networking/JcloudsPortForwardingStubbedLiveTest.java
Part of #173 - please review + merge here, to decrease the size of PR #173 !
Reason for refactoring is:
1. share the one impl of the stubbed ComputeServiceRegistry (previously we had two)
2. allow that to be re-used by other tests in PR #173, that location's templateOptions config values are correctly merged.
=> pr173: Refactor stubbing of jclouds for tests

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsLocationTest.java
Currently we assume port 22 for ssh unless a
portforwarder has been configured.  This uses the getLoginPort
from nodemetadata to determine the ssh port.
=> Use login port for ssh

utils/common/src/test/java/org/apache/brooklyn/util/text/VersionComparatorTest.java
Simple addition of test to document `-SNAPSHOT` semantic version ordering.
=> Add test for -SNAPSHOT versus other versions

launcher-common/src/main/java/org/apache/brooklyn/launcher/common/BasicLauncher.java, launcher/src/main/java/org/apache/brooklyn/launcher/BrooklynLauncher.java
The properties passed in `getBrooklynPropertiesSupplier` have less precedence than global and local  properties.
=> Let downstream projects pass custom brooklyn properties to Brooklyn

software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessWinRmDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/VanillaWindowsProcess.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/VanillaWindowsProcessWinRmDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/lifecycle/WinRmExecuteHelper.java, software/winrm/src/main/java/org/apache/brooklyn/util/core/internal/winrm/WinRmTool.java, software/winrm/src/main/java/org/apache/brooklyn/util/core/internal/winrm/winrm4j/Winrm4jTool.java
- update the `install.reboot.required` action to use computername when running the install command and the reboot command
- set small and reasonable default value for connection retries of winrm4j client
=> Ability to perform installation on a Windows Blueprint which changes Computer Name and requires reboot

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/LocationExternalConfigYamlTest.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/SoftwareProcessImpl.java
several more tests, including one which failed before the fix -- and of course the fix itself
=> fix for issue where $brooklyn:external refs in provisioning.properties are resolved too early

core/src/main/java/org/apache/brooklyn/core/network/AbstractOnNetworkEnricher.java, core/src/main/java/org/apache/brooklyn/core/network/OnPublicNetworkEnricher.java, core/src/main/java/org/apache/brooklyn/core/network/OnSubnetNetworkEnricher.java, core/src/test/java/org/apache/brooklyn/core/network/OnPublicNetworkEnricherRebindTest.java, core/src/test/java/org/apache/brooklyn/core/network/OnPublicNetworkEnricherTest.java, core/src/test/java/org/apache/brooklyn/core/network/OnSubnetNetworkEnricherTest.java
Some entities publish their endpoint using the public hostname (e.g. `MySqlNode` publishes `datastore.url` using the sensor `host.name`). If trying to connect to it from within the same subnet, this can fail if the public ip/hostname is not accessible.
This topic is covered in the "Working with Multiple Networks" proposal (see dev@brooklyn email thread). That suggests we should use the subnet address in things like the datastore.url. That will likely break things for some of our users. But while we discuss/finalise that proposal...
This enricher allows one to publish another sensor that definitely uses the subnet address. It will publish the sensor as things like `datastore.url.mapping.subnet`.
This is really a temporary solution (hence marking this as `@Beta`).
=> Adds OnSubnetNetworkEnricher

api/src/main/java/org/apache/brooklyn/api/entity/EntitySpec.java, api/src/main/java/org/apache/brooklyn/api/internal/AbstractBrooklynObjectSpec.java, core/src/main/java/org/apache/brooklyn/entity/group/zoneaware/BalancingNodePlacementStrategy.java, core/src/main/java/org/apache/brooklyn/entity/group/zoneaware/ProportionalZoneFailureDetector.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/BrooklynImageChooser.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/ComputeServiceRegistryImpl.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/SoftwareProcessDriverLifecycleEffectorTasks.java
Fixing [BROOKLYN-271](https://issues.apache.org/jira/browse/BROOKLYN-271)
Avoiding object references in catalog ConfigKey cards, for example:
Last picture shows that default value of `softwareProcess.lifecycleTasks` config key does not contain the object hashcode `@XXXXX`. Then, objects `toString` methods are modified to avoid the hashcode.
=> Fix BROOKLYN-271: Avoiding object hashcode in entities' toString.

logging/logback-includes/src/main/resources/brooklyn/logback-logger-excludes.xml
The previous change to “SEVERE” doesn’t work, because that is not a
logbook logging level.
In the stdout of Brooklyn, we were still getting:
10:55:48,833 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.cxf] to DEBUG
With this change, we get:
10:58:19,047 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.cxf] to ERROR
=> Change org.apache.cxf log level to ERROR

core/src/main/java/org/apache/brooklyn/core/mgmt/internal/LocalUsageManager.java, core/src/main/java/org/apache/brooklyn/core/mgmt/usage/LocationUsage.java, core/src/main/java/org/apache/brooklyn/location/ssh/SshMachineLocation.java, core/src/test/java/org/apache/brooklyn/util/core/internal/ssh/RecordingSshTool.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsSshMachineLocation.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/test/core/mgmt/usage/JcloudsLocationUsageTrackingTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/test/core/mgmt/usage/LocationUsageTrackingTest.java
Previously, we sometimes tried to ssh to a VM when it was destroyed to get its metadata. Avoid that!
Also changes the `LocalUsageManager`, to call toMetadataRecord() outside of the mutex.
=> BROOKLYN-299: fix LocationUsage mutex

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsSshMachineLocation.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsSshMachineLocationStubbedLiveTest.java
Previously would throw NPE if privateAddresses was empty.
=> Fix JcloudsSshMachineLocation.getSubnetIp

core/src/main/java/org/apache/brooklyn/util/core/task/ssh/SshTasks.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocationConfig.java
When using the `dontCreateUser` option on locations jclouds initialization won't run which means it won't overwrite `/etc/sudoers` leaving in the defaults. For CentOS that means having `requiretty` enabled. This will lead to all `sudo` calls from Brooklyn failing because we are running without a session.
It becomes even bigger problem because the `installDevUrandom` will fail (silently) and the machine will be unresponsive for no apparent reason.
The changes 
* run the `/etc/sudoers` fix if explicitly requested or if `dontCreateUser` is set.
* convert commands executed during location obtain to tasks so they are visible in the acitivty tab
* fails location obtaining on a non-0 exit code
=> Add dontRequireTtyForSudo option to locations

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/EmptyWindowsProcessYamlTest.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/EmptyWindowsProcessWinRmDriver.java, utils/common/src/main/java/org/apache/brooklyn/util/net/UserAndHostAndPort.java
=> BROOKLYN-303: Fix EmptyWindowsProcess

software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessSshDriver.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessEntityTest.java
Currently 'pre.install.command' and related steps do not fail if the command(s) returns a non-zero exit.
This can mean your install will fail but Brooklyn won't detect it (perhaps until some subsequent stage, or not at all).
This change adds detection of the return code and failure if it is non-zero. The 'contract' for the methods is added as a comment.  The AbstractSoftwareProcessSshDriver is changed to detect the failure and throw an exception. The AbstractSoftwareProcessWinRmDriver already does the right thing and doesn't need changed.
While this could break some existing blueprints, I think in such cases it's more likely that it is highlighting a problem that has been missed, rather than causing a problem because someone is explicitly relying on that behaviour.
=> Ensure detection of failed pre.install.command and related commands.

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/CampResolver.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/EntityNameYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlEntityNameTest.java, core/src/main/java/org/apache/brooklyn/entity/stock/BasicApplicationImpl.java
Previously, if an entity in the catalog did not have an explicit display 
name then it got the name from the item’s metadata. This was fine in
simple use-cases, but bad if using sub-types or if entities wanted to
declare their own defaultDisplayName.
(Deletes `EntityNameYamlTest.testBrooklynCatalog`, as was spotted by @geomacy in https://github.com/apache/brooklyn-server/pull/200 after merge).
=> Entity display name: fix catalog item defaults

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AbstractYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/EntitiesYamlTest.java, core/pom.xml, core/src/main/java/org/apache/brooklyn/util/core/json/BidiSerialization.java, core/src/main/java/org/apache/brooklyn/util/core/json/BrooklynObjectsJsonMapper.java, core/src/main/java/org/apache/brooklyn/util/core/json/ConfigurableSerializerProvider.java, core/src/main/java/org/apache/brooklyn/util/core/json/ErrorAndToStringUnknownTypeSerializer.java, core/src/main/java/org/apache/brooklyn/util/core/json/MultimapSerializer.java, core/src/main/java/org/apache/brooklyn/util/core/json/PossiblyStrictPreferringFieldsVisibilityChecker.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/AbstractBrooklynRestResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/util/WebResourceUtils.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/util/json/BrooklynJacksonJsonProvider.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/util/json/BrooklynJacksonSerializerTest.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessSshDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/ShellEnvironmentSerializer.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/ShellEnvironmentSerializerTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessShellEnvironmentTest.java, utils/common/src/main/java/org/apache/brooklyn/util/javalang/Reflections.java, utils/common/src/test/java/org/apache/brooklyn/util/javalang/ReflectionsTest.java
Serialize complex objects to JSON instead of calling toString() when building the shell environment variables for `SoftwareProcess`.
```
brooklyn.catalog:
id: mapping-entity
item:
type: VanillaSoftwareProcess
env:
MAPPINGS: $brooklyn:config("mappings")
services:
- type:  mapping-entity
mappings:
key1: val1
key2: val2
```
Will result in an `MAPPINGS={"key1":"val1","key2":"val2"} ` environment variable.
=> Serialize complex objects as JSON in shell.env.

test-framework/src/main/java/org/apache/brooklyn/test/framework/TestFrameworkAssertions.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/TestSshCommandImpl.java
Fixes build by restoring behaviour changed in #212, which broke `TestSshCommandTest.shouldNotBeUpIfAssertionsFail` because only one failure was in the exception message.
=> TestSshCommand checks all assertions rather than throwing first

core/src/main/java/org/apache/brooklyn/core/entity/AbstractEntity.java, core/src/main/java/org/apache/brooklyn/core/entity/EntityInternal.java, core/src/main/java/org/apache/brooklyn/feed/function/FunctionPollConfig.java, core/src/main/java/org/apache/brooklyn/feed/shell/ShellPollConfig.java, core/src/main/java/org/apache/brooklyn/feed/ssh/SshPollConfig.java, core/src/main/java/org/apache/brooklyn/feed/windows/WindowsPerformanceCounterPollConfig.java, core/src/main/java/org/apache/brooklyn/util/core/task/DynamicTasks.java, core/src/main/java/org/apache/brooklyn/util/core/task/Tasks.java, policy/src/main/java/org/apache/brooklyn/policy/autoscaling/AutoScalerPolicy.java, software/base/src/main/java/org/apache/brooklyn/entity/chef/ChefAttributePollConfig.java, software/base/src/main/java/org/apache/brooklyn/entity/machine/AddMachineMetrics.java, software/base/src/main/java/org/apache/brooklyn/entity/machine/MachineAttributes.java, software/base/src/main/java/org/apache/brooklyn/entity/machine/MachineEntity.java, software/base/src/main/java/org/apache/brooklyn/entity/machine/MachineEntityImpl.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/SoftwareProcessImpl.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/lifecycle/MachineLifecycleEffectorTasks.java, software/base/src/main/java/org/apache/brooklyn/feed/jmx/JmxAttributePollConfig.java, software/base/src/main/java/org/apache/brooklyn/feed/jmx/JmxOperationPollConfig.java, software/base/src/test/java/org/apache/brooklyn/entity/machine/MachineEntityEc2LiveTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessEntityTest.java
Moves the sensor feed for machine metrics to the SoftwareProcess, controlled by a configuration key with default set to _false_ normally and _true_ for `MachineEntity`. Also contributes static helper methods for feed `PollConfig` creation.
=> Move machine metrics to SoftwareProcess entity

rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/ActivityApi.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ActivityResource.java
Example 
GET http://localhost:8081/v1/activities/abc123/children/recurse
```
{
"sCxsLgvm": {
"id": "sCxsLgvm",
"displayName": "invoking start[locations] on 1 node",
"description": "",
"entityId": "z81e0jl9j4",
"entityDisplayName": "simple-app",
"tags": [
"SUB-TASK",
{
"type": "org.apache.brooklyn.core.test.entity.LocalManagementContextForTests"
},
{
"wrappingType": "contextEntity",
"entity": {
"type": "org.apache.brooklyn.api.entity.Entity",
"id": "z81e0jl9j4"
}
}
],
"submitTimeUtc": 1466502440778,
"startTimeUtc": 1466502440778,
"endTimeUtc": 1466502441114,
"currentStatus": "Completed",
"result": [
null
],
"isError": false,
"isCancelled": false,
"children": [
{
"link": "/activities/WfYmdAuS",
"metadata": {
"id": "WfYmdAuS",
"taskName": "start",
"entityId": "cmfr998e06", …
```
=> Adds the ability for you to fetch all children of an activity

core/src/main/java/org/apache/brooklyn/core/mgmt/persist/BrooklynMementoPersisterToObjectStore.java, core/src/main/java/org/apache/brooklyn/util/core/xstream/XmlUtil.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindEntityTest.java, core/src/test/java/org/apache/brooklyn/core/test/qa/performance/XmlPerformanceTest.java, core/src/test/java/org/apache/brooklyn/util/core/xstream/XmlSerializerTest.java, core/src/test/java/org/apache/brooklyn/util/core/xstream/XmlUtilTest.java
I'm not convinced by this approach (calling a special method `XmlUtil.xpathHandlingIllegalChars()`, which retries the xpath having escaped the illegal characters). It works well enough for us because we are just making very basic use of xpath - it is primarily to just extact the entity id from the xml file, before we try to fully deserialize it.
=> BROOKLYN-305: handle invalid xml chars in attribute vals

software/base/src/main/java/org/apache/brooklyn/entity/java/VanillaJavaAppSshDriver.java
The output from the classpath gathering step currently includes Brooklyn's "Executed ... , result: 0" info, which means that classpaths look like this:
CLASSPATH="/tmp/brooklyn-sam/apps/l8wk2l74in/entities/VanillaJavaApp_zn86w6blx8/lib/derby-10.12.1.1.jar:/tmp/brooklyn-sam/apps/l8wk2l74in/entities/VanillaJavaApp_zn86w6blx8/lib/my-app-1.0.jar:/tmp/brooklyn-sam/apps/l8wk2l74in/entities/VanillaJavaApp_zn86w6blx8/lib/**Executed**:/tmp/brooklyn-sam/apps/l8wk2l74in/entities/VanillaJavaApp_zn86w6blx8/lib**/tmp/brooklyn-20160629-191833075-b9bF-customizing-classpath_VanillaJ.sh,**:/tmp/brooklyn-sam/apps/l8wk2l74in/entities/VanillaJavaApp_zn86w6blx8/lib/**result**:/tmp/brooklyn-sam/apps/l8wk2l74in/entities/VanillaJavaApp_zn86w6blx8/lib/**0**"
Did something change internally? It's hard to believe …
=> Fix VanillaJavaApp's stdin and env

karaf/features/src/main/feature/feature.xml, karaf/init/src/main/resources/OSGI-INF/blueprint/blueprint.xml, policy/src/main/resources/catalog.bom, pom.xml, software/base/src/main/java/org/apache/brooklyn/entity/chef/ChefConfig.java, software/base/src/main/java/org/apache/brooklyn/entity/chef/ChefLifecycleEffectorTasks.java, software/base/src/main/java/org/apache/brooklyn/entity/chef/ChefSoloDriver.java, test-framework/src/main/resources/catalog.bom
* adds missing bundles for persistence
* enable persistence by default
* add missing entityType for policies (required)
* remove deprecated config key, causing duplicate name warning in logs
* remove TargetableTestComponent from catalog.bom - it's not a user-facing entity, meant to be subclassed
=> Misc OSGi fixes

core/src/main/java/org/apache/brooklyn/core/BrooklynFeatureEnablement.java, core/src/test/java/org/apache/brooklyn/core/BrooklynFeatureEnablementPerformanceTest.java, core/src/test/java/org/apache/brooklyn/core/BrooklynFeatureEnablementTest.java
Previously if a downstream project set a default during static init, 
that was indistinguishable from subsequent explicit calls to 
setEnablement (or from brooklyn properties). Therefore the 
brooklyn.properties didn’t overwrite the default.
=> Fixes BrooklynFeatureEnablement setting defaults

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/BrooklynDslCommon.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/DslComponent.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ByonLocationsYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ConfigInheritanceYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/EmptySoftwareProcessYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/EmptyWindowsProcessYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/EntitiesYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/EntityNameYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/EntityRefsYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlEntityNameTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/policy/CreatePasswordSensorIntegrationTest.java, camp/camp-brooklyn/src/test/resources/test-referencing-entities.yaml, core/src/main/java/org/apache/brooklyn/core/entity/Entities.java, core/src/test/java/org/apache/brooklyn/core/entity/EntitiesTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindEnricherTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindEntityTest.java, core/src/test/java/org/apache/brooklyn/entity/group/DynamicClusterTest.java, launcher/src/test/java/org/apache/brooklyn/launcher/blueprints/AbstractBlueprintTest.java, launcher/src/test/java/org/apache/brooklyn/launcher/blueprints/Windows7zipBlueprintLiveTest.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/EntityConfigResource.java
- Adds proper test coverage
- Fixes sibling/descendant/ancestor so will never return self
=> Yaml entity refs: support $brooklyn:self()

karaf/apache-brooklyn/src/main/resources/etc/org.apache.brooklyn.osgilauncher.cfg, karaf/features/src/main/feature/feature.xml, software/base/src/main/java/org/apache/brooklyn/feed/jmx/JmxHelper.java
e.g. tomcat failed to reach service-up because it couldn't create the JMXMP connector due to classloading problems.
=> Fix jmxmp connector in karaf

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/CampInternalUtils.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/BrooklynDslCommon.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlEntityTest.java, core/src/main/java/org/apache/brooklyn/core/BrooklynFeatureEnablement.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogBomScanner.java, core/src/main/java/org/apache/brooklyn/core/effector/AddSensor.java, core/src/main/java/org/apache/brooklyn/core/entity/drivers/ReflectiveEntityDriverFactory.java, core/src/main/java/org/apache/brooklyn/core/location/geo/HostGeoInfo.java, core/src/main/java/org/apache/brooklyn/core/mgmt/classloading/JavaBrooklynClassLoadingContext.java, core/src/main/java/org/apache/brooklyn/core/mgmt/entitlement/Entitlements.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/AbstractManagementContext.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/transformer/CompoundTransformerLoader.java, core/src/main/java/org/apache/brooklyn/core/objs/BrooklynTypes.java, core/src/main/java/org/apache/brooklyn/core/sensor/DurationSinceSensor.java, core/src/main/java/org/apache/brooklyn/core/sensor/ssh/SshCommandSensor.java, core/src/main/java/org/apache/brooklyn/location/byon/ByonLocationResolver.java, core/src/main/java/org/apache/brooklyn/location/ssh/SshMachineLocation.java, core/src/main/java/org/apache/brooklyn/util/core/ClassLoaderUtils.java, core/src/main/java/org/apache/brooklyn/util/core/flags/TypeCoercions.java, core/src/test/java/org/apache/brooklyn/core/objs/BasicSpecParameterFromClassTest.java, karaf/apache-brooklyn/pom.xml, karaf/apache-brooklyn/src/main/resources/etc/default.catalog.bom, karaf/features/src/main/feature/feature.xml, karaf/init/src/main/resources/catalog-classes.bom, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/PolicyResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/security/provider/DelegatingSecurityProvider.java, software/base/src/main/java/org/apache/brooklyn/entity/resolve/HardcodedCatalogEntitySpecResolver.java, software/winrm/src/main/java/org/apache/brooklyn/location/winrm/WinRmMachineLocation.java
* Disables loading `catalog.bom` (can be enabled through a feature flag).
* Moves all `catalog.bom` items to be loaded through `default.catalog.bom`
* Fallback class loading - replace `Class.forName(..)`, `classLoader.loadClass(...)` usages with a centralized logic. 
Class loading logic:
* Supports embedding the bundle's symbolidName and version in the class name (for example `org.apache.brooklyn.core:0.10.0.SNAPHOT:org.apache.brooklyn.core.mgmt.entitlement.PerUserEntitlementManager`
* try to load from the entity's catalog item libraries
* Class.forName, using the calling class' class loader
* mgmt.getCatalogClassLoader.loadClass
* scanning all bundles matching `org.apache.brooklyn.*:0.10.0-SNAPSHOT` by default. Can be overriden with a system property.
=> Karaf fixes - class loading

karaf/features/src/main/feature/feature.xml
Required for running blueprint tests on Karaf.
=> Add brooklyn-test-framework feature.

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ExternalConfigYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/JcloudsLocationExternalConfigYamlTest.java, core/src/main/java/org/apache/brooklyn/core/location/cloud/AbstractCloudMachineProvisioningLocation.java, core/src/main/java/org/apache/brooklyn/location/ssh/SshMachineLocation.java, core/src/main/java/org/apache/brooklyn/util/core/config/ConfigBag.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsSshMachineLocation.java
If external config is resolved too early, it can lead to resolved values being persisted (security flaw). Also, changes to the external config supplier are not reflected when the config is subsequently read
=> Prevents premature resolving of external config

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java
Failure in the command will abort machine obtain, so make sure the command reports successfull result on non-centos machines.
=> Fix setting the hostname on non-centos machines

core/src/main/java/org/apache/brooklyn/core/entity/Entities.java
Previously, after rebind then enrichers using this would have their
own copy of their object (due to xstream deserialisation). Instead,
use an enum.
This does not fix the problem for existing persisted state of enrichers
that have their own object!
=> Fix Entities.UNCHANGED marker, for rebind

launcher/src/test/resources/mssql-test.yaml, software/base/src/main/resources/org/apache/brooklyn/software/winrm/utils/enable-credssp.ps1, software/base/src/main/resources/org/apache/brooklyn/software/winrm/utils/invoke-command-credssp.ps1
(please do not merge immediately, doing live tests)
Using Invoke-Command in windows scripts is not very obvious and requires Windows blueprint.
Developer include all these lines in their ps scripts, windows username and password and then passing parameters.
With this change using CredSSP should be just one line in the install script and one line in the YAML to add the script on the Windows machine.
Here it is important the name of the script since for future users it will be included in their new Blueprint YAMLs as well as in their `.ps1` or `.cmd` scripts.
We should files like this and https://github.com/apache/brooklyn-server/blob/master/software/base/src/main/resources/org/apache/brooklyn/software/base/custom-enable-credssp.ps1  into some convention.
Can you please share thoughts about …
=> Windows helper script for using Invoke-Command -Auth CredSSP

karaf/itest/src/test/java/org/apache/brooklyn/AssemblyTest.java, karaf/itest/src/test/java/org/apache/brooklyn/core/catalog/internal/CatalogBomScannerTest.java, karaf/itest/src/test/java/org/apache/brooklyn/core/catalog/internal/DefaultBomLoadTest.java, karaf/itest/src/test/java/org/apache/brooklyn/launcher/osgi/OsgiLauncherTest.java, karaf/itest/src/test/java/org/apache/brooklyn/security/CustomSecurityProviderTest.java, karaf/itest/src/test/java/org/apache/brooklyn/security/StockSecurityProviderTest.java
@neykov setting these timeouts seems to fix `AssemblyTest` for me locally. I've added the timeout to everywhere else that we do `@Inject` in itests (I saw a failure in `OsgiLauncherTest` for `gave up waiting for service org.apache.brooklyn.api.mgmt.ManagementContext`).
=> Fix AssemblyTest (increase timeout for FeaturesService)

core/src/main/java/org/apache/brooklyn/enricher/stock/PercentageEnricher.java
Stops long stream of `WARN` log messages when using `PercentageEnricher` on a sensor that already has a `RendererHint` applied
=> Fix adding multiple RendererHints for percentage enricher

karaf/apache-brooklyn/pom.xml, karaf/features/src/main/feature/feature.xml
Don’t depend on bundles that are in brooklyn-library when building
brooklyn-server: they won’t be available yet.
Long-term solution is to move all of this into brooklyn-dist, and 
then we can re-enable these.
=> brooklyn-server karaf: don’t depend on library

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/DslComponent.java, core/src/main/java/org/apache/brooklyn/enricher/stock/PercentageEnricher.java
Does not pollute `INFO` log with exception stack traces. Also replaces check for zero with a `DoubleMath.fuzzyCompare()` call using an epsilon of 1x10^-12 to allow for floating point inaccuracies.
=> Return when PercentageEnricher cannot compute result

core/src/main/java/org/apache/brooklyn/core/effector/EffectorTasks.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/EffectorUtils.java, core/src/test/java/org/apache/brooklyn/core/effector/EffectorExceptionLoggedTest.java, test-support/pom.xml, test-support/src/main/java/org/apache/brooklyn/test/LogWatcher.java
Also see https://github.com/apache/brooklyn-library/pull/49 (but please review and merge this first).
=> BROOKLYN-313: log.debug exceptions thrown by effectors

parent/pom.xml
Note that this will make the project fail on 32 bit JDKs, at least on Windows.
=> Fix tests out of memory crashes

karaf/init/src/main/resources/catalog-classes.bom
As discussed with @neykov and @Graeme-Miller 
Previously the `catalog-classes.bom` included the Brooklyn version number in which the bundles are to be found. This works well when installing and using Brooklyn, but these bundle version numbers make their way into the persisted state.
After upgrading Brooklyn and restarting, it uses the existing persisted state. The bundle with the old Brooklyn version is not in this new karaf install, so it fails with the exception below:
```
14:30:50,959 WARN  102 internal.CatalogInitialization [nager-HYVJ5hka-0] Error populating catalog (rethrowing): java.lang.IllegalStateException: Bundle from null failed to install: Bundle CatalogBundleDto{symbolicName=or
g.apache.brooklyn.core, version=0.10.0.20160711_1846, url=null} not previously registered, but URL …
```
=> catalog-classes.bom: don’t specify bundle id/version

core/src/main/java/org/apache/brooklyn/core/objs/BrooklynTypes.java, parent/pom.xml
The BrooklynTypes cache was keeping references to classes indefinitely, preventing the OSGi class loaders and frameworks from being GCed.
=> Fix memory leak where unused class references are kept around

karaf/init/src/main/resources/catalog-classes.bom
Add `iconUrl: ...` for things in karaf's catalog-classes.bom
These use references to external URLs, rather than things on the classpath, because we don't want to rely on having started the catalog's bundles (or classloading from the "right" bundle) when returning icons.
=> Add logo urls to karaf catalog-classes.bom

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/DslComponent.java, core/src/main/java/org/apache/brooklyn/core/sensor/StaticSensor.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/InfrastructureDeploymentTestCase.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/InfrastructureDeploymentTestCaseImpl.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/LoopOverGroupMembersTestCase.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/LoopOverGroupMembersTestCaseImpl.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/ParallelTestCase.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/ParallelTestCaseImpl.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/RelativeEntityTestCase.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/RelativeEntityTestCaseImpl.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/TargetableTestComponent.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/TestCase.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/TestEffector.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/TestEffectorImpl.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/TestFrameworkAssertions.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/TestHttpCall.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/TestSensor.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/InfrastructureDeploymentTestCaseTest.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/LoopOverGroupMembersTestCaseTest.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/RelativeEntityTestCaseTest.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/TestEffectorTest.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/TestFrameworkAssertionsTest.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/TestHttpCallTest.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/TestSensorTest.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/entity/TestEntity.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/entity/TestEntityImpl.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/entity/TestInfrastructure.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/entity/TestInfrastructureImpl.java
Adds an entity for test cases that need to resolve their target from another entity. For example, to make assertions on the child of a group member.
=> Test relative entities

core/src/main/java/org/apache/brooklyn/core/entity/Attributes.java, core/src/main/java/org/apache/brooklyn/core/server/BrooklynServerConfig.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/lifecycle/MachineLifecycleEffectorTasks.java, software/base/src/test/java/org/apache/brooklyn/entity/ExpungingJcloudsLocationLiveTest.java
=> BROOKLYN-264 Stop app while VM still being provisioned: vm is left

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsSshMachineLocation.java
Try-catch in getOptionalNode/getOptionalImage (e.g. if called by user
in rebind code, then don’t fail outright if cloud throws exception
=> Fix for BROOKLYN-314

core/src/test/java/org/apache/brooklyn/core/mgmt/internal/EffectorUtilsTest.java, core/src/test/java/org/apache/brooklyn/util/core/internal/ssh/RecordingSshTool.java, software/base/pom.xml, software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessDriver.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/VanillaSoftwareProcessTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/VanillaWindowsProcessTest.java, software/winrm/src/test/java/org/apache/brooklyn/util/core/internal/winrm/RecordingWinRmTool.java
For "	Don’t call postInstallCommand if skipInstall=true", why did we previous still call postInstall @grkvlt ?
The bulk of this PR is the unit testing of VanillaSoftwareProcess, using the `RecordSshTool` to stub out all the ssh commands.
Note the "Adds EffectorUtilsTest" is unrelated - I meant to include it in a PR a while ago, but accidentally missed it! We previously didn't have any tests that covered these methods directly.
=> VanillaSoftwareProcess tests

core/src/main/java/org/apache/brooklyn/entity/stock/ConditionalEntity.java, core/src/main/java/org/apache/brooklyn/entity/stock/ConditionalEntityImpl.java, core/src/test/java/org/apache/brooklyn/entity/stock/ConditionalEntityTest.java
Allows entity creation to be controlled using a configuration key value.
=> Create OptionalEntity to allow configurable addition of child entities

core/src/main/java/org/apache/brooklyn/core/effector/ssh/SshCommandEffector.java, core/src/main/java/org/apache/brooklyn/core/entity/BrooklynConfigKeys.java, core/src/main/java/org/apache/brooklyn/core/sensor/ssh/SshCommandSensor.java, core/src/main/java/org/apache/brooklyn/util/core/json/ShellEnvironmentSerializer.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessSshDriver.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/ShellEnvironmentSerializerTest.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/TestSshCommandImpl.java
Builds on https://github.com/apache/brooklyn-server/pull/208
=> Serialize environment values - implement for all entities

core/src/main/java/org/apache/brooklyn/core/effector/ssh/SshCommandEffector.java, core/src/main/java/org/apache/brooklyn/core/sensor/ssh/SshCommandSensor.java
Use the config resolver on the complete environment map before serializing to strings in SSH command sensor and effector.
=> Resolve all environment variables

api/src/main/java/org/apache/brooklyn/api/internal/AbstractBrooklynObjectSpec.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynEntityDecorationResolver.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/CampInternalUtils.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/TestSensorAndEffectorInitializer.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/SpecParameterParsingTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/SpecParameterUnwrappingTest.java, core/src/main/java/org/apache/brooklyn/core/objs/BasicSpecParameter.java, core/src/main/java/org/apache/brooklyn/core/objs/SpecParameterPredicates.java
Implements behaviour required to merge `brooklyn.parameters` sections of specifications in YAML files, allowing addition of new parameters to entities without having to specify the complete list again.
=> Merge brooklyn.parameters in YAML files

rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/EntityApi.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/EntityResource.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/EntityResourceTest.java
Previously it returned json:
* it wrapped it in quotes.
* it did strange things with \n: the result rendered as “\n” rather than actual new-line characters (though it was more complicated than that - an angular UI did recognise the “\n” as a single character).
=> rest api: entity/spec returns unquoted text/x-yaml

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/SpecParameterUnwrappingTest.java
Fixes `SpecParameterUnwrappingTest#testParameterDefaultsUsedInConfig()`
=> Fix non-deterministic test of SpecParameter by choosing correct entity

launcher/src/test/java/org/apache/brooklyn/launcher/CleanOrphanedLocationsIntegrationTest.java
On Windows some leftover files remain in the `osgi/cache` folder, triggering the rat plugin failure. It's a temporary folder so move it to the build folder.
=> Move tests temporary folders to the target folder

core/src/main/java/org/apache/brooklyn/core/config/internal/AbstractStructuredConfigKey.java, core/src/main/java/org/apache/brooklyn/core/entity/AbstractEntity.java, core/src/main/java/org/apache/brooklyn/core/entity/internal/EntityConfigMap.java, core/src/main/java/org/apache/brooklyn/core/objs/AbstractEntityAdjunct.java, core/src/main/java/org/apache/brooklyn/core/objs/proxy/InternalPolicyFactory.java, core/src/main/java/org/apache/brooklyn/entity/group/SshCommandMembershipTrackingPolicy.java, core/src/test/java/org/apache/brooklyn/entity/group/SshCommandMembershipTrackingPolicyTest.java
Allows easy creation of new load balancer entities by defining tracking policies in YAML that execute the required commands over SSH when an entity is added or removed.
=> Add new member tracking policy with configurable SSH commands

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/BrooklynDslCommon.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ObjectsYamlTest.java, core/src/main/java/org/apache/brooklyn/core/entity/EntityFunctions.java, core/src/main/java/org/apache/brooklyn/core/entity/EntityPredicates.java, core/src/test/java/org/apache/brooklyn/core/entity/EntityFunctionsTest.java, core/src/test/java/org/apache/brooklyn/core/entity/EntityPredicatesTest.java
* Extends `$brooklyn:object()` syntax to support parameterised constructors and static factory methods
* Adds variants of `EntityPredicates.config*()` and `attribute*()` that accept strings
* Adds variants of `EntityFunctions.config()` and `attribute()` that accept strings
* Adds variants of `EntityFunctions.config()` and `attribute()` that accept format specifier
=> Conveniences to make groups easier to configure in YAML

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/networking/SharedLocationSecurityGroupCustomizer.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/networking/SharedLocationSecurityGroupCustomizerTest.java
A location customizer that creates a single shared security group for each entity it is applied to as well as an individual entity.  The shared entity allows full tcp and udp traffic within members of the group.
This PR includes 85c65ed078060cd01f74732b7cc4bddef8a58006 from @bostko 's #276.
The implementation use the JcloudsLocationSecurityGroupCustomizer but has a no arg constructor so can be used in yaml.
=> Shared location customizer

core/src/main/java/org/apache/brooklyn/core/entity/AbstractEntity.java, core/src/main/java/org/apache/brooklyn/core/entity/Attributes.java, core/src/main/java/org/apache/brooklyn/enricher/stock/AbstractMultipleSensorAggregator.java, core/src/main/java/org/apache/brooklyn/enricher/stock/Enrichers.java, core/src/main/java/org/apache/brooklyn/enricher/stock/Joiner.java, core/src/main/java/org/apache/brooklyn/enricher/stock/MapAggregator.java, core/src/main/java/org/apache/brooklyn/entity/group/SshCommandMembershipTrackingPolicy.java, core/src/test/java/org/apache/brooklyn/core/entity/EntityTypeTest.java, core/src/test/java/org/apache/brooklyn/enricher/stock/EnrichersTest.java
Adds `ENTITY`, `MEMBER` and `ALL_MEMBERS` as targets for `SshCommandMembershipTrackingPolicy`, updates `Joiner` to handle map entries as key-value pairs, adds `MapAggregator` to generate maps from entity sensor pairs and adds new `ENTITY_ID`, `APPLICATION_ID` and `CATALOG_ID` default sensors to entities.
=> Adds a target configuration to the SSH command executing member tracker

core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogInitialization.java, core/src/main/java/org/apache/brooklyn/core/sensor/DependentConfiguration.java
(longer term the location registry should be removed in favour of pure catalog,
but this is a tactical fix)
also minor fix w dep config seeing null values
=> ensures locations are made available to location registry when catalog is reset

core/src/main/java/org/apache/brooklyn/core/mgmt/internal/EntityManagementSupport.java
fixes a deadlock observed with a screwy blueprints, when:
"item added" callback:  locking EntityManagementSupport to get subscription context, while updating members
```
at org.apache.brooklyn.core.mgmt.internal.EntityManagementSupport.getSubscriptionContext(EntityManagementSupport.java:362)
- waiting to lock <0x0000000088908188> (a org.apache.brooklyn.core.mgmt.internal.EntityManagementSupport)
at org.apache.brooklyn.core.entity.AbstractEntity$BasicSubscriptionSupport.getSubscriptionContext(AbstractEntity.java:1519)
at org.apache.brooklyn.core.entity.AbstractEntity$BasicSensorSupport.emitInternal(AbstractEntity.java:1191)
at org.apache.brooklyn.core.entity.AbstractEntity$BasicSensorSupport.emit(AbstractEntity.java:1184)
at org.apache.brooklyn.core.entity.EntityDynamicType.addSensorIfAbsen …
```
=> don't hold lock on EntityManagementSupport for longer than needed

core/src/main/java/org/apache/brooklyn/entity/stock/ConditionalEntity.java, core/src/main/java/org/apache/brooklyn/entity/stock/ConditionalEntityImpl.java, core/src/test/java/org/apache/brooklyn/entity/stock/ConditionalEntityTest.java
Adds an enricher that propagates `service.isUp` from the child entity, if one is created. This allows other entities to use the `service.isUp` sensor of the `ConditionalEntity` as a latch, without needing to know the identity (or even presence) of the child. A configuration setting enables propagation of other sensors from the child.
=> Change conditional entity to reflect service state of optional child

rest/rest-client/pom.xml, rest/rest-client/src/main/java/org/apache/brooklyn/rest/client/BrooklynApi.java
These aren’t enough to fix BROOKLYN-338, but it’s a start:
* Ensures rest-client imports the resteasy marshallers package,
which it calls with reflection (via the resteasy ProxyBuilder).
* Passes the ProxyBuilder a classloader that has access to the 
rest-api classes and to rest-client’s classloader (which thus 
can access the marshallers).
=> BROOKLYN-338: BrooklynApi fixes for karaf

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/BasicJcloudsLocationCustomizer.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/ChildEntityCustomizer.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocationCustomizer.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/SudoTtyFixingCustomizer.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/networking/JcloudsLocationSecurityGroupCustomizer.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/softlayer/SoftLayerSameVlanLocationCustomizer.java
Extends the jclouds location customizer to be a `BasicConfigurableObject` allowing better configuration etc. when created using `$brooklyn:object` in the DSL, and add a new `ChildEntityCustomizer` that creates a child entity before the main entity has started up, allowing more flexible configuration.
=> Child entity customizer

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocationConfig.java
All blueprints using centos are failing if they don't specify this option manually
=> Open iptables by default

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynEntityDecorationResolver.java
Adds `#decorate(EntitySpec<?>, ConfigBag)` as an overloaded deprecated method in `BrooklynEntityDecorationResolver` class, for backwards compatibility.
See https://github.com/cloudsoft/brooklyn-tosca/pull/113
=> Adds deprecated decorate method to preserve backwards compatibility

karaf/features/src/main/feature/feature.xml, karaf/httpcomponent-extension/pom.xml, karaf/pom.xml, pom.xml
winrm4j version update has fixes for OSGi. Also adding an extension bundle to httpcomponents-asyncclient so that it's able to see `org.apache.http.ssl package` (that's fixed in later revision releases of the jar).
=> Fix winrm4j in Karaf

software/base/src/main/java/org/apache/brooklyn/entity/java/JavaSoftwareProcessSshDriver.java
This tries incrementing the Java version we're installing if the current one fails. This primarily addresses the problem of Java 7 not being available by default on Ubuntu 16.04.
Tested with Tomcat7 on GCE, AWS & Bluebox on Ubuntu 14 / 16, Centos 6 / 7
=> Try alternative Java versions

core/src/main/java/org/apache/brooklyn/core/location/cloud/CloudLocationConfig.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsHardwareProfilesStubbedLiveTest.java
Also changes JcloudsLocation’s template building so that if
a config key has a default value then that will be used, if there is
no explicit value (or empty value) set.
=> Set default minRam to 1gb

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlEntityTest.java
On the other hand removing `services` works just fine.
The problem is that the camp parser doesn't see items which are in the same catalog and already parsed. Only already added items are visible. The catalog parsers does a poor-man's validation on the top level items only, we need to replace that with the normal CAMP parser workflow, but able to see items in the current catalog preceding the current item.
=> [BROOKLYN-343] A test to illustrate a failing case where cross-referencing catalog items fails

karaf/features/src/main/feature/feature.xml
* load brooklyn-launcher-common only once
* fix java-xmlbuilder dependency version
=> OSGi Features cleanup

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AppYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ByonLocationsYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ConfigInheritanceYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ConfigLocationInheritanceYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ConfigParametersYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ConfigYamlTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/persist/XmlMementoSerializerTest.java, core/src/test/java/org/apache/brooklyn/util/core/file/ArchiveUtilsTest.java, karaf/features/src/main/feature/feature.xml, launcher/pom.xml, parent/pom.xml, pom.xml, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/LocationResourceTest.java
Removes the dependency on google-http-client, depending directly on apache-httpcomponents
=> Update geoip to latest version

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AppYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ByonLocationsYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ConfigInheritanceYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ConfigLocationInheritanceYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ConfigParametersYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ConfigYamlTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/persist/XmlMementoSerializerTest.java, core/src/test/java/org/apache/brooklyn/util/core/file/ArchiveUtilsTest.java, karaf/features/src/main/feature/feature.xml, launcher/pom.xml, parent/pom.xml, pom.xml, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/LocationResourceTest.java
This reverts commit e71b4d0b8d176dd16d1543466316845392e5b6a0.
The change relies on jackson 2.7.5, while Brooklyn is still on 2.4.5.
=> Revert "Update geoip to latest version"

core/src/test/java/org/apache/brooklyn/core/mgmt/internal/LocalUsageManagerTest.java
`shouldSkipOnBoxBaseDirResolution` return type was changed from boolean to
Boolean in super-class.
=> Fix LocalUsageManagerTest

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/networking/SharedLocationSecurityGroupCustomizer.java
Previously it was ImmutableList so could not be used from YAML; changed
to a normal List.
=> Fix SharedLocationSecurityGroupCustomizer.udpPortRanges

launcher/src/test/java/org/apache/brooklyn/launcher/blueprints/CouchbaseBlueprintTest.java, launcher/src/test/java/org/apache/brooklyn/launcher/blueprints/MongoDbBlueprintTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/policy/jclouds/os/CreateUserPolicyTest.java, rest/rest-server/src/test/resources/vanilla-software-process-with-resource.yaml
See individual commits for further description (copy-pasted here for your convenience):
```
commit 384de14a710e1bbbccebd83a0f61ab158f29f116
Author: Aled Sage <aled.sage@gmail.com>
Date:   Fri Sep 23 18:18:10 2016 +0100
Re-write CreateUserPolicyTest to use RecordingSshTool
Previously it use its own RecordingSshMachineLocation, so changing it
to use our more standard mechanism.
commit ab5d7b84940a7802bf807e590c1ccf1c6808c05a
Author: Aled Sage <aled.sage@gmail.com>
Date:   Fri Sep 23 18:17:10 2016 +0100
Fix vanilla-software-process-with-resource.yaml
Typo of “tempalte” broke integration test, which broke
org.apache.brooklyn.rest.test.entity.VanillaSoftwareProcessTest
commit 42a547913e86b1e8a1b4d1de2cf9f68df0f5dc4d
Author: Aled Sage <aled.sage@gmail.com>
Date:   Fri Sep 23 18:15:13 2016 +0100 …
```
=> Fix or disable integration tests

software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessStopsDuringStartTest.java
/cc @aledsage is this the best fix?  (it stalls for 2m most the time when doing `mvn clean install` without this.  haven't thought too much about it though!)
=> fix long-running unit test

core/src/test/java/org/apache/brooklyn/location/localhost/LocalhostMachineProvisioningLocationTest.java
Use @BeforeMethod rather than @BeforeClass for test setup/teardown
The PR build for https://github.com/apache/brooklyn-server/pull/355 (see https://builds.apache.org/job/brooklyn-server-pull-requests/org.apache.brooklyn$brooklyn-core/1138/consoleFull) shows all but the first test in `LocalhostMachineProvisioningLocationTest` failing with the exception:
```
2016-09-27 21:49:31,219 INFO  TESTNG FAILED: "Surefire test" - org.apache.brooklyn.location.localhost.LocalhostMachineProvisioningLocationTest.obtainLowNumberedPortsAutomatically() finished in 0 ms
java.lang.IllegalStateException: Management context no longer running
at org.apache.brooklyn.core.mgmt.internal.LocalManagementContext.getLocationManager(LocalManagementContext.java:270)
at …
```
=> Fix LocalhostMachineProvisioningLocationTest

core/src/main/java/org/apache/brooklyn/feed/http/HttpFeed.java, software/base/pom.xml, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessEntityHttpFeedRebindTest.java
As stated in https://issues.apache.org/jira/browse/BROOKLYN-354, the underlying issue was already fixed in master. This just adds unit tests for it.
=> BROOKLYN-354: Rebind failed (when an NingxController entity's hostname sensor was null)

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/DslComponent.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/JcloudsLocationExternalConfigYamlLiveTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/JcloudsRebindStubYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/JcloudsRebindWithExternalConfigTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/JcloudsRebindWithYamlDslTest.java, core/src/main/java/org/apache/brooklyn/core/mgmt/BrooklynTaskTags.java, core/src/main/java/org/apache/brooklyn/util/core/config/ConfigBag.java, core/src/main/java/org/apache/brooklyn/util/core/config/ResolvingConfigBag.java, core/src/main/java/org/apache/brooklyn/util/core/task/TaskBuilder.java, core/src/main/java/org/apache/brooklyn/util/core/task/ValueResolver.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindTestFixture.java, core/src/test/java/org/apache/brooklyn/util/core/internal/ssh/RecordingSshTool.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsSshMachineLocation.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsAddressesLiveTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsRebindStubTest.java
There are two parts to fixing this:
1. Fix for NPE in `JcloudsLocation.getComputeService`: we are more careful when copying the `ResolvingConfigBag`, so we don't resolve all the values too early when copying it from one `ResolvingConfigBag` to another.
2. Fix for creation of DSL tasks (e.g. in `DslComponent.newTask()`) so that we pass through the current task's context entity when we create the DSL task.
For (2), it's not clear to me if that is the right fix. The alternative would be to ensure that it is the entity's `ExecutionContext` that is used to execute the created task (which would thus automatically set the entity-context as a tag on the task). Presumably we are currently sometimes using the vanilla management context's `ExecutionContext` instead.
=> BROOKLYN-349: fix DSL resolution in location

api/src/main/java/org/apache/brooklyn/api/catalog/CatalogConfig.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/SpecParameterParsingTest.java, core/src/main/java/org/apache/brooklyn/core/objs/BasicSpecParameter.java, core/src/test/java/org/apache/brooklyn/core/objs/BasicSpecParameterFromClassTest.java, core/src/test/java/org/apache/brooklyn/core/objs/BasicSpecParameterFromListTest.java, policy/src/main/java/org/apache/brooklyn/policy/action/StopAfterDurationPolicy.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/domain/EntityConfigSummary.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/transform/CatalogTransformer.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/transform/EntityTransformer.java, server-cli/src/main/java/org/apache/brooklyn/cli/lister/ItemDescriptors.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/RelativeEntityTestCase.java
Based on https://github.com/apache/brooklyn-server/pull/354
This expose a new `pinned` flag and `constraints` key to the REST API. It allows the following:
- A blueprint can specify a config key or parameter as pinned by using `@CatalogConfig(pinned = true)` or in yaml `pinned: true`
- In case of config keys or parameters pinned in YAML, the priority is auto incremented to keep the order (code lost in [this commit](https://github.com/apache/brooklyn-server/commit/6f624c78b1e7fe72c6df1ecd297b922721b2c023#diff-5310fbeb1f42a3a4cf0508ea441440baL82))
=> Allow REST API to return the pinned config key and their constraints for catalog apps 

core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/BasicEntityRebindSupport.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessRebindNotRunningEntityTest.java
Entity is reported as on-fire if the starting/stopping task was
aborted due to a Brooklyn rebind. This will set the
SERVICE_NOT_IP_INDICATORS to say what the problem is.
=> Rebind when entity starting: report notUpIndicator for reason

core/src/main/java/org/apache/brooklyn/core/location/cloud/CloudLocationConfig.java, core/src/test/java/org/apache/brooklyn/location/ssh/SshMachineLocationTest.java, core/src/test/java/org/apache/brooklyn/util/core/internal/ssh/RecordingSshTool.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsUtil.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsStubTemplateBuilder.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/networking/JcloudsReachableAddressStubbedLiveTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/networking/JcloudsReachableAddressStubbedTest.java, utils/common/src/main/java/org/apache/brooklyn/util/net/ReachableSocketFinder.java
Used changes from https://github.com/aledsage/brooklyn-server/tree/test-JcloudsLocation-chooseReachableAddress
and https://github.com/bostko/brooklyn-server/tree/test-JcloudsLocation-chooseReachableAddress
=> Test jclouds location choose reachable address

utils/test-support/src/main/java/org/apache/brooklyn/test/support/BrooklynLeakListener.java
The package name was wrong, so it was never finding the
LocalManagementContext class in order to try to delete any left-over
instances.
=> Fix BrooklynLeakListener (ref to LocalManagementContext)

locations/jclouds/pom.xml, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsUtil.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsByonLocationResolverSoftlayerLiveTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/networking/JcloudsReachableAddressStubbedTest.java, software/winrm/src/test/java/org/apache/brooklyn/util/core/internal/winrm/RecordingWinRmTool.java
Use managementHostAndPort for all customizations made in
- obtainOnce(ConfigBag)
- registerMachineLocation(ConfigBag, NodeMetadata)
=> Reduce decisions for HostAndPort which will be used in JcloudsLocation

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsSshMachineLocation.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/AbstractJcloudsStubbedUnitTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsByonLocationResolverStubbedRebindTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsByonLocationResolverStubbedTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsSshMachineLocationStubbedTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/StubbedComputeServiceRegistry.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/UnsupportedComputeService.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/networking/JcloudsPortForwardingStubbedTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/networking/JcloudsReachableAddressStubbedTest.java
Following on from @bostko's great changes in https://github.com/apache/brooklyn-server/pull/366 (to allow us to write more real unit tests, for JcloudsLocation testing), this PR converts the easiest tests into real unit tests.
@duncangrant you may well find this helpful for the JcloudsLocation customizer changes that you are making.
=> More jclouds location unit tests

api/src/main/java/org/apache/brooklyn/api/location/MachineLocationCustomizer.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ConfigLocationInheritanceYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/JcloudsCustomizerInstantiationYamlDslTest.java, launcher-common/src/main/java/org/apache/brooklyn/launcher/command/support/CloudExplorerSupport.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocationConfig.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocationCustomizer.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/BailOutJcloudsLocation.java
Change so that getCustomizers is only called once during provisioning.
This ensures that only a single instance of a customizer configured
with DSL will be called.  This means that state can be kept between
steps.
=> One instance of customizer at each customize step

core/src/main/java/org/apache/brooklyn/entity/group/DynamicGroupImpl.java, core/src/test/java/org/apache/brooklyn/entity/group/DynamicGroupTest.java
I think this would be the expected behaviour.
The current behaviour would cause entities like [brooklyn-dns-etc-hosts-generator](https://github.com/brooklyncentral/brooklyn-dns/blob/9898438dd2c8ddbe258ab93b1b66b42818b8121a/brooklyn-dns-etc-hosts-generator.bom#L43-L49) to be overenthusiastic at best and a security hole/information leak at worst.
=> DynamicGroup filters entities in its app, not the management context

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlLocationTest.java, core/src/test/java/org/apache/brooklyn/core/entity/AbstractApplicationLegacyTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/internal/LocalUsageManagerTest.java, core/src/test/java/org/apache/brooklyn/core/objs/BasicSpecParameterFromListTest.java, core/src/test/java/org/apache/brooklyn/core/test/BrooklynMgmtUnitTestSupport.java, launcher/src/test/java/org/apache/brooklyn/launcher/CleanOrphanedLocationsIntegrationTest.java, server-cli/src/test/java/org/apache/brooklyn/cli/CliTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessStopsDuringStartTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/VanillaSoftwareProcessTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/VanillaWindowsProcessTest.java
If we leave the management context running, it will not be garbage collected (because its threads reference it, so it's not just about reachability from the test class). This memory leak causes our tests to get slower and slower on the jenkins build server.
=> Tidy tests to always terminate ManagementContext

core/src/main/java/org/apache/brooklyn/core/network/OnPublicNetworkEnricher.java, core/src/test/java/org/apache/brooklyn/core/network/OnPublicNetworkEnricherTest.java, core/src/test/java/org/apache/brooklyn/core/network/OnSubnetNetworkEnricherTest.java
I'm not entirely sure what the best way is to wire in and use the `OnPublicNetworkEnricher`. Two of the use-cases are:
1. in an environment with port-mappings (e.g. cloud's DNAT, or docker), look up the registered port mapping in the `PortForwardManager`. This is the existing behaviour.
2. Where a sensor (e.g. URI or hostAndPort) has been published with the subnet-address, publish an equivalent sensor using the public IP (so using the same port).
It is this second use-case that this PR enables.
For "normal clouds" (i.e. without DNAT), then option 2 is an obvious way to go. However:
* what if there isn't a public address? The "host.address" sensor would normally be populated with the private ip instead, so that would be used for the public url - but is that too misleading for a value of …
=> OnPublicNetworkEnricher config with sensor

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/enricher/TransformerEnricherWithDslTest.java, core/src/main/java/org/apache/brooklyn/core/BrooklynFeatureEnablement.java, core/src/main/java/org/apache/brooklyn/util/core/task/BasicExecutionManager.java
* Adds thread startup jittering so we can lure out any concurrency bugs hiding in the code base. Testing `core` with this results in a handful of failures. Similar problems are very apparent on the windows builds where the machines have a single CPU and are frequently failing. I'd enable this by default for testing only if it wasn't slowing the tests to a craw.
* Adds a test which shows the problem with the transformer resolver. It's failing under normal conditions infrequently, so use with the above enabled.
Tests are marked as `Broken` because there's no fix available for `BOOKLYN-356` yet so they might fail builds. The tests are otherwise fully implemented/working.
=> [BROOKLYN-356] Transformer value resolver test

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/BrooklynDslDeferredSupplier.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/BrooklynDslCommon.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/EntitiesYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/dsl/DslTest.java, core/src/test/java/org/apache/brooklyn/util/core/task/TasksTest.java, core/src/test/java/org/apache/brooklyn/util/core/task/ValueResolverTest.java
The same DSL object could be used in mutliple entities created from the same spec, so one entity resolving would block the rest even if they already have the values. The objects are stateless so need for a lock.
=> Remove lock on DSL objects - they are stateless

core/src/main/java/org/apache/brooklyn/core/mgmt/internal/BrooklynGarbageCollector.java
Before the change I was getting readings like `brooklyn gc (after) - using 2.59 GB / 2.86 GB (1268 MB real) memory with `-DXmx=3G`. `2.86` is `maxMemory` same as `Xmx`. `1268` is `totalMemory` which is the currently allocated memory by the JVM from the operating system. The used memory can't be more than the `totalMemory`.
Confirmed the new readings by comparing to jconsole.
The PR reverts to the previous version of the expression (cc @ahgittin).
=> Fix calculation of currently used memory by the JVM

core/pom.xml
`com.maxmind.db:maxmind-db:jar:1.2.1` depends on `jackson-databind [2.7.0,)`
which causes excessive download of dependencies (all pom versions in the range,
including snapshots). We already include it explicitly anyway so can save on
the extra http requests. It's also forces maven to check frequently whether
new versions are available so it can use them.
=> Break version range dependency on jackson-databind

core/src/main/java/org/apache/brooklyn/core/entity/BrooklynConfigKeys.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/SoftwareProcess.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/lifecycle/MachineLifecycleEffectorTasks.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessEntityLatchTest.java
Adds the ability to delay stop of a software process until an appropriate sensor is published on some entity that depends on that process.
=> Add a stop latch to SoftwareProcess.

core/src/main/java/org/apache/brooklyn/policy/AbstractInvokeEffectorPolicy.java, core/src/main/java/org/apache/brooklyn/policy/InvokeEffectorOnCollectionSensorChange.java, core/src/main/java/org/apache/brooklyn/policy/InvokeEffectorOnSensorChange.java, core/src/test/java/org/apache/brooklyn/policy/AbstractInvokeEffectorPolicyTest.java, core/src/test/java/org/apache/brooklyn/policy/InvokeEffectorOnCollectionSensorChangeTest.java, core/src/test/java/org/apache/brooklyn/policy/InvokeEffectorOnSensorChangeIntegrationTest.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/networking/JcloudsLocationSecurityGroupCustomizer.java
Supports tracking the number of effector tasks that are ongoing and publishing that as an "is busy" sensor on the entity the policy is attached to. Tracking is enabled by providing a value for `isBusySensor` when configuring the policy.
=> Add AbstractInvokeEffectorPolicy

core/src/main/java/org/apache/brooklyn/util/core/task/BasicExecutionManager.java
A NullPointerException in ServiceReplacer was being swallowed in BasicExecutionManager, this makes exemptions for logging specific types of Exceptions.
=> Enable BasicExecutionManager logging for specific exceptions

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/networking/InboundPortsJcloudsLocationCustomizer.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/networking/JcloudsLocationSecurityGroupCustomizer.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/networking/NetworkingEffectors.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/networking/SharedLocationSecurityGroupCustomizer.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/networking/JcloudsLocationSecurityGroupCustomizerTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/networking/SharedLocationSecurityGroupCustomizerTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/location/NetworkingEffectorsLiveTests.java
Unite the code from 
https://github.com/apache/brooklyn-server/pull/276
and https://github.com/apache/brooklyn-server/pull/292
OPEN_INBOUND_PORTS_IN_SECURITY_GROUP_EFFECTOR tested after brooklyn restarts. All works fine.
=> Clean up duplicated code in JcloudsLocationCustomizers

software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/SoftwareProcess.java
Adds a new `ConfigKey<Map<?,?>>` to allow setting further template variable substitutions in YAML.
=> Added configuration for template substitution variable map

pom.xml
- align to version pulled in by the `kubernetes-client` feature
=> Bump version of snakeyaml to 1.16

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AbstractJcloudsRebindStubYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/DslAndRebindYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/JavaWebAppWithDslYamlRebindIntegrationTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/RebindOsgiTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindCatalogEntityTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindCatalogItemTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindCatalogWhenCatalogPersistenceDisabledTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindEntityDynamicTypeInfoTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindEntityTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindLocationTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindManagerExceptionHandlerTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindOptions.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindPolicyTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindTestFixture.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindTestUtils.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/transformer/CompoundTransformerTest.java, core/src/test/java/org/apache/brooklyn/location/byon/FixedListMachineProvisioningLocationRebindTest.java, core/src/test/java/org/apache/brooklyn/location/multi/MultiLocationRebindTest.java, launcher/src/test/java/org/apache/brooklyn/launcher/blueprints/AbstractBlueprintTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsByonLocationResolverStubbedRebindTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/RebindJcloudsLocationLiveTest.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/clocker/ClockerDynamicLocationPatternRebindTest.java
This is an attempt to fix the frequent test failures on Apache Jenkins Windows slaves. The tests would fail with `The process cannot access the file because it is being used by another process` while rebinding against the on-disk persisted state.
While I wasn't able to reproduce this I believe it's due to the tests not stopping persistence on the old management context. It probably tries to write to the persisted state while the new management context rebinds, leading to file locking errors. The fix is to stop persistence in the old management context before rebind. Note that the old management context is still kept alive, only persistence is stopped, so we can work with the old entities.
A couple of example failures:
* https://builds.apache.org/view/Brooklyn/job/brooklyn-master-windows/85 …
=> Tests - stop persistence before rebind

core/src/main/java/org/apache/brooklyn/core/mgmt/internal/NonDeploymentManagementContext.java
The transformer can be added before the entity is managed (e.g. if
specified in the entity spec, as is often done via yaml). In that case,
the entity’s management context is still a `NonDeploymentManagementContext`.
The subscriptions are stored in a queue. When the entity is managed,
the subscriptions are replayed.
However, the queued subscriptions did not store the entity context.
Therefore when the transformer received its events, it didn’t have
an entity context so could not determine which entity it was talking
about.
This caused brooklyn-library’s `EnrichersSlightlySimplerYamlTest.testWithAppEnricher`
to fail.
=> Fix Transformer (for when registered before entity managed)

core/src/main/java/org/apache/brooklyn/core/entity/AbstractApplication.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessEntityLatchTest.java
Previously in app.stop, we set the serviceUp=false before setting
expectedState=stopping. This meant there was a race where we could
briefly infer the actual state as on_fire.
This caused failure of `SoftwareProcessEntityLatchTest.testStopLatchBlocks`:
the attributeWhenReady latch would abort because it received an
event saying that the app was on_fire, so the stop_latch completely
immediately.
The fix is simple: in app.stop, set the expectedSate=stopping before
setting serviceUp=false.
@neykov @geomacy you'll both be interested in this.
=> Fix app.stop so doesn’t go on-fire briefly

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AbstractJcloudsStubYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AbstractYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ConfigParametersYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ConfigTypeCoercionYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/EntityNameYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/EntityRefsYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ExternalConfigBrooklynPropertiesTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ReferencedYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/WrapAppTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlEntityTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlRebindTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/SpecParameterParsingTest.java, camp/camp-brooklyn/src/test/resources/org/apache/brooklyn/camp/brooklyn/config-type-coercion-test.yaml, utils/common/src/main/java/org/apache/brooklyn/util/text/Strings.java, utils/common/src/test/java/org/apache/brooklyn/util/text/StringsTest.java
Several minor fixes/changes, plus one significant test in https://github.com/apache/brooklyn-server/commit/e9c1f4cbb67d1bd89d1e7d84f8730225047ea337 which highlights a change in behaviour since early Oct
Also see related PR adding this to release notes
=> Test change to coercion of default config values

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/DslComponent.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/dsl/DslTest.java, core/src/main/java/org/apache/brooklyn/core/location/internal/LocationConfigMap.java, core/src/main/java/org/apache/brooklyn/core/mgmt/BrooklynTaskTags.java, core/src/main/java/org/apache/brooklyn/core/objs/proxy/InternalEntityFactory.java, core/src/main/java/org/apache/brooklyn/util/core/config/ResolvingConfigBag.java, core/src/main/java/org/apache/brooklyn/util/core/task/BasicExecutionContext.java, core/src/main/java/org/apache/brooklyn/util/core/task/ValueResolver.java, core/src/test/java/org/apache/brooklyn/util/core/task/TasksTest.java, software/base/src/main/java/org/apache/brooklyn/entity/system_service/SystemServiceEnricher.java
When executing a task which is already tagged with a context entity in the execution context of another task, the task ends up with two context entities in its tags. It's indeterministic which one will be available through BrooklynTaskTags.getContextEntity. 
The context entity should be set by internal code at a single place. Remove all places where we are setting the context additionally and add a warning at runtime if detected. To be changed to an exception after a release or two, currently a warning in the logs.
Merge together with https://github.com/apache/brooklyn-library/pull/71.
=> Don't allow multiple context entities in a task's tags

core/src/main/java/org/apache/brooklyn/core/effector/ssh/SshCommandEffector.java, core/src/main/java/org/apache/brooklyn/core/sensor/PortAttributeSensorAndConfigKey.java, core/src/main/java/org/apache/brooklyn/core/sensor/ssh/SshCommandSensor.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicCluster.java, core/src/test/java/org/apache/brooklyn/location/ssh/SshMachineLocationTest.java, core/src/test/java/org/apache/brooklyn/util/core/xstream/XmlSerializerTest.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, parent/pom.xml, software/base/src/test/java/org/apache/brooklyn/entity/AbstractEc2LiveTest.java
SshCommandEffector resolves shell.env against the target entity rather than always resolving it against the entity the effector is attached to. This also fixes the resolution of the execution directory.
=> SshCommandEffector + shell.env

core/src/test/java/org/apache/brooklyn/util/core/http/HttpToolIntegrationTest.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/TestHttpCall.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/TestHttpCallImpl.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/TestHttpCallTest.java, utils/common/src/main/java/org/apache/brooklyn/util/http/HttpTool.java
This adds the possibility to:
- do GET, POST, PUT, DELETE and OPTIONS requests
- specify headers
- specify request body for POST and PUT requests
=> Improvement of TestHttpCall entity

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ConfigInheritanceYamlTest.java
This PR contains a failing test, which demonstrates the underlying problem in https://issues.apache.org/jira/browse/BROOKLYN-377.
I believe that https://github.com/apache/brooklyn-server/pull/385 will fix this. We should rebase + retest at that point. In particular, if I change `ValueResolver` to delete `.tagIfNotNull(BrooklynTaskTags.getTargetOrContextEntityTag(Tasks.current()))` then the test passes.
@neykov @drigodwin you'll both likely be interested in this.
=> BROOKLYN-377: adds testConfigOnParentUsesConfigKeyDeclaredOnParent

karaf/features/src/main/feature/feature.xml
- servicemix `okio` version 1.2.0_1
- still wrap: `okhttp` 2.2.0 but with explicit dependency on `okio` 1.2.x bundle
=> Use servicemix bundle for okio

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/BrooklynDslCommon.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/DslComponent.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/DslAndRebindYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/EntitiesYamlTest.java, core/src/main/java/org/apache/brooklyn/util/core/task/ValueResolver.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/TargetableTestComponentImpl.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/yaml/TestHttpCallYamlTest.java
Note this builds on https://github.com/apache/brooklyn-server/pull/416; please review + merge that PR first. I'll then rebase so the initial commits disappear.
@googlielmo you'll be interested in this.
=> BROOKLYN-381: support nested DSL for $brooklyn:entity()

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/DslComponent.java
Fixes a typo in a comment, spotted during review of https://github.com/apache/brooklyn-server/pull/417
=> [TRIVIAL] DslComponent: fix typo in comment

software/base/src/test/java/org/apache/brooklyn/entity/software/base/VanillaSoftwareProcessIntegrationTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/VanillaSoftwareProcessStreamsIntegrationTest.java
Fixes VanillaSoftwareProcessStreamsIntegrationTest.testGetsStreams,
for if run multiple times on the same machine.
@neykov can you take a quick look please?
=> SoftwareProcess integration tests: use INSTALL_UNIQUE_LABEL

utils/common/src/main/java/org/apache/brooklyn/test/Asserts.java, utils/common/src/test/java/org/apache/brooklyn/test/AssertsTest.java
And update javadoc to say why. Also makes the timeout configurable
via `-Dbrooklyn.test.defaultTimeout=1s`.
=> Asserts: use DEFAULT_LONG_TIMEOUT in eventually()

.mvn/jvm.config, parent/pom.xml
* Will be picked up when building a sub-module
* Doesn't work with `--file` option ([MNG-5889](https://issues.apache.org/jira/browse/MNG-5889))
=> Set default JVM memory settings for the build

core/src/main/java/org/apache/brooklyn/core/feed/AbstractFeed.java, core/src/main/java/org/apache/brooklyn/core/objs/AbstractEntityAdjunct.java, core/src/main/java/org/apache/brooklyn/util/core/json/BidiSerialization.java, core/src/main/java/org/apache/brooklyn/util/core/json/BrooklynObjectsJsonMapper.java, core/src/test/java/org/apache/brooklyn/core/mgmt/persist/XmlMementoSerializerTest.java, core/src/test/java/org/apache/brooklyn/core/test/entity/TestEntity.java, core/src/test/java/org/apache/brooklyn/core/test/entity/TestEntityImpl.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/SensorResourceTest.java, software/base/src/main/java/org/apache/brooklyn/entity/system_service/SystemServiceEnricher.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/ShellEnvironmentSerializerTest.java, test-support/src/main/java/org/apache/brooklyn/test/LogWatcher.java
* Also do the same for policies, enrichers and feeds.
* Adds AbstractEntityAdjunct.getEntity() to make that easier.
* Adds TestEntity.sleepEffector
And tests xml persistence of a task, while I'm at it.
=> BROOKLYN-383: fix json serialisation of tasks

launcher/src/main/java/org/apache/brooklyn/launcher/BrooklynWebServer.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/ServerApi.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/filter/CsrfTokenFilter.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/AbstractBrooklynRestResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/EntityConfigResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/LogoutResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/SensorResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ServerResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/security/jaas/SecurityProviderHttpSession.java, rest/rest-resources/src/main/resources/OSGI-INF/blueprint/service.xml, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/filter/CsrfTokenFilterTest.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/testing/BrooklynRestResourceTest.java, rest/rest-server/src/main/webapp/WEB-INF/web.xml, rest/rest-server/src/test/java/org/apache/brooklyn/rest/BrooklynRestApiLauncher.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/CsrfTokenFilterLauncherTest.java, utils/common/src/main/java/org/apache/brooklyn/util/http/HttpToolResponse.java
Adds a filter which returns and requires special cookies/headers to protect against forged cross-site requests.  Extensive documentation in `CsrfTokenFilter`.  @neykov or @m4rkmckenna or @geomacy you might be best placed to check this.
Also small tidy to logout process in https://github.com/apache/brooklyn-server/commit/e9aecbac1ccdebec1cb07f0f44c5c73f0137c64d -- would be useful if someone familiar with the thinking behind the existing process (switching to user) gives it a quick eyeball (probably @neykov or @bostko ?)
=> Use CSRF headers

core/src/main/java/org/apache/brooklyn/core/entity/BrooklynConfigKeys.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/BasicJcloudsLocationCustomizer.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/BailOutJcloudsLocation.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/BasicJcloudsLocationCustomizerTest.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/SoftwareProcess.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/lifecycle/MachineLifecycleEffectorTasksTest.java
Repeats https://github.com/apache/brooklyn-server/pull/168 but puts the location customizers into the entity's provisioning properties rather than setting it on the entity directly. It required moving `SoftwareProcess.PROVISIONING_PROPERTIES` to `BrooklynConfigKeys` so that it could be referenced from `brooklyn-locations-jclouds`.
=> BasicJcloudsLocationCustomizer is an EntityInitializer

core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/BasicLocationRebindSupport.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindLocationTest.java, core/src/test/java/org/apache/brooklyn/location/localhost/LocalhostLocationResolverRebindTest.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/lifecycle/MachineLifecycleEffectorTasks.java
When rebinding a location, if a config flag corresponds to a field
with `@SetFromFlag` then just set the field, and don’t leave the 
key-value inside `config().getBag()`.
Some classes use fields to store internal state, which should not be
passed to child locations (e.g. `LocalhostMachineProvisioningLocation.origConfigs`).
=> BROOKLYN-396: test and fix

core/src/main/java/org/apache/brooklyn/core/location/Machines.java, core/src/test/java/org/apache/brooklyn/core/location/MachinesTest.java
The `SshMachineLocation` interface does *NOT* implement `HasSubnetHostname` but it does include the method `getPrivateAddresses()` which means that when something creates a machine and sets the config key `SshMachineLocation.PRIVATE_ADDRESSES` with the private IP then the `machines.getSubnetHostname(Location)` helper method (called during entity startup) will happily set the `SUBNET_HOSTNAME` attribute to the public IP (via `location.getAddress().getHostAddress()`
=> Use subnet IP on machine locations that dont implement HasSubnetHostname

core/src/test/java/org/apache/brooklyn/core/entity/ApplicationLifecycleStateTest.java
This test is failing occasionally (non-deterministically) when running `mvn clean install`. Therefore disabling until we make it more reliable!
=> Disable testChildFailuresOnStartButWithQuorumCausesAppToSucceed

test-framework/src/main/java/org/apache/brooklyn/test/framework/TestHttpCall.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/TestHttpCallImpl.java
This enables self signed and other certificates to be used within `TestHttpCall`. Tested on AWS with the [brooklyncentral/brooklyn-tomcat-7-server](https://github.com/brooklyncentral/brooklyn-tomcat-7-server) tests.
=> Allow all certs in TestHttpCall

core/src/test/java/org/apache/brooklyn/core/mgmt/persist/FileBasedStoreObjectAccessorWriterTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindTestUtils.java
File access locks for exactly 30 seconds in Virtualbox.
=> Increase persistence timeout

core/src/main/java/org/apache/brooklyn/core/entity/lifecycle/ServiceStateLogic.java, core/src/test/java/org/apache/brooklyn/core/entity/ApplicationLifecycleStateTest.java, core/src/test/java/org/apache/brooklyn/core/entity/lifecycle/ServiceStateLogicTest.java
`ComputeServiceState.onEvent` should only be called in the event handler executor to keep the ordering of events.
Before the change what would happen is on calling `setExpectedState(state)` a "state.expected" event would be scheduled, with `ComputeServiceState.onEvent(null)` called in the same thread right after. This would create a race condition when calling `setExpectedState` in quick succession (`onEvent` called from the `setExpectedState` thread and from the event handler thread with different values).
=> Fix out of order events triggered by ComputeServiceState

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/ComputeServiceRegistryImpl.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsRateLimitedRetryLiveTest.java
Question: Is 500ms and 6 retries a sensible level? It feels to me like a large backoff is good for API calls to a cloud. I can see this might slow things down in some situations (e.g. when it was a transient connectivity problem), but that still seems unlikely to happen often. In all the important cases I can think of, a larger backoff + retry time seems desirable.
When running the `testCreateMany` to provision 20 VMs concurrently in AWS, I managed to cause rate-limiting when calling `RunInstances`, getting back `503 Service Unavailable` for 6 of the 20 VMs:
```
grep -E "JavaUrlHttpCommandExecutorService.*Receiving.* 503 Service Unavailable" brooklyn.debug.log 
2016-11-20 21:41:07,014 DEBUG o.j.h.i.JavaUrlHttpCommandExecutorService [pool-3-thread-7]: Receiving response 305126632: HTTP/1.1 …
```
=> BROOKLYN-394: increase jclouds retry/backoff time

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ConfigYamlTest.java, core/src/test/java/org/apache/brooklyn/core/test/entity/TestEntity.java, core/src/test/java/org/apache/brooklyn/core/test/entity/TestEntityImpl.java
@neykov here are some additional tests to demonstrate the behaviour of `@SetFromFlag`, and config either at the top-level YAML or inside the `brooklyn.config:`.
=> ConfigYaml test (for @SetFromFlag variants)

core/src/main/java/org/apache/brooklyn/core/entity/lifecycle/ServiceStateLogic.java, core/src/test/java/org/apache/brooklyn/core/entity/ApplicationLifecycleStateTest.java, core/src/test/java/org/apache/brooklyn/core/entity/lifecycle/ServiceStateLogicTest.java
@neykov (cc @Graeme-Miller) can you review please?
As discussed in https://github.com/apache/brooklyn-server/pull/454 (due to the failing test in its PR build for `LoopOverGroupMembersTestCaseTest.testMultipleChildrenWhichPass`), a lot of places expect the actual state to have been calculated/set by the time that `setExpectedState()` has returned.
Short-term, it's better than we live with the race-condition fixed by https://github.com/apache/brooklyn-server/pull/452, rather than change the semantics of `setExpectedState()`.
=> Revert #452: setExpectedState sets actualState synchronously

core/src/main/java/org/apache/brooklyn/core/mgmt/internal/BrooklynGarbageCollector.java, core/src/test/java/org/apache/brooklyn/core/mgmt/internal/EntityExecutionManagerTest.java
Background tasks get in the way, messing with the logic of what to evict next.
Note that this only changes the expectations in the tests, doesn't improve the GC as suggested in BROOKLYN-401.
=> [BROOKLYN-401] Fix failing GC tasks test

karaf/pom.xml, parent/pom.xml
Version 0.12 adds the option to dump licence violations to the console.
Also removes the unused rat-check profile, the plugin is already included in the default build in build/plugins.
=> Upgrade rat plugin version

core/src/main/java/org/apache/brooklyn/core/entity/EntityInternal.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/LocalEntityManager.java, core/src/main/java/org/apache/brooklyn/entity/group/AbstractGroupImpl.java, core/src/test/java/org/apache/brooklyn/entity/group/GroupTest.java
As discussed with @geomacy in https://github.com/apache/brooklyn-server/pull/453#discussion_r89106124 ...
Making these fields non-private is asking for trouble - it makes it
harder to reason about what the class does and whether it’s safe,
particularly around thread safety etc.
It is also exposing more implementation detail than is required, making
refactoring harder in the future.
If there is a compelling reason to provide access to the fields,
we can consider adding accessor(s).
=> LocalEntityManager: make fields private

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/ComputeServiceRegistryImpl.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/AbstractJcloudsLiveTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/AbstractJcloudsStubbedLiveTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsAwsImageChoiceStubbedLiveTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsHardwareProfilesStubbedLiveTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsImageChoiceStubbedLiveTest.java
See https://issues.apache.org/jira/browse/BROOKLYN-399 for a description of the surprisingly large performance boost we get from this simple change!
=> BROOKLYN-399: aws-ec2 only looks up images in specified region

launcher/src/test/java/org/apache/brooklyn/rest/jsgui/BrooklynJavascriptGuiLauncher.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/BrooklynPropertiesSecurityFilterTest.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/BrooklynRestApiLauncher.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/BrooklynRestApiLauncherTest.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/BrooklynRestApiLauncherTestFixture.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/CsrfTokenFilterLauncherTest.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/HaMasterCheckFilterTest.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/entitlement/AbstractRestApiEntitlementsTest.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/resources/ServerResourceIntegrationTest.java
improves logic of #434 -- https://github.com/apache/brooklyn-server/pull/434/commits/bfdf522c452df262b3b4bb55cd567ddf45b31fa7
that change caused some tests to fail if you had a security provider set in `brooklyn.properties` locally!  this ensures that an explicit `AnyoneSecurityProvider` is respected.
=> if AnyoneSecurityProvider is set explicitly then switch it out for Nop

locations/jclouds/pom.xml, parent/pom.xml, pom.xml
jclouds now correctly imports the dual-licensed version of jna, 
so we can rely on that rather than excluding it ourselves.
See https://github.com/jclouds/jclouds/commit/b3882cbfed873a5975d4918d1fb8b836b544c421. This is definitely in jclouds 1.9.2. (and 1.9.3 as well): see https://github.com/jclouds/jclouds/blob/rel/jclouds-1.9.2/drivers/sshj/pom.xml#L110.
With this change, looking at `mvn dependency:tree -Dverbose` includes the output below, and shows that the only "jna" dependencies are version 4.1.0.
```
[INFO] |     +- com.jcraft:jsch.agentproxy.usocket-jna:jar:0.0.8:compile
[INFO] |     |  +- net.java.dev.jna:jna:jar:4.1.0:compile
[INFO] |     |  \- net.java.dev.jna:jna-platform:jar:4.1.0:compile
[INFO] |     |     \- (net.java.dev.jna:jna:jar:4.1.0:compile - omitted for duplicate) …
```
=> Remove net.java.dev.jna dependency exclusion

test-framework/src/main/java/org/apache/brooklyn/test/framework/TestHttpCallImpl.java
This fixes HTTPS YAML tests. Previously the `trustAll(trustAll)` was not working due to no URL being specified during the build method which caused it to be ignored [here](https://github.com/apache/brooklyn-server/blob/master/utils/common/src/main/java/org/apache/brooklyn/util/http/HttpTool.java#L361).
=> Fix https tests

core/src/main/java/org/apache/brooklyn/core/effector/Effectors.java, core/src/main/java/org/apache/brooklyn/core/entity/Entities.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicCluster.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicClusterImpl.java, core/src/main/java/org/apache/brooklyn/util/core/task/ParallelTask.java, core/src/main/java/org/apache/brooklyn/util/core/task/SequentialTask.java, core/src/test/java/org/apache/brooklyn/entity/group/DynamicClusterRebindTest.java, core/src/test/java/org/apache/brooklyn/entity/group/DynamicClusterTest.java
The option configures the maximum number of simultaneous `Startable` effector invocations that will be made on members of the group.
=> Adds maxConcurrentChildCommands parameter to DynamicCluster

pom.xml
Depends on #457. Fixes wiring problems with the new jclouds in Karaf.
`jclouds 1.9.3` depends on guava [16-20), so it will bind to the latest version it finds - which is 18. And Brooklyn is stuck on 16.0.1. Bumping Brooklyn to 18.0 moves everything to depend on the same version of guava thus solving the wiring problems.
Note that `guava-16.0.1` is still pulled in the Karaf distribution by [jclouds](https://github.com/jclouds/jclouds-karaf/blob/master/feature/src/main/resources/feature.xml#L30). But is not loaded at runtime.
=> Upgrade guava to v18.0

core/src/test/java/org/apache/brooklyn/location/ssh/SshMachineLocationIntegrationTest.java, core/src/test/java/org/apache/brooklyn/location/ssh/SshMachineLocationTest.java
The test requires an ssh server to be listening on port 22.
=> Fix project build, mark test as integration

karaf/features/pom.xml, pom.xml
Deploying the project as is leads to the creation of two staging repos. With modules using the `karaf-maven-plugin` in one and the rest in the other bucket.
This is caused by a bug in `wagon-http-2.8` already fixed in maven 3.3.3. `karaf-maven-plugin` has a dependency on `wagon-http-2.8` so it pulls in the version even in versions of maven that use later (and fixed) releases.
Nexus will create a unique repo based on a number of factors - the IP of the user and the User-Agent being included. If one of those changes during deployment it will lead to a new staging repo being created.
Changes already applied on 0.10.0 branch.
Merge together with https://github.com/apache/brooklyn-library/pull/81 and https://github.com/apache/brooklyn-dist/pull/66.
=> Upgrade karaf-maven-plugin to avoid double User-Agent bug

core/src/main/java/org/apache/brooklyn/entity/stock/LocationEntity.java, core/src/main/java/org/apache/brooklyn/entity/stock/LocationEntityImpl.java, core/src/test/java/org/apache/brooklyn/entity/stock/LocationEntityTest.java
A new type that allows configuring different entities depending on the location being deployed to. Uses configuration like this:
```YAML
- type: org.apache.brooklyn.entity.stock.LocationEntity
location.entity.spec.default:
$brooklyn:entitySpec:
type: traefik-load-balancer
location.entity.spec.aws-ec2:
$brooklyn:entitySpec:
type: elastic-load-balancer
location.entity.spec.gce:
$brooklyn:entitySpec:
type: google-load-balancer
```
The map entries can also be class names like `JcloudsLocation` or ISO 3166 country codes like `UK`.
=> Adding new LocationEntity for creating location specific entities

pom.xml
Freemarker 2.3.25 adds support for iterating over map entries, which will be useful for some entity implementations.
@ygy could you review this please?
=> Upgrade free marker to 2.3.25 (from 2.3.22)

karaf/features/src/main/feature/feature.xml
JMX in a Tomcat deployment was failing in Karaf with the exception `java.lang.RuntimeException: java.io.IOException: java.lang.ClassNotFoundException: javax.management.openmbean.CompositeDataSupport`. This was because of a missing dependency from the wrap of `org.glassfish.external/opendmk_jmxremote_optional_jar`. 
Unfortunately adding an `$Import-Package=javax.management.openmbean` here would exclude the other files included from the jar so `$DynamicImport-Package` is used.
=> Fix JMX Karaf import

core/src/main/java/org/apache/brooklyn/core/mgmt/persist/ClasspathConfigLoader.java, core/src/main/java/org/apache/brooklyn/core/mgmt/persist/ConfigLoader.java, core/src/main/java/org/apache/brooklyn/core/mgmt/persist/DeserializingClassRenamesProvider.java, karaf/init/src/main/java/org/apache/brooklyn/launcher/osgi/OsgiConfigLoader.java, karaf/init/src/main/resources/OSGI-INF/blueprint/blueprint.xml
This will make the code search for another file `etc/org.apache.brooklyn.persistence.class.rename.properties` during the deserialization and load the properties accordingly.
The file `etc/org.apache.brooklyn.persistence.class.rename.properties` does not exist by default but can be created manually. The aim is for any blueprint author to setup rewrite rules for the persistence state, if some classnames from its own blueprints change. Of course, the default rules provided by Brooklyn are always loaded
=> Allow a user to add or override deserialize configuration in karaf

core/src/main/java/org/apache/brooklyn/util/core/config/ResolvingConfigBag.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/ComputeServiceRegistryImpl.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/zone/AwsAvailabilityZoneExtensionTest.java
This fixes the deployment of blueprints that give a specific availability zone as the region. For example:
```yaml
location:
jclouds:aws-ec2:
region: us-east-1b
services:
- type: org.apache.brooklyn.entity.webapp.tomcat.Tomcat8Server
```
The problem was introduced in the fix for https://issues.apache.org/jira/browse/BROOKLYN-399 (see #458). Setting `LocationConstants.PROPERTY_REGIONS` to a region like `us-east-1b` causes jclouds to throw an `IllegalStateException` in `TemplateBuilder#locationId`.
=> Drop availability zone suffixes when configuring AWS regions

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogOsgiLibraryTest.java, utils/common/src/main/java/org/apache/brooklyn/test/http/TestHttpRecordingRequestInterceptor.java, utils/common/src/main/java/org/apache/brooklyn/test/http/TestHttpRequestHandler.java, utils/common/src/main/java/org/apache/brooklyn/test/http/TestHttpServer.java
This PR only improves test coverage, and adds a failing test for BROOKLYN-421 (marked as `groups="Broken"`). It does not attempt to fix the actual issue.
=> BROOKLYN-421: add tests for catalog library loading

karaf/init/src/main/java/org/apache/brooklyn/launcher/osgi/OsgiLauncher.java, karaf/init/src/main/resources/OSGI-INF/blueprint/blueprint.xml
default catalog location can now be configured using the below PID
`org.apache.brooklyn.osgilauncher/default.catalog.location`
default has been set as `${karaf.etc}/default.catalog.bom`
⚠️  Depends on https://github.com/apache/brooklyn-dist/pull/76
=> Make the default catalog location configurable

core/src/main/resources/org/apache/brooklyn/core/mgmt/persist/jcloudsProviderRenames.properties
This adds the `jcloudsProviderRenames.properties` file missing from #508
=> Add jcloudsProviderRenames.properties

karaf/init/src/main/resources/OSGI-INF/blueprint/blueprint.xml
The delimiter for DependsOn is a space not a comma
=> DependsOn delimiter change

karaf/features/src/main/feature/feature.xml
This adds the Azure classic and Azure ARM locations from jclouds labs to the karaf features.
=> Add Azure Location

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AbstractYamlTest.java
This is useful for writing more advanced tests that want to use YAML - in particular, I want it for refactoring performance/load tests such as https://github.com/apache/brooklyn-library/blob/master/qa/src/test/java/org/apache/brooklyn/qa/load/LoadTest.java (which need a major overhaul - I made a start on that; PR to follow soon hopefully).
=> AbstractYamlTest: make setUpPlatform overridable

core/src/main/java/org/apache/brooklyn/core/location/LocationConfigKeys.java, core/src/main/java/org/apache/brooklyn/core/location/cloud/CloudLocationConfig.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/ComputeServiceRegistryImpl.java
`oauth.endpoint` is required by Azure ARM but isn't passed through to the jcloudsProperties.
=> Allow oauth.endpoint in location

core/src/test/java/org/apache/brooklyn/core/mgmt/persist/DeserializingJcloudsRenamesProviderTest.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/ComputeServiceRegistryImpl.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsUtil.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsRenamesRebindTest.java
Without this fix, I get errors when rebinding to my existing persisted state that had used `openstack-mitaka-nova`. The error was:
```
2017-01-12 13:08:09,540 DEBUG 127 o.a.b.l.j.JcloudsSshMachineLocation [Timer-1] Problem getting image for SshMachineLocation[10.104.2.116:amp@10.104.2.116/10.104.2.116:22(id=bwjjhxas6l)], image id RegionOne/e16a7bca-7363-45b1-bd6a-0
2479d4cea77 (continuing)
java.util.NoSuchElementException: key [openstack-mitaka-nova] not in the list of providers or apis: {providers=[softlayer, go2cloud-jhb1, aws-s3, openhosting-east1, aws-ec2, serverlove-z1-man, elastichosts-sat-p, elastichosts-lon-b, gogrid, skalicloud-sdg-my, rackspace-cloudfiles-uk, azureblob, elastichosts-lon-p, rackspace-cloudfiles-us, rackspace-cloudservers-us, azurecompute-arm, …
```
=> Fix+test rename-jclouds-provider

core/src/main/java/org/apache/brooklyn/core/policy/AbstractPolicy.java, core/src/main/java/org/apache/brooklyn/entity/group/AbstractMembershipTrackingPolicy.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindDynamicGroupTest.java, core/src/test/java/org/apache/brooklyn/entity/group/MembershipTrackingPolicyRebindTest.java
This means you don't get more `added` events for things that were already in the group. I think this is the expected behaviour.
=> AbstractMemberTrackingPolicy does not call MEMBER_ADDED on group members when rebinding

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/ComputeServiceRegistryImpl.java
The Azure ARM jclouds provider loads hardware details from all regions unless the one on which we are going to launch is specified.
=> Specify the Azure ARM region

core/src/main/java/org/apache/brooklyn/core/location/cloud/CloudLocationConfig.java, core/src/main/java/org/apache/brooklyn/core/location/cloud/names/BasicCloudMachineNamer.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsMachineNamer.java, utils/common/src/main/java/org/apache/brooklyn/util/text/StringShortener.java, utils/common/src/test/java/org/apache/brooklyn/util/text/StringShortenerTest.java
Azure ARM only allows alphanumeric characters in it's naming. The default for Brooklyn is to use `-` characters to split up blocks of alphanumeric chars which breaks this. This adds an exception for `azurecompute-arm` in the same style as VM name length.
Tested with Tomcat 7 on Azure ARM, AWS and OpenStack
=> Fix Azure ARM VM names

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/networking/SecurityGroupEditor.java
A small enhancement to support use cases where you have the id of a group you want to delete; this addition allows you to delete the group with just the id, rather than have an extra round-trip to fetch the group so you can then delete it.
=> Add removeSecurityGroup by id

core/src/main/java/org/apache/brooklyn/core/BrooklynFeatureEnablement.java, karaf/features/src/main/feature/feature.xml, karaf/init/pom.xml, launcher/src/main/java/org/apache/brooklyn/launcher/BrooklynWebServer.java, rest/rest-resources/pom.xml, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/filter/CorsImplSupplierFilter.java, rest/rest-resources/src/main/resources/OSGI-INF/blueprint/service.xml, rest/rest-server/src/main/webapp/WEB-INF/web.xml, rest/rest-server/src/test/java/org/apache/brooklyn/rest/BrooklynRestApiLauncher.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/CorsFilterLauncherTest.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/CsrfTokenFilterLauncherTest.java
Include org.apache.cxf.rs.security.cors.CrossOriginResourceSharing implementation
=> Add experimental CORS server support

core/src/main/java/org/apache/brooklyn/util/core/LoaderDispatcher.java
See https://issues.apache.org/jira/browse/BROOKLYN-426 for details.
Tested this with a badly behaving bundle, and confirmed that we were able to list the catalog contents when this fix is used.
=> BROOKLYN-426: avoid propagating NoClassDefFoundError

core/src/main/java/org/apache/brooklyn/core/config/ConfigUtils.java, core/src/main/java/org/apache/brooklyn/core/internal/BrooklynProperties.java, core/src/main/java/org/apache/brooklyn/core/internal/BrooklynPropertiesImpl.java, core/src/main/java/org/apache/brooklyn/core/location/BasicLocationDefinition.java, core/src/main/java/org/apache/brooklyn/core/location/BasicLocationRegistry.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/BasicExternalConfigSupplierRegistry.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/DeferredBrooklynProperties.java, core/src/test/java/org/apache/brooklyn/core/config/BrooklynPropertiesBuilderTest.java, core/src/test/java/org/apache/brooklyn/core/config/BrooklynPropertiesTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/internal/LocalManagementContextTest.java, launcher/src/main/java/org/apache/brooklyn/launcher/BrooklynLauncher.java, launcher/src/test/java/org/apache/brooklyn/launcher/BrooklynLauncherRebindToCloudObjectStoreTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/BailOutJcloudsLocation.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsLocationTest.java, software/base/src/main/java/org/apache/brooklyn/entity/brooklynnode/LocalBrooklynNodeImpl.java
As discussed in https://issues.apache.org/jira/browse/BROOKLYN-404, the fix is to change `BrooklynProperties` so it no longer exposes the map interface. This means we can much more easily control its mutators and its accessors to avoid such `ConcurrentModificationException`s.
This PR does *not* do anything about @neykov's additional suggestion in jira: "Taking a step back I think we should either let users update the properties in a non-hackish way (that is include the mutators in the interface which getConfig() returns) or introduce an alternative "scratch" space to serve the same purpose."
Currently, if someone wants to modify the `BrooklynProperties`, it needs to be cast to `BrooklynProperties` (whereas `managementContext.getConfig()` returns `StringConfigMap`, which is a …
=> BROOKLYN-404: fix ConcurrentModificationException in BrooklynProperties

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/JcloudsCustomizerInstantiationYamlDslTest.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java
preRelease and postRelease of JcloudsLocationCustomizers are not being 
called as expected during the release of a Jclouds machine location.
The problem is that the "setup" used in JcloudsLocation.obtainOnce includes a copy of the flags passed from MachineLifecycleEffectorTasks#stopAnyProvisionedMachines,
which includes the customizers. However, the "setup" used in the "release"
method of JcloudsLocation is taken from the JcloudsLocation itself, which
is the provisioning (i.e. parent) location, which doesn't have those 
customizers in it.
It would actually make more sense to get the location customizers from
the machine location, as a given parent could have mutiple machines
with different customizers.
The changes here include an addition to the …
=> JcloudsLocation is not releasing its customizers (BROOKLYN-427)

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsUtil.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsLocationReachabilityPredicateInstantiationTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/networking/JcloudsReachableAddressStubbedTest.java, utils/common/src/main/java/org/apache/brooklyn/util/net/Networking.java, utils/common/src/main/java/org/apache/brooklyn/util/net/ReachableSocketFinder.java, utils/common/src/test/java/org/apache/brooklyn/util/net/ReachableSocketFinderTest.java
This changes the semantics of ReachableSocketFinder. Previously it would return as soon as any host+port was reached. Now it determines the status of each socket in order. The checks are concurrent but, for example, if the third of five sockets is reachable the status of the first and second will also be determined.
These changes are motivated by some other work on JcloudsLocation that I will open a pull request for shortly.
=> Add findOpenSocketsOnNode to ReachableSocketFinder

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/DslDeferredFunctionCall.java, core/src/main/java/org/apache/brooklyn/core/sensor/DependentConfiguration.java, core/src/main/java/org/apache/brooklyn/core/sensor/MaxConcurrencySensor.java, core/src/main/java/org/apache/brooklyn/core/sensor/ReleaseableLatch.java, core/src/main/java/org/apache/brooklyn/util/core/task/ValueResolver.java, core/src/main/java/org/apache/brooklyn/util/core/task/ValueResolverIterator.java, core/src/test/java/org/apache/brooklyn/core/sensor/MaxConcurrencySensorTest.java, core/src/test/java/org/apache/brooklyn/core/sensor/ReleaseableLatchRebindTest.java, core/src/test/java/org/apache/brooklyn/core/test/BrooklynMgmtUnitTestSupport.java, core/src/test/java/org/apache/brooklyn/util/core/task/ValueResolverIteratorTest.java, core/src/test/java/org/apache/brooklyn/util/core/task/ValueResolverTest.java, software/base/src/main/java/org/apache/brooklyn/entity/chef/ChefLifecycleEffectorTasks.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/SoftwareProcessDriverLifecycleEffectorTasks.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/lifecycle/MachineLifecycleEffectorTasks.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessEntityLatchTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/test/mysql/DynamicToyMySqlEntityBuilder.java, utils/common/src/main/java/org/apache/brooklyn/test/Asserts.java, utils/common/src/main/java/org/apache/brooklyn/util/guava/Maybe.java
Setting a `ReleaseableLatch` as the latch of a `SoftwareProcess` allows for controlling the behaviour of the start/stop effector.
When `ReleaseableLatch.Factory.maxConcurrency(int)` is used as the value of the latch (either directly or by referncing a `MaxConcurrencySensor`) only the specified maximum number of threads will be able to execute the immediate step the latch is guarding.
It's very similar to `DynamicCluster.MAX_CONCURRENT_CHILD_COMMANDS` but allows for finer-grained control (though is specific to `SoftwareProcess`).
Merge together with https://github.com/apache/brooklyn-library/pull/87.
=> Limit parallelism of start/stop steps on SoftwareProcess

core/src/main/java/org/apache/brooklyn/core/mgmt/persist/DeserializingProvider.java, logging/logback-includes/src/main/resources/brooklyn/logback-logger-excludes.xml
* SSHJ logging goes to debug log only
* Users don't need to see config cache size
=> Silence the info log

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsSshMachineLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsWinRmMachineLocation.java
Avoids direct access to `node` field, which may be `null`.
=> Avoid NPE on getSubnetIp()

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsSshMachineLocation.java
Config access during rebind causes unfortunate edge-case for customer using an externalised config supplier that delegates to another entity (so not really "external") which is not guaranteed to have rebound.
Lazily instantiate `runScriptFactory` to prevent config access during rebind.
=> Avoid config access during rebind

core/src/main/java/org/apache/brooklyn/core/location/internal/LocationConfigMap.java
Turns out it's too chatty, with non-trivial callers to add calling context to.
=> Don't log the "No location resolving context found" error by default

core/pom.xml, karaf/features/src/main/feature/feature.xml, karaf/pom.xml, parent/pom.xml, pom.xml
Behaves much better using Karaf 4.0.8 - I can successfully start Karaf and run the REST API with web client.
Needs more testing, also needs confirming whether all previous changes are needed.
---
4.0.6 description
Changes due to:
- avoid rewiring from system bundle to javax.annotation-api at a later stage, leading to rewiring. Introduce a dependency on javax.annotation-api as early as possible (from brooklyn-core in this case)
- Reorder bundle loading - rest-resources after karaf-init because it depends on the ManagementContext service
Do not merge as Karaf 4.0.6 has an error which prevents rest-resources from loading. For more details see https://issues.apache.org/jira/browse/KARAF-4720, https://github.com/apache/karaf/pull/241. 
4.0.7 is just about to be released, the patch wasn't …
=> Upgrade to Karaf 4.0.8

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/DslComponent.java, core/src/test/java/org/apache/brooklyn/core/config/MapListAndOtherStructuredConfigKeyTest.java, pom.xml, utils/common/src/main/java/org/apache/brooklyn/util/javalang/coerce/EnumTypeCoercions.java
These changes are needed to compile Brooklyn with JDK 1.8, if/when we switch to Java 1.8.
At the same time they work with 1.7, which remains the selected `java.version` for compiling.
- minor source changes (generics)
=> Get ready for compiling with JDK 1.8 / Java 1.8

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/BrooklynDslCommon.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AbstractYamlRebindTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/DslAndRebindYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogOsgiLibraryTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/DslTest.java, core/src/main/java/org/apache/brooklyn/core/sensor/DependentConfiguration.java, utils/common/src/main/java/org/apache/brooklyn/util/net/Urls.java, utils/common/src/test/java/org/apache/brooklyn/util/net/UrlsTest.java
As stated in the comments within the code, the url encoding is based on "x-www-form-urlencoded". Therefore care must be taken if encoding username or password (e.g. in http://myuser:mypass@myhost"). It will not encode space correctly, and will not escape "*". The latter we can probably live with, but the former will be wrong.
=> BROOKLYN-421: Adds DSL for $brooklyn:urlEncode(...)

core/src/main/java/org/apache/brooklyn/core/objs/AbstractConfigurationSupportInternal.java, core/src/test/java/org/apache/brooklyn/core/config/ConfigTypeCoercionTest.java
Deferred values are not resolved in certain cases when in containers. The error I was getting was:
```
2017-01-27 16:44:23,958 DEBUG 118 o.a.b.c.b.s.d.BrooklynDslDeferredSupplier [ger-GCJlrQu1-259] Resolved DynamicClusterImpl{id=q9r9izpwme} from $brooklyn:sensor("kubernetes.url")
2017-01-27 16:44:23,958 DEBUG 118 o.a.b.c.b.s.d.BrooklynDslDeferredSupplier [ger-GCJlrQu1-625] Resolved Sensor: kubernetes.url (java.lang.Object) from $brooklyn:sensor("kubernetes.url")
2017-01-27 16:44:23,959 WARN  143 o.a.b.u.j.c.TypeCoercerExtensible [ger-GCJlrQu1-628] Failed to coerce collection from java.util.Collections$UnmodifiableRandomAccessList to java.util.Collection<? exten
ds org.apache.brooklyn.api.sensor.Sensor<?>>; returning uncoerced result to preserve (deprecated) backwards compatibility …
```
=> Resolve deferred values in containers (list, map) on config().getNonBlocking(...)

software/base/src/test/java/org/apache/brooklyn/entity/AbstractEc2LiveTest.java, software/base/src/test/java/org/apache/brooklyn/entity/AbstractMultiDistroLiveTest.java, software/base/src/test/java/org/apache/brooklyn/entity/AbstractOpenstackLiveTest.java, software/base/src/test/java/org/apache/brooklyn/entity/SimpleAppOpenstackLiveTest.java
A bit of refactoring to add openstack live test. There is some
work required to tidy and rationalize the various multi platform
live tests; this isn't it but may be a first step.
This change pulls up some functionality from the AbstractEc2LiveTest 
into a base class  AbstractMultiDistroLiveTest. 
The aws-ec2 live test then is a child of that, and there 
is also a new base class, AbstractOpenstackLiveTest, to do the same
job for Openstack. The comments describe how to use it.
This change is only to add this class as a basis for further tests to come.
=> Add Openstack live test.

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/networking/SecurityGroupEditor.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/networking/JcloudsLocationSecurityGroupCustomizerTest.java
jclouds on AWS uses 'jclouds#' while on Openstack it is 'jclouds-'.
Also fix some incorrect log messages and add a bit of detail to them.
=> SecurityGroupEditor- Allow for different jclouds prefixes on different clouds

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/BrooklynImageChooser.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/BrooklynImageChooserTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsAwsImageChoiceStubbedLiveTest.java
As discusson on the Apache Brooklyn discussion mailing list this PR updates BrooklynImageChooser to prefer centos over ubuntu
=> Prefer centos 7

utils/common/src/main/java/org/apache/brooklyn/util/repeat/Repeater.java, utils/common/src/test/java/org/apache/brooklyn/util/repeat/RepeaterTest.java
The Future returned by the Executor can be cancelled if it does not return a value after the required timeout.
=> Make the Repeater class use a threads to execute the checks

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AbstractYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ReferencedOsgiYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ReferencedYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogOsgiYamlEntityTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogOsgiYamlLocationTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogOsgiYamlPolicyTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogOsgiYamlTemplateTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlEntityTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlLocationTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlTemplateTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/SpecParameterParsingOsgiTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/SpecParameterParsingTest.java, core/src/test/java/org/apache/brooklyn/feed/function/FunctionFeedTest.java, core/src/test/java/org/apache/brooklyn/policy/InvokeEffectorOnCollectionSensorChangeTest.java, policy/src/test/java/org/apache/brooklyn/policy/ha/ServiceReplacerTest.java
Starting an embedded OSGi container is slow - over half a second per `setUp()` call (and thus per test method) that uses it. It will likely be considerably slower on the jenkins build machine etc. This PR separates out those classes that include an embedded OSGi container into those tests that actually need it and those that don't. It primarily moves code around (e.g. separating out the osgi-based tests from `CatalogYamlLocationTest` into a new `CatalogOsgiYamlLocationTest`).
It also cherry-pick @ahgittin's commit that was included in https://github.com/apache/brooklyn-server/pull/480 (which marks some more slow tests as "integration").
If you're wondering why just moving the code has resulted in a bunch of extra lines (`+1,956 −1,038` according to the "Files changed" summary), there are …
=> Speed up tests

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AbstractYamlRebindTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/CompositeEffectorYamlRebindTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/CompositeEffectorYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/HttpCommandEffectorYamlRebindTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/HttpCommandEffectorYamlTest.java, core/src/main/java/org/apache/brooklyn/core/effector/AddSensor.java, core/src/main/java/org/apache/brooklyn/core/effector/CompositeEffector.java, core/src/main/java/org/apache/brooklyn/core/effector/Effectors.java, core/src/main/java/org/apache/brooklyn/core/effector/http/HttpCommandEffector.java, core/src/main/java/org/apache/brooklyn/core/entity/EntityInitializers.java, core/src/main/java/org/apache/brooklyn/core/sensor/http/HttpRequestSensor.java, core/src/test/java/org/apache/brooklyn/core/effector/CompositeEffectorIntegrationTest.java, core/src/test/java/org/apache/brooklyn/core/effector/CompositeEffectorTest.java, core/src/test/java/org/apache/brooklyn/core/effector/http/HttpCommandEffectorIntegrationTest.java, core/src/test/java/org/apache/brooklyn/core/effector/http/HttpCommandEffectorTest.java, core/src/test/resources/org/apache/brooklyn/core/effector/http/int-response.json, core/src/test/resources/org/apache/brooklyn/core/effector/http/list-response.json, core/src/test/resources/org/apache/brooklyn/core/effector/http/login.json, core/src/test/resources/org/apache/brooklyn/core/effector/http/map-response.json, core/src/test/resources/org/apache/brooklyn/core/effector/test.json, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/EffectorApi.java
- add HttpCommnadEffector
- add CompositeEffector
- add EntityInitializers util class to resolve DSL injected as params
into the HttpCommandEffector
---
It is based on https://github.com/apache/brooklyn-server/pull/152 which was not merged as it didn't handle rebind properly, happy to sort it out in this PR but I've not touched rebinding yet.
=> initial work to support HttpEntity

core/src/main/java/org/apache/brooklyn/core/mgmt/BrooklynTaskTags.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/LocalSubscriptionManager.java
previously they didn't even have a name; now they have a nice name, description, and a tag.
there is some attempt to optimize the use of toString so it isn't hugely computationally expensive,
although this will increase expense a bit; i tend to think it's worth it for increased visibility.
(if we are publishing vast numbers of sensor events maybe we are doing something wrong, and if this
is identified as the bottleneck we can parameterise it, and in any case when we come to be multi-host
we'll need to revisit how we do this as currently we're thinking a good datastore is good enough for
the intended volumes, as opposed to a dedicated message bus.)
=> better presentation for sensor publishing tasks

core/src/main/java/org/apache/brooklyn/core/entity/AbstractApplication.java, core/src/test/java/org/apache/brooklyn/core/entity/ApplicationLifecycleStateTest.java
A bug was introduced in https://github.com/apache/brooklyn-server/pull/393 where if there are errors in a custom `Application.doStart(...)`, the `start` effector fails but the application does not.
This corrects that using a special exception to allow children problems to pass through.
/cc @sjcorbett @neykov
=> Fix application start problems

core/src/main/java/org/apache/brooklyn/core/mgmt/classloading/JavaBrooklynClassLoadingContext.java
The rename was used for loading from app classpath, but not for the white-list fallbacks.
=> Apply class renames mapping to white-listed bundles

core/src/main/java/org/apache/brooklyn/core/location/cloud/CloudLocationConfig.java, core/src/main/java/org/apache/brooklyn/util/core/task/BasicTask.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/ConnectivityResolver.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/ConnectivityResolverOptions.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/DefaultConnectivityResolver.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocationConfig.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsUtil.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/ManagementAddressResolveResult.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/AbstractJcloudsStubbedLiveTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/BasicLocationNetworkInfoInitializerTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/DefaultConnectivityResolverTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsByonLocationResolverStubbedRebindTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/networking/JcloudsReachableAddressStubbedTest.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/lifecycle/MachineLifecycleEffectorTasks.java, software/base/src/test/java/org/apache/brooklyn/entity/AbstractEc2LiveTest.java, utils/common/src/main/java/org/apache/brooklyn/util/net/ReachableSocketFinder.java, utils/common/src/test/java/org/apache/brooklyn/util/net/ReachableSocketFinderTest.java
`ConnectivityResolver` is a special customiser used by `JcloudsLocation` to determine the address and credentials with which a location should be contacted. By default it should behave as the previous logic in `JcloudsLocation`, but it exposes options to have Brooklyn prefer to contact VMs on private addresses and can be injected on a per-entity basis. For example:
```yaml
services:
- type: server
location: the-same-private-network-as-brooklyn
brooklyn.initializers:
- type: org.apache.brooklyn.location.jclouds.DefaultConnectivityResolver
mode: ONLY_PRIVATE
- type: server
location: another-cloud
```
Would result in the first entity being managed on the instance's private address (and deployment failing if this was not possible) and the second being managed on its public …
=> ConnectivityResolver

utils/common/src/main/java/org/apache/brooklyn/util/net/ReachableSocketFinder.java, utils/common/src/test/java/org/apache/brooklyn/util/net/ReachableSocketFinderTest.java
Use the default grace period. I think leaving it as `ZERO` was an oversight on my behalf.
=> Increase timeout in ReachableSocketFinderTest

api/src/main/java/org/apache/brooklyn/api/mgmt/ManagementContext.java, api/src/main/java/org/apache/brooklyn/api/mgmt/Scratchpad.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/BrooklynCampPlatform.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ExternalConfigYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ReloadBrooklynPropertiesTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/test/lite/CampPlatformWithJustBrooklynMgmt.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/AbstractManagementContext.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/BasicScratchpad.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/DeferredBrooklynProperties.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/NonDeploymentManagementContext.java, core/src/test/java/org/apache/brooklyn/core/mgmt/internal/LocalManagementContextRebindTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/internal/LocalManagementContextTest.java, karaf/init/src/main/java/org/apache/brooklyn/launcher/osgi/OsgiLauncher.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/security/jaas/BrooklynLoginModule.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/security/provider/DelegatingSecurityProvider.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/util/json/BrooklynJacksonJsonProvider.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/filter/EntitlementContextFilterTest.java
Replaces analogous but incorrect usage of `ManagementContext.getConfig()`.
=> Provide a scratchpad area per management context

core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/transformer/impl/DeleteOrphanedStateTransformer.java, core/src/main/java/org/apache/brooklyn/util/core/file/ArchiveUtils.java, core/src/main/java/org/apache/brooklyn/util/core/osgi/BundleMaker.java, launcher-common/src/main/java/org/apache/brooklyn/launcher/common/BasicLauncher.java, launcher/src/main/java/org/apache/brooklyn/launcher/BrooklynLauncher.java, launcher/src/main/java/org/apache/brooklyn/launcher/BrooklynWebServer.java, launcher/src/test/java/org/apache/brooklyn/launcher/BrooklynLauncherTest.java, launcher/src/test/java/org/apache/brooklyn/launcher/CleanOrphanedLocationsIntegrationTest.java, launcher/src/test/java/org/apache/brooklyn/launcher/WebAppRunnerTest.java, utils/common/src/main/java/org/apache/brooklyn/util/javalang/LoadedClassLoader.java, utils/common/src/main/java/org/apache/brooklyn/util/net/Networking.java, utils/common/src/main/java/org/apache/brooklyn/util/os/Os.java
Prompted by the following (from https://builds.apache.org/job/brooklyn-server-pull-requests/1730/ ):
```
Test Result (3 failures / +3)
org.apache.brooklyn.launcher.CleanOrphanedLocationsIntegrationTest.testCleanedCopiedPersistedState
org.apache.brooklyn.launcher.CleanOrphanedLocationsIntegrationTest.testSelectionWithOrphanedLocationsInData
org.apache.brooklyn.launcher.BrooklynLauncherTest.testErrorsCaughtByApiAndRestApiWorks
```
The first two have been observed in several places, and might be fixed by the first commit here.  The second one is less frequent but the second commit here might help and should improve logging.
=> Attempted non-determinate test fixes

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java
Not able to provision windows machines with current master. The username when deploying to a winrm target is always empty. Fix it by following the same approach the SSH branch takes to populate the username.
Tested by running `WinRmMachineLocationLiveTest` against Amazon.
=> Set the username for Windows locations correctly

rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/LogoutApi.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/LogoutResource.java, rest/rest-resources/src/main/resources/OSGI-INF/blueprint/service.xml
- Give valid WWW-Authorization header to the client.
Previously it was just WWW-Authorization: Basic
Where it has to be WWW-Authorization: Basic realm="something" _That was major Chrome complain for dissrespecting that header._
- LogoutApi#unAuthorize method useful for making browsers forget Basic Authentication
This PR should be reviewed and merged together with https://github.com/apache/brooklyn-ui/pull/36
=> BROOKLYN-323: Use proper WWW-Authorization header in karaf

core/pom.xml, karaf/features/src/main/feature/feature.xml, parent/pom.xml, pom.xml, rest/rest-api/pom.xml
This upgrade CXF to 3.1.9.
It also bumps httpcomponents to 4.4.4 (thus replacing https://github.com/apache/brooklyn-server/pull/362)
~~It cherry-picks @neykov's https://github.com/apache/brooklyn-server/pull/334 (for karaf 4.0.8 upgrade).~~
It requires a new release of winrm4j (which must include https://github.com/cloudsoft/winrm4j/pull/48). This PR will fail to build until that dependency is available. For now, it says ~~0.5.0-ea1~~ 0.5.0 which I built for myself locally.
For this to work fully, it also requires https://github.com/apache/brooklyn-library/pull/73 to be merged.
~~It will require a change in brooklyn-dist as well (Svet's https://github.com/apache/brooklyn-dist/pull/48). I've been testing with https://github.com/apache/brooklyn-dist/pull/82, which builds on that.~~
=> [WIP] CXF upgrade

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/WindowsYamlLiveTest.java, launcher/src/test/java/org/apache/brooklyn/launcher/blueprints/Windows7zipBlueprintLiveTest.java, launcher/src/test/resources/install7zip.ps1, locations/jclouds/pom.xml, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsSshingLiveTest.java, parent/pom.xml, pom.xml, software/base/src/test/java/org/apache/brooklyn/entity/software/base/VanillaWindowsProcessWinrmExitStatusLiveTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/lifecycle/WinRmExecuteHelperUnitTest.java, software/winrm/src/main/java/org/apache/brooklyn/location/winrm/WinRmMachineLocation.java, software/winrm/src/main/java/org/apache/brooklyn/util/core/internal/winrm/winrm4j/Winrm4jTool.java, test-support/src/main/java/org/apache/brooklyn/test/LogWatcher.java
Update to new Winrm4j API, sharing a single context for all clients. Also updates some libraries to avoid convergence errors with the winrm4j dependencies.
Do not merge until Winrm4j 5.0 is released.
=> Terminate winrm client context on Brooklyn exit

core/src/main/java/org/apache/brooklyn/core/entity/Entities.java, core/src/main/java/org/apache/brooklyn/core/entity/EntityPredicates.java, core/src/test/java/org/apache/brooklyn/core/entity/EntitiesTest.java, utils/common/src/main/java/org/apache/brooklyn/util/guava/Functionals.java, utils/common/src/test/java/org/apache/brooklyn/util/guava/FunctionalsTest.java
Provides general-purpose blocking wait on any entity predicate. Example:
````
Entities.waitFor(
machineEntity,
EntityPredicates.attributeEqualTo(MACHINE_STATE, MachineState.REBOOTING),
Duration.FIVE_SECONDS);
````
=> Generalised Entities.waitFor()

api/src/main/java/org/apache/brooklyn/api/internal/AbstractBrooklynObjectSpec.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ConfigParametersYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogOsgiLibraryTest.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogUtils.java, core/src/main/java/org/apache/brooklyn/core/entity/Entities.java, core/src/main/java/org/apache/brooklyn/core/objs/AbstractBrooklynObject.java, core/src/main/java/org/apache/brooklyn/core/objs/proxy/InternalEntityFactory.java, core/src/main/java/org/apache/brooklyn/util/core/ClassLoaderUtils.java, rest/rest-server/pom.xml, rest/rest-server/src/test/java/org/apache/brooklyn/rest/BrooklynRestApiLauncherTestFixture.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/test/entity/RedisClusterIntegrationTest.java
fixes https://issues.apache.org/jira/browse/BROOKLYN-445 and failing tests included here
means catalog BOMs should be written such that any entity/policy/etc which wants to access resources in the bundle is defined as its own item
=> Do not runtime-inherit catalog item in the spec to fix config key list problem

core/src/main/java/org/apache/brooklyn/core/entity/Entities.java, core/src/main/java/org/apache/brooklyn/core/entity/EntityPredicates.java, core/src/test/java/org/apache/brooklyn/core/entity/EntitiesTest.java, utils/common/src/main/java/org/apache/brooklyn/util/guava/Functionals.java, utils/common/src/test/java/org/apache/brooklyn/util/guava/FunctionalsTest.java
Cherry-picks "generalised Entities.waitFor()" into the 0.9.x branch. See #584.
=> Backport 584 to 0.9.x

core/src/main/java/org/apache/brooklyn/core/entity/Entities.java, core/src/main/java/org/apache/brooklyn/core/entity/EntityPredicates.java, core/src/test/java/org/apache/brooklyn/core/entity/EntitiesTest.java, utils/common/src/main/java/org/apache/brooklyn/util/guava/Functionals.java, utils/common/src/test/java/org/apache/brooklyn/util/guava/FunctionalsTest.java
Cherry-picks "generalised Entities.waitFor()" into the 0.10.x branch. See #584.
=> Backport 584 to 0.10.x

locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/BailOutJcloudsLocation.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/entitlement/AbstractRestApiEntitlementsTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/lifecycle/MachineLifecycleEffectorTasksTest.java
Fixes a bunch of `*ApiEntitlementsTest` failures as seen in https://builds.apache.org/view/Brooklyn/job/brooklyn-integration-tests/64/testngreports/
```
Message: code=200; reason=OK; content=true expected [401] but found [200]
Stacktrace:
at org.testng.Assert.fail(Assert.java:94)
at org.testng.Assert.failNotEquals(Assert.java:513)
at org.testng.Assert.assertEqualsImpl(Assert.java:135)
at org.testng.Assert.assertEquals(Assert.java:116)
at org.testng.Assert.assertEquals(Assert.java:389)
at org.apache.brooklyn.rest.entitlement.AbstractRestApiEntitlementsTest.assertStatusCodeEquals(AbstractRestApiEntitlementsTest.java:110)
at org.apache.brooklyn.rest.entitlement.AbstractRestApiEntitlementsTest.assert401(AbstractRestApiEntitlementsTest.java:106)
at …
```
=> Fix Integration tests

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/DefaultConnectivityResolver.java
Publish Attributes.ADDRESS before guessing the EC2 hostname.
Fixes the case where host.address was set to the FQDN in EC2.
=> Fix publication of EC2 host address in DefaultConnectivityResolver

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/BrooklynDslCommon.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/DslComponent.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/rebind/RebindDslTest.java, camp/camp-brooklyn/src/test/resources/org/apache/brooklyn/camp/brooklyn/rebind/dsl-2016-07-entity-klcueb1ide, core/src/main/java/org/apache/brooklyn/util/core/xstream/ObjectWithDefaultStringImplConverter.java, core/src/main/java/org/apache/brooklyn/util/core/xstream/XmlSerializer.java, core/src/test/java/org/apache/brooklyn/util/core/xstream/XmlSerializerTest.java
Tests + fixes https://issues.apache.org/jira/browse/BROOKLYN-451
=> BROOKLYN-451: Adds yaml-dsl rebind tests (for historic state)

core/src/main/java/org/apache/brooklyn/core/enricher/AbstractEnricher.java, core/src/main/java/org/apache/brooklyn/enricher/stock/AbstractAggregator.java, core/src/main/java/org/apache/brooklyn/enricher/stock/AbstractTransformer.java, core/src/main/java/org/apache/brooklyn/enricher/stock/Aggregator.java, core/src/main/java/org/apache/brooklyn/enricher/stock/Joiner.java, core/src/main/java/org/apache/brooklyn/enricher/stock/Propagator.java, core/src/main/java/org/apache/brooklyn/enricher/stock/Transformer.java, core/src/main/java/org/apache/brooklyn/enricher/stock/reducer/Reducer.java, pom.xml, server-cli/src/main/java/org/apache/brooklyn/cli/AbstractMain.java, server-cli/src/main/java/org/apache/brooklyn/cli/CloudExplorer.java, server-cli/src/main/java/org/apache/brooklyn/cli/ItemLister.java, server-cli/src/main/java/org/apache/brooklyn/cli/Main.java, server-cli/src/test/java/org/apache/brooklyn/cli/CliTest.java, server-cli/src/test/java/org/apache/brooklyn/cli/CloudExplorerLiveTest.java
Replaces list-objects' `--catalog-only` and `--ignore-impls` arguments with `--all-classes` and `--include-impls` respectively.
ItemLister defined a few options as booleans whose default was true. Airline treats boolean options as having zero arity and whose existence implies truth. See Airline's [MetadataLoader](https://github.com/airlift/airline/blob/0.7/src/main/java/io/airlift/airline/model/MetadataLoader.java#L156) class.
I've removed the default from all other boolean options to make it clearer that the value is set by Airline.
CloudExplorerLiveTest passes.
=> Use boolean Options correctly in ItemLister

core/src/main/java/org/apache/brooklyn/core/mgmt/persist/OsgiClassPrefixer.java, core/src/main/java/org/apache/brooklyn/feed/CommandPollConfig.java, core/src/main/java/org/apache/brooklyn/feed/ssh/SshPollConfig.java, core/src/main/java/org/apache/brooklyn/util/core/xstream/ClassRenamingMapper.java, core/src/main/java/org/apache/brooklyn/util/core/xstream/XmlSerializer.java, core/src/main/resources/org/apache/brooklyn/core/mgmt/persist/deserializingClassRenames.properties, core/src/test/java/org/apache/brooklyn/core/mgmt/persist/XmlMementoSerializerTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindHistoricSshFeedTest.java, core/src/test/resources/org/apache/brooklyn/core/mgmt/rebind/ssh-feed-no-bundle-prefixes-zv7t8bim62, core/src/test/resources/org/apache/brooklyn/core/mgmt/rebind/ssh-feed-zv7t8bim62
The historic persisted state added here for testing comes from a clocker.io blueprint.
The "Fix classRenames for SshPollConfig anonymous classes" is me playing it safe, to re-add the anonymous inner classes that might be referenced by customers out there. As the comment in the code says, we can't just use `deserializingClassRenames.properties`, because persistence format for a static versus anonymous (non-static) inner class is different.
For the "Fix xstream deserialising osgi class renames", I discussed this with @neykov first. We both agreed that we don't particularly like the fix, but that at least it's localised and it fixes the problem (which is causing rebind to older versions of Brooklyn to fail). We'd like to revisit this, and see about pushing the calls to the class-renames into …
=> BROOKLYN-453: Fix rebind for classrename with bundle prefix

software/winrm/src/main/java/org/apache/brooklyn/core/sensor/windows/WinRmCommandSensor.java
Use default dir obtained on the winrm sesion
until Apache Brooklyn has working concept for RUN_DIR on VanillaWindowsProcess
=> WinRmCommandSensor default executionDir

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/CompositeEffectorYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/HttpCommandEffectorYamlTest.java
this should fix the build failures we are seeing after 16th March
cc @geomacy please have a look at this
=> use http://httpbin instead of https for tests

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/WinRmMachineLocationExternalConfigYamlTest.java, software/winrm/src/main/java/org/apache/brooklyn/location/winrm/WinRmMachineLocation.java
- This allows WinrmTool props to be supplied via external configuration providers.
- WinRmTool instantiation is made to be the same as in SshMachineLocation#connectSsh
=> WinRmMachineLocation obtaining WinRmTool parameters via its config().get

core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/ApplicationApi.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/CatalogApi.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/CatalogResource.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/CatalogResourceTest.java
and testing things like inserting a manifest and loading files from the bundles
not directly useful in Brooklyn yet, but some preparatory tests and utils:
* confirming that we should be able to refactor BOMs to have scripts etc in separate files, installing them as JAR bundles
* making it easier to work with ZIPs and JARs that are supplied
* inserting manifest entries if needed (to install a raw ZIP, so we are attractive to non-java users)
* testing the above, without needing maven to build bundles
@aledsage @neykov @geomacy worth your taking a quick look at the above so you know they are available, also comments on below useful ... will prep something for ML but obv what i write will be better if you give me ideas sooner :)
i think we should change …
=> `BundleMaker` REST call allowing to add ZIP/JAR to catalog

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AbstractJcloudsStubYamlTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindTestUtils.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/AbstractJcloudsStubbedUnitTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsRebindStubUnitTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/StubbedComputeServiceRegistry.java
* Makes the stubbed location more functional by implementing the getNodeMetadata, setting the location field on the NodeMetadata;
* Disabled aws hostname lookup - nothing to ssh into;
* Sets the HA manager for the new rebind management context to disabled. This fixes it to return MASTER state. That's what the launcher does when no HA configured.
=> Improve test location rebind stub

core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogBomScanner.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogBundleLoader.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogBundleTracker.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogUtils.java, core/src/main/java/org/apache/brooklyn/util/core/osgi/BundleMaker.java, rest/rest-api/pom.xml, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/CatalogApi.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/CatalogResource.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/CatalogResourceTest.java, utils/common/src/test/java/org/apache/brooklyn/util/osgi/OsgiTestResources.java
Builds on top of #485. It implements the missing bits and pieces, such as:
- fields `version` and `bundle` are required under `brooklyn.catalog` when uploading a ZIP/JAR archive
- returns 400 HTTP status code is anything goes wrong during the process of the archive (as this is a bad input, therefore a bad request)
- avoid using the `CatalogPopulator` as it reloads all bundles. Instead, it uses the new `CatalogBundleLoader` that loads only a given bundle
- if the bundle has been installed, but the CAMP parser fails, the bundle is uninstalled
- adds more unit tests, especially to check error handling
=> `BundleMaker` REST call allowing to add ZIP/JAR to catalog - Part #2

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/CatalogResource.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/test/entity/VanillaSoftwareProcessTest.java
There is still an issue when the `FEATURE_LOAD_BUNDLE_CATALOG_BOM` is enabled; the REST API won't return the added items as it is currently handled by the `CatalogBomScanner`
But, this feature is disabled by default so we can probably live with that for now
=> Returns catalog items created via REST API when coming from an archive

core/src/test/java/org/apache/brooklyn/core/mgmt/persist/XmlMementoSerializerPerformanceTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/dto/MementoGeneratorsPerformanceTest.java
The output on my machine is shown below. This is with a deliberately big entity (100 config keys and 100 sensor values).
```
2017-03-20 14:38:06,468 INFO  test=PerformanceTestDescriptor{summary=mementoSerializer.serializeEntityMemento(size=65850chars), iterations=1000, warmupIterations=100, job=org.apache.brooklyn.core.mgmt.persist.XmlMementoSerializerPerformanceTest$1@28e5dd6d, minAcceptablePerSecond=1.0}; result=PerformanceTestResult{duration=2s 350ms, warmup=574ms, iterations=1000, warmupIterations=100, ratePerSecond=425.531914893617, histogram={1.049ms-2.097ms: 119, 2.097ms-4.194ms: 876, 4.194ms-8.389ms: 5}, cpuTotalFraction=1.0238435008590299, cpuSampleFractions=[1.038314, 1.016156843156843], minAcceptablePerSecond=1.0}
```
and:
```
2017-03-20 14:37:21,040 INFO …
```
=> Adds perf test for xml serialiser (and memento-gem)

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/BrooklynCampReservedKeys.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynComponentTemplateResolver.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynEntityDecorationResolver.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynEntityMatcher.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/BrooklynTagsRebindTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/TagsYamlTest.java, core/src/main/java/org/apache/brooklyn/core/mgmt/BrooklynTags.java
```yaml
services:
- type: BasicApplication
brooklyn.tags: [tag1, tag2]
```
`brooklyn.tags` adds NamedStringTag to an entity spec.
_Tags can be inspected via REST API `/v1/applications/<appId>/entities/<entityId>/tags`_
=> BROOKLYN-460: Brooklyn Camp syntax for adding tags to an entity spec

core/src/test/java/org/apache/brooklyn/util/core/xstream/XmlSerializerTest.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/TestFrameworkAssertions.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/TestFrameworkAssertionsTest.java, utils/common/src/main/java/org/apache/brooklyn/util/net/Networking.java
Each relies on the two objects being compared being instances of the same `Comparable<T>`.
I also took the opportunity to simplify the logic in `TestAssertions`.
=> Add greaterThan and lessThan test framework assertions

core/src/main/java/org/apache/brooklyn/util/core/osgi/BundleMaker.java
When cloning a zip, we were using the ZipEntry from the input zip.
This causes issues, as the info in the input ZipEntry is not necessarily correct for the output zip.
Specifically, compressed size can be different. This causes exceptions when the wrong amount of bytes are written.
This change means that a new ZipEntry is created, and the info from the input ZipEntry is ignored.
=> BundleMaker copy fix

core/src/main/java/org/apache/brooklyn/util/core/internal/ssh/ShellAbstractTool.java, core/src/main/java/org/apache/brooklyn/util/core/internal/ssh/ShellTool.java, core/src/main/java/org/apache/brooklyn/util/core/internal/ssh/SshTool.java, core/src/test/java/org/apache/brooklyn/util/core/internal/ssh/sshj/SshjToolIntegrationTest.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, utils/common/src/main/java/org/apache/brooklyn/util/ssh/BashCommands.java
Required for some clouds (e.g. azure-arm), when using `useJcloudsSshInit: false`
Tested on `azure-arm` using a location like that below (which previously failed):
```
brooklyn.catalog:
id: azure-arm-lon-centos7
name: "Azure ARM UK South Centos 7.3"
itemType: location
item:
type: jclouds:azurecompute-arm
identity: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
credential: xxxxxxxx
endpoint: https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
oauth.endpoint: https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/token
jclouds.azurecompute.arm.publishers: OpenLogic
jclouds.azurecompute.operation.timeout: 120000
jclouds.compute.resourcename-prefix: myprefix
useJcloudsSshInit: false
destroyOnFailure: false
machineCreateAttempts: 1 …
```
=> Adds authSudo support (for sudo’ing with password)

test-framework/src/main/java/org/apache/brooklyn/test/framework/TestFrameworkAssertions.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/TestFrameworkAssertionsTest.java
Previously `matches: <regex>` would not work well for multi-line.
For example, if using something like:
```
type: TestSshCommand
assert.out:
- matches: ".*foo.*"
```
and the ssh command outputs:
```
foo1
foo2
```
then it would not match.
You can see this in pure java: `"foo1\nfoo2\n".matches(".*foo.*")` is false.
This PR changes our "matches" to do two things: first it tries to match the regex against the entire string; but if that does't work then it splits the input string into multiple lines and checks if the regex matches against any single line - if it does, then it considers it a match.
Do you agree that is what the user will find most intuitive?
=> yaml-test assertions: fix use of “matches”

launcher-common/src/main/java/org/apache/brooklyn/launcher/command/support/CloudExplorerSupport.java, locations/jclouds/src/main/java/org/apache/brooklyn/core/mgmt/persist/jclouds/JcloudsBlobStoreBasedObjectStore.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/BlobStoreContextFactory.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/BlobStoreContextFactoryImpl.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsUtil.java, locations/jclouds/src/test/java/org/apache/brooklyn/core/mgmt/persist/jclouds/BlobStoreExpiryTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/core/mgmt/persist/jclouds/BlobStoreTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/core/mgmt/persist/jclouds/JcloudsExpect100ContinueTest.java
Fixes a bug introduced in this PR https://github.com/apache/brooklyn-server/commit/013b38bf0f146114d3a67423c0dcc3661b50f88c#diff-30cb47bc0f055776b4a246abeddd4ad7L99
Before that change we would ask the JCloudsLocation directly for config. JCloudsLocation uses a ResolvingConfigBag which will resolve dsl (e.g. "$brooklyn:external").
After the above change, we get the ConfigBag from the location first and ask the ConfigBag for the result. When we get the ConfigBag from the location we create a new ConfigBag to return, but we do not create a resolving config bag.
This PR changes back to asking the location directly for config
=> Fixed BlobStoreContextFactoryImpl. It can now have dsl in its config

core/src/main/java/org/apache/brooklyn/util/core/task/ScheduledTask.java
See https://issues.apache.org/jira/browse/BROOKLYN-446
=> BROOKLYN-446: deprecate broken ScheduledTask constructors

utils/common/src/main/java/org/apache/brooklyn/util/collections/CollectionMerger.java, utils/common/src/test/java/org/apache/brooklyn/util/collections/CollectionMergerTest.java
I think we've got away with this for so long because different objects didn't have the same hashcode, so it rarely had to execute the equals method!
=> BROOKLYN-461: fix CollectionMerger’s Ref.equals

core/src/main/java/org/apache/brooklyn/core/entity/lifecycle/ServiceStateLogic.java, core/src/main/java/org/apache/brooklyn/entity/group/SequenceGroup.java, core/src/main/java/org/apache/brooklyn/entity/group/SequenceGroupImpl.java, core/src/main/java/org/apache/brooklyn/entity/stock/SequenceEntity.java, core/src/main/java/org/apache/brooklyn/entity/stock/SequenceEntityImpl.java, core/src/test/java/org/apache/brooklyn/entity/group/SequenceGroupTest.java, core/src/test/java/org/apache/brooklyn/entity/stock/SequenceEntityTest.java
An entity and a group that manage sequential sensor values
=> Sequencer entity

utils/common/src/main/java/org/apache/brooklyn/util/text/Identifiers.java
Define `brooklyn.experimental.feature.random_seed` with the value of the seed for the random number generator. Means that when locations and entities are created in the same order after startup, they will have the same predictable identifiers, which is useful for testing or demonstrations.
=> Allow setting random number generator seed for identifiers

karaf/itests/pom.xml, karaf/itests/src/test/java/org/apache/brooklyn/karaf/itests/FeatureInstallationTest.java
Without these fixes, it fails if the local .m2 doesn't already have the pre-built artifacts it needs.
For example, the command below fails if your local .m2 is empty. I think this is important for being able to build RCs cleanly, rather than it relying on finding existing artifacts on the file system.
```
mvn clean install -Dmaven.repo.local=/Users/aledsage/temp/mvn-repo-for-itest-testing
```
The failures were:
```
FeatureInstallationTest.testBrooklynApiFeature » Multi Error
FeatureInstallationTest.testBrooklynCoreFeature » Multi Error
FeatureInstallationTest.testBrooklynLocationsJcloudsFeature » Multi Error
```
with errors like:
```
2017-04-11 19:53:22,005 | WARN  | pool-28-thread-1 | AetherBasedResolver              | 7 - org.ops4j.pax.url.mvn - 2.5.2 | Error resolving artifact …
```
=> Fix itests

karaf/itests/src/test/java/org/apache/brooklyn/karaf/itests/FeatureInstallationTest.java
Without this, if you run:
```
nohup mvn clean install ... < /dev/null &
```
then your background process is stopped (according to `jobs`). When you foreground the process again (via `fg %1`) then it reports the tests have failed with the errors below:
```
22:12:34.027 [main] DEBUG o.o.p.e.k.c.i.KarafTestContainer - Shutting down the test container (Pax Runner)
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1,175.983 sec <<< FAILURE! - in org.apache.brooklyn.karaf.itests.FeatureInstallationTest
org.apache.brooklyn.karaf.itests.FeatureInstallationTest  Time elapsed: 1,175.981 sec  <<< ERROR!
java.lang.RuntimeException: Cannot get the remote bundle context
at org.ops4j.pax.exam.rbc.client.intern.RemoteBundleContextClientImpl.getRemoteBundleContext(RemoteBundleContextClientImp …
```
=> Fix itest for running backgrounded

core/src/main/java/org/apache/brooklyn/util/core/xstream/ObjectWithDefaultStringImplConverter.java
Previously xstream was injecting the wrong class loader, so we’d
get errors like:
```
ClassNotFoundException: org.apache.brooklyn.camp.brooklyn.spi.dsl.methods.DslComponent$DslConfigSupplier
```
=> Fix rebind of DSL instances

rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/CatalogApi.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/CatalogResource.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/CatalogResourceTest.java
This allow passing `latest` as the version for the following endpoints:
- `GET /v1/catalog/applications/<symbolicName>/<version>`
- `GET /v1/catalog/entities/<symbolicName>/<version>`
- `GET /v1/catalog/policies/<symbolicName>/<version>`
- `GET /v1/catalog/locations/<symbolicName>/<version>`
- `DELETE /v1/catalog/applications/<symbolicName>/<version>`
- `DELETE /v1/catalog/entities/<symbolicName>/<version>`
- `DELETE /v1/catalog/policies/<symbolicName>/<version>`
- `DELETE /v1/catalog/locations/<symbolicName>/<version>`
For the `GET` requests, the latest catalog item matching the `symbolicName` will be returned. Similarly, for the `DELETE` requests, the latest catalog item matching the `symbolicName` will be deleted.
This is very useful to get the information back of an entity if one …
=> Allow passing "latest" as version for catalog endpoints

utils/common/src/main/java/org/apache/brooklyn/util/ssh/BashCommands.java
Versions of Java prior to 1.8 are not available by standard on Ubuntu 16.x+, this adds the repo for older versions required by some software.
=> Enable older Java versions

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/DefaultConnectivityResolver.java
When a server provisions but JClouds fails to connect to it, the server is killed and re-provisioned. When this happens the private and public address of the old server remain in the `host.address` sensors because of a null check in `DefaultConnectivityResolver`. This PR removes that so the machine correctly obtains the address of the re-provisioned machine.
=> Fix address publish bug

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogOsgiYamlEntityTest.java
Some testing resources are JARs and cannot be included in the release build. Tests must be written to gracefully handle the absence of those test resources. Some new tests failed to include the check for the presence of the resources and therefore fail the release build.
=> Resolve release build failures due to optional JARs

core/src/test/java/org/apache/brooklyn/util/core/ssh/BashCommandsIntegrationTest.java, utils/common/src/main/java/org/apache/brooklyn/util/ssh/BashCommands.java
Also changes waitForFileContents to `cat file` if the check fails
=> Adds BashCommands.waitForFileExists

core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindAbstractCommandFeedTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindHistoricSshFeedTest.java, software/winrm/src/main/java/org/apache/brooklyn/feed/windows/CmdFeed.java, software/winrm/src/test/java/org/apache/brooklyn/feed/windows/RebinWinrmCmdFeedTest.java, software/winrm/src/test/resources/org/apache/brooklyn/feed/windows/winrm-cmd-feed-a8pno3muco, software/winrm/src/test/resources/org/apache/brooklyn/feed/windows/winrm-cmd-feed-no-bundle-prefixes-akc24nlh2k
Tested with restart with Aled's blueprint.
=> Fix BROOKLYN-493 Rebind fails when using WinRmCommandSensor

core/src/main/java/org/apache/brooklyn/util/core/ClassLoaderUtils.java, core/src/test/java/org/apache/brooklyn/util/core/ClassLoaderUtilsTest.java
If we add a non-bundle jar through `brooklyn.libraries` subsequent white list loads fail.
=> Don't fail white list loading if invalid bundles present

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/AbstractBrooklynRestResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/CatalogResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/util/DefaultExceptionMapper.java
include the trace on the first encounter of a new type or simply a new place where a type is thrown from;
subsequent instances won't get the trace but handy when debugging if the first one does
=> better logging of REST exceptions

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/BrooklynDslDeferredSupplier.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ExternalConfigYamlTest.java
See https://issues.apache.org/jira/browse/BROOKLYN-269
=> BROOKLYN-269: don’t log sensitive resolved DSL values

core/src/main/java/org/apache/brooklyn/util/core/xstream/XmlUtil.java
Be explicit to use UTF_8. Otherwise, on some environments (e.g. windows?) it could use a different encoding.
See https://issues.apache.org/jira/browse/BROOKLYN-489
However, I'm struggling to test this. For @iyovcheva, the `XmlUtilTest` passed in her IDE. This included when we created another little test there to read the persisted state file that was failing (`qf4zems55y`, and call `XmlUtil.xpath`). Maybe there's something different about the character encodings when running brooklyn in karaf, versus in the IDE?!
I also tried reproducing by changing `parent/pom.xml`, the `maven-surefire-plugin` configuration to include `-Dfile.encoding=ISO-8859-1`. I then ran `mvn test -Dtest=XmlUtilTest -Dfile.encoding=ISO-8859-1`. I confirmed that `Charset.defaultCharset()` writes out `ISO-8859-1`, but …
=> BROOKLYN-489: Fix XmlUtil.xpath character encoding

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AbstractYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ExternalConfigYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/WinRmMachineLocationExternalConfigYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/AbstractCatalogXmlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogMakeOsgiBundleTest.java, core/src/main/java/org/apache/brooklyn/core/mgmt/ha/OsgiManager.java, core/src/test/java/org/apache/brooklyn/core/BrooklynVersionTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/classloading/ClassLoaderFromBrooklynClassLoadingContextTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/osgi/OsgiPathTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/osgi/OsgiTestingLeaksAndSpeedTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/osgi/OsgiVersionMoreEntityTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/persist/XmlMementoSerializerDelegatingClassLoaderTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/persist/XmlMementoSerializerTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/ActivePartialRebindVersionTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/ManagementPlaneIdTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindTestFixture.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindTestUtils.java, core/src/test/java/org/apache/brooklyn/core/test/entity/LocalManagementContextForTests.java, core/src/test/java/org/apache/brooklyn/util/core/ClassLoaderUtilsTest.java, core/src/test/java/org/apache/brooklyn/util/core/osgi/BundleMakerTest.java, utils/rt-felix/src/main/java/org/apache/brooklyn/rt/felix/EmbeddedFelixFramework.java
This speeds up build time from 17m to 11m on my machine by reusing OSGi framework containers where possible.  That also fixes an OSGi container which is causing lots of build failures on Jenkins.
See the last commit which is the only thing new, and the `OsgiManager` class is the main significant difference in that.  Other things are just wiring to control bundle reuse or not.
This includes #645 and #647 so if this build passes we can assume the failures in those PR's are ignorable (they seem to be due to memory leaks).  But merge those before merging this (and I can rebase this if needed once they are merged.)
/cc @neykov @aledsage @geomacy
=> Reuse embedded OSGi container in tests

core/src/test/java/org/apache/brooklyn/core/config/DeferredConfigTest.java
fix logic where future no longer guaranteed to be available when non-blocking
=> expand test of future value

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlLocationTest.java, core/src/main/java/org/apache/brooklyn/core/location/BasicLocationRegistry.java, core/src/main/java/org/apache/brooklyn/core/location/CatalogLocationResolver.java, core/src/main/java/org/apache/brooklyn/core/location/internal/LocationConfigMap.java, core/src/main/java/org/apache/brooklyn/core/location/internal/LocationInternal.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/ConnectivityResolver.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/DefaultConnectivityResolver.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocationConfig.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsMachineLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsSshMachineLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/api/JcloudsLocationConfigPublic.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/api/JcloudsLocationPublic.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/api/JcloudsMachineLocationPublic.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/LocationResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/transform/CatalogTransformer.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/transform/LocationTransformer.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/util/BrooklynRestResourceUtils.java
Discovered when trying to use the REST API that we didn't get much of the location detail we might want; in particular we didn't have info on provider/endpoint/region, and the parent spec was not accurately identified.  Tracked the latter to confusion around `ORIGINAL_SPEC` which I've clarified and deprecated the confusing other field, and the former to a place where flags weren't pulled in, just config.
Also had trouble accessing some of the data because it required a cast to `JcloudsLocation`, which pulled in an OSGi dependency on the main brooklyn-jclouds package, and classes in that package pulled in jclouds bundles through their signatures, giving a huge set of bundle constraints in my downstream project.  Have refactored here so that we can access many common things through an `api` …
=> Clean up location metadata and OSGi packaging

software/base/src/test/java/org/apache/brooklyn/entity/software/base/lifecycle/SoftwareProcessDriverCopyResourcesTest.java
Because it uses LocalhostMachineProvisioningLocation (breaks the Apache brooklyn-server Jenkins build).
Follows https://github.com/apache/brooklyn-server/pull/662.
=> Make SoftwareProcessDriverCopyResourcesTest an integration test.

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ApplicationResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/CatalogResource.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/BrooklynRestApiLauncherTestFixture.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/entitlement/ApplicationResourceEntitlementsTest.java
CatalogResource closes ZipFiles cleanly and ApplicationResource checks the invoke-effector permission before invoking the start effector.
=> Minor CatalogResource and ApplicationResource fixes

core/src/main/java/org/apache/brooklyn/entity/group/DynamicCluster.java
Updating DynamicCluster.CLUSTER_ONE_AND_ALL_MEMBERS_UP description as it might be ambiguous at the moment.
=> DynamicCluster.CLUSTER_ONE_AND_ALL_MEMBERS_UP clarification

software/base/src/test/java/org/apache/brooklyn/entity/AbstractMultiDistroLiveTest.java, software/base/src/test/java/org/apache/brooklyn/entity/AbstractOpenstackLiveTest.java
* explicitly disable HA - marks the node as MASTER instead of INITIALIZING
* don't retry machine creation - just slows down the test when the node being tested is misconfigured
* makes the centos config overridable by extending tests
* don't require beefy machines for tests - can be overrided if needed
=> Multi distro live test improvements

core/src/main/java/org/apache/brooklyn/util/core/internal/ssh/SshTool.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/BasicJcloudsLocationCustomizer.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocationCustomizer.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsSshMachineLocationStubbedTest.java, software/winrm/src/main/java/org/apache/brooklyn/util/core/internal/winrm/WinRmTool.java
Adds JcloudsLocationCustomizer hook to allow node / config configuration which can be used by a customizer to configure the ssh / winrm config tool with runtime data such as machineid
=> Adds JcloudsLocationCustomizer hook to allow node / config configuration

software/winrm/src/main/java/org/apache/brooklyn/util/core/internal/winrm/winrm4j/Winrm4jTool.java
Fixes https://github.com/cloudsoft/winrm4j/issues/63
To test add in location configuration:
brooklyn.winrm.config.use.unique.context: true
=> Flag allowing a Winrm4jTool to use unique context

core/src/main/java/org/apache/brooklyn/core/objs/BasicSpecParameter.java, core/src/main/java/org/apache/brooklyn/util/core/task/BasicExecutionContext.java, parent/pom.xml, pom.xml, utils/groovy/src/test/java/org/apache/brooklyn/util/groovy/GroovJavaMethodsTest.java
This updates the Java version to `1.8` and makes a couple of changes to get Brooklyn to build again.  
For demonstration purposes I've switched a `new Callable ...` in 
[BasicExecutionContext.java](https://github.com/apache/brooklyn-server/compare/master...geomacy:switch-to-java-8?expand=1#diff-1876d3c7b9d3cc5d485f7469b403e281R216) to use a Java 8 lambda expression, really just to prove that it is Java 8! (This was useful as it showed we needed to update the Checkstyle plugin to a level that works with 8).   
I've tested that Brooklyn runs in both classic and Karaf launchers, and can successfully deploy a basic server and a couple of apps from Brooklyn Central, (a three tier app and `brooklyn-etcd`). 
There's a matching update to `brooklyn-ui`, …
=> Switch to Java 8

api/src/main/java/org/apache/brooklyn/api/sensor/EnricherSpec.java, camp/camp-base/src/main/java/org/apache/brooklyn/camp/spi/resolve/interpret/PlanInterpretationContext.java, core/src/test/java/org/apache/brooklyn/core/network/OnPublicNetworkEnricherTest.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/CatalogResource.java, utils/common/src/main/java/org/apache/brooklyn/util/javalang/Reflections.java
Fixes generics compilation errors that the Eclipse compiler reports, with Java 8 (in Eclipse 4.6.3).
=> Fix generics usage (for compilation in Eclipse)

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/DslYamlTest.java
Test previously failed non-deterministically in jenkins (e.g. see https://github.com/apache/brooklyn-server/pull/693#issuecomment-303414269)
=> Fix DslYamlTest

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/aws/AbstractEbsVolumeCustomizer.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/aws/EbsVolumeCustomizers.java
Allows user to specify an additional AWS hard drive to be added at provisioning time, e.g.:
```
provisioning.properties:
customizers:
- $brooklyn:object:
type:                               org.apache.brooklyn.location.jclouds.aws.EbsVolumeCustomizers$WithNewVolume
object.fields:
availabilityZone:                 us-west-1a
ec2DeviceName:                    /dev/sdf
osDeviceName:                     /dev/xvdf
mountPoint:                       /data
permissions:                      700
sizeInGib:                        20
filesystemType:                   ext4
deleteOnTermination:              false
```
=> Adds EBS Location Customizers

software/winrm/src/test/java/org/apache/brooklyn/util/core/internal/winrm/RecordingWinRmTool.java
Adds `getLastConstructorProps()` to `RecordingWinRmTool`, in line with `RecordingSshTool`
=> Adds getLastConstructorProps to RecordingWinRmTool

utils/common/pom.xml, utils/common/src/main/java/org/apache/brooklyn/util/javalang/Reflections.java, utils/common/src/main/java/org/apache/brooklyn/util/javalang/coerce/CommonAdaptorTryCoercions.java, utils/common/src/main/java/org/apache/brooklyn/util/javalang/coerce/TypeCoercerExtensible.java, utils/common/src/test/java/org/apache/brooklyn/util/javalang/ReflectionsTest.java, utils/common/src/test/java/org/apache/brooklyn/util/javalang/coerce/TypeCoercionsTest.java
Motivated by investigating the list->iterable coercion problems (see https://github.com/apache/brooklyn-server/pull/698), I also added tests and fixed the casting to/from arrays.
=> Fix type-coercion to/from arrays

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/DslComponent.java, core/src/main/java/org/apache/brooklyn/core/sensor/DependentConfiguration.java, core/src/main/java/org/apache/brooklyn/util/core/task/BasicTask.java
Motivated by @duncangrant encountering more problems like that in https://issues.apache.org/jira/browse/BROOKLYN-449, but this time when it tried to call `DslComponent` which called `GroovyJavaMethods.truth`.
Now the only use of `GroovyJavaMethods` are:
* If we genuinely have a Groovy-specific object, such as a `Closure` 
* `AbstractAggregatingEnricher` constructor uses `GroovyJavaMethods.castToPredicate()` (but that code is all deprecated since 0.7.0, so should just be deleted - assuming it is never mentioned in anyone's persisted state?!)
---
These changes will change the semantics of our `attributeWhenReady` etc very slightly, for people taking advantage of the more unusual groovy'isms.
The difference between `GroovyJavaMethods.truth` and `JavaGroovyEquivalents.groovyTruth()` is that …
=> Remove GroovyJavaMethods.* usage

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java
- the config still doesn't contain the correct value for
USE_HTTPS_WINRM, when it is set via provisioning.properties
=> Getting the correct value for WinRmMachineLocation.USE_HTTPS_WINRM

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java
=> Fix for BROOKLYN-510: failure with inboundPorts specified

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsByonLocationResolver.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/DefaultConnectivityResolverTest.java
Ensure we use the `ConfigBag` that we pass into the methods (rather than `location.config().get(...)`) because the ConfigBag will contain the union of the location's config along with any overrides/additions that were passed in to methods like `obtain()` (e.g. via an entity's `provisioning.properties`).
See individual commits for details.
Much longer term, all this config usage is a bit worrying! For an entity, there is special config lookup so that it correctly handles inherited config etc. For locations, we don't have runtime-management inheritance (which is a relief!) so things are a lot simpler. But the big code differences between Location and Entity are worrying.
=> Fix JcloudsLocation config usage

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/CatalogResource.java
Fixes break from https://github.com/apache/brooklyn-server/pull/672,
I merged without re-running unit tests :-(
=> Check versionedName to avoid NPE.

software/winrm/src/main/java/org/apache/brooklyn/core/sensor/windows/WindowsPerformanceCounterSensors.java, software/winrm/src/main/java/org/apache/brooklyn/feed/windows/WindowsPerformanceCounterFeed.java
WindowsPerformanceCounterSensors does not show values on some deployments.
=> [BROOKLYN-515] WindowsPerformanceCounterSensors does not show values

software/winrm/src/main/java/org/apache/brooklyn/core/sensor/windows/WindowsPerformanceCounterSensors.java, software/winrm/src/main/java/org/apache/brooklyn/feed/windows/WindowsPerformanceCounterFeed.java, software/winrm/src/test/java/org/apache/brooklyn/feed/windows/RebindWindowsPerformanceCounterFeedTest.java, software/winrm/src/test/resources/org/apache/brooklyn/feed/windows/windows-performance-counter-feed-no-bundle-prefixies-ueauyeu41d, software/winrm/src/test/resources/org/apache/brooklyn/feed/windows/windows-performance-counter-feed-tu4kk0xvf8
Also make WindowsPerformanceCounterFeed$GetPerformanceCountersJob to not throw 
exception when no machine is found.
=> [BROOKLYN-516] Persist feed of WindowsPerformanceCounterSensors initializer

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/AbstractComputeServiceRegistry.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/AwsEc2SessionAwareComputeServiceRegistry.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/AwsEc2SessionAwareLocationConfig.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/ComputeServiceRegistryImpl.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JCloudsPropertiesBuilder.java
Allows the following catalog item to be added to add locations for all AWS regions such that if the Brooklyn server is running on an EC2 instance and that instance has been assigned an IAM role with e.g `AmazonEC2FullAccess` then the credentials can be inferred from the instance profile.
This PR furthermore refactors the existing `ComputeServiceRegistryImpl` class into an abstract class to allow the  new `AwsEc2SessionAwareComputeServiceRegistry` class to reuse as much as possible.
```
brooklyn.catalog:
version: 0.1.0-SNAPSHOT
items:
- id: amazon-anywhere
itemType: location
item:
type: jclouds:aws-ec2
displayName: AWS (any region)
jclouds.computeServiceRegistry:
$brooklyn:object:
type: org.apache.brooklyn.location.jclouds.AwsEc2SessionAwareComputeServiceRegistry
- id: …
```
=> adds a new ComputeServiceRegistry to handle when Brooklyn runs on an ec2 instance and want to pick up credentials from an IAM role

core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/AbstractRebindHistoricTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindHistoricSshFeedTest.java, software/winrm/src/test/java/org/apache/brooklyn/feed/windows/RebindWindowsPerformanceCounterFeedTest.java, software/winrm/src/test/java/org/apache/brooklyn/feed/windows/RebindWinrmCmdFeedTest.java
(from RebindAbstractCommandFeedTest), and support `getPersistanceFile` for more types
=> Rename to AbstractRebindHistoricTest

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynYamlTypeInstantiator.java, core/src/main/java/org/apache/brooklyn/entity/group/AbstractMembershipTrackingPolicy.java, core/src/test/java/org/apache/brooklyn/core/entity/PolicyRegistrationTest.java, core/src/test/java/org/apache/brooklyn/core/policy/basic/BasicPolicyTest.java, core/src/test/java/org/apache/brooklyn/core/policy/basic/PolicyConfigTest.java, core/src/test/java/org/apache/brooklyn/core/policy/basic/PolicySubscriptionTest.java, core/src/test/java/org/apache/brooklyn/core/policy/basic/PolicyTypeTest.java, core/src/test/java/org/apache/brooklyn/core/test/policy/TestPolicy.java, core/src/test/java/org/apache/brooklyn/entity/group/MembershipTrackingPolicyTest.java, policy/src/main/java/org/apache/brooklyn/policy/autoscaling/AutoScalerPolicy.java, policy/src/main/java/org/apache/brooklyn/policy/ha/ServiceReplacer.java, policy/src/main/java/org/apache/brooklyn/policy/ha/ServiceRestarter.java, policy/src/test/java/org/apache/brooklyn/policy/autoscaling/AutoScalerPolicyMetricTest.java, policy/src/test/java/org/apache/brooklyn/policy/autoscaling/AutoScalerPolicyReconfigurationTest.java, policy/src/test/java/org/apache/brooklyn/policy/autoscaling/AutoScalerPolicyTest.java, policy/src/test/java/org/apache/brooklyn/policy/ha/ServiceReplacerTest.java, policy/src/test/java/org/apache/brooklyn/policy/ha/ServiceRestarterTest.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/testing/mocks/RestMockSimplePolicy.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/util/BrooklynRestResourceUtilsTest.java
Changes (mostly test) code to use `PolicySpec` to create policies, rather than calling the policy's constructor. There are two big reasons for doing this:
1. the `PolicySpec` approach is the same as is used by yaml blueprints - by using/testing in this way, we are more confident that we'll be able to do the same in yaml blueprints.
2. we want to simplify our code - reducing the number of ways a policy/enricher/location/entity can be created and configured will give us some simplification.
=> Use PolicySpec instead of policy constructor

core/src/test/java/org/apache/brooklyn/core/entity/EntitySetFromFlagTest.java, core/src/test/java/org/apache/brooklyn/core/entity/PolicySetFromFlagTest.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/clocker/StubContainerLocation.java
This PR just changes tests, to stop testing things that we shouldn't support!
We should stop supporting `@SetFromFlag` on entity fields. It's been discouraged for a long time, and is a bad idea - one should use config keys and sensors instead! Unfortunately it's not as easy to tell people to not use it on policies, enrichers and locations - those don't have sensors!
In a subsequent PR, I'm going to add support for `deprecatedNames` on `ConfigKey`. Removing the need to support `@SetFromFlag` on entity fields will allow config code to be made simpler longer term.
Here, I change the `EntitySetFromFlagTest` (which uses `@SetFromFlag` on fields) to be `PolicySetFromFlagTest`.
This PR also changes `StubContainerLocation` (which is a test class) to remove the field `@SetFromFlag("owner") private …
=> Change SetFromFlag tests

core/src/main/java/org/apache/brooklyn/core/config/BasicConfigKey.java, core/src/main/java/org/apache/brooklyn/core/config/ConfigKeys.java, core/src/main/java/org/apache/brooklyn/core/config/ListConfigKey.java, core/src/main/java/org/apache/brooklyn/core/config/MapConfigKey.java, core/src/main/java/org/apache/brooklyn/core/config/SetConfigKey.java, core/src/main/java/org/apache/brooklyn/core/config/internal/AbstractCollectionConfigKey.java, core/src/main/java/org/apache/brooklyn/core/config/internal/AbstractStructuredConfigKey.java, core/src/test/java/org/apache/brooklyn/core/config/MapConfigKeyAndFriendsMoreTest.java
This change is motivated by (and is is preparation for) supporting deprecated names for`ConfigKey`s.
=> Add ConfigKey builders

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ConfigLocationInheritanceYamlTest.java, launcher-common/src/main/java/org/apache/brooklyn/launcher/command/support/CloudExplorerSupport.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/BasicJcloudsLocationCustomizer.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocationCustomizer.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/LocationCustomizerDelegate.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/BailOutJcloudsLocation.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsSshMachineLocationStubbedTest.java
Makes customizers aware of obtain failures in case they need to clean up.
Also wraps the customizer calls into a delegate.
=> JcloudsLocationCustomizer.onObtainError

core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, core/src/test/resources/catalog.bom
Fixes CatalogDtoTest.testCatalogLookup which installs the jar even though it's not a proper osgi bundle.
https://builds.apache.org/view/B/view/Brooklyn/job/brooklyn-integration-tests/73/testngreports/org.apache.brooklyn.core.catalog.internal/CatalogDtoTest/testCatalogLookup/
=> Makes core-tests.jar installable in the catalog, add metadata

core/src/main/java/org/apache/brooklyn/core/entity/Entities.java, core/src/test/java/org/apache/brooklyn/core/test/qa/performance/AbstractPerformanceTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/core/mgmt/persist/jclouds/BlobStorePersistencePerformanceTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/test/qa/performance/ScalabilityPerformanceTest.java, test-support/src/main/java/org/apache/brooklyn/test/performance/PerformanceMeasurer.java, test-support/src/main/java/org/apache/brooklyn/test/performance/PerformanceTestDescriptor.java
See individual commits for minor changes / improvements to our `AbstractPerformanceTest` support, which builds up to adding the `ScalabilityPerformanceTest`.
=> Test performance/scalability of many entities

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/networking/creator/DefaultAzureArmNetworkCreator.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/networking/creator/DefaultAzureArmNetworkCreatorTest.java
In an upcoming release of JClouds, support for Azure ARM will be added. The JClouds code for Azure ARM will place each created VM into a network based on it's group ID. As we do not use the concept of a group ID in Brooklyn, this means that each VM deployed by Brooklyn is deployed in it's own subnet. 
For most other clouds, a sensible default network is provided by the cloud. As such a Brooklyn user can be assured that if he deploys a blueprint with multiple VMs, they can reach each other on the private IPs that are provided. Unless we create a default network in Azure, those blueprints will not be portable and a user will have to manually create a network first. I believe that it is confusing for a user to have the clouds act differently on networking, which is an essential part of …
=> A default network is now created when deploying to Azure ARM

parent/pom.xml
I think since we upgrade java it will be useful to have later maven-compiler-plugin.
If you approve this change, I will do the same PR for brooklyn-ui and brooklyn-dist.
=> Update maven-compiler-plugin to 3.6.1

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/networking/creator/DefaultAzureArmNetworkCreator.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/networking/creator/DefaultAzureArmNetworkCreatorTest.java
* Don’t use RETURNS_DEEP_STUBS as causes non-deterministic test failure
on my dev machine (ClassCastException when calling `thenReturn(...)`!)
* Tidy logging
* Assert create() calls are made
* Minor renames (e.g. _PREFIX to indicate DEFAULT_RESOURCE_GROUP constant is just the naming prefix)
Note the aim of the logging improvements is to ensure there is just one log.info message per provision request to say we're messing with the user's templateOptions, and one info message if we're creating default resource group, and one info message if creating default network/subnet. If we don't touch the user's config then we just log at debug.
=> DefaultAzureArmNetworkCreator improvements

rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/CatalogApi.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/CatalogResource.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/CatalogResourceTest.java
When `POST`ing a catalog item (YAML file) with an ID and version that already exists, the REST API returns a `400` with a message inviting the user to use a `forceUpdate` flag if one wishes to. However, this flag is only available internally and not exposed to the REST API.
Another issue is that under the same condition for ZIP/JAR archives, the `OsgiArchiveInstaller` silently ignores the update and therefore, the REST API returns a `201` even though it has done anything.
This fixes both above issues by:
- exposing a `forceUpdate` flag on the REST API for `/v1/catalog`
- checking the result code from `OsgiArchiveInstaller.install()` method and throws the same error message inviting the user to use the `forceUpdate` flag
=> Allow catalog item to be force-updated via query string flag on the REST API

core/src/main/java/org/apache/brooklyn/util/core/task/system/internal/ExecWithLoggingHelpers.java, core/src/test/java/org/apache/brooklyn/location/ssh/SshMachineLocationIntegrationTest.java, core/src/test/java/org/apache/brooklyn/location/ssh/SshMachineLocationTest.java, core/src/test/java/org/apache/brooklyn/util/core/internal/ssh/RecordingSshTool.java, test-support/src/main/java/org/apache/brooklyn/test/LogWatcher.java, utils/common/pom.xml, utils/common/src/main/java/org/apache/brooklyn/util/stream/LoggingOutputStream.java, utils/common/src/main/java/org/apache/brooklyn/util/stream/StreamGobbler.java, utils/common/src/test/java/org/apache/brooklyn/util/stream/LoggingOutputStreamTest.java
Improves thread usage when executing ssh remote commands. Simplifies the code to use a new `LoggingOutputStream`, rather than using the `StreamGobbler` thread.
@neykov I'd appreciate your thoughts. It only does the first part of https://issues.apache.org/jira/browse/BROOKLYN-440; it doesn't do your suggestion of having the single thread polling to see if the streams have any bytes available.
=> BROOKLYN-440: ssh not use StreamGobbler for logging stdout

core/src/main/java/org/apache/brooklyn/core/mgmt/internal/BrooklynShutdownHooks.java, karaf/init/src/main/java/org/apache/brooklyn/launcher/osgi/OsgiLauncher.java
Under karaf if you restarted the brooklyn-init bundle
either manually or due to a re-wire the management context would not
restart (requiring you to resart karaf). This change allows the OSGi
launcher to reset the shutdown flag enabling bundle / management context restart
See [BROOKLYN-522](https://issues.apache.org/jira/browse/BROOKLYN-522)
=> Adds method to reset the shutdown flag within BrooklynShutdownHooks

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ReferencedYamlTest.java
Add/update some test cases for internal references in catalog BOMs, one working, two failing but marked WIP so this is safe to merge
Working on fixing it as part of #746
=> Catalog internal references

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/networking/creator/DefaultAzureArmNetworkCreator.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/networking/creator/DefaultAzureArmNetworkCreatorTest.java
Important Note: Azure ARM doesn't currently work with the master of Brooklyn. Currently, after a Azure ARM VM is created, JClouds attempts to list all of the nodes in the resource group but cannot parse the result due to a missing property (vhd for DataDisk). I have tested with the latest JClouds code in master and we do not have this issue. 
However, we are currently on the latest released version of JClouds (2.0.1) and we cannot pull in the code in mater until there is another JClouds release. As such, the code that has been written for default network has been written against the code in JClouds master and will work when we upgrade to the next version of JClouds. If you need working Azure ARM support, and default networking build JClouds master locally, and build brooklyn against it. …
=> Azure ARM default network fixes from PR suggestions

locations/container/src/main/java/org/apache/brooklyn/container/location/kubernetes/KubernetesClientRegistryImpl.java, locations/container/src/main/java/org/apache/brooklyn/container/location/kubernetes/KubernetesLocationConfig.java
Adds a config key to the `KubernetesLocation` that accepts a `.kube/config` file location, and uses the contents to configure the location. Makes using provisioned Kubernetes clusters from providers like Bluemix or GKE easier.
=> Allow Kubernetes location configuration using kubeconfig

locations/container/pom.xml
Without this the build will fail when preforming a release
=> Adds patent pom relative path to `brooklyn-locations-container`

rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/ActivityApi.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/PolicyConfigResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ServerResource.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/PolicyResourceTest.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/ServerResourceTest.java
Using the REST API from the GUI used to return `"error": "no response from server"` and return code 0 for methods that return String.
The problem was that the received response was not in json format, while the expected response content type is `application/json`.
=> Fix REST API response of methods with String return type

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/PolicyConfigResource.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/PolicyResourceTest.java
Those changes require more careful testing and updates.
We need to revert them from master and reopen in a separate PR.
=> Revert PolicyConfigResource changes from the REST API response fix.

pom.xml
`azurecompute-arm` has changed considerably since `2.0.1`. `jclouds-labs` providers usually backport all master changes to iterate quickly, free to break backwards compatibility.
Notably `templateOptions` has completely different fields.  
Also https://github.com/jclouds/jclouds/pull/1113 is included, fixing edge cases with Amazon security groups.
=> Update jclouds to 2.0.2

core/src/main/java/org/apache/brooklyn/core/entity/AbstractApplication.java, core/src/main/java/org/apache/brooklyn/core/entity/trait/AsyncStartable.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/BasicEntityRebindSupport.java, core/src/main/java/org/apache/brooklyn/entity/stock/AsyncApplication.java, core/src/main/java/org/apache/brooklyn/entity/stock/AsyncApplicationImpl.java, core/src/test/java/org/apache/brooklyn/core/entity/EntityAsyncTest.java, core/src/test/java/org/apache/brooklyn/entity/stock/AsyncApplicationTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessRebindNotRunningEntityTest.java
Adds `AsyncApplication`: An app that starts up asynchronously. Calling start will call start on its children, but it does not expect the children to have started by the time the start() effector has returned. Instead, it infers from the children's state whether they are up or not.
An example use-case is where the app kicks off some async children. These children call out to whichever system they integrate with (e.g. provisioning resources), and then several hours later get callbacks to say whether it started/succeeded. Instead of leaving the `start()` method running for several hours, we let the start method return and then we transition automatically to the right state. I didn't want to leave the `start()` method executing for a long time, because then on Brooklyn-restart the effector …
=> Async entities

rest/rest-server/src/test/java/org/apache/brooklyn/rest/resources/ServerResourceIntegrationTest.java
Fixes the integration test `ServerResourceIntegrationTest.testGetUser()`.
=> Fixes tested response from /server/user

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AggregatorYamlTest.java, core/src/main/java/org/apache/brooklyn/enricher/stock/Aggregator.java, utils/common/src/main/java/org/apache/brooklyn/util/javalang/coerce/CommonAdaptorTypeCoercions.java, utils/common/src/test/java/org/apache/brooklyn/util/javalang/coerce/TypeCoercionsTest.java
Use case is that we have a cluster - we want to propagate the sensor form any of the cluster's members, where that value is not null (in the same format as the child's value).
This is important for the cluster to be used in the same way as a simple child might be used (for "substitutability" of entity types, in object-oriented terms).
=> Add 'first' to aggregator

rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/ServerApi.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/domain/HighAvailabilitySummary.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ServerResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/transform/HighAvailabilityTransformer.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/ServerResourceTest.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/testing/BrooklynRestApiTest.java
This is useful for systems that use/manage Brooklyn - they want to know the stable id of that Brooklyn server, which will be the same after restarts or after HA failovers.
=> REST API returns plane-id

core/src/main/java/org/apache/brooklyn/core/mgmt/ha/HighAvailabilityManagerImpl.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/AbstractManagementContext.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/LocalManagementContext.java
Fixes https://issues.apache.org/jira/browse/BROOKLYN-120
Moves the setting of `managementContext.managementNodeId` from `LocalManagementContext` constructor into `AbstractManagementContext` constructor, to ensure it's set early enough!
=> BROOKLYN-120: fix NPE in /v1/server/up/extended

core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, core/src/main/java/org/apache/brooklyn/core/mgmt/ha/OsgiArchiveInstaller.java
Fixes issue with installing bundles, causing the following error:
```
karaf@brooklyn()> feature:install -r jclouds-api-route53
Error executing command: Unable to build resource for brooklyn:fo9y9ghsab: Unsupported 'Bundle-ManifestVersion' value: 1
```
Sets `Bundle-ManifestVersion` to 2 for Brooklyn generated bundles.
=> Fix feature install bundle version issue

launcher-common/src/main/java/org/apache/brooklyn/launcher/common/BasicLauncher.java, launcher/src/main/java/org/apache/brooklyn/launcher/BrooklynLauncher.java, launcher/src/test/java/org/apache/brooklyn/launcher/BrooklynViewerLauncher.java, launcher/src/test/java/org/apache/brooklyn/launcher/blueprints/AbstractBlueprintTest.java
As per the javadoc:
```
/**
* A convenience for started the Brooklyn REST api and web-app in a test, so that one can visually
* inspect the app that the test creates. This is intended as a read-only view (but it has the real
* management context so one can perform actions through this UI).
* 
* It expects to be configured with an existing {@link org.apache.brooklyn.api.mgmt.ManagementContext}.
* 
* Various other configuration options (e.g. {@link #application(String)) will be ignored.
* 
* An example of where this is very useful is when testing a blueprint where an effector hangs - 
* one can visually inspect the app, drilling into the activities view to see what it is doing
* and why it is blocked.
```
Note that `AbstractBlueprintTest` used to do this with `BrooklynLauncher`, but that is …
=> Adds BrooklynViewerLauncher (for tests)

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlEntityOsgiTypeRegistryTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlEntityTest.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, core/src/main/java/org/apache/brooklyn/core/typereg/BasicBrooklynTypeRegistry.java, core/src/main/java/org/apache/brooklyn/core/typereg/RegisteredTypes.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/CatalogResourceTest.java
Needed because our routines sometimes rewrite the plan
=> Allow equivalent plans when replacing

core/src/main/java/org/apache/brooklyn/core/config/external/vault/VaultExternalConfigSupplier.java
I consider as healthier to not log `responseBody` from vault.
=> Reduce logging for Vault external config supplier

core/src/main/java/org/apache/brooklyn/location/localhost/LocalhostMachineProvisioningLocation.java, core/src/main/java/org/apache/brooklyn/util/core/BrooklynNetworkUtils.java, core/src/test/java/org/apache/brooklyn/core/location/SimulatedLocation.java, core/src/test/java/org/apache/brooklyn/location/localhost/LocalhostMachineProvisioningLocationTest.java, core/src/test/java/org/apache/brooklyn/location/ssh/SshMachineLocationIntegrationTest.java, core/src/test/java/org/apache/brooklyn/location/ssh/SshMachineLocationPerformanceTest.java, core/src/test/java/org/apache/brooklyn/location/ssh/SshMachineLocationReuseIntegrationTest.java, core/src/test/java/org/apache/brooklyn/location/ssh/SshMachineLocationTest.java, launcher/src/main/java/org/apache/brooklyn/launcher/BrooklynWebServer.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/test/core/mgmt/usage/JcloudsLocationUsageTrackingTest.java, software/winrm/src/test/java/org/apache/brooklyn/location/winrm/WinRmMachineLocationTest.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/TestEndpointReachableTest.java, utils/common/src/main/java/org/apache/brooklyn/util/net/Networking.java, utils/common/src/test/java/org/apache/brooklyn/util/net/NetworkingUtilsTest.java, utils/common/src/test/java/org/apache/brooklyn/util/net/ReachableSocketFinderTest.java
Fixes two annoying network issues:
* Sometimes when disconnected Brooklyn detects a non-usable NIC address as localhost and things like SSH fail subsequently
* If start-use-stop-immediately_restart brooklyn, it will normally take a different port eg 8082 because the first one eg 8081 will be in `TIME_WAIT` state.  Allow webserver to `REUSE_ADDR` so it takes the same port in this case.  Minor but hits me a lot when I'm testing!
=> Improve localhost detection and webserver binding

core/src/main/java/org/apache/brooklyn/core/entity/lifecycle/ServiceStateLogic.java, core/src/main/java/org/apache/brooklyn/entity/group/AbstractGroup.java, core/src/main/java/org/apache/brooklyn/entity/group/AbstractGroupImpl.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicClusterImpl.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicMultiGroupImpl.java, core/src/test/java/org/apache/brooklyn/entity/group/DynamicClusterTest.java, utils/common/src/main/java/org/apache/brooklyn/util/collections/QuorumCheck.java, utils/common/src/main/java/org/apache/brooklyn/util/javalang/coerce/CommonAdaptorTypeCoercions.java, utils/common/src/test/java/org/apache/brooklyn/util/collections/QuorumChecksTest.java
They were buggy and could deadlock -- and I think fundamentally flawed (as comments there suggested).
@grkvlt I think you added these; can you check that the workarounds suggested in the last commit is sufficient?
There are a few other minor tidies also.
=> Removes `FIRST` sensors on children

utils/common/src/main/java/org/apache/brooklyn/util/os/Os.java
- ensure required bundle has been loaded before shutdown
- fail gracefully if the deletion hook fails
=> prevent benign error in file deletion shutdown-hook

core/src/main/java/org/apache/brooklyn/core/config/external/vault/VaultExternalConfigSupplier.java
`getDataAsStringMap` allows obtaining vault data with single call.
=> Useful getDataAsStringMap for VaultExternalConfigSupplier

core/src/main/java/org/apache/brooklyn/core/config/external/vault/VaultExternalConfigSupplier.java
Previously body & headers were logged now only the URI and status code is logged
(builds upon #774 )
=> Removes all logging of vault responses

karaf/itests/pom.xml, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/ActivityApi.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/EntityApi.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/LocationApi.java
The missing annotations mean that brooklyn-client is unable to proxy the affected classes (since Resteasy expects to work with every method), and by extension that every build of the project fails. I think the simplest way to solve this is to expose the deprecated methods at `.../deprecated`.
=> Restore HTTP annotations to deprecated API methods

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/JcloudsCustomizerInstantiationYamlDslTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/JcloudsTemplateOptionsYamlAwsTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/JcloudsTemplateOptionsYamlTest.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/templates/customize/TemplateOptionsOption.java
At the moment it's not possible to specify DSL in template options - for example you can't do 
- type: some-type-publishing-subnet-id
id: ent1
- type: some-service
id: service
provisioning.properties:
templateOptions:
subnetId: $brooklyn:entity("ent1").attributeWhenReady("subnet.id")
see new test [here](https://github.com/geomacy/brooklyn-server/commit/d2f5bf9e0a5038208ff98aedb16795c217d01fc7#diff-99cb6184bb386646b61f6678346ec63bR75).
This adds support in `TemplateOptionsOption` for resolving the values supplied for the options. This allows the approach in the blueprint above to be used.
=> Support DSL in template options

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AggregatorYamlTest.java, core/src/main/java/org/apache/brooklyn/enricher/stock/Aggregator.java, core/src/main/java/org/apache/brooklyn/enricher/stock/Enrichers.java, core/src/main/java/org/apache/brooklyn/enricher/stock/MathAggregatorFunctions.java, core/src/test/java/org/apache/brooklyn/enricher/stock/MathAggregatorFunctionsTest.java
Adds support for simple `min` and `max` aggregators.
Also extracts utility functions into `MathAggregatorFunctions` (marking them as `@Beta`), deprecating the nested classes and static methods in `Enrichers`.
The motivation for min/max is for a CouchDB cluster (in pure yaml) - we want all the members of the cluster to know about each other. We can add a sensor to each node that indicates the number of nodes it knows about. We can then add a `min` aggregator on the cluster that tells us the size of the smallest partition.
=> Aggregator: support min/max

core/src/main/java/org/apache/brooklyn/enricher/stock/UpdatingMap.java, core/src/test/java/org/apache/brooklyn/enricher/stock/UpdatingMapTest.java
And adds a test for using `UpdatingMap` to set the service-not-up-indicators
=> UpdatingMap: support configuring ‘producer’

core/src/test/java/org/apache/brooklyn/feed/http/JsonFunctionsTest.java, karaf/features/src/main/feature/feature.xml, parent/pom.xml, pom.xml
This supports `.size()`
Also fix the json-path dependency, to exclude conflicting versions.
The `.size()` is very useful for things like a CouchDB cluster - we can easily add a sensor that retrieves json for the members of the cluster. We'd also like a sensor for the size of that list (so we can check that all CouchDB nodes know about each other at startup).
=> Upgrade json-path to 2.4.0 (from 2.0.0)

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/BrooklynDslCommon.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/DslComponent.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/DslAndRebindYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/DslYamlTest.java
Provides `$brooklyn:template(...)` evaluated against the context entity as a freemarker template.
The main advantage of the new DSL is that it's now possible to do simple expressions in YAML - both logical or algebraic.
Re-implements the most useful parts of #392 for easier merge.
I think providing a shortcut for the expression as `$brooklyn:"some template"` will be useful as well, but will get this to the mailing list for discussion.
=> Freemarker DSL

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogMakeOsgiBundleTest.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicCluster.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicClusterImpl.java, core/src/test/java/org/apache/brooklyn/entity/group/DynamicClusterTest.java
Similar to `SoftwareProcess`, this allows a dynamic cluster to wait for
`service.isUp` before returning from `start()`. It defaults to not waiting
(for backwards compatibility).
Previously, it would return as soon as all the initial member’s start()
effectors had finished executing.
---
Note that the new test `testReportsServiceUpAsSoonAsQuorumSize()` just demonstrates existing behaviour - this PR does not change that behaviour.
=> Adds DynamicCluster.START_TIMEOUT

core/src/main/java/org/apache/brooklyn/core/sensor/http/HttpRequestSensor.java, core/src/main/java/org/apache/brooklyn/feed/http/HttpFeed.java, core/src/test/java/org/apache/brooklyn/core/sensor/http/HttpRequestSensorTest.java, core/src/test/java/org/apache/brooklyn/feed/http/HttpFeedIntegrationTest.java, core/src/test/java/org/apache/brooklyn/feed/http/HttpFeedTest.java, utils/common/src/main/java/org/apache/brooklyn/test/http/RecordingHttpRequestHandler.java
For a description of pre-emptive basic auth, see https://hc.apache.org/httpcomponents-client-ga/tutorial/html/authentication.html (section 4.6. Preemptive authentication). As is described in that link, pre-emptive basic auth should be used with caution!
However, if you really do need to use basic auth then some servers don't send back the right challenge-response in the headers of the 401 response. For example, this seems to be the case with CouchDB!
We've seen in some downstream project people working around it by auto-generating the basic-auth header, and configuring the `HttpRequestSensor` accordingly. That is a bad pattern! (e.g. we lose the fact that this is a credential, so would never be able to use externalised configuration to ensure the passwords are not logged or written to …
=> Adds HttpFeed.preemptiveBasicAuth

karaf/features/src/main/feature/feature.xml
I added this in https://github.com/apache/brooklyn-server/pull/784, but turns out that broke karaf!
Including `org.ow2.asm:5.0.4` breaks things badly:
```
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.commons.AdviceAdapter not found by org.apache.aries.proxy.impl [20]
```
`org.ow2.asm.all:5.0.2` is already included in karaf; we'll just rely on that instead:
```
ASM all classes with debug info (49)
------------------------------------
Bnd-LastModified = 1398065775616
Created-By = 1.8.0 (Oracle Corporation)
Implementation-Title = ASM all classes
Implementation-Vendor = France Telecom R&D
Implementation-Version = 5.0.2
Manifest-Version = 1.0
Tool = Bnd-1.50.0
Bundle-DocURL = http://asm.objectweb.org
Bundle-ManifestVersion = 2
Bundle-Name = ASM all classes with debug info …
```
=> Remove `org.ow2.asm` (already included in Karaf)

test-framework/pom.xml, test-framework/src/test/java/org/apache/brooklyn/test/framework/live/TestFrameworkLiveTest.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/live/TestFrameworkRun.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/live/TestFrameworkSuiteBuilder.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/yaml/SimpleTestFrameworkTest.java, test-framework/src/test/resources/test-framework-examples/simple-catalog.bom, test-framework/src/test/resources/test-framework-examples/simple-catalog.locations.bom, test-framework/src/test/resources/test-framework-examples/simple-catalog.tests.bom
Useful for running the test framework tests as live tests on the project.
From the test included in the PR, example usage:
```
TestFrameworkSuiteBuilder.create()
.test()
.prerequisiteResource("test-framework-examples/simple-catalog.bom")
.prerequisiteResource("test-framework-examples/simple-catalog.locations.bom")
.testResource("test-framework-examples/simple-catalog.tests.bom")
.location("simple-entity-dummy")
.add()
.buildProvider();
```
=> Test Framework TestNG runner

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AggregatorYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/PropagatorYamlTest.java, core/src/main/java/org/apache/brooklyn/core/sensor/http/HttpRequestSensor.java, core/src/main/java/org/apache/brooklyn/enricher/stock/AbstractAggregator.java, core/src/main/java/org/apache/brooklyn/feed/http/JsonFunctions.java, core/src/test/java/org/apache/brooklyn/core/sensor/http/HttpRequestSensorTest.java
Previously the `HttpRequestSensor` failed if no `jsonPath: ` is suppiled in the yaml. I've added a failing test, but not worked specifically on that. It doesn't pick up the default value of `$`.
Added support for setting `jsonPath` to blank, so that it just takes the pure-string value (i.e. no json parsing).
Also added a few more (unrelated!) tests.
=> HttpRequestSensor: handling non-json

core/src/main/java/org/apache/brooklyn/entity/group/DynamicCluster.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicClusterImpl.java, core/src/test/java/org/apache/brooklyn/core/test/entity/TestClusterImpl.java, core/src/test/java/org/apache/brooklyn/entity/group/DynamicClusterTest.java
Adds cluster.max.size to dynamic cluster, and prevents the cluster from being manually increased beyond that size
=> Adds cluster.max.size to dynamic cluster

core/src/test/java/org/apache/brooklyn/core/test/entity/TestSizeRecordingCluster.java, core/src/test/java/org/apache/brooklyn/core/test/entity/TestSizeRecordingClusterImpl.java, policy/src/main/java/org/apache/brooklyn/policy/autoscaling/AutoScalerPolicy.java, policy/src/test/java/org/apache/brooklyn/policy/autoscaling/AutoScalerPolicyPoolSizeTest.java
Currently, if a user resizes a cluster with an `AutoScalerPolicy` such that the pool size is now outside the min and max pool size for the policy, the cluster is not resized to the bounds
=> AutoScalerPolicy to resize to limits on expunge

core/src/main/java/org/apache/brooklyn/core/objs/proxy/ClassLoaderCache.java, core/src/main/java/org/apache/brooklyn/core/objs/proxy/InternalEntityFactory.java, core/src/test/java/org/apache/brooklyn/core/objs/proxy/ClassLoaderCacheTest.java, core/src/test/java/org/apache/brooklyn/core/test/qa/performance/EntityPerformanceTest.java
Fixes https://issues.apache.org/jira/browse/BROOKLYN-528
As well as fixing the space leak and decreasing the memory usage, this improves performance of entity creation from about 90 per second to about 230 per second (on my laptop).
=> BROOKLYN-528: same proxy class for all entities of type

core/src/main/java/org/apache/brooklyn/util/core/osgi/Osgis.java, core/src/test/java/org/apache/brooklyn/util/core/osgi/OsgisTest.java
Useful for `brooklyn.libraries` when name:version of pre-installed bundle is specified.
@m4rkmckenna as discussed - can you take a look please?
=> Osgis.bundleFinder: support version range

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsWinRmMachineLocation.java
do a better job of returning public IP but above all don't NPE
=> fix npe that can occur with WinRM when no subnet IP

core/src/main/java/org/apache/brooklyn/core/mgmt/persist/FileBasedStoreObjectAccessor.java
See https://issues.apache.org/jira/browse/BROOKLYN-526.
This is a suggestion for a fix.  Not sure how to go about testing this!
=> Sync file system on temp file before moving it.

api/src/main/java/org/apache/brooklyn/api/mgmt/rebind/mementos/PolicyMemento.java, api/src/main/java/org/apache/brooklyn/api/objs/EntityAdjunct.java, api/src/main/java/org/apache/brooklyn/api/objs/HighlightTuple.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/RebindIteration.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/dto/BasicPolicyMemento.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/dto/MementosGenerators.java, core/src/main/java/org/apache/brooklyn/core/objs/AbstractEntityAdjunct.java, core/src/test/java/org/apache/brooklyn/core/policy/basic/BasicPolicyTest.java, policy/src/test/java/org/apache/brooklyn/policy/autoscaling/AutoScalerPolicyRebindTest.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/domain/PolicySummary.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/transform/PolicyTransformer.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/PolicyResourceTest.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/testing/mocks/RestMockSimplePolicy.java
Policies now return highlights from the REST API. Highlights are a map of ids -> (description, time, task id). They are used to expose more information about a policy, for example the last action or the triggers for a policy.
I have also updated the rebind code such that policies can have there highlights re-bound.
In the future highlights will be extended to all adjuncts.
=> Added highlights to policy endpoint

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/StubbedComputeServiceRegistry.java
Workaround waiting for a fix for https://issues.apache.org/jira/browse/JCLOUDS-1332
Uses `destroyNodesMatchingId` instead of `destroyNode` as it consistently invokes `cleanUpIncidentalResourcesOfDeadNodes`
=> Modify jcloudsLocation.releaseNode

api/src/main/java/org/apache/brooklyn/api/catalog/BrooklynCatalog.java, core/src/main/java/org/apache/brooklyn/core/BrooklynVersion.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogUtils.java, core/src/main/java/org/apache/brooklyn/core/typereg/BasicBrooklynTypeRegistry.java, core/src/main/java/org/apache/brooklyn/core/typereg/RegisteredTypes.java
The switch to osgi bundles and `TypeRegistry` caused confusion where people were consuming the `BrooklynCatalog` API and expecting (reasonably) to see the things they've added.  This PR makes those methods also look in the `TypeRegistry` with `...Legacy(...)` methods added to explicitly search only in the catalog.
All methods are deprecated so in 1.0 we can hopefully delete!
=> Fix back compat of catalog java api

core/src/main/java/org/apache/brooklyn/core/BrooklynFeatureEnablement.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogInitialization.java, core/src/main/java/org/apache/brooklyn/core/mgmt/persist/BrooklynPersistenceUtils.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/RebindIteration.java, server-cli/src/main/java/org/apache/brooklyn/cli/Main.java
prevents errors trying to check legacy catalog items
#814 caused legacy CI instances to be created for TR items which could cause errors; this limits search to legacy CIs to prevent error, and confirms TR items also
=> use type registry when confirming catalog on startup

camp/camp-brooklyn/src/test/resources/java-web-app-and-db-with-function-2.yaml, camp/camp-brooklyn/src/test/resources/java-web-app-and-db-with-function.yaml, camp/camp-brooklyn/src/test/resources/test-java-web-app-spec-and-db-with-function.yaml, camp/camp-brooklyn/src/test/resources/visitors-creation-script.sql, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/BasicExternalConfigSupplierRegistry.java, launcher/src/test/resources/java-web-app-and-db-with-function.yaml, launcher/src/test/resources/visitors-creation-script.sql, locations/container/src/test/resources/generic-application.tests.bom
some of our tests and examples used plain-text passwords, and this has caused some alarm when people have seen them.  we can say "you can use external but we haven't" though isn't it better if our message is "you *should* use external just like we've shown" ?
this sets up a pre-defined external provider called
`brooklyn-demo-sample` which defines `hidden-brooklyn-password` as `br00k11n`.
it can be overridden; PR to follow for docs to explain this.
i think examples elsewhere should be updated to use this wherever a plaintext password is encoded in a blueprint for anything other than the simplest teaching example (clearly caveated and linking to the docs).  i'll do the rest of the stock brooklyn ones shortly.
=> use external config in examples

camp/camp-brooklyn/src/test/resources/visitors-creation-script.sql, launcher/src/test/resources/visitors-creation-script.sql
An issue was created by https://github.com/apache/brooklyn-server/pull/812.
That PR removed the password needed to create the user brooklyn'@'localhost
=> Fix creation script

api/src/main/java/org/apache/brooklyn/api/objs/HighlightTuple.java, core/src/main/java/org/apache/brooklyn/core/enricher/AbstractEnricher.java, core/src/main/java/org/apache/brooklyn/core/entity/lifecycle/ServiceStateLogic.java, core/src/main/java/org/apache/brooklyn/core/feed/AbstractFeed.java, core/src/main/java/org/apache/brooklyn/core/feed/AttributePollHandler.java, core/src/main/java/org/apache/brooklyn/core/feed/Poller.java, core/src/main/java/org/apache/brooklyn/core/objs/AbstractEntityAdjunct.java, core/src/main/java/org/apache/brooklyn/enricher/stock/AbstractAggregator.java, core/src/main/java/org/apache/brooklyn/enricher/stock/AbstractMultipleSensorAggregator.java, core/src/main/java/org/apache/brooklyn/enricher/stock/AbstractTransformer.java, core/src/main/java/org/apache/brooklyn/enricher/stock/AbstractTypeTransformingEnricher.java, core/src/main/java/org/apache/brooklyn/enricher/stock/Aggregator.java, core/src/main/java/org/apache/brooklyn/enricher/stock/Combiner.java, core/src/main/java/org/apache/brooklyn/enricher/stock/Joiner.java, core/src/main/java/org/apache/brooklyn/enricher/stock/Propagator.java, core/src/main/java/org/apache/brooklyn/enricher/stock/UpdatingMap.java, core/src/main/java/org/apache/brooklyn/enricher/stock/reducer/Reducer.java, core/src/main/java/org/apache/brooklyn/entity/group/AbstractMembershipTrackingPolicy.java, core/src/main/java/org/apache/brooklyn/entity/group/SshCommandMembershipTrackingPolicy.java, core/src/test/java/org/apache/brooklyn/core/policy/basic/BasicPolicyTest.java, core/src/test/java/org/apache/brooklyn/enricher/stock/TransformingEnricherTest.java, policy/src/main/java/org/apache/brooklyn/policy/autoscaling/AutoScalerPolicy.java, policy/src/main/java/org/apache/brooklyn/policy/ha/ServiceFailureDetector.java, policy/src/main/java/org/apache/brooklyn/policy/ha/ServiceReplacer.java, policy/src/main/java/org/apache/brooklyn/policy/ha/ServiceRestarter.java, policy/src/test/java/org/apache/brooklyn/policy/autoscaling/AutoScalerPolicyRebindTest.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/testing/mocks/RestMockSimplePolicy.java, software/base/src/main/java/org/apache/brooklyn/entity/machine/pool/ServerPoolImpl.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/SoftwareProcessImpl.java, software/base/src/test/java/org/apache/brooklyn/entity/brooklynnode/SelectMasterEffectorTest.java
Applies #813 to a policy (`ServiceRestarter`) to see how it works.  As reported there it works good, REST and persistence acting as expected.
The API for policy authors was a little awkward, and there were some PR review comments in #813.  This addresses both of these.
I will be adding highlight info to more policies and adjuncts.  If this is reviewed in time I'll do it in a different branch, else I'll add them here for simplicity.
=> More on adjunct highlights

policy/src/main/java/org/apache/brooklyn/policy/action/AbstractScheduledEffectorPolicy.java, policy/src/main/java/org/apache/brooklyn/policy/action/PeriodicEffectorPolicy.java, policy/src/main/java/org/apache/brooklyn/policy/action/ScheduledEffectorPolicy.java, policy/src/main/resources/catalog.bom, policy/src/test/java/org/apache/brooklyn/policy/action/PeriodicEffectorPolicyTest.java, policy/src/test/java/org/apache/brooklyn/policy/action/ScheduledEffectorPolicyTest.java
Adds policies to execute effectors at specific times, either singly or repeated.
=> New periodic and scheduled effector policies

policy/src/main/java/org/apache/brooklyn/policy/action/AbstractScheduledEffectorPolicy.java, policy/src/main/java/org/apache/brooklyn/policy/action/PeriodicEffectorPolicy.java, policy/src/test/java/org/apache/brooklyn/policy/action/ScheduledPolicyRebindTest.java
This should have been included in #822 to test `rebind()`, also includes minor tidying.
=> Rebind test for scheduled policies

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogOsgiVersionMoreEntityRebindTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogOsgiVersionMoreEntityTest.java
Apache releases require there to be no binary files included in the release. Some of the tests depend on binary files and these tests must be skipped at release time. This PR adds the check for this to tests which had previously missed them out.
=> Add check for test resources

policy/src/main/java/org/apache/brooklyn/policy/autoscaling/AutoScalerPolicy.java, policy/src/test/java/org/apache/brooklyn/policy/autoscaling/AutoScalerPolicyPoolSizeTest.java
minor test bug - ensure that policy doesn't start before size reaches 6,
and fix execution context bug found in autoscaler changing pool size
=> fix non-det failure in scaling down test

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AbstractYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/EmptySoftwareProcessYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/FunctionSensorYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/VanillaSoftwareProcessYamlTest.java, core/src/main/java/org/apache/brooklyn/core/sensor/function/FunctionSensor.java, core/src/test/java/org/apache/brooklyn/core/entity/RecordingSensorEventListener.java, core/src/test/java/org/apache/brooklyn/core/sensor/function/FunctionSensorTest.java, core/src/test/java/org/apache/brooklyn/util/core/internal/ssh/ExecCmdAsserts.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/EmptySoftwareProcessImpl.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/VanillaSoftwareProcess.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/VanillaSoftwareProcessImpl.java
See individual commits for more details.
The `FunctionSensor` I primarily added to make it easier to write my `VanillaSoftwareProessYamlTest`, but I think it's a useful addition to allow you to do in yaml what you can do in java entities (i.e. to add a `FunctionFeed` to an entity).
=> Config for VanillaSoftwareProcess disabling ssh polling

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/api/JcloudsLocationConfigPublic.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsMaxConcurrencyStubbedTest.java
Workaround for https://issues.apache.org/jira/browse/BROOKLYN-533: `maxConcurrentMachineDeletions` will ensure that at most this many machine deletions are done at one time for a given `JcloudsLocation` instance.
=> BROOKLYN-533: adds maxConcurrentMachineDeletions

core/src/test/java/org/apache/brooklyn/core/test/entity/TestEntityImpl.java, policy/src/main/java/org/apache/brooklyn/policy/action/AbstractScheduledEffectorPolicy.java, policy/src/main/java/org/apache/brooklyn/policy/action/PeriodicEffectorPolicy.java, policy/src/main/java/org/apache/brooklyn/policy/action/ScheduledEffectorPolicy.java, policy/src/test/java/org/apache/brooklyn/policy/action/AbstractEffectorPolicyTest.java, policy/src/test/java/org/apache/brooklyn/policy/action/PeriodicEffectorPolicyTest.java, policy/src/test/java/org/apache/brooklyn/policy/action/ScheduledEffectorPolicyTest.java, policy/src/test/java/org/apache/brooklyn/policy/action/ScheduledPolicyRebindTest.java
The `PeriodicEffectorPolicy` rebind test(s) were failing non-deterministically in the jenkins master build, and same for me locally.
This PR makes a bunch of changes to fix those, along with various other improvements to the policy implementations. The config / documented behaviour of the policies should be unaffected by these changes.
=> Fix PeriodicEffectorPolicy

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/FunctionSensorYamlTest.java, core/src/main/java/org/apache/brooklyn/core/sensor/function/FunctionSensor.java
It was trying to serialise the TypeCoercions function. We don’t need
that - it coerces automatically.
This is important: the brooklyn master build will fail without this fix!
=> [IMPORTANT] Fix FunctionSensor’s rebind

karaf/init/src/main/resources/catalog-classes.bom, policy/src/main/resources/catalog.bom, test-framework/src/main/resources/catalog.bom
Square brackets within the yaml string meant it was interpreted as an array and broke the initial catalog load. This puts speach marks around so it's interpreted as a string.
=> Fix catalog YAML

core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java
following the change in https://github.com/apache/brooklyn-server/pull/814,
legacy compatibility caused persistence of registered types from bundles, unnecessarily (and error-prone on rebind where it expects a real CatalogItemDto)
=> limit reset/persistence to legacy items

core/src/main/java/org/apache/brooklyn/core/mgmt/ha/HighAvailabilityManagerImpl.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/AbstractManagementContext.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/LocalUsageManager.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/ManagementNodeStateListenerManager.java, core/src/main/java/org/apache/brooklyn/core/mgmt/usage/ManagementNodeStateListener.java, core/src/main/java/org/apache/brooklyn/core/server/BrooklynServerConfig.java, core/src/main/java/org/apache/brooklyn/util/core/flags/TypeCoercions.java, core/src/test/java/org/apache/brooklyn/core/mgmt/ha/HighAvailabilityManagerInMemoryTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/ha/HighAvailabilityManagerTestFixture.java, core/src/test/java/org/apache/brooklyn/core/mgmt/usage/ManagementNodeStateListenerTest.java, core/src/test/java/org/apache/brooklyn/util/core/internal/TypeCoercionsTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/core/mgmt/persist/jclouds/HighAvailabilityManagerJcloudsObjectStoreTest.java
As discussed on the dev@brooklyn mailing list, subject `UsageListener: notified of promotion to master?`...
Adds support for registering a `ManagementNodeStateListener`, to be notified of the Brooklyn server's state changes such as when it becomes "master".
=> Add ManagementNodeStateListener support

core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java
If the BasicBrooklynCatalog fails to load a catalog item, it will now fall back to the type registry.
=> Fix BasicBrooklynCatalog create Spec

core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java
When adding a catalog item, throw an exception if there is no brooklyn.catalog in the YAML
=> Throw sensible exception when no brooklyn.catalog

core/src/main/java/org/apache/brooklyn/util/core/osgi/BundleMaker.java, core/src/test/java/org/apache/brooklyn/util/core/osgi/BundleMakerTest.java
Fixes the jenkins exception we hit in https://github.com/apache/brooklyn-server/pull/847#issuecomment-333528749.
This fixes the exception. However, the underlying cause on jenkins was probably a messed up build (the classpath dir should not have been empty!).
Note that I couldn't add the test for this because git can't have an empty dir (it needs to be really empty, rather than containing a single `.gitignore` file or whatever).
The test I ran locally was:
```
@Test
public void testCreateJarFromEmptyClasspathDir() throws Exception {
generatedJar = bundleMaker.createJarFromClasspathDir("/org/apache/brooklyn/util/core/osgi/test/bundlemaker/emptyfolder/");
assertJarContents(generatedJar, ImmutableMap.of(), false);
}
```
=> Fix BundleMaker to handle an empty classpath dir

core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogInitialization.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/RebindIteration.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindCatalogEntityTest.java
Builds on code tidy/deletions in https://github.com/apache/brooklyn-server/pull/846. Please review/merge that first, and then I'll rebase this. Only the final commit in this PR needs reviewed separately.
Move catalog init code to `CatalogInitialization`
Move code from `RebindIteration` so it delegates everything to the `CatalogInitialization`.
Just refactors (no change in behaviour).
=> Catalog init refactor

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/SpecParameterUnwrappingTest.java, core/src/main/java/org/apache/brooklyn/core/entity/BrooklynConfigKeys.java
Since Brooklyn 0.12.0 ([this PR](https://github.com/apache/brooklyn-server/pull/819) precisely) some config keys' name have been deprecated generated a warning when installing a blueprint using those. 
This fixes it by using the new names. It also fixes a typo for `latch.install.resources`
=> Update config keys' deprecated names

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java
In most conditions for AWS deployments (machine sshable) Brooklyn was retrieving the `public-hostname` [metadata](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) for both public **AND** private hostname sensors.
=> Retrieve the right AWS metadata for private hostname

api/src/main/java/org/apache/brooklyn/api/catalog/Catalog.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogClasspathDo.java
As discussed on dev@brooklyn mailing list (subject "Deprecating @Catalog annotation?")
=> Deprecate `@Catalog` annotation

core/src/main/java/org/apache/brooklyn/core/mgmt/ha/OsgiArchiveInstaller.java
This happens when there is an existing unmanaged bundle with the same id
and a replacement bundle is uploaded without the force flag
Tested manually using boms and jars (yaml only and with java)
using curl and br tool.
=> Fix npr when reading streamed bundle

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogOsgiVersionMoreEntityTest.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogBundleLoader.java, core/src/main/java/org/apache/brooklyn/core/mgmt/ha/OsgiArchiveInstaller.java, core/src/main/java/org/apache/brooklyn/core/typereg/BasicBrooklynTypeRegistry.java, core/src/main/java/org/apache/brooklyn/core/typereg/BasicRegisteredType.java, utils/common/src/main/java/org/apache/brooklyn/util/osgi/VersionedName.java, utils/common/src/test/java/org/apache/brooklyn/util/osgi/VersionedNameTest.java
previously this was only allowed if older bundle was a wrapper, or if it was forced;
this could cause problems if such a disallowed addition was forced and then you tried to rebind!
now it stores the bundle from which a registered type comes, so we can sensibly have several types.
we could even allow them to be different - which would of course cause chaos for users,
but if we allow multi-tenant catalogs it will be essential (we simply have to filter for visible
types when looking at the registry, and prevent bundle name collisions - eg by prefixing with tenant)
though for now we don't allow them to be different.
needs testing and test cases still
=> allow types from different bundles if equivalent

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java
This reverts commit 8877368aa4c04e21eecd167538f878c4e0681900.
Please see discussion on this PR: https://github.com/apache/brooklyn-server/pull/869
=> Revert "Retrieve the right AWS metadata for private hostname"

core/src/main/java/org/apache/brooklyn/core/entity/Entities.java, core/src/main/java/org/apache/brooklyn/enricher/stock/AbstractMultipleSensorAggregator.java, core/src/test/java/org/apache/brooklyn/core/entity/ApplicationLifecycleStateStressTest.java, core/src/test/java/org/apache/brooklyn/core/entity/ApplicationLifecycleStateTest.java
As @neykov mentions on #860 we've fixed tests attempted to be fixed in #641 described in https://issues.apache.org/jira/browse/BROOKLYN-525 .
This is the test-only subset of that closed PR.  Curious to see how it fares in jenkins.  Worth retesting this a couple times to make sure the items are fixed.
=> Enable more tests fixed by sensor order guarantees

core/src/main/java/org/apache/brooklyn/entity/group/DynamicCluster.java, core/src/test/java/org/apache/brooklyn/entity/group/DynamicClusterTest.java
If I create a cluster inside a cluster currently the memberSpec is inherited by the second cluster. When that memberSpec is inherited it loops creating an infinite structure. This isn't useful and therefore memberSpecs shouldn't be inherited.
=> Stop memberSpecs being inherited

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/BrooklynDslDeferredSupplier.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/DslComponent.java, core/src/main/java/org/apache/brooklyn/core/mgmt/BrooklynTaskTags.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/LocalSubscriptionManager.java, core/src/main/java/org/apache/brooklyn/util/core/task/BasicExecutionContext.java, core/src/test/java/org/apache/brooklyn/core/mgmt/internal/LocalSubscriptionManagerTest.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/templates/customize/TemplateOptionsOption.java
Execution contexts weren't getting set on subscriptions.  Seems this has always been the case, and I guess subscribers weren't relying on having an execution context, but they should be able to, so policies don't always have to use their own (although they probably should for anything long-running, for cleaner task separation).  This adds a test that shows the problem, then the solution which specially sets the execution context.  (Pretty much everywhere else this isn't a problem because we submit via EC rather than ExecutionManager; but in subscriptions we can't do that given how task tags are passed in.  Ideally should refactor LSM so that it takes the EC not the tags -- but this is easier and works just as well.)
=> Fix execution context on subscriptions

core/src/test/java/org/apache/brooklyn/core/entity/RecordingSensorEventListener.java, core/src/test/java/org/apache/brooklyn/enricher/stock/UpdatingMapTest.java
need to allow a first default event as that transformation may be running slowly
=> avoid UpdatingMapTest non-det failure

api/src/main/java/org/apache/brooklyn/api/mgmt/rebind/mementos/BrooklynMementoPersister.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynComponentTemplateResolver.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/CampInternalUtils.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/EntitiesYamlTest.java, core/src/main/java/org/apache/brooklyn/core/BrooklynFeatureEnablement.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogInitialization.java, core/src/main/java/org/apache/brooklyn/core/config/BasicConfigKey.java, core/src/main/java/org/apache/brooklyn/core/config/internal/AbstractConfigMapImpl.java, core/src/main/java/org/apache/brooklyn/core/location/CatalogLocationResolver.java, core/src/main/java/org/apache/brooklyn/core/mgmt/BrooklynTags.java, core/src/main/java/org/apache/brooklyn/core/mgmt/ha/OsgiManager.java, core/src/main/java/org/apache/brooklyn/core/mgmt/persist/BrooklynMementoPersisterToObjectStore.java, core/src/main/java/org/apache/brooklyn/core/mgmt/persist/XmlMementoSerializer.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/BasicCatalogItemRebindSupport.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/RebindContextImpl.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/RebindContextLookupContext.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/RebindIteration.java, core/src/main/java/org/apache/brooklyn/core/objs/proxy/InternalEntityFactory.java, core/src/main/java/org/apache/brooklyn/core/resolve/entity/CatalogEntitySpecResolver.java, core/src/main/java/org/apache/brooklyn/core/typereg/BasicBrooklynTypeRegistry.java, core/src/main/java/org/apache/brooklyn/core/typereg/BundleUpgradeParser.java, core/src/main/java/org/apache/brooklyn/util/core/ClassLoaderUtils.java, core/src/main/java/org/apache/brooklyn/util/core/task/Tasks.java, core/src/main/java/org/apache/brooklyn/util/core/task/ValueResolver.java, core/src/test/java/org/apache/brooklyn/core/config/MapListAndOtherStructuredConfigKeyTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/persist/XmlMementoSerializerTest.java, core/src/test/java/org/apache/brooklyn/core/typereg/BundleUpgradeParserTest.java, core/src/test/java/org/apache/brooklyn/util/core/task/TasksTest.java, launcher/src/test/java/org/apache/brooklyn/launcher/BrooklynLauncherRebindCatalogOsgiTest.java, launcher/src/test/java/org/apache/brooklyn/launcher/BrooklynLauncherUpgradeCatalogOsgiTest.java
Follow on from #872 which actually applies the upgrade in most places.
One known gap, and possibly some unknown gaps, but the main cases are working.
Suggest revisiting post-YOML as that will make it easier to handle upgrades due to a single instantiation path (instead of the many we currently have).
=> Upgrade types and bundles as per bundle manifest headers

karaf/features/src/main/feature/feature.xml
https://github.com/apache/brooklyn-server/pull/882 added brooklyn-cli to a catalog.bom. This causes brooklyn to fail to start, as karaf can't find brooklyn-cli. This PR adds brooklyn-cli to karaf
=> Add brooklyn-cli as a feature to karaf

api/src/main/java/org/apache/brooklyn/api/mgmt/ExecutionContext.java, api/src/main/java/org/apache/brooklyn/api/objs/Configurable.java, core/src/main/java/org/apache/brooklyn/util/core/task/BasicExecutionContext.java, core/src/test/java/org/apache/brooklyn/util/core/task/ValueResolverTest.java
Also avoid `StackOverflowError` in `ExecutionContext.getImmediately(task)`
When a non-`BasicTask` is passed in.
---
The motivation for deprecating setting a `ConfigKey` as a `Task` is that we really shouldn't be doing it! It can get very messed up if one tries to `getImmediately` or get non-blocking (e.g. by a `Transformer` that is trying to evaluate its result when triggered). That can leave the task in a cancelled state, so all subsequent calls to `task.get()` (i.e. all calls to `config().get(mykey)`) will fail!
Instead, we should be using `TaskFactory` (which is how the DSL evaluation works).
It's good to deprecate this before a major release of 1.0.0.
It would be good to add an overloaded method for setting config to `set(ConfigKey<T>, TaskFactory<T>)` so that such usage doesn't …
=> Deprecates use of Task in ConfigKey

rest/rest-api/src/main/java/org/apache/brooklyn/rest/domain/ApplicationSpec.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/domain/ConfigSummary.java
As per as [the discussion on the ML](https://lists.apache.org/thread.html/274c9b60e5fc15a7f25f0311dd0139667d0c7a5536ff86523010089d@%3Cdev.brooklyn.apache.org%3E), this revert the use of `@JsonInclude` annotation for certain fields of domain objects to insure backward compatibility.
=> Revert @JsonInclude annotations to what it was in 0.12.0 for backward compatibility

core/src/main/java/org/apache/brooklyn/core/config/internal/AbstractConfigMapImpl.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/dto/BasicEntityMemento.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindEntityTest.java, utils/common/src/main/java/org/apache/brooklyn/config/ConfigMap.java
Fixes two issues noted with rebind of dynamic config.  See first commit first for failing test, then the others which fix it and comment.
=> Config on entity dynamic goes on type after persistence

api/src/main/java/org/apache/brooklyn/api/mgmt/ManagementContext.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/BrooklynDslDeferredSupplier.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/DslComponent.java, core/src/main/java/org/apache/brooklyn/core/entity/EntityAsserts.java, core/src/main/java/org/apache/brooklyn/core/mgmt/BrooklynTaskTags.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/AbstractManagementContext.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/LocalSubscriptionManager.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/NonDeploymentManagementContext.java, core/src/main/java/org/apache/brooklyn/util/core/task/BasicExecutionContext.java, core/src/main/java/org/apache/brooklyn/util/core/task/BasicTask.java, core/src/main/java/org/apache/brooklyn/util/core/task/Tasks.java, core/src/test/java/org/apache/brooklyn/core/mgmt/internal/LocalSubscriptionManagerTest.java, core/src/test/java/org/apache/brooklyn/enricher/stock/EnrichersTest.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/templates/customize/TemplateOptionsOption.java
Builds on #875 (review that first) adding just:
* a `Task.warning(msg, false)` that doesn't `LOG.warning`
* `mgmt.lookup(...)` methods supporting adjuncts and more predicates
* removing unnecessary task finalization warnings
* routine to `assertEntityHealthyEventually`
=> Misc enhancements - warnings and more lookup conveniences

api/src/main/java/org/apache/brooklyn/api/mgmt/ManagementContext.java, core/src/main/java/org/apache/brooklyn/core/entity/EntityAsserts.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/AbstractManagementContext.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/NonDeploymentManagementContext.java, core/src/main/java/org/apache/brooklyn/util/core/task/BasicTask.java, core/src/main/java/org/apache/brooklyn/util/core/task/Tasks.java, core/src/test/java/org/apache/brooklyn/enricher/stock/EnrichersTest.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/ApplicationApi.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/EntityApi.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/domain/EntitySummary.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ApplicationResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/EntityConfigResource.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/ApplicationResourceTest.java
This allows clients to efficiently get selected sensors they are interested in.
Does this by adding a `@JsonAnyGetter` map to `EntitySummary`, as done for `TypeSummary` and elsewhere, returning data in `sensors` key.
Re-enables the `fetch` test (disabled in #156) to assert this, but with better logging if the problem recurs.
Also sets batch config read task as transient so it doesn't clutter the activities view.
=> REST `/applications/fetch` can request selected sensors

rest/rest-resources/src/main/resources/OSGI-INF/blueprint/service.xml
This change add some missing endpoint for the karaf distribution:
- `/v1/catalog/bundles`
- `/v1/catalog/types`
=> Add missing REST endpoints for karaf distribution

policy/src/main/resources/catalog.bom
Confirmed that these policies and enrichers are now listed in the catalog.
Successfully used them in a simplistic example:
```
location: localhost
services:
- type: org.apache.brooklyn.entity.stock.BasicStartable
- type: org.apache.brooklyn.entity.stock.BasicStartable
brooklyn.policies:
- type: org.apache.brooklyn.policy.failover.ElectPrimaryPolicy
brooklyn.enrichers:
- type: org.apache.brooklyn.policy.failover.PrimaryRunningEnricher
- type: org.apache.brooklyn.policy.failover.PropagatePrimaryEnricher
```
=> Add ElectPrimaryPolicy (and enrichers) to catalog.bom

utils/common/src/main/java/org/apache/brooklyn/util/javalang/coerce/CommonAdaptorTypeCoercions.java, utils/common/src/test/java/org/apache/brooklyn/util/javalang/coerce/TypeCoercionsTest.java
This fixes https://issues.apache.org/jira/browse/BROOKLYN-561
=> BROOKLYN-461: coerce empty string to URI as null

software/base/src/main/java/org/apache/brooklyn/entity/software/base/VanillaSoftwareProcessImpl.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/VanillaSoftwareProcessTest.java
When stop / starting a VanillaSoftwareProcess with ssh monitoring the
process will never be marked as healthy after a stop start.
On a restart the feeds are not disconnected so a service.notup.indicator
is set.  When this is cleared on start the ServiceNotUpLogic will detect
the change and set the isUp sensor true.  However when stopping the
process feeds are disconnected so no service.notup indicators are set.
This means the ServiceNotUp logic will not detect a change on start and
won't set the service isUp sensor to true.
Fixed by setting a service.notUp.indicator on stop.
=> Fix VSP stop/start when ssh monitoring disabled

core/src/main/java/org/apache/brooklyn/entity/group/DynamicCluster.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicClusterImpl.java, core/src/main/java/org/apache/brooklyn/entity/group/zoneaware/BalancingNodePlacementStrategy.java, core/src/test/java/org/apache/brooklyn/core/location/SimulatedLocation.java, core/src/test/java/org/apache/brooklyn/entity/group/DynamicClusterWithAvailabilityZonesRebindTest.java, core/src/test/java/org/apache/brooklyn/entity/group/DynamicClusterWithAvailabilityZonesTest.java
Fixes https://issues.apache.org/jira/browse/BROOKLYN-545
Below is an extract from the comments in the code, explaining it - see other code comments for more info:
```
// Previously, when there was a mutable default value for ZONE_FAILURE_DETECTOR, the second cluster
// would include failure info for the first cluster's zone-locations. When these were unmanaged,
// the zone-locations would become dangling referenes within the ZoneFailureDetector. This caused
// NPE on rebind.
//
// Config key persistence was then changed so that statically defined keys (such as ZONE_FAILURE_DETECTOR,
// declared on the DynamicCluster class) would not be persisted. This meant that the ZoneFailureDetector
// state was no longer persisted for either location. The NPE on rebind went away, but the config key
// …
```
=> BROOKLYN-545: Fix DynamicCluster.zoneFailureDetector default val

core/src/main/resources/org/apache/brooklyn/core/mgmt/persist/deserializingClassRenames.properties
Fixes https://issues.apache.org/jira/browse/BROOKLYN-566
These were renamed in https://github.com/apache/brooklyn-library/pull/123, which broke rebind if the persisted state contained a SaltEntity from 0.11.0.
Also see https://github.com/apache/brooklyn-library/pull/144
=> BROOKLYN-566: fix SaltEntity rebind to historic state

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/DslUtils.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ObjectsYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/DslUtilsTest.java
See https://issues.apache.org/jira/browse/BROOKLYN-565?focusedCommentId=16264592&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16264592 for an explanation of why the attempted fix was reverted. Leaving the tests (marked "Broken") in this PR, because they are still useful to demonstrate the failure and the workaround.
=> BROOKLYN-565: fix Brooklyn:object with nested dsl

core/src/main/java/org/apache/brooklyn/core/sensor/password/CreatePasswordSensor.java, core/src/test/java/org/apache/brooklyn/core/sensor/password/CreatePasswordSensorTest.java
Character groups are groups like "capital letters", "numbers", etc. This option allows a blueprint to require that the generated password contains at least one character from every group.
It is common (e.g. Microsoft default password policy) to see a requirement like "must contain characters from at least 3 groups". Previously, this sensor could not guarantee that this would happen.
Use it like this:
```yaml
- type: org.apache.brooklyn.core.sensor.password.CreatePasswordSensor
name: my.password
password.length: 10
password.character.groups:
- "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
- "abcdefghijklmnopqrstuvwxyz"
- "1234567890"
- "-_=+[{]};:|`~,<.>/?!@#$%^&*()"
```
=> CreatePassworkSensor: support "character groups"

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/DslAndRebindYamlTest.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/RebindExceptionHandlerImpl.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/RebindIteration.java
Adds test, marked as "Broken" so not run by jenkins, which demonstrates the bug reported at https://issues.apache.org/jira/browse/BROOKLYN-549
=> BROOKLYN-549: fix policy rebind's execution context

core/src/main/java/org/apache/brooklyn/util/core/json/BrooklynObjectsJsonMapper.java, core/src/main/java/org/apache/brooklyn/util/core/json/DurationSerializer.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/ShellEnvironmentSerializerTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessShellEnvironmentTest.java
This change is useful when generating environment variables.
The use-case was a blueprint that took a map of values, turning it into an env variable that is a json string. If that map contained a `Duration`, then the env variable would contain something like `{"delay": {"nanos": 30000000}}`. With this change, it will instead generate `{"delay": "5m"}`.
=> ShellEnvSerializer: handle Duration

core/src/main/java/org/apache/brooklyn/core/location/AbstractMachineLocation.java, core/src/main/java/org/apache/brooklyn/location/localhost/LocalhostMachineProvisioningLocation.java, core/src/main/java/org/apache/brooklyn/location/ssh/SshMachineLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsSshMachineLocation.java, software/winrm/src/main/java/org/apache/brooklyn/location/winrm/WinRmMachineLocation.java
Introduces `AbstractMachineLocation` base class to hold responsibilities that may otherwise be duplicated between `SshMachineLocation` and `WinRmMachineLocation`.
=> AbstractMachineLocation base class

core/src/main/java/org/apache/brooklyn/entity/group/DynamicCluster.java
This is required so child clusters don't inherit this from their parent as it doesn't work.
=> Stop dynamiccluster.zone.enable inheritance

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AbstractYamlRebindTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/SetLimitsCustomizerIntegrationTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/SetLimitsCustomizerTest.java, core/src/test/java/org/apache/brooklyn/util/core/internal/ssh/ExecCmdAsserts.java, software/base/src/main/java/org/apache/brooklyn/entity/machine/SetLimitsCustomizer.java, software/base/src/test/java/org/apache/brooklyn/entity/machine/SetLimitsCustomizerTest.java
I tested this with the catalog item:
```
brooklyn.catalog:
id: my-nginx-node
itemType: entity
item:
type: org.apache.brooklyn.entity.proxy.nginx.NginxController
brooklyn.parameters:
- name: ulimits
type: java.util.List
description: |
Contents to add to the limits config file
default:
- "* soft nofile 16384"
- "* hard nofile 16384"
- "* soft nproc 16384"
- "* hard nproc 16384"
provisioning.properties:
machineCustomizers:
- $brooklyn:object:
type: io.cloudsoft.amp.cluster.customizer.SetLimitsCustomizer
contents: $brooklyn:config("ulimits")
nginx.sticky: false
install.version: 1.12.1
```
I deployed this to aws eu-west-1 using `imageId: eu-west-1/ami-5f76b626` (i.e. the official centos marketplace image).
I then checked that the nginx process had the correct …
=> Adds SetLimitsCustomizer for centos/rhel

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/transform/TaskTransformer.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/ActivityRestTest.java
Fixes https://issues.apache.org/jira/browse/BROOKLYN-571
=> BROOKLYN-571: fix rest activity for unmanaged entity

core/src/main/java/org/apache/brooklyn/entity/group/DynamicClusterImpl.java, core/src/test/java/org/apache/brooklyn/entity/group/DynamicClusterTest.java
Previously the limit was ignored by resizeByDelta.
=> DynamicCluster's max size applies to all calls to grow

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java
`JcloudsMaxConcurrencyStubbedTest` demonstrates the need for this synchronization: tearDown can fail because the `obtain` is called in a different thread from the `releaseMachine`. The id added to `vmInstanceIds` in obtain was not yet visible to the thread executing `releaseMachine`, so it failed.
To reproduce, try setting `@Test(invocationCount=...)` to something big. For me, it failed after 200ish runs.
```
2017-12-20 16:24:31,348 INFO  TESTNG INVOKING CONFIGURATION: "Surefire test" - @BeforeMethod org.apache.brooklyn.location.jclouds.JcloudsMaxConcurrencyStubbedTest.setUp()
2017-12-20 16:24:31,349 INFO  Added external config supplier named 'brooklyn-demo-sample': org.apache.brooklyn.core.config.external.InPlaceExternalConfigSupplier@67a84d80
2017-12-20 16:24:31,349 INFO  TESTNG PASSED …
```
=> Sync on jcloudsLocation.vmInstanceIds

core/src/main/java/org/apache/brooklyn/entity/group/DynamicClusterImpl.java, core/src/test/java/org/apache/brooklyn/entity/group/DynamicClusterTest.java
Building on PR #916 and the conversation in https://github.com/apache/brooklyn-server/pull/916#discussion_r157902790, this changes the behaviour of resize so that it will grow to the maxSize.
For example, imaging the extreme case where we have `initialSize=1, maxSize=10`, and an auto-scaler policy decides that the cluster should be resized to 11. Instead of throwing an exception, the behaviour now will be that the first call to `resize(11)` will cause us to resize to the max of 10 (logging a warning). A subsequent call to `resize(11)` by the policy will throw the `InsufficientCapacityException`.
=> DynamicCluster: resize to maxSize, before throwing InsufficientCapacity

core/src/main/java/org/apache/brooklyn/core/mgmt/ha/HighAvailabilityManagerImpl.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ServerResource.java
ServerResource#getHighAvailabilityPlaneStates obtains a new plane sync
record when the master node ID in the first one it obtained is null.
This generally only happens when the web-console tries to obtain the
HA status before the server has started up.
Fixes https://issues.apache.org/jira/browse/BROOKLYN-167.
=> Fix reporting of master ID when web API used before persistence is ready

rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/BundleApi.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/domain/TypeDetail.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/BundleResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/transform/TypeTransformer.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/BundleAndTypeResourcesTest.java
It was noted that if the same type is defined in two different bundles, the API does not let you distinguish between the two.  This adds `/catalog/bundles/{symbolicName}/{version}/types/{typeSymbolicName}/{typeVersion}` to resolve that.  (It also adds the two immediate ancestor paths, with `../types` listing types in the bundle and `../types/{typeSymbolicName}` giving `TypeDetail` assuming `typeVersion==version`).
It also adds a bunch of tests for behaviour when adding the same type ID:
```
testAddSameTypeTwiceInSameBundle_SilentlyDeduped()
testAddSameTypeTwiceInSameBundleDifferentDisplayName_LastOneWins()
testAddSameTypeTwiceInSameBundleDifferentDefinition_Disallowed()
testAddSameTypeTwiceInDifferentBundleDifferentDefinition_Disallowed() …
```
=> Bundle type endpoint

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/test/policy/failover/ElectPrimaryTest.java
`ElectPrimaryTest.testSelectionModeFailoverReelectWithPreference` sometimes fails in apache jenkins. This reduces the race by us waiting for 100ms after changing the sensor, before we invoke the effector manually!
The race happens in `testSelectionModeFailoverReelectWithPreference` when the `ElectPrimaryPolicy` invokes the effector (because the child's WEIGHT_SENSOR has changed), and at the same  time the test explicitly invokes the `ElectPrimaryEffector`.
There are two threads concurrently executing the effector: the policy's invocation is using `SelectionMode.FAILOVER` and the test's invocation is using `SelectionMode.BEST`. The first   thread calculates `newPrimary=a` (because that is the current primary, and it is still ok). We then context switch to the second thread which calculates …
=> ElectPrimaryTest: decrease race

core/src/main/java/org/apache/brooklyn/location/ssh/SshMachineLocation.java, core/src/main/java/org/apache/brooklyn/util/core/mutex/MutexSupport.java, core/src/main/java/org/apache/brooklyn/util/core/mutex/WithMutexes.java, core/src/test/java/org/apache/brooklyn/util/core/mutex/WithMutexesTest.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessSshDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/lifecycle/ScriptHelper.java
Modifies signature of `WithMutexes.acquireMutex()` to throw unchecked `RuntimeInterruptedException` to ease the burden on callers.
=> WithMutexes cleanup

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlPolicyTest.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicFabric.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/BundleAndTypeResourcesTest.java
icons set on catalog items previously could only come in metadata, unlike name and description which could be in metadata _or_ in the `item` yaml.  as setting an `iconUrl` in the item yaml is valid (like `description` and display `name`), we should also special case check this when preparing catalog item metadata, treating all three the same.  see the most recent commit.
this fixes a bug where the icons in `policy/src/main/resource/catalog.bom` weren't getting picked up in the catalog (but they were being seen when instances were deployed).
two tiny other commits which i've noticed in the course of debugging also
=> Fix icons in catalog, and a few misc

core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, policy/src/main/resources/catalog.bom, test-framework/src/main/resources/catalog.bom
In YAML, one can mark a catalog item as `deprecated` but it works only when the flag it set as the `brooklyn.catalog` level.
This allows each catalog item to use the deprecated flag as one see fit. For example, I used it for the deprecated policies/enrichers we have within Brooklyn (see changes in bom files)
=> Allow deprecation as the catalog item level

software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessSshDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessWinRmDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/VanillaWindowsProcessWinRmDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/lifecycle/WinRmExecuteHelper.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/VanillaWindowsProcessTest.java, software/winrm/src/test/java/org/apache/brooklyn/util/core/internal/winrm/RecordingWinRmTool.java
This PR prevents processes concurrently trying to install items on the same winrm location.  It is as similar as possible to how we handle ssh.
=> Winrm hold mutex for install

api/src/main/java/org/apache/brooklyn/api/catalog/BrooklynCatalog.java, api/src/main/java/org/apache/brooklyn/api/typereg/RegisteredType.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AbstractJcloudsRebindStubYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AbstractJcloudsStubYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AbstractYamlRebindTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AbstractYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/JcloudsRebindWithYamlDslTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlEntityTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/qa/performance/CatalogPerformanceTest.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogUtils.java, core/src/main/java/org/apache/brooklyn/core/typereg/BasicBrooklynTypeRegistry.java, core/src/main/java/org/apache/brooklyn/core/typereg/RegisteredTypes.java, core/src/test/java/org/apache/brooklyn/core/catalog/internal/StaticTypePlanTransformerTest.java, core/src/test/java/org/apache/brooklyn/core/typereg/BasicBrooklynTypeRegistryTest.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/CatalogResource.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/CatalogResourcePerformanceTest.java
this populates the `supertypes` field of `RegisteredType` instances better, now including all java supertypes (and for specs only including what it's a spec for, ie `Entity`, now excluding the `EntitySpec` class).
this is WIP as i'd also like to include declared `RegisteredType` supers.
this is slightly messy on the API however.  specifically consider a YAML type `b` declaring its super as a java `type: a.A`, and a YAML type `c` declaring super `type: b`.  in java, the supers of `c` would then be `[ RegisteredType[b], Class[a.A] ]` (plus any supers of `a.A`).  what should this look like in REST?
currently we return a list of strings for all supers so the json response in `TypeSummary` will include `supertypes: [ b:0.0.0_SNAPSHOT, a.A ]`.
other options are available to better distinguish …
=> collect supertypes for registered types

core/src/main/java/org/apache/brooklyn/core/entity/lifecycle/ServiceStateLogic.java, core/src/main/java/org/apache/brooklyn/util/core/javalang/ReflectionScanner.java, parent/pom.xml, pom.xml, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/BundleAndTypeResourcesTest.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/CatalogResourceTest.java, server-cli/src/main/java/org/apache/brooklyn/cli/lister/ClassFinder.java
0.9.9-RC1 is unable to read classes containing lambda functions. This meant that `brooklyn list-objects` did not output all classes. Refer to ronmamo/reflections#15 for futher context.
There is a more recent release of reflections that I think fixes further issues (see GitHub) but it relies on Guava v20. ronmamo/reflections#194
Reflections' dependency on com.google.code.findbugs:annotations is excluded because it clashes with a version from airline and should only be needed at compile time anyway.
=> Update Reflections dependency

utils/common/src/main/java/org/apache/brooklyn/util/repeat/Repeater.java
See https://issues.apache.org/jira/browse/BROOKLYN-573
=> BROOKLYN-573: repeater not log stacktrace repeatedly

rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/EffectorResourceTest.java
`tearDown` in EffectorResourceTest is copied from elsewhere but calls
TestRendererHints.clearRegistry();
which is documented to be called from only one test in the suite (it's already called from SensorResourceTest).
This change prevents a race condition resulting in intermittent failure of SensorResourceTest
=> Remove unnecessary tearDown step with duplicate call of method

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/BrooklynDslDeferredSupplier.java
We ran a test in QA that lasted 1 hour. There were 98,275 of these debug log messages (out of 226,712 total log messages at debug or above).
=> BROOKLYN-576: decrease debug logging for resolved DSL

core/src/main/java/org/apache/brooklyn/util/core/text/TemplateProcessor.java, core/src/test/java/org/apache/brooklyn/util/core/text/TemplateProcessorTest.java
DotSplittingTemplateModel implements `TemplateHashModelEx2` (rather than just `TemplateHashModel`), meaning config/sensor map key/vals can be iterated in templates.
For example:
```
<#list config['sections'] as k, v>
${k} = ${v}
</#list>
```
Until now a snippet like this would have caused an exception with message "NonExtendedHashException: For "#list" list source: Expected an extended hash, but this has evaluated to a hash (wrapper: org.apache.brooklyn.util.core.text.TemplateProcessor$DotSplittingTemplateModel)"
=> Support iteration of hashes in templates

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/DefaultConnectivityResolver.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/AbstractJcloudsLiveTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsWinrmingLiveTest.java
- add Azure ARM live test
- improve error message for DefaultConnectivityResolver
---
When `DefaultConnectivityResolver.getReachableAddresses` now fails when no reachable address are found with this error message
```
2018-02-21 11:47:15,502 ERROR None of the addresses [168.63.120.198, 10.0.0.4] of node {id=brp4hwrr/brp4hwrr-9f7, providerId=/subscriptions/012e832d-7b27-4c30-9f21-22cdd9159d12/resourceGroups/brp4hwrr/providers/Microsoft.Compute/virtualMachines/brp4hwrr-9f7, name=brp4hwrr-9f7, location={scope=REGION, id=westeurope, description=West Europe, parent=azurecompute-arm, iso3166Codes=[NL]}, group=brp4hwrr, imageId=westeurope/MicrosoftWindowsServer/WindowsServer/2016-Datacenter, os={family=windows, version=2016-Datacenter, description=2016-Datacenter, is64Bit=true}, …
```
=> Improve JcloudsWinrmingLiveTest coverage

rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/EffectorResourceTest.java
e.g. this failed in https://builds.apache.org/view/B/view/Brooklyn/job/brooklyn-server-master-docker/69/
```
Regression
org.apache.brooklyn.rest.resources.EffectorResourceTest.testInvokeEffectorWithTimeoutTimesOut
Error Message
responseMap={id=TfFAYVbX, displayName=sleepEffector, description=Invoking effector sleepEffector on TestEntity:et9d with parameters {duration=5m}, entityId=et9dfmhgbc, entityDisplayName=TestEntity:et9d, tags=[EFFECTOR, {type=org.apache.brooklyn.api.mgmt.ManagementContext}, {wrappingType=contextEntity, entity={type=org.apache.brooklyn.api.entity.Entity, id=et9dfmhgbc}}, {wrappingType=targetEntity, entity={type=org.apache.brooklyn.api.entity.Entity, id=et9dfmhgbc}}, {entityId=et9dfmhgbc, effectorName=sleepEffector}], submitTimeUtc=1.524143241939E12, …
```
=> Fix non-deterministic EffectorResourceTest

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/SshCommandSensorYamlRebindTest.java, core/src/main/java/org/apache/brooklyn/core/sensor/ssh/SshCommandSensor.java, core/src/main/java/org/apache/brooklyn/util/core/flags/TypeCoercions.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindHistoricSshCommandSensorTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindTestFixture.java, core/src/test/resources/org/apache/brooklyn/core/mgmt/rebind/ssh-command-sensor-entity-dnlz7hpbdg, core/src/test/resources/org/apache/brooklyn/core/mgmt/rebind/ssh-command-sensor-feed-a9ekg3cnu0, utils/common/src/main/java/org/apache/brooklyn/util/guava/Functionals.java, utils/common/src/main/java/org/apache/brooklyn/util/text/StringFunctions.java
See the two separate commits:
* First fixes the big problem that rebind to historic persisted state is broken
* Second improves the `SshCommandSensor` so that we don't use anonymous inner classes (making our persisted state easier to support long-term)
=> Fix SshCommandSensor rebind

parent/pom.xml
This is required for Jenkins build as we now use a local m2 cache
=> Add .m2 folder in the list of ignore folders for the RAT plugin.

core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindHistoricSshCommandSensorTest.java, core/src/test/java/org/apache/brooklyn/entity/group/SshCommandMembershipTrackingPolicyTest.java
Noticed test output from SCMTPT failing with
the tool output referring to the commands from RHSCST in a
brooklyn-server build failure.
=> Add RecordingSshTool clears to selected tests

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/templates/customize/ExtraPublicKeyDataToAuthOption.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/provider/AbstractJcloudsLocationTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/provider/AwsEc2LocationLiveTest.java, utils/common/src/main/java/org/apache/brooklyn/util/internal/BrooklynSystemProperties.java
we install this ourselves in addition so no need, and if we ask jclouds to do it, it seems to break sometimes (eg when keyPair is set).
there is a system property that can be set to revert for legacy behaviour.
=> disable jclouds authorizePublicKey for extra ssh public key data

api/src/main/java/org/apache/brooklyn/api/mgmt/rebind/RebindManager.java, api/src/main/java/org/apache/brooklyn/api/mgmt/rebind/mementos/BrooklynMementoPersister.java, core/src/main/java/org/apache/brooklyn/core/entity/AbstractEntity.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/EntityManagementSupport.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/NonDeploymentManagementContext.java, core/src/main/java/org/apache/brooklyn/core/mgmt/persist/BrooklynMementoPersisterToObjectStore.java, core/src/main/java/org/apache/brooklyn/core/mgmt/persist/PersistenceObjectStore.java, core/src/main/java/org/apache/brooklyn/core/mgmt/persist/StoreObjectAccessorLocking.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/PeriodicDeltaChangeListener.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/RebindManagerImpl.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindEntityTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindTestUtils.java, software/base/src/main/java/org/apache/brooklyn/entity/machine/MachineAttributes.java
Most of the changes are to allow us to write tests, and the tests themselves. The actual important production-code changes is really just two if statements wrapping the calls to `onAttributeChanged(attribute)` and `onChanged(entity)`!
=> Persistence efficient: unchanged and transient attributes

core/src/main/java/org/apache/brooklyn/core/typereg/RegisteredTypes.java, core/src/test/java/org/apache/brooklyn/core/typereg/RegisteredTypesTest.java
This PR follows on from #968 
It adds 2 commits.  The first adds tests for the functionality fixed in #968 
The second changes the logic in #968 in a way that I think is equivalent but I haven't managed to add the requisite test coverage to prove this.
=> Add registered types test

api/src/main/java/org/apache/brooklyn/api/entity/Entity.java, core/src/main/java/org/apache/brooklyn/core/entity/EntityInternal.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/ApplicationApi.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/domain/EntityDetail.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ApplicationResource.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/ApplicationResourceTest.java
and adds some new features:
noticed that fetch actually recurses through all children entities which was never the intention and is wasteful at scale.  also for usability it would be nice to include tags and all/regex sensors and config values.  this adds support for that.
i've deprecated the existing `/fetch` call but left its behaviour unchanged.  have also expanded description of `/list` endpoint.
to make this easier i've promoted `getAll()` from SensorSupportInternal. previously we had no way on the public API to list all sensors for an entity.
it is still @Beta.
=> add an /applications/details endpoint which corrects problems with /fetch

LICENSE, NOTICE, core/src/main/java/org/apache/brooklyn/util/core/json/PossiblyStrictPreferringFieldsVisibilityChecker.java, core/src/test/java/org/apache/brooklyn/util/core/internal/TypeCoercionsTest.java, karaf/features/src/main/feature/feature.xml, locations/container/pom.xml, locations/jclouds/pom.xml, pom.xml, server-cli/LICENSE, server-cli/NOTICE, utils/common/src/test/java/org/apache/brooklyn/util/javalang/coerce/TypeCoercionsTest.java
Update:
* fasterxml.jackson.version 2.7.5 -> 2.9.6
* groovy.version 2.3.7 -> 2.4.15
* commons-beanutils.version 1.9.1 -> 1.9.3
* commons-collections.version 3.2.1 -> 3.2.2
In response to CVEs in the old versions.  (It is not confirmed that those CVEs impact us, but the upgrade is advisable even so.)
The Jackson update also requires an update::
* snakeyaml.version 1.17 -> 1.21
Which is done.  Some of these required minor test changes and some pom-fu and feature-fu to prevent the old versions from being pulled in, hence the changeset being larger than usual for a version bump.
=> Version bumps

karaf/features/src/main/feature/feature.xml
it can cause startup failures; for now live with both snakeyaml versions installed.
=> undo the redeclation of jclouds-byon-api that avoids snakeyaml 1.17

karaf/features/src/main/feature/feature.xml
The feature entry for jclouds-all-compute still requires the snakeyaml 1.17 to be explicitly
added. Now both versions of snakeyaml are available.
=> karaf/features: include snakeyaml 1.17 bundle explicitly

pom.xml
see https://bitbucket.org/asomov/snakeyaml/issues/412/restore-the-boolean-constructors-for for more info
=> use snakeyaml 1.22, avoid binary compatibility issues in 1.20 and 1.21

parent/pom.xml
useful if they do `mvn clean deploy` and rebuild brooklyn projects, as they shouldn't be attempting to deploy brooklyn projects.
(they might rebuild eg the ui if they are whitelabelling.  the alternative is that they _do_ deploy them, but
specify alternative repos via the command line or a .mvn/maven.config)
=> add a profile to allow downstream projects not to deploy brooklyn projects

core/src/main/java/org/apache/brooklyn/core/config/ListConfigKey.java, core/src/main/java/org/apache/brooklyn/core/config/MapConfigKey.java, core/src/main/java/org/apache/brooklyn/core/config/SetConfigKey.java, core/src/main/java/org/apache/brooklyn/core/config/internal/AbstractCollectionConfigKey.java, core/src/main/java/org/apache/brooklyn/core/config/internal/AbstractStructuredConfigKey.java
now supports generics _or_ plain, so persistence is simpler when plain,
(as done for BasicConfigKey)
=> restore the field `subType` for sub-element config keys

core/src/main/java/org/apache/brooklyn/core/mgmt/internal/EntityManagerInternal.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/LocalEntityManager.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/NonDeploymentEntityManager.java, core/src/main/java/org/apache/brooklyn/core/objs/proxy/InternalEntityFactory.java, core/src/test/java/org/apache/brooklyn/core/entity/proxying/EntityManagerTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/DeployFailureTest.java
Fix for https://issues.apache.org/jira/browse/BROOKLYN-600
Note the `LocalEntityManager. discardPremanaged(Entity)` is a bit more complex/long that it might need to be because I want to make sure it does no harm - fail if the entity or any child is already managed (because then should call `unmanage()` instead.
=> BROOKLYN-600: cleanup entities on deploy-failure

core/src/main/java/org/apache/brooklyn/core/objs/AbstractEntityAdjunct.java, core/src/main/java/org/apache/brooklyn/core/policy/AbstractPolicy.java, policy/src/test/java/org/apache/brooklyn/policy/autoscaling/AutoScalerPolicyRebindTest.java
This reverts commit f6ad11846de2d9ba2e9004648179270e3ca3c25f, reversing
changes made to c782aae54f424e317c0999f5cde3fab19bc45cfb.
This PR broke `DynamicClusterWithAvailabilityZonesRebindTest.testRebindWithCustomZoneFailureDetector`, because it caused the feed to be persisted (which should not have been).
I created this revert by running:
```
git revert f6ad11846d -m 1
```
=> Revert "This closes #988"

karaf/features/pom.xml, pom.xml
Bumping jetty version to 9.3.24 (from 9.3.14) done in #991 clashes with jetty that ships in karaf 4.1.2, breaking the build. Therefore bumping karaf to 4.1.6.
Replaces https://github.com/apache/brooklyn-server/pull/994 - difference is this PR also bumps the `karaf.plugin.version` to match.
Also see https://github.com/apache/brooklyn-ui/pull/70
=> Bump karaf to 4.1.6 (from 4.1.2)

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ExternalConfigYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/FunctionSensorYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/JcloudsTemplateOptionsYamlAwsTest.java, core/src/test/java/org/apache/brooklyn/core/config/ConfigKeyDeprecationTest.java, core/src/test/java/org/apache/brooklyn/core/effector/EffectorExceptionLoggedTest.java, core/src/test/java/org/apache/brooklyn/core/entity/ApplicationLoggingTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/persist/XmlMementoSerializerTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindHistoricEntitySpecTest.java, core/src/test/java/org/apache/brooklyn/enricher/stock/MathAggregatorFunctionsTest.java, core/src/test/java/org/apache/brooklyn/location/ssh/SshMachineLocationIntegrationTest.java, core/src/test/java/org/apache/brooklyn/location/ssh/SshMachineLocationTest.java, software/base/src/test/java/org/apache/brooklyn/entity/machine/MachineEntityRebindTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessStopsDuringStartTest.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/TestSensorTest.java, test-support/src/main/java/org/apache/brooklyn/test/LogWatcher.java
prevents the logs from missing useful output if testing for a higher-level message,
useful when investigating tests, esp SoftwareProcessStopsDuringStartTest.testStopDuringProvisionWaitsForCompletion where the log messages we want aren't showing because we reset it to warn.
also use try-close syntax for LogWatcher.
=> LogWatcher - don't change log level if not needed

utils/common/src/test/java/org/apache/brooklyn/util/collections/CollectionMergerTest.java
Following on from https://github.com/apache/brooklyn-server/pull/996, this adds a test for that functionality.
=> Add testMergeMapsPreferringSecondOnConflict

karaf/features/src/main/feature/feature.xml
Fixes the following Karaf startup exception:
```
ERROR  82 o.a.a.b.c.BlueprintContainerImpl [tures-3-thread-1] Unable to start blueprint container for bundle org.apache.brooklyn.karaf-init/1.0.0.SNAPSHOT
org.osgi.service.blueprint.container.ComponentDefinitionException: java.lang.NoClassDefFoundError: org/objectweb/asm/commons/AdviceAdapter
at org.apache.aries.blueprint.container.ReferenceRecipe.internalCreate(ReferenceRecipe.java:141) ~[?:?]
at org.apache.aries.blueprint.di.AbstractRecipe$1.call(AbstractRecipe.java:81) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:90) ~[?:?]
at org.apache.aries.blueprint.container.BeanRecipe.setProperty(BeanRecipe.java:810) ~[?:?]
at …
```
=> Add ow2 bundles not included in Karaf

parent/pom.xml
Latest version of Java 1.8.0_191 enforces that Manifest classpath entries be relative.
https://issues.apache.org/jira/browse/SUREFIRE-1588
=> Fix for SUREFIRE-1588

api/src/main/java/org/apache/brooklyn/api/catalog/CatalogItem.java, api/src/main/java/org/apache/brooklyn/api/objs/BrooklynObjectType.java, core/src/main/java/org/apache/brooklyn/core/catalog/CatalogPredicates.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogApplicationItemDto.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogItemBuilder.java, core/src/main/java/org/apache/brooklyn/enricher/stock/aggregator/AggregationJob.java, core/src/test/java/org/apache/brooklyn/core/plan/XmlPlanToSpecTransformer.java, policy/src/main/java/org/apache/brooklyn/policy/failover/PropagatePrimaryEnricher.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ApplicationResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/transform/CatalogTransformer.java, server-cli/src/main/java/org/apache/brooklyn/cli/ItemLister.java
previously `template` was the only way to class something as an application, and it did both:
* generate a spec for an `Application`
* add the `catalog_template` tag so it looks llke a template
this adds support for an `itemType: application` which only does the first of these
=> add distinction between "application" and "template" in catalog itemType

pom.xml
Allows https://github.com/apache/brooklyn-dist/pull/136 review comments to be addressed - i.e. moving docker plugin version to shared pom in brooklyn-server
=> Add version for docker build plugin

karaf/features/src/main/feature/feature.xml
This is a dependency of cxf that was introduced by the version change to 3.2.7.
This adds cxf commands to the karaf shell such as listing endpoints.
=> Add cxf-karaf-commands dependency

pom.xml, software/winrm/pom.xml
Bump versions to match those in karaf 4.2.2, and cxf 3.2.7
And remove exclusions` for winrm4j, which are not needed and make things harder for downstream projects.
The version bumps should not change what actually happens at runtime: these higher numbered bundles will be the ones that export their packages, because they are added by cxf etc. The consequences of depending on the wrong (older) version are: 1) we compile against a different version from that used at runtime; 2) it bloats the distro size and memory usage (because both versions are present); and 3) it cab contribute towards re-wiring problems at startup (where bundles are stopped and started because different versions are being added).
=> Fix dependency versions

karaf/jetty-config/src/main/resources/jetty.xml, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/BrooklynImageChooser.java, parent/pom.xml, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/LogoutApi.java, rest/rest-resources/pom.xml, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/filter/BrooklynSecurityProviderFilterHelper.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/filter/CsrfTokenFilter.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/filter/EntitlementContextFilter.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/LogoutResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ScriptResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ServerResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/security/provider/AbstractSecurityProvider.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/security/provider/AnyoneSecurityProvider.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/security/provider/BlackholeSecurityProvider.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/security/provider/BrooklynUserWithRandomPasswordSecurityProvider.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/security/provider/DelegatingSecurityProvider.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/security/provider/ExplicitUsersSecurityProvider.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/security/provider/LdapSecurityProvider.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/security/provider/SecurityProvider.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/util/MultiSessionAttributeAdapter.java, rest/rest-resources/src/main/resources/OSGI-INF/blueprint/service.xml, rest/rest-server/src/test/java/org/apache/brooklyn/rest/CsrfTokenFilterLauncherTest.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/entitlement/AuthenticateAnyoneSecurityProvider.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/security/provider/TestSecurityProvider.java
mainly to know if each other have authorized.  see https://github.com/apache/brooklyn-server/pull/1032/commits/1a15c36ad9a5caa76bab2e140c89cc4770fa0abb for the main new code, in `MultiSessionAttributeAdapter`.
note this has some historic aborted stuff, in case we need to revisit.  that can be ignored, best to evaluate this _not_ commit-by-commit!
also...
previously it redirected to the user-specific logout; but some clients didn't respect that, and assumed the logout had happened.
not convinced there is a good reason for /logout/{user} ... and if there is, you can now use /logout/redirect to get to it.
previously that was neglected
it's more accurate, and allows clients to distinguish problems from auth fails
=> fix session sharing and simplify logout

karaf/jetty-config/src/main/resources/jetty.xml, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/filter/CsrfTokenFilter.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/util/MultiSessionAttributeAdapter.java
Jetty 9.4 HouseKeeper cleans the session each 10 minutes by default, that is a problem if you are more than 10 minutes in a module browse to other even the MultiSessionAttributeAdapter tries to give you the correct previous session where the Oauth token is stored.
This increase the time scavenge interval and re-send the CSRF token each time.
Also changed the NO CONNECTION message in UI: https://github.com/apache/brooklyn-ui/pull/122
=> Fix session cleaner

core/src/test/java/org/apache/brooklyn/util/core/internal/TypeCoercionsTest.java, utils/common/src/main/java/org/apache/brooklyn/util/javalang/coerce/PrimitiveStringTypeCoercions.java, utils/common/src/test/java/org/apache/brooklyn/util/javalang/coerce/TypeCoercionsTest.java
changes to use a Maybe allow for additional rules to do more coercion
=> tidy string/primitive coercion

karaf/features/src/main/feature/feature.xml, pom.xml
Bumps commons-compress from 1.4 to 1.18. **This update includes security fixes.**
<details>
<summary>Vulnerabilities fixed</summary>
*Sourced from [The Sonatype OSS Index](https://ossindex.sonatype.org/vuln/c30fadee-a5fc-47e5-9b28-3bd160719296).*
> **[CVE-2012-2098]  Cryptographic Issues**
> Algorithmic complexity vulnerability in the sorting algorithms in bzip2 compressing stream (BZip2CompressorOutputStream) in Apache Commons Compress before 1.4.1 allows remote attackers to cause a denial of service (CPU consumption) via a file with many repeating inputs.
> 
> Affected versions: <= 1.4.0
</details>
=> [Security] Bump commons-compress from 1.4 to 1.18

karaf/features/src/main/feature/feature.xml, pom.xml
The updated xstream includes dependencies on libraries that are not
OSGi bundles. This servicemix repackaging, includes these libraries
within the bundle.
Follows on from #1038
=> Use servicemix bundle of xstream at runtime

core/src/main/java/org/apache/brooklyn/util/core/xstream/XmlSerializer.java
Test fails when evaluates * even Karaf works well and can execute Brooklyn and deserializate the classes.
=> Wildcard modified to ** instead *

api/pom.xml, camp/camp-server/pom.xml, karaf/features/src/main/feature/feature.xml, karaf/init/pom.xml, karaf/start/pom.xml, launcher/pom.xml, parent/pom.xml, pom.xml, rest/rest-resources/pom.xml, rest/rest-server/pom.xml, utils/common/pom.xml
Apache Brooklyn uses a lot of the same dependencies are provided by Apache Karaf. However, we redeclare these dependencies and rely on notes and comments to upgrade them when Karaf is upgraded.
Karaf provides a `<dependencyManagement>` element that we can import into our parent `pom.xml`.
This PR does this and removes any duplicates. Where we use a conflicting/alternative version they have been grouped together and commented that they are overriding versions in Karaf. All of them are holding back to older versions of the dependency.
Some properties that are not used with a `<dependency>` are used within a `features.xml` file to declare a `<bundle dependency....>`. These have been grouped next to the `<karaf.version>` property to aid in remembering to update them when Karaf is upgraded. …
=> Use dependencyManagement from Karaf as a bom

core/src/test/java/org/apache/brooklyn/core/entity/lifecycle/ServiceStateLogicTest.java, core/src/test/java/org/apache/brooklyn/entity/stock/LocationEntityTest.java, launcher/src/test/java/org/apache/brooklyn/launcher/BrooklynLauncherTest.java, policy/src/test/java/org/apache/brooklyn/policy/loadbalancing/LoadBalancingPolicySoakTest.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/EffectorResourceTest.java, utils/test-support/src/main/java/org/apache/brooklyn/test/support/FlakyRetryAnalyser.java
We know that some of our unit tests are flaky. Testng has support for retrying tests by implementing `IRetryAnalyzer` interface, then reference that for selected tests.
This does exactly that, and add the retry strategy to the usual suspects.
As a side note, these flaky tests are because of races conditions, or test environments not being properly setup/cleanup. **We should definitely fix the root cause!** But for now, retrying maximum 3 times would eliminate false positive.
=> Retry flaky unit tests

pom.xml
* [SECURITY] Bump `jackson-databind` from 2.9.7 to 2.9.8
Due to transitive dependencies involving `jackson-databind` the following upgrades were also required:
* Bump `cxf.version` from 3.2.7 to 3.2.8
* Bump `jetty.version` from 9.4.12.v20180830 to 9.4.14.v20181114 
* Bump `winrm4` from 0.6.1 to 0.7.0
=> SECURITY Bump jackson-databind to 2.9.8

launcher/src/test/java/org/apache/brooklyn/launcher/BrooklynLauncherErrorTest.java, launcher/src/test/java/org/apache/brooklyn/launcher/BrooklynLauncherTest.java
See https://issues.apache.org/jira/browse/BROOKLYN-611 (from [this comment](https://github.com/apache/brooklyn-server/pull/1049#issuecomment-471919561)).
I'm going to propose this workaround of moving the test into its own class for now, until a proper fix for 611 can be worked out.
=> Move testErrorsCaughtByApiAndRestApiWorks to its own class

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/AwsEc2SessionAwareLocationConfig.java, logging/logback-includes/src/main/resources/brooklyn/logback-logger-excludes.xml
* tune logging so `[profile xxx]` in `~/.aws/config` doesn't cause lots of WARNs
* better description of the role/profile config key
=> minor changes to make working w AWS profiles easier

core/src/main/java/org/apache/brooklyn/core/mgmt/entitlement/Entitlements.java
The UI calls to `extended` end point and that need being entitled for SERVER_STATUS entitlement.  The read-only role hadn't this and that makes show a error message on the interface.
=> Adds SERVER_STATUS entitlement for read-only role

test-framework/src/main/java/org/apache/brooklyn/test/framework/TestCase.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/TestCaseImpl.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/TestCaseTest.java
This adds a new config key called `on.finally.spec` where one can configure it to execute a new entity, regardless of the state of the test. This is very useful to execute cleanups for tests
=> Add support for finally block in TestCase entity

utils/common/src/main/java/org/apache/brooklyn/util/net/ReachableSocketFinder.java
Since the size of 'sockets' can be large, cached thread pool has a high risk in running out of memory and causes the program crashing. Using newFixedThreadPool() is more secure and should be preferred.
=> [SECURITY] change Executors.newCachedThreadPool() to newFixedThreadPool(int)

parent/pom.xml
instead of the root module, so that the SHA-1 written to manifests accurately reflects the state of the code that built it
=> take build number from submodules' git sha1

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/test/policy/failover/ElectPrimaryTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindFeedWithHaTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessStopsDuringStartTest.java
This follows #1049 and add the `FlakyRetryAnalyser` to more tests, based on the latest failure from Jenkins (see: https://lists.apache.org/list.html?dev@brooklyn.apache.org)
=> Add Flaky retry analyser to more tests

parent/pom.xml
Following #1068 "Bumps karaf version to 4.2.7 (latest)" the Brooklyn build was
failing with the below error. 
Seems we can now remove the override from 81edd728
as part of #1035 "Use dependencyManagement from Karaf as a bom".
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.5:process (default) on project rpm-packaging: Failed to resolve dependencies for one or more projects in the reactor. Reason: Missing:
[ERROR] ----------
[ERROR] 1) javax.xml.bind:jaxb-api:jar:2.3.2
[ERROR]
[ERROR]   Try downloading the file manually from the project website.
[ERROR]
[ERROR]   Then, install it using the command:
[ERROR]       mvn install:install-file -DgroupId=javax.xml.bind -DartifactId=jaxb-api -Dversion=2.3.2 -Dpackaging=jar -Dfile=/path/to/file
[ERROR] …
```
=> Remove override for karaf jaxb-api following upgrade to 4.2.7

parent/pom.xml
This is when builds are run within docker, the home directory is not properly expanded and the brooklyn persisted state (created by unit tests) ends up in the workspace. Subsequently, the RAT plugin checks the file within the workspace and fails because of these.
Ignoring them should fix the build issue on docker
=> Ignore RAT check for `.brooklyn` persisted state created by tests

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AutoScalerPolicyYamlTest.java
This has a failing test to demonstrate https://issues.apache.org/jira/browse/BROOKLYN-613 (with the unit test marked as `groups="Broken"` to avoid it breaking the jenkins build, if it were run).
=> BROOKLYN-613: failing rebind test for AutoScalerPolicy config using DSL

karaf/features/src/main/feature/feature.xml, locations/jclouds/pom.xml, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/networking/creator/DefaultAzureArmNetworkCreator.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsStubTemplateBuilder.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsWinrmingLiveTest.java, pom.xml
jclouds 2.1.2 is the latest with a jclouds-karaf build (there isn't one yet for 2.1.3 or 2.2.0).
The biggest improvement (for me) in jclouds 2.1.2 [1] is support for "EC2 r5, t3, and x1 instance types".
I've smoke-tested this in the karaf distro by deploying a Windows entity to aws-ec2.
Note that `org.apache.jclouds.labs/azurecompute/${jclouds.version}` was removed in jclouds 2.1.2. That's fine - we only really want to support azure ARM rather than the ancient azure-classic.
[1] https://jclouds.apache.org/releasenotes/2.1.2/
=> Upgrade jclouds to 2.1.2 (from 2.1.0)

parent/pom.xml, pom.xml
... and bump related versions.
This is so our CXF version matches the one listed for Karaf 4.2.7 (see https://karaf.apache.org/news.html).
It required a new release of winrm4j (0.8.0 has just been released - it is in the sonatype main repo, https://oss.sonatype.org/index.html#nexus-search;quick~winrm4j, but hadn't been synced to search.maven.org yet last time I looked; that normally takes a couple of hours I think).
I tested this by building all of brooklyn, and then (in the karaf `brooklyn-dist/karaf/apache-brooklyn/target/assembly/`) I provisioned a new AWS windows VM with winzip installed:
```
name: windows@aws
location:
jclouds:aws-ec2:
region: us-west-2
identity: <snip>
credential: <snip>
imageNameRegex: Windows_Server-2012-R2_RTM-English-64Bit-Base-.*
imageOwner: 801119661308 …
```
=> Upgrade CXF from 3.2.8 to 3.3.2

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/AbstractComputeServiceRegistry.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java
Azure-ARM locations with no defined `endpoint` led to extreme server performance issues at app deployment time. Eventually causes OOME, Jackson serialisation timeouts, can even hang Chrome sub-process.
Added a check for missing endpoint parameter when deploying to Azure-ARM locations to avoid this issue on the server.
=> add check for missing endpoint

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynComponentTemplateResolver.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynYamlTypeInstantiator.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/CampTypePlanTransformer.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/BrooklynDslInterpreter.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/DslUtils.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/BrooklynDslCommon.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/parse/DslParser.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ValidationMissingTypeYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/DslYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/TagsYamlTest.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/EntityManagementSupport.java, core/src/main/java/org/apache/brooklyn/core/sensor/StaticSensor.java, core/src/main/java/org/apache/brooklyn/core/typereg/BasicBrooklynTypeRegistry.java, core/src/main/java/org/apache/brooklyn/core/typereg/BrooklynTypePlanTransformer.java, core/src/main/java/org/apache/brooklyn/core/typereg/TypePlanTransformers.java, core/src/main/java/org/apache/brooklyn/enricher/stock/aggregator/DashboardAggregator.java, core/src/main/java/org/apache/brooklyn/util/core/ClassLoaderUtils.java, policy/src/main/java/org/apache/brooklyn/policy/action/AbstractScheduledEffectorPolicy.java, policy/src/main/java/org/apache/brooklyn/policy/action/PeriodicEffectorPolicy.java, policy/src/test/java/org/apache/brooklyn/policy/action/PeriodicEffectorPolicyTest.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/AdjunctApi.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/domain/AdjunctDetail.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/AdjunctResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ApplicationResource.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/AdjunctResourceTest.java
Fixes a few minor things I've encountered:
* When invalid plans were sent, the error messages were awful.  Now they are more concise and sometimes more relevant.
* We never called `destroy` on adjuncts
* a couple other negligible things
=> Tidies - adjunct destroy, and better error messages

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/BrooklynDslCommon.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/DslParseComponentsTest.java, core/src/main/java/org/apache/brooklyn/core/sensor/DependentConfiguration.java
Previously, the `$brooklyn:formatString()` didn't accept nested DSL for its pattern, i.e. the first parameter of the function. This fixes it.
=> Add support for use of DSL when specifying the pattern for $brooklyn:formatString()

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java
Although it's not strictly secret, IMO it'd be preferable not to expose the `identity` field in `JcloudsLocation.toString()`, which does pop up in a few random places in the web UI. Display name and ID ought to be sufficient.
=> JcloudsLocation: don’t expose cloud identity in toString()

karaf/jetty-config/src/main/resources/jetty.xml, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/filter/BrooklynSecurityProviderFilterHelper.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/util/MultiSessionAttributeAdapter.java
Allow set up the max age for the cookies using the propertie
```
org.apache.brooklyn.server.maxSessionAge = XX # in seconds
```
Also another propertie for the max inactive interval has been added instead of keep it hard coded as before. The default value if none is configured is the same as before 3601s
```
org.apache.brooklyn.server.maxInactiveInterval = XX # in seconds
```
=> Adding logic to manage a max session age

camp/camp-brooklyn/src/test/yaml/python-webserver.bom
`apt-get install` will try to prompt the user for confirmation when installing a package unless the `-y` parameter is provided. This causes the install to abort is there is no attached terminal.
=> Don’t prompt for confirmation with apt-get

karaf/pom.xml
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …
=> [SECURITY] Use HTTPS to resolve dependencies in Maven Build

utils/jmx/jmxmp-ssl-agent/src/main/java/org/apache/brooklyn/util/jmx/jmxmp/JmxmpAgent.java
Adds a note to the documentation comment for `JmxmpAgent`, to note potential vulnerabilities using JMXMP and to remind users that they should consider their security requirements before using this class.
=> update comment to note potential vulnerabilities for JmxmpAgent

pom.xml, test-support/src/main/java/org/apache/brooklyn/test/LogWatcher.java
Fixes the following CVEs
https://nvd.nist.gov/vuln/detail/CVE-2017-5929
https://nvd.nist.gov/vuln/detail/CVE-2019-10086
=> Update library versions due to CVEs

core/pom.xml, core/src/main/java/org/apache/brooklyn/util/core/crypto/FluentKeySigner.java, core/src/test/java/org/apache/brooklyn/util/core/crypto/SecureKeysAndSignerTest.java, karaf/features/src/main/feature/feature.xml, pom.xml, utils/jmx/jmxmp-ssl-agent/src/test/java/org/apache/brooklyn/util/jmx/jmxmp/JmxmpAgentSslTest.java
This pull request builds on and extends https://github.com/apache/brooklyn-server/pull/1039.
The original branch for that PR was deleted. The git fu to get a branch with these commits was:
```
git fetch upstream pull/1039/head:bump-bouncycastle
git checkout bump-bouncycastle
git pull --rebase
````
---
The build still has the following unit test failures:
```
Tests run: 2366, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 105.431 sec <<< FAILURE! - in TestSuite
testInjectCertificateAuthority(org.apache.brooklyn.util.core.crypto.SecureKeysAndSignerTest)  Time elapsed: 0.181 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
at org.apache.brooklyn.util.core.crypto.SecureKeysAndSignerTest.testInjectCertificateAuthority(SecureKeysAndSignerTest.java:89)
```
As per …
=> [WIP] Bump bouncycastle: 1.51 to 1.61

core/pom.xml, karaf/features/src/main/feature/feature.xml, pom.xml
Bumps `bouncycastle.version` from 1.51 to 1.61.
Updates `bcprov-ext-jdk15on` from 1.51 to 1.61. **This update includes security fixes.**
<details>
<summary>Vulnerabilities fixed</summary>
*Sourced from [The Sonatype OSS Index](https://ossindex.sonatype.org/vuln/3a59870b-28b3-4b6b-86b0-9629ebe9de40).*
> **[CVE-2015-6644] Information disclosure**
> > An information disclosure vulnerability in Bouncy Castle could enable a local malicious application to gain access to user?s private information
> > 
> > -- [source.android.com](https://source.android.com/security/bulletin/2016-01-01#information_disclosure_vulnerability_in_bouncy_castle)
> 
> Affected versions: < 1.55.0
</details>
<details>
<summary>Changelog</summary>
*Sourced from [bcprov-ext-jdk15on's …
=> [Security] Bump bouncycastle.version from 1.51 to 1.61

karaf/features/src/main/feature/feature.xml
See description in https://issues.apache.org/jira/browse/BROOKLYN-627, which this is intended to fix.
I wrote a little script to loop round, starting Brooklyn and tearing it down again (deleting the data dir each time) to see if I could reproduce the error reported in BROOKLYN-627. I could not do so locally, and it continued to work after this fix!
I think it's worth including this fix, speculatively, as it could plausibly fix the non-deterministic issue.
=> BROOKLYN-627: fix okhttp/kubernetes startup issue

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynComponentTemplateResolver.java, core/src/main/java/org/apache/brooklyn/core/mgmt/EntityManagementUtils.java
At present if you refer to an entity which is trivially wrapped to make an application, in a `$brooklyn:entitySpec` DSL, the application is added without being unwrapped.  This is inconsistent with behaviour elsewhere, eg in the UI for "add child" and when a trivially-app-wrapped entity is referred to in `brooklyn.children`.
(FYI a "trivially-app-wrapped" entity is what you get if you say `services: [ { type: my-entity } ]` or in other places where an entity is supplied but the code needs an application and so constructs a trivial BasicApplication instance with the entity as a child.)
This PR corrects the above behaviour, so that eg such a trivially-wrapped-app can be used in a dynamic cluster and the entity is used as the spec, not the application.
Note that it is straightforward to …
=> Unwrap entity specs when used from the DSL

core/src/main/java/org/apache/brooklyn/core/effector/AddEffectorInitializerAbstractProto.java, core/src/main/java/org/apache/brooklyn/core/effector/AddSensorInitializerAbstractProto.java
This makes AddEffectorInitializerAbstractProto public as a recent change
had made it private.  Alternatively we could have pushed the utility
functions to the implementation.
=> There are shared utility functions no longer public

core/src/main/java/org/apache/brooklyn/core/entity/AbstractEntity.java, core/src/main/java/org/apache/brooklyn/core/entity/EntityPostInitializable.java, core/src/main/java/org/apache/brooklyn/core/objs/proxy/InternalEntityFactory.java, core/src/test/java/org/apache/brooklyn/core/entity/EntityInitializersTest.java
For use to add extra validation logic after all initializers have run.
=> add a post-init hook interface for entities

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/BrooklynDslDeferredSupplier.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/DslDeferredFunctionCall.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/DslUtils.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/BrooklynDslCommon.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/DslComponent.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/CustomTypeConfigYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/DslParseTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/DslSerializationTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/TagsYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/DslTestObjects.java, core/src/main/java/org/apache/brooklyn/core/resolve/jackson/BeanWithTypeUtils.java, core/src/main/java/org/apache/brooklyn/core/resolve/jackson/BrooklynJacksonSerializationUtils.java, core/src/main/java/org/apache/brooklyn/core/resolve/jackson/JacksonBetterDelegatingDeserializer.java, core/src/main/java/org/apache/brooklyn/core/resolve/jackson/WrappedValue.java, core/src/main/java/org/apache/brooklyn/core/resolve/jackson/WrappedValuesSerialization.java, core/src/main/java/org/apache/brooklyn/util/core/task/InterruptingImmediateSupplier.java, core/src/test/java/org/apache/brooklyn/core/entity/EntityConfigTest.java, core/src/test/java/org/apache/brooklyn/core/resolve/jackson/LoggingSerializationTest.java, core/src/test/java/org/apache/brooklyn/util/core/task/ValueResolverTest.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/AdjunctResourceTest.java
brooklyn DSL expressions could get mangled when used within a bean-with-type; this improves some small details of how DSL is serialized and deserialized by Jackson for bean with type.  it also improves `WrappedValue` deserialization and handling of `$brooklyn:literal` (deferred until needed)
=> DSL serialization and deserialization

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynComponentTemplateResolver.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynEntityDecorationResolver.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/CustomTypeConfigYamlTest.java, core/src/main/java/org/apache/brooklyn/core/objs/proxy/InternalEntityFactory.java, core/src/main/java/org/apache/brooklyn/core/resolve/jackson/BeanWithTypeUtils.java, core/src/main/java/org/apache/brooklyn/core/resolve/jackson/BrooklynRegisteredTypeJacksonSerialization.java, core/src/main/java/org/apache/brooklyn/entity/group/AbstractGroupImpl.java, core/src/main/java/org/apache/brooklyn/util/core/flags/BrooklynTypeNameResolution.java, core/src/main/java/org/apache/brooklyn/util/core/flags/TypeCoercions.java, core/src/main/java/org/apache/brooklyn/util/core/task/ValueResolver.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsTypeCoercionsWithBuilderTest.java, utils/common/src/main/java/org/apache/brooklyn/util/guava/Maybe.java, utils/common/src/main/java/org/apache/brooklyn/util/guava/TypeTokens.java, utils/common/src/test/java/org/apache/brooklyn/util/guava/TypeTokensTest.java
Allow bean-with-type conversion as part of type coercion.  Maintain data as maps in config a little bit longer.
Major rework of `CustomTypeConfigYamlTest` to do a much better job of enumerating different test cases.
=> Resolve some edge cases in dealing with bean with type config 

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/BrooklynDslCommon.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/CustomTypeConfigYamlOsgiTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/CustomTypeConfigYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/DslSerializationTest.java, core/src/main/java/org/apache/brooklyn/core/resolve/jackson/BeanWithTypeUtils.java, core/src/main/java/org/apache/brooklyn/core/resolve/jackson/BrooklynJacksonSerializationUtils.java, core/src/main/java/org/apache/brooklyn/core/resolve/jackson/WrappedValue.java, core/src/main/java/org/apache/brooklyn/core/resolve/jackson/WrappedValuesSerialization.java, core/src/test/java/org/apache/brooklyn/core/resolve/jackson/MapperTestFixture.java, core/src/test/java/org/apache/brooklyn/core/resolve/jackson/WrappedValuesSerializationTest.java, core/src/test/java/org/apache/brooklyn/util/core/internal/ssh/RecordingSshTool.java
the latter allows us to supply custom objects and then chain additional DSL syntax eg
`$brooklyn:object("[my.CustomType]").attributeWhenReady(...)`
using the normal map argument this is impossible:
```
$brooklyn:object:
type: my.CustomType
```
=> Misc minor - recording SSH track task, and $brooklyn:object accept string

rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/BundleApi.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/BundleResource.java
This adds a new REST API endpoint to the `BundleResource`, which returns the bundle as a ZIP file when invoked
=> Add support for downloading bundle as ZIP files

rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/ApplicationApi.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ApplicationResource.java
When POST requests to `/v1/applications` are made, the beta endpoint do not behave as expected. This is because the form parameters were annotated with only the swagger annotation, not jax-rs, making them effectively useless.
Instead, jax-rs took the first parameter as the body (which is its default) and ignored the others.
=> Use the jax-rs annotations to recognize correctly parameters 

software/winrm/src/main/java/org/apache/brooklyn/util/core/internal/winrm/winrm4j/PrettyXmlWriter.java, software/winrm/src/main/java/org/apache/brooklyn/util/core/internal/winrm/winrm4j/Winrm4jTool.java, software/winrm/src/test/java/org/apache/brooklyn/util/core/internal/winrm/winrm4j/PrettyXmlWriterTest.java
Winrm writes xml to the error stream when powershell commands are run.  This adds an inline pretty printer to the xml so that when it is displayed on the UI it is readable.  Currently it's one single line.
=> Pretty print winrm xml

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/BrooklynDslCommon.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/DslComponent.java, core/src/main/java/org/apache/brooklyn/core/config/ConfigConstraints.java, core/src/main/java/org/apache/brooklyn/core/config/internal/AbstractConfigMapImpl.java, core/src/main/java/org/apache/brooklyn/core/entity/AbstractEntity.java, core/src/main/java/org/apache/brooklyn/core/entity/internal/EntityConfigMap.java, core/src/main/java/org/apache/brooklyn/core/location/AbstractLocation.java, core/src/main/java/org/apache/brooklyn/core/location/internal/LocationConfigMap.java, core/src/main/java/org/apache/brooklyn/core/objs/AbstractConfigurationSupportInternal.java, core/src/main/java/org/apache/brooklyn/core/objs/AbstractEntityAdjunct.java, core/src/main/java/org/apache/brooklyn/core/objs/AdjunctConfigMap.java, core/src/main/java/org/apache/brooklyn/core/objs/BrooklynObjectInternal.java, core/src/test/java/org/apache/brooklyn/core/entity/EntityConfigTest.java, core/src/test/java/org/apache/brooklyn/core/policy/basic/BasicPolicyTest.java, logging/logback-includes/src/main/resources/brooklyn/logback-appender-stdout.xml, utils/common/src/main/java/org/apache/brooklyn/test/Asserts.java, utils/common/src/main/java/org/apache/brooklyn/util/exceptions/ReferenceWithError.java, utils/common/src/main/java/org/apache/brooklyn/util/time/Time.java, utils/common/src/test/java/org/apache/brooklyn/util/time/DurationTest.java
Previously the enforcement of config key constraints was spotty -- there was an explicit check in a few places, such as entity initialization -- but many places it was skipped.
This now does validation when individual keys are set (although not if a map is set, and not if it is a deferred supplier / future / etc) _and_ when keys are retrieved.  Where config keys are declared by a context (eg an entity) the declared key is looked up and used for constraints, so validation is performed even if anonymous (untyped) config keys are used to set or retrieved.
Extensive tests added.
=> Better validation for config keys

core/src/main/java/org/apache/brooklyn/util/core/task/ssh/internal/AbstractSshExecTaskFactory.java, core/src/main/java/org/apache/brooklyn/util/core/task/system/ProcessTaskWrapper.java
Extra streams are created to handle the different windows powershell streams but these were not being passed to winrm.  This fixes that.
=> Pass newly created streams to winrm

api/src/main/java/org/apache/brooklyn/api/mgmt/EntityManager.java, core/src/main/java/org/apache/brooklyn/core/config/ConfigConstraints.java, core/src/main/java/org/apache/brooklyn/core/config/ConstraintViolationException.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/BrooklynGarbageCollector.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/EntityManagementSupport.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/EntityManagerInternal.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/LocalEntityManager.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/NonDeploymentEntityManager.java, core/src/main/java/org/apache/brooklyn/core/objs/proxy/InternalEntityFactory.java, core/src/test/java/org/apache/brooklyn/core/config/ConfigKeyConstraintTest.java, core/src/test/java/org/apache/brooklyn/core/entity/proxying/EntityManagerTest.java, core/src/test/java/org/apache/brooklyn/core/entity/proxying/InternalEntityFactoryTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/ha/HotStandbyTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/osgi/OsgiVersionMoreEntityTest.java, utils/common/src/main/java/org/apache/brooklyn/test/Asserts.java, utils/common/src/main/java/org/apache/brooklyn/util/text/Strings.java, utils/common/src/test/java/org/apache/brooklyn/util/text/StringsTest.java
Useful where we want to see whether there are any runtime validation problems in the spec but not actually start stuff
=> Extend Java API for creation to support dry-run and to report-but-not-fail on constraint violations

core/src/main/java/org/apache/brooklyn/core/mgmt/internal/EntityManagementSupport.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/onthefly/OnTheFlyDynamicLocationPatternRebindTest.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/onthefly/OnTheFlyDynamicLocationPatternTest.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/onthefly/StubAttributes.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/onthefly/StubContainer.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/onthefly/StubContainerImpl.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/onthefly/StubContainerLocation.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/onthefly/StubHost.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/onthefly/StubHostImpl.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/onthefly/StubHostLocation.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/onthefly/StubInfrastructure.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/onthefly/StubInfrastructureImpl.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/onthefly/StubInfrastructureLocation.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/onthefly/StubResolver.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/onthefly/StubResolverTest.java, software/base/src/test/java/org/apache/brooklyn/core/location/dynamic/onthefly/StubUtils.java
And rename tests from `clocker` to `onthefly` because the pattern is more useful than just as used in that downstream project.
=> Fix intermittent unmanagement race

core/src/main/java/org/apache/brooklyn/core/mgmt/internal/BrooklynGarbageCollector.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/LocalEntityManager.java
allow tasks to unmanage the entity where they are running; improve the logic which was meant to allow this
=> don't interrupt tasks related to a deletion/unmanagement

core/src/main/java/org/apache/brooklyn/core/config/external/vault/VaultExternalConfigSupplier.java, core/src/main/java/org/apache/brooklyn/core/config/external/vault/VaultUserPassExternalConfigSupplier.java, core/src/test/java/org/apache/brooklyn/core/config/external/vault/VaultExternalConfigSupplierLiveTest.java
SMART-153 Notes/Testing done
Original behaviour:
- Brooklyn does not start when vault is set up but sealed or not running
Implementation notes: 
- Brooklyn not prevented from starting up with vault sealed/unavailable.
- Attempt to recover from bad state done when vault is accessed (either during deployment or while app running).
- Deployment/Effector fails if vault unavailable.
- Re-try mechanism that tries to recover from a bad state in 1s intervals, up to a specified number of times.
- Number of retries specified in a new property config as below, optional with a default value of 10.
"brooklyn.external.vault.recoverTryCount=X"
TESTING
1. Startup
1.1 Vault unavailable
* login successful
* token set to ""
1.2 Vault running and sealed
* login successful
* token set to ""
1.3 Vault running …
=> SMART-153 - Fixes around sealed/unavailable vault

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/security/provider/DelegatingSecurityProvider.java
If vault is used for security provider and is not ready on startup then
the security provider will fail and will be replaced by the
BlackholeSecurityProvider. This change means that whenever a security
provider fails, the DelegatingSecurityProvider will attempt to
re-initialize it on subsequent authorization attempts.
This change does mean that, when failing over to the BlackholeSecurityProvider, it could be slower to let no one authenticate.
I have added a second change as I noticed a fairly impressive memory leak in how the security provider was used.  Again I'm pretty sure no behaviour was changed here.
=> Fix issue where vault not ready on init

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/filter/BrooklynSecurityProviderFilterJavax.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/filter/BrooklynSecurityProviderFilterJersey.java
Additional header for when using login form now uses X_ to show it is
non-standard.
Handles NPE when server still starting.
=> Improve extra header name, cleanup NPE

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/security/provider/LdapSecurityProvider.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/security/provider/LdapSecurityProviderLiveTest.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/security/provider/LdapSecurityProviderTest.java
Updated login approach was a bit rubbish and doesn't really make sense.
New approach keeps the CN with configured realm and ou as before.
If the username contains a \ or @ then the username is used as the
security principal.  This allows NETBIOS\username or username@realm for
the username field.
=> Ldap login changes

core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, core/src/main/java/org/apache/brooklyn/core/typereg/BrooklynBomYamlCatalogBundleResolver.java
Tags added to the blueprint in composer, are set on the bundle when added to the catalog. 
This PR should be merged together with this one: https://github.com/apache/brooklyn-ui/pull/219
=> Added support for tagged bundles

api/src/main/java/org/apache/brooklyn/api/mgmt/ha/ManagementPlaneSyncRecordPersister.java, core/src/main/java/org/apache/brooklyn/core/mgmt/ha/HighAvailabilityManagerImpl.java, core/src/main/java/org/apache/brooklyn/core/mgmt/ha/ManagementPlaneSyncRecordPersisterToObjectStore.java
Changes related to automatic terminated node removal on startup.
Requirements:
- new configuration property to specify threshold of inactivity after which terminated nodes are to be removed
- nodes removed from persistence on startup of the server
Implementation Notes:
- property in 'brooklyn.cfg' added: brooklyn.ha.timeoutForInactiveNodeRemovalOnStartup
- format of property is a duration, e.g 1h30m, 2d12h, 30s, etc.
- loadSyncRecord() loads the management node data from persistence store. If property above is specified (not ZERO) and node is terminated, compares if its inactivity period is higher than threshold and if so, removes from the persistence store.
- loadSyncRecord() is also periodically called during run so isStartup property introduced to ensure this code is fired only during …
=> Feature - Terminated Node Deletion from persistence on startup

core/src/main/java/org/apache/brooklyn/core/effector/AddDeploySensorsInitializer.java, core/src/main/java/org/apache/brooklyn/core/objs/proxy/InternalEntityFactory.java
This looks up a new configuration options called `brooklyn.deployment.initializers` (comma separated list). If specified on a Brooklyn instance, all deployments will load and execute these initializers. Theses classes are expected to be `EntityInitializer`, if an error occur (either cast or anything else) then the deployment will fail.
The code will try to:
1. load the class from the default class loader.
2. if (1) fails, it will try to load the class from the `TypeRegistry`. This is to allow execution of custom initializers that might be installed in the catalog later on.
3. if (1) and (2) fails, then the deployment is aborted.
This PR contains a new initializer that give more information about the deployment (who and when currently) but it is not set by default (see …
=> Add support setup default initializers for all deployment

core/src/main/java/org/apache/brooklyn/core/mgmt/persist/BrooklynMementoPersisterToObjectStore.java, core/src/main/java/org/apache/brooklyn/core/mgmt/persist/BrooklynPersistenceUtils.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/PeriodicDeltaChangeListener.java
Reverting changes of PR: https://github.com/apache/brooklyn-server/pull/1191
Due to change in solution design, these changes are no longer necessary and should be removed
=> revert for undesired changes - persistence export feature

rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/ServerApi.java, utils/rest-swagger/src/main/java/org/apache/brooklyn/rest/apidoc/RestApiResourceScanner.java
This adds a couple of extra fields in the swagger document: info, showing the current build version, the available schemas, and also the possible authentication mechanism
=> Add info and security definition to the swagger doc

api/src/main/java/org/apache/brooklyn/api/mgmt/EntityManager.java, api/src/main/java/org/apache/brooklyn/api/mgmt/rebind/PersistenceExceptionHandler.java, api/src/main/java/org/apache/brooklyn/api/mgmt/rebind/RebindManager.java, api/src/main/java/org/apache/brooklyn/api/mgmt/rebind/mementos/BrooklynMementoPersister.java, core/src/main/java/org/apache/brooklyn/core/catalog/CatalogPredicates.java, core/src/main/java/org/apache/brooklyn/core/mgmt/ha/ManagementPlaneSyncRecordPersisterToObjectStore.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/LocalEntityManager.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/NonDeploymentManagementContext.java, core/src/main/java/org/apache/brooklyn/core/mgmt/persist/BrooklynMementoPersisterToObjectStore.java, core/src/main/java/org/apache/brooklyn/core/mgmt/persist/BrooklynPersistenceUtils.java, core/src/main/java/org/apache/brooklyn/core/mgmt/persist/XmlMementoSerializer.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/PersistenceExceptionHandlerImpl.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/RebindContextImpl.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/RebindIteration.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/RebindManagerImpl.java, core/src/main/java/org/apache/brooklyn/util/core/xstream/LambdaPreventionMapper.java, core/src/main/java/org/apache/brooklyn/util/core/xstream/XmlSerializer.java, core/src/test/java/org/apache/brooklyn/core/entity/EntitySpecTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/persist/XmlMementoSerializerPerformanceTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/persist/XmlMementoSerializerTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindEntityTest.java, core/src/test/java/org/apache/brooklyn/util/core/xstream/XmlSerializerTest.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ServerResource.java, utils/common/src/main/java/org/apache/brooklyn/test/Asserts.java
It has always been a bad idea but previously we have allowed it.  This causes obscure but horrible problems in many cases:
* lambdas which don't implement Serializable are written by xstream as `null`, and read back as null, with no warning
* lambdas which do implement Serializable might be okay written by xstream but might not, and can be read differently or not at all by different JVMs, and are even more brittle than inner classes
This PR causes us to be stricter about persisting lambdas e.g. within a config key or part of an effector so that we fail fast.
Default is to FAIL if we attempt to write one which will be treated as null, and WARN otherwise.  This can be configured in brooklyn.cfg using the keys in LambdaPreventionMapper.
In addition this adds a delta-persistence synchronously …
=> Be stricter about java lambdas in data which is persisted

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/security/provider/LdapSecurityProvider.java
If ldap user is a member of no groups then they will fail to login but
will have a user associated with the session that cannot easily be
logged out or login as another user.
Fixed by not allowing authentication of a user in no groups.
=> Fix partial login when ldap user in no groups

rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/ServerApi.java
The API '/v1/server/ha/state' failed to work with HTTP error 406 - Not Acceptable.
Changing @produces to @consumes fixes the error.
=> fix for 406 http error on post request ha/state

core/src/main/java/org/apache/brooklyn/core/mgmt/entitlement/WebEntitlementContext.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/filter/EntitlementContextFilter.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/security/provider/LdapSecurityProvider.java
Adds a new attribute in the WebEntitlementContext sincronized with the user session to keep the origin of the user groups
=> Adding new attribute to control save the user groups origin

core/src/main/java/org/apache/brooklyn/util/core/xstream/XmlSerializer.java, core/src/test/java/org/apache/brooklyn/util/core/xstream/CompilerCompatibilityTest.java, core/src/test/java/org/apache/brooklyn/util/core/xstream/ConverterTestFixture.java, pom.xml
Snyk detected the next vulnerabilities on prev version:
```
✗ Arbitrary Code Execution [High Severity][https://snyk.io/vuln/SNYK-JAVA-COMTHOUGHTWORKSXSTREAM-1569176] in com.thoughtworks.xstream:xstream@1.4.17
✗ Arbitrary Code Execution [High Severity][https://snyk.io/vuln/SNYK-JAVA-COMTHOUGHTWORKSXSTREAM-1569177] in com.thoughtworks.xstream:xstream@1.4.17
✗ Arbitrary Code Execution [High Severity][https://snyk.io/vuln/SNYK-JAVA-COMTHOUGHTWORKSXSTREAM-1569178] in com.thoughtworks.xstream:xstream@1.4.17
✗ Arbitrary Code Execution [High Severity][https://snyk.io/vuln/SNYK-JAVA-COMTHOUGHTWORKSXSTREAM-1569179] in com.thoughtworks.xstream:xstream@1.4.17
✗ Arbitrary Code Execution [High Severity][https://snyk.io/vuln/SNYK-JAVA-COMTHOUGHTWORKSXSTREAM-1569180] in …
```
=> Bump xstream to 1.4.18 due to high level vulnerabilities

core/src/main/java/org/apache/brooklyn/util/core/logbook/LogBookQueryParams.java, core/src/main/java/org/apache/brooklyn/util/core/logbook/file/FileLogStore.java, core/src/main/java/org/apache/brooklyn/util/core/logbook/opensearch/OpenSearchLogStore.java, core/src/test/java/org/apache/brooklyn/util/core/logbook/file/FileLogStoreTest.java, core/src/test/java/org/apache/brooklyn/util/core/logbook/opensearch/OpenSearchLogStoreTest.java, core/src/test/resources/brooklyn/util/core/logbook/file/log-sample.txt
It try to find the Ids in the fields and the message for both, `FileLogStore` and `OpenSearchLogStore`,  instead of only search for it on the message as before.
Requires changes in the UI for sending the Ids as independent fields in the query parameters: 
https://github.com/apache/brooklyn-ui/pull/275
=> Fix logbook query by EntityId or TaskId

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ServerResource.java
Calling the terminate on the temporary management context causes closure of OSGI which results in terminating AMP server after this operation. The removal of the termination call fixes the issue. 
It's fine as the temp management context is garbage collected.
=> ensuring the server is not terminated after persistence import

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ServerResource.java
Removing data subdir as not present in a brooklyn generated persistence export
=> Fix for importing a brooklyn generated export

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/BrooklynWebConfig.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/security/provider/LdapSecurityProvider.java
New ConfigKey for set up a regex pattern to be matched by the user names before checking credentials in the LDAP server, avoiding unnecessary request
eg. for  `domain\user` pattern:
```
brooklyn.webconsole.security.ldap.user_name_regex=.*\\.*
```
=> Add user name regex for LDAP authentication

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ServerResource.java
Export feature originally captured a zip 'brooklyn-state-id-timestamp' which also contained a subdir named 'web-persistence-id-timestamp' causing the data dir being unable to be found (as it was not in root but in web-persistence...').
Not straightforward to find the subdir name because of extra data like timestamp, but not really necessary for it to be there so removed.
Now, in the root of archive there is a data dir that has the persistence state data.
=> removing extra subdir causing import issues

test-framework/src/test/resources/test-framework-examples/example-catalog-test.bom, test-framework/src/test/resources/test-framework-examples/example-catalog.bom
Set correct path for `tomcat.png` icon URL on the Apache server.
=> Fix path to tomcat icons on apache.org

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynComponentTemplateResolver.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynEntityDecorationResolver.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/CampTypePlanTransformer.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ConfigYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlEntityTest.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, core/src/main/java/org/apache/brooklyn/core/config/Sanitizer.java, core/src/main/java/org/apache/brooklyn/core/server/BrooklynServerConfig.java, core/src/main/java/org/apache/brooklyn/core/typereg/AbstractTypePlanTransformer.java, core/src/main/java/org/apache/brooklyn/core/typereg/TypePlanTransformers.java, core/src/main/java/org/apache/brooklyn/util/core/osgi/Osgis.java, core/src/test/java/org/apache/brooklyn/core/config/SanitizerTest.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/ServerApi.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ApplicationResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ServerResource.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/EffectorUtilsRestTest.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/EntityConfigResourceTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/VanillaSoftwareProcessStreamsTest.java
This allows the set of tokens used to determine potentially sensitive names to be configured, and allows a configuration to block deployment and some catalog additions of blueprints where such config keys are in plaintext.  Makes these settings available via API to the UI.  Suppresses potentially sensitive data in logs in many places.
=> Configurable sanitizing

api/src/main/java/org/apache/brooklyn/api/mgmt/rebind/mementos/ManagedBundleMemento.java, api/src/main/java/org/apache/brooklyn/api/typereg/OsgiBundleWithUrl.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AbstractYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/test/lite/CampYamlLiteTest.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogBundleDto.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogItemDtoAbstract.java, core/src/main/java/org/apache/brooklyn/core/mgmt/ha/OsgiManager.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/RebindIteration.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/RebindManagerImpl.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/dto/BasicManagedBundleMemento.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/dto/MementosGenerators.java, core/src/main/java/org/apache/brooklyn/core/typereg/BasicBrooklynTypeRegistry.java, core/src/main/java/org/apache/brooklyn/core/typereg/BasicManagedBundle.java, core/src/main/java/org/apache/brooklyn/core/typereg/BasicOsgiBundleWithUrl.java, core/src/main/java/org/apache/brooklyn/core/typereg/BrooklynBomYamlCatalogBundleResolver.java, core/src/main/java/org/apache/brooklyn/core/typereg/BrooklynCatalogBundleResolver.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/domain/BundleSummary.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/BundleResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/CatalogResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/LocationResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ServerResource.java
First commit fixes a problem where if a location is deleted and the bundle was a dedicated BOM for that location, the bundle wasn't deleted.  Now the "delete-empty-bom-bundles" check is done on all type deletions.  (This caused weirdness where if you then try to add the bundle again, it says it is already installed (which was true, though it shouldn't be), and the uninstall triggers the delete-empty-bom-bundles check so at _this_ point the original bundle is also deleted, so if you then try to add the bundle yet again, it works.)
Second commit extends the metadata on bundles to record those added via the REST API and which are thus deleteable, for use in a UI update to follow.
=> Fix catalog deletion bundles and transient

core/src/main/java/org/apache/brooklyn/core/effector/AddSensorInitializer.java, core/src/main/java/org/apache/brooklyn/core/resolve/jackson/BeanWithTypeUtils.java, core/src/main/java/org/apache/brooklyn/entity/group/GroupsChangePolicy.java, core/src/main/java/org/apache/brooklyn/util/core/config/ConfigBag.java, core/src/main/resources/catalog.bom, core/src/test/java/org/apache/brooklyn/core/resolve/jackson/BrooklynRegisteredTypeJacksonSerializationTest.java, core/src/test/java/org/apache/brooklyn/entity/group/GroupsChangePolicyTest.java
This should now be working.
I've been testing this code with this yaml
```   
location: localhost
name: Brooklyn Deployment
services:
- type: org.apache.brooklyn.entity.software.base.EmptySoftwareProcess
example: "dfdfsdfsfs"
displayName: "MyEntity"
brooklyn.initializers:
- type: org.apache.brooklyn.core.sensor.StaticSensor
name: tf.resource.type
static.value: aws_instance
- type: org.apache.brooklyn.entity.group.DynamicGroup
name: EC2 instances
brooklyn.policies:
- type: org.apache.brooklyn.entity.group.GroupsChangePolicy
group: $brooklyn:self()
member.policies: kdjsldl
member.initializers:
- type: org.apache.brooklyn.core.sensor.StaticSensor
name: testsensor
target.type: string
static.value: …
```
=> Groups change policy

pom.xml
That release includes Pax Logging 2.0.13 update:
- with logback 1.2.9 upgrade, fixing CVE-2021-42550
- with log4j 2.17.0 upgrade, fixing CVE-2021-45105
=> Bumping Karaf to the staging version 4.3.5 for update

pom.xml
Karaf updates:
> This release is an important release on the Karaf 4.3.x series containing:
> - upgrade to Pax Logging 2.0.14 with log4j 2.17.1 (fixing CVE-2021-44832)
> - prepare JDK 18 support
> - fix deployment issue by upgrading to Apache Felix FileInstall 3.7.4
> - and much more!
> The Release Notes are available here: https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12311140&version=12351123
=> Updated to Apache Karaf 4.3.6

pom.xml
Mitigates [CVE-2021-27568 ](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-27568) cataloged by [Snyk](https://security.snyk.io/vuln/SNYK-JAVA-NETMINIDEV-1078499) as **Critical**
=> Updated to json-smart 1.4.7

.gitignore, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/TypeApi.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/TypeResource.java
adds an optional iconUrl query parameter, if an alternate icon is specified in the context of an entity
useful in the composer to show custom icons on entities
=> allow lookup of an icon url with respect to an entity

core/src/main/java/org/apache/brooklyn/core/config/Sanitizer.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessStreamsTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/VanillaSoftwareProcessStreamsTest.java
so we can suppress multiline maps esp multiline json/yaml/properties passed as env vars
=> if env var is multiline string, sanitize each line

core/src/main/java/org/apache/brooklyn/util/core/logbook/LogBookQueryParams.java, core/src/main/java/org/apache/brooklyn/util/core/logbook/LogStore.java, core/src/main/java/org/apache/brooklyn/util/core/logbook/LogbookConfig.java, core/src/main/java/org/apache/brooklyn/util/core/logbook/file/FileLogStore.java, core/src/main/java/org/apache/brooklyn/util/core/logbook/opensearch/OpenSearchLogStore.java, core/src/test/java/org/apache/brooklyn/util/core/logbook/file/FileLogStoreTest.java
Adds recursive task query for logbook using limited breadth-first search of child tasks.
Uses https://github.com/apache/brooklyn-server/pull/1316 for UI component.
Signed-off-by: Andrew Donald Kennedy <andrew.international@gmail.com>
=> Adds recursive LogBook query feature

software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/ContainerCommons.java, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/ContainerTaskFactory.java, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/DockerEffector.java, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/DockerSensor.java, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/JobBuilder.java, software/base/src/main/resources/catalog.bom, software/base/src/test/java/org/apache/brooklyn/tasks/kubectl/DockerEffectorTest.java, software/base/src/test/java/org/apache/brooklyn/tasks/kubectl/DockerSensorTest.java, software/base/src/test/java/org/apache/brooklyn/tasks/kubectl/JobBuilderTest.java, software/base/src/test/resources/org/apache/brooklyn/kubectl/sample-both.yaml, software/base/src/test/resources/org/apache/brooklyn/kubectl/sample-effector-dev.yaml, software/base/src/test/resources/org/apache/brooklyn/kubectl/sample-effector.yaml, software/base/src/test/resources/org/apache/brooklyn/kubectl/sample-sensor.yaml
**What**
`kubectl` task factory that allows blueprint designers to externalize effectors and sensors  to containers run on a Kubernetes cluster.
**Why**
Because it is practical and higly customizable. 
**Testing**
Sample blueprints are provided. Also tests for sensor, effector and task factory.
=> Adding Kubectl Task factory, Docker effector  and Docker Sensor

rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/EffectorResourceTest.java
This fixes the test which had been marked as WIP in two other PRs.
This closes #1274.
This closes #1240.
=> fix intermittent failing test

api/src/main/java/org/apache/brooklyn/api/objs/EntityAdjunct.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/DynamicMultiGroupYamlRebindTest.java, core/src/main/java/org/apache/brooklyn/core/entity/AbstractEntity.java, core/src/main/java/org/apache/brooklyn/core/entity/Entities.java, core/src/main/java/org/apache/brooklyn/core/entity/EntityAdjuncts.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/AsyncCollectionChangeAdapter.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/CollectionChangeListener.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/EntityManagementSupport.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/LocalEntityManager.java, core/src/main/java/org/apache/brooklyn/core/mgmt/persist/BrooklynMementoPersisterToObjectStore.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/PeriodicDeltaChangeListener.java, core/src/main/java/org/apache/brooklyn/core/objs/proxy/InternalEntityFactory.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicGroupImpl.java, core/src/main/java/org/apache/brooklyn/util/core/json/BidiSerialization.java
Build on #1307, fixing the races that could cause persistence files for unmanaged items.  Expands test to cover enrichers also.  Several routes identified and fixed, plus better warnings, per the individual commits.
=> Fix persistence deletion race

core/src/main/java/org/apache/brooklyn/core/mgmt/internal/BrooklynGarbageCollector.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/EntityResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/transform/TaskTransformer.java
take at least 1 task with each unique name, and the "best" / most recent -- this will ensure 'start' shows up if it is still in memory (unless there are 200+ tasks of different names, which is unusual), instead of showing 20+ other tasks with the same name
=> better "interesting task" analysis for API when working with limits

core/src/main/java/org/apache/brooklyn/core/entity/AbstractEntity.java, core/src/main/java/org/apache/brooklyn/core/entity/EntityPredicates.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicGroup.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicGroupImpl.java, core/src/main/java/org/apache/brooklyn/util/core/predicates/DslPredicates.java, core/src/test/java/org/apache/brooklyn/util/core/predicates/DslPredicateEntityTest.java
All `dynamicgroup.ancestor` to point to an entity (or a different application) to restrict what entities are permitted to join the group.
Tested with `brooklyn-terraform` to restrict discovery in our group to a specific terraform configuration `efs-tier-tf`, as follows:
```
- id: efs-tier-tf
item:
type: terraform
name: EFS+VM (TF)
location: localhost
tf.configuration.url: classpath://updating-web-with-efs-efs-volume.zip
tf_var.name: amp-alex-2
tf_var.ami: ami-0fe9b2de9ff3caeb2   # 2021-10
brooklyn.initializers:
- type: terraform-drift-compliance-check
terraform.resources-drift.enabled: true
- id: efs-tier
iconUrl: classpath://efs.png
item:
name: Shared Storage (EFS)
services:
- type: efs-tier-tf
id: efs-tier-tf
- type: …
```
=> Dynamic group ancestor

core/src/main/java/org/apache/brooklyn/util/core/internal/ssh/ShellAbstractTool.java, core/src/main/java/org/apache/brooklyn/util/core/internal/ssh/sshj/SshjTool.java, core/src/test/java/org/apache/brooklyn/util/core/internal/ssh/sshj/SshjToolIntegrationTest.java, utils/common/src/main/java/org/apache/brooklyn/util/exceptions/Exceptions.java
sshj clears the interrupted flag and hides the interruption exception inside a ConnectException;
now we look inside it
this also causes Thread.currentThread().interrupt() to be set when we propagate InterruptedException;
previously it was not
=> better check for thread interruption with sshj connections

api/src/main/java/org/apache/brooklyn/api/objs/EntityAdjunct.java, api/src/main/java/org/apache/brooklyn/api/sensor/Feed.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/SshCommandSensorYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/DslPredicateYamlTest.java, core/src/main/java/org/apache/brooklyn/core/feed/AbstractFeed.java, core/src/main/java/org/apache/brooklyn/core/feed/PollConfig.java, core/src/main/java/org/apache/brooklyn/core/feed/Poller.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/EntityManagementSupport.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/BasicEntityRebindSupport.java, core/src/main/java/org/apache/brooklyn/core/sensor/AbstractAddTriggerableSensor.java, core/src/main/java/org/apache/brooklyn/core/sensor/http/HttpRequestSensor.java, core/src/main/java/org/apache/brooklyn/core/sensor/ssh/SshCommandSensor.java, core/src/main/java/org/apache/brooklyn/entity/group/GroupsChangePolicy.java, core/src/main/java/org/apache/brooklyn/feed/AbstractCommandFeed.java, core/src/main/java/org/apache/brooklyn/feed/function/FunctionFeed.java, core/src/main/java/org/apache/brooklyn/feed/http/HttpFeed.java, core/src/main/java/org/apache/brooklyn/feed/shell/ShellFeed.java, core/src/main/java/org/apache/brooklyn/util/core/predicates/DslPredicates.java, core/src/test/java/org/apache/brooklyn/core/test/entity/TestEntity.java, core/src/test/java/org/apache/brooklyn/util/core/predicates/DslPredicateEntityTest.java, core/src/test/java/org/apache/brooklyn/util/core/predicates/DslPredicateTest.java, policy/src/main/java/org/apache/brooklyn/policy/enricher/HttpLatencyDetector.java, software/base/src/main/java/org/apache/brooklyn/entity/brooklynnode/BrooklynEntityMirrorImpl.java, software/base/src/main/java/org/apache/brooklyn/feed/jmx/JmxFeed.java, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/ContainerSensor.java, software/winrm/src/main/java/org/apache/brooklyn/core/sensor/windows/WinRmCommandSensor.java, software/winrm/src/main/java/org/apache/brooklyn/feed/windows/WindowsPerformanceCounterFeed.java, utils/common/src/main/java/org/apache/brooklyn/util/time/Duration.java
Add 'jsonpath` and key/index accessors for predicates.  Replace unflattened behaviour with `has-element`.
Most feeds now support conditions.  Initial execution logic improved (to run after entity starts, so it isn't denied due to failed `isManagedActive` check), with special handling for those which require service up to automatically subscribe to it.
=> Predicates & feeds improvements

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ConfigParametersYamlTest.java, core/src/main/java/org/apache/brooklyn/core/config/ConfigConstraints.java, core/src/test/java/org/apache/brooklyn/core/config/ConfigKeyConstraintTest.java
This skips the validation of the property if no constratint is present
that has 'required' word or 'Predicates.notNull()', when the property
value is null.
=> Skip property validation against the constraint if property is null

core/src/main/java/org/apache/brooklyn/core/entity/trait/StartableMethods.java, core/src/main/java/org/apache/brooklyn/core/workflow/steps/CustomWorkflowStep.java, core/src/main/java/org/apache/brooklyn/core/workflow/steps/appmodel/ClearSensorWorkflowStep.java, core/src/main/java/org/apache/brooklyn/core/workflow/steps/appmodel/SetSensorWorkflowStep.java, core/src/main/java/org/apache/brooklyn/entity/stock/AbstractStartableImpl.java, core/src/main/java/org/apache/brooklyn/entity/stock/BasicStartable.java, core/src/main/java/org/apache/brooklyn/entity/stock/BasicStartableImpl.java, core/src/main/java/org/apache/brooklyn/entity/stock/WorkflowStartable.java, core/src/main/java/org/apache/brooklyn/entity/stock/WorkflowStartableImpl.java, core/src/test/java/org/apache/brooklyn/core/workflow/WorkflowBeefyStepTest.java, core/src/test/java/org/apache/brooklyn/entity/stock/WorkflowStartableTest.java, karaf/init/src/main/resources/catalog.bom, software/base/src/main/java/org/apache/brooklyn/entity/software/base/WorkflowSoftwareProcess.java, utils/common/src/main/java/org/apache/brooklyn/util/text/StringEscapes.java, utils/common/src/test/java/org/apache/brooklyn/util/text/StringEscapesTest.java
Add a `workflow-entity` where `start` / `stop` are defined by workflow.
Also allow `set-sensor service.problems['key'] = "value"` syntax, and same for `clear-sensor`, to allow updating map entries.
=> Workflow startable, and map sensor key access

api/src/main/java/org/apache/brooklyn/api/mgmt/classloading/BrooklynClassLoadingContext.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogMakeOsgiBundleTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogOsgiVersionMoreEntityTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogOsgiYamlLocationTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogScanOsgiTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/NestedRefsCatalogYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/test/lite/CampYamlLiteTest.java, camp/camp-brooklyn/src/test/resources/nested-refs-catalog-yaml-test-2.bom.yaml, camp/camp-brooklyn/src/test/resources/nested-refs-catalog-yaml-test-3.bom.yaml, core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, core/src/main/java/org/apache/brooklyn/core/mgmt/classloading/BrooklynClassLoadingContextSequential.java, core/src/main/java/org/apache/brooklyn/core/mgmt/classloading/JavaBrooklynClassLoadingContext.java, core/src/main/java/org/apache/brooklyn/core/mgmt/classloading/OsgiBrooklynClassLoadingContext.java, core/src/main/java/org/apache/brooklyn/core/resolve/entity/CatalogEntitySpecResolver.java, core/src/main/java/org/apache/brooklyn/core/resolve/jackson/BrooklynRegisteredTypeJacksonSerialization.java, core/src/main/java/org/apache/brooklyn/core/typereg/BasicBrooklynTypeRegistry.java, core/src/main/java/org/apache/brooklyn/core/typereg/RegisteredTypes.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/BundleAndTypeResourcesTest.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/CatalogResourceTest.java, utils/rt-felix/src/test/java/org/apache/brooklyn/rt/felix/EmbeddedFelixFrameworkTest.java
prefer local bundle then libraries when resolving entity references in a definition.
previously this was done in some places, esp for resources, but missed a lot of places where would be needed for entities or bean types.
two key changes to allow this:
* item libraries now explicitly includes its containing bundle
* catalog validateResolve is now able to switch the kind if that is determined as appropriate once all peers are loaded
=> Use libraries as search path more

core/src/main/java/org/apache/brooklyn/core/entity/Entities.java, core/src/main/java/org/apache/brooklyn/util/core/task/BasicTask.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindTestFixture.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/lifecycle/MachineLifecycleEffectorTasks.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessEntityTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessRebindNotRunningEntityTest.java
previously there was a window where a location instance might be removed from the parent before the provisioner releases it, and if the provisioner fails in that window the reference to the location is lost and cannot be subsequently deleted
=> don't remove the location from an entity on stop until it is confirmed released

core/src/main/java/org/apache/brooklyn/core/workflow/WorkflowSensor.java, core/src/test/java/org/apache/brooklyn/util/core/xstream/XmlSerializerTest.java
Removes final designation from WorkflowSensor allowing downstream projects to extend it. WorkflowPollCallable params are made visible to allow comparison of workflowsensors to determine if they've changed (e.g. for a diff)
=> Makes WorkflowSensor public and extensible

core/src/main/java/org/apache/brooklyn/core/workflow/WorkflowPolicy.java
Removes `final` designator from WorkflowPolicy to allow extension in downstream
=> Removes final from WorkflowPolicy

Jenkinsfile, pom.xml
Builds on #1384 to test Jenkins is working again after Apache INFRA reinstalling the pipeline-github plugin.
Merge #1384 in favour of this, unless you really want the comment about the plugin.
=> Mitigate CVE 2023 1370

utils/common/src/main/java/org/apache/brooklyn/util/time/Time.java
Problem with test and one of the assertions in a different timezone.
`Assert.assertEquals(Time.makeDateStampStringZ(instant), "20200101-1200Z");` - that is the problematic one - `Time.makeDateStampStringZ` as per its annotation should represent time in the UTC zone, however it calls `makeDateStampString` which uses `SimpleDateFormat` from `Date` which is aware of the timezone and uses default timezone, therefore returning time in current zone rather than UTC. Given the above, I have implemented another function `makeDateStampStringZ` that sets the timezone in SimpleDateFormat to be UTC which solves the issue  (in summary, we didn't set the UTC timezone where we expected to have it)
=> fix for the test failing in different timezone

core/src/main/java/org/apache/brooklyn/util/core/text/TemplateProcessor.java, core/src/test/java/org/apache/brooklyn/util/core/text/TemplateProcessorTest.java
Improves access to child entities in workflow allowing children to be accessed as ${entity.children[n]} in addition to the current syntax $brooklyn:child("id")
=> Workflow entity child and member access pt 184904864

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/WorkflowExpressionsYamlTest.java, core/src/main/java/org/apache/brooklyn/core/config/Sanitizer.java, core/src/main/java/org/apache/brooklyn/core/workflow/steps/variables/TransformVariableWorkflowStep.java, core/src/test/java/org/apache/brooklyn/core/resolve/jackson/BrooklynMiscJacksonSerializationTest.java, utils/common/src/main/java/org/apache/brooklyn/util/text/Secret.java, utils/common/src/test/java/org/apache/brooklyn/util/text/SecretTest.java
tostring and json serialization automatically suppress the payload; it is a `Supplier` so can be unwrapped where needed, including now in workflow with the `get` transform
cc @iuliana @jcabrerizo this can be used wherever we need extra assurance that credentials are not accidentally logged or shown in ui
=> add a Secret object which can be used to capture a secret

core/src/main/java/org/apache/brooklyn/core/workflow/steps/variables/SetVariableWorkflowStep.java, core/src/test/java/org/apache/brooklyn/core/workflow/WorkflowMapAndListTest.java, core/src/test/java/org/apache/brooklyn/core/workflow/WorkflowTransformTest.java
Adds ability to specify list index in workflows, e.g.:
```
let list mylist = [1, 2, 3]
let mylist[1] = 4",
return ${mylist[1]}
```
=> Implements list index specifiers for workflows

core/src/main/java/org/apache/brooklyn/core/config/Sanitizer.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/AbstractBrooklynRestResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/EntityResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/transform/TaskTransformer.java
It avoids to return the `task-summary` and the `output` of each step inside a workflow.
The automatic refresh of the view was pulling those, sometimes, huge objects few times per minute make the UI work slower than expected
=> Activities tab rest optimization

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/WorkflowExpressionsYamlTest.java, core/src/main/java/org/apache/brooklyn/core/sensor/DependentConfiguration.java, core/src/main/java/org/apache/brooklyn/util/core/text/TemplateProcessor.java
When calling attributeWhenReady using workflow syntax we should not abort when the entity is on fire.  This is different from what we do using DSL expressions.
This gives us more control in pure workflow based entities where we can choose how to respond to the entities status
=> Allow on fire in workflow expressions

core/src/main/java/org/apache/brooklyn/core/workflow/ShorthandProcessor.java, core/src/main/java/org/apache/brooklyn/core/workflow/ShorthandProcessorEpToQst.java, core/src/main/java/org/apache/brooklyn/core/workflow/ShorthandProcessorExprParser.java, core/src/main/java/org/apache/brooklyn/core/workflow/ShorthandProcessorQst.java, core/src/main/java/org/apache/brooklyn/core/workflow/WorkflowStepDefinition.java, core/src/main/java/org/apache/brooklyn/core/workflow/steps/appmodel/ClearSensorWorkflowStep.java, core/src/main/java/org/apache/brooklyn/core/workflow/steps/appmodel/SetConfigWorkflowStep.java, core/src/main/java/org/apache/brooklyn/core/workflow/steps/appmodel/SetSensorWorkflowStep.java, core/src/main/java/org/apache/brooklyn/core/workflow/steps/appmodel/UpdateChildrenWorkflowStep.java, core/src/main/java/org/apache/brooklyn/core/workflow/steps/variables/SetVariableWorkflowStep.java, core/src/main/java/org/apache/brooklyn/core/workflow/steps/variables/TransformReplace.java, core/src/main/java/org/apache/brooklyn/core/workflow/steps/variables/TransformSetWorkflowVariable.java, core/src/main/java/org/apache/brooklyn/core/workflow/steps/variables/TransformSplit.java, core/src/main/java/org/apache/brooklyn/core/workflow/steps/variables/TransformVariableWorkflowStep.java, core/src/main/java/org/apache/brooklyn/core/workflow/utils/ExpressionParser.java, core/src/main/java/org/apache/brooklyn/core/workflow/utils/ExpressionParserImpl.java, core/src/main/java/org/apache/brooklyn/core/workflow/utils/WorkflowSettingItemsUtils.java, core/src/test/java/org/apache/brooklyn/core/workflow/ExpressionParserTest.java, core/src/test/java/org/apache/brooklyn/core/workflow/ShorthandProcessorEpToQstTest.java, core/src/test/java/org/apache/brooklyn/core/workflow/ShorthandProcessorQstTest.java, core/src/test/java/org/apache/brooklyn/core/workflow/WorkflowMapAndListTest.java, core/src/test/java/org/apache/brooklyn/core/workflow/WorkflowNestedAndCustomExtensionTest.java, utils/common/src/main/java/org/apache/brooklyn/test/Asserts.java, utils/common/src/main/java/org/apache/brooklyn/util/guava/Maybe.java
Add an expression parser, and use it to improve shorthand parsing and workflow steps
`let x = ${"some long expression with spaces"}` no longer gets confused by the spaces inside the interpolated experssion
and you can do things like:
e.g. `set-sensor map_sensor["key value with space"] = xxx`
also brackets are now supported for config, map key support for `let`, and better atomicity guarantees for sensors, handling for lists (use `list_thing[] = ...` to add)
=> Expression parsing

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/filter/LoggingResourceFilter.java
If not available in the context
This fixes a minor issue where the username is logged at the start of a rest request but at the end often fails because it doesn't look it up using BrooklynSecurityProviderFilterHelper.
Per @ahgittin 's suggestion it also adds the username to the logging context.  This means we can log the username with any activities that don't create a task.  This PR https://github.com/apache/brooklyn-dist/pull/186 will modify the log to do this.
It doesn't look like there are any unit tests here so I've just tested locally using the basicauth security provider - I assume this will work with other security providers but I think this will be specific to the provider.  It should at least do the same in both places now.
=> Lookup user using BrooklynSecurityProviderFilterHelper

core/src/main/java/org/apache/brooklyn/core/resolve/jackson/BeanWithTypeUtils.java
Sanitizing BeanWithType exception message when conversion fails.
=> Sanitizing BeanWithType exception message
