launcher/src/test/java/org/apache/brooklyn/rest/jsgui/BrooklynJavascriptGuiLauncher.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/BrooklynRestApiLauncher.java
was assuming all dirs are checked out; now looks in classpath
=> fix failing test searching for jsgui

core/src/main/java/org/apache/brooklyn/core/location/LocationPropertiesFromBrooklynProperties.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsPropertiesFromBrooklynProperties.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsLocationResolverTest.java
including b.l.j.jclouds.xxx properties (which jclouds understands) and known multi-word
=> Improve how properties to pass to jclouds are selected

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ByonLocationsYamlTest.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsWinRmMachineLocation.java, logging/logback-includes/src/main/resources/brooklyn/logback-logger-excludes.xml, pom.xml, software/base/src/main/java/org/apache/brooklyn/entity/software/base/EmptyWindowsProcess.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/EmptyWindowsProcessWinRmDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/VanillaWindowsProcess.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/VanillaWindowsProcessImpl.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/VanillaWindowsProcessWinRmDriver.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/test/location/WinRmMachineLocationLiveTest.java, software/winrm/src/main/java/org/apache/brooklyn/location/winrm/AdvertiseWinrmLoginPolicy.java, software/winrm/src/main/java/org/apache/brooklyn/location/winrm/WinRmMachineLocation.java, software/winrm/src/main/java/org/apache/brooklyn/util/core/internal/winrm/WinRmTool.java, software/winrm/src/main/java/org/apache/brooklyn/util/core/internal/winrm/winrm4j/Winrm4jTool.java
- added config key for use Https or not
- added config key for using NTLM
- refactor WINRM_PORT usage
=> Upgrade winrm4j to version 0.3.1

camp/camp-server/pom.xml, camp/camp-server/src/main/java/org/apache/brooklyn/camp/server/dto/ApiErrorDto.java
The code is already refactored to use fasterxml jackson provider, remove leftover dependency.
Follow up to https://github.com/apache/brooklyn-server/pull/11.
=> Remove unused dependency

core/src/main/java/org/apache/brooklyn/location/ssh/SshMachineLocation.java, core/src/test/java/org/apache/brooklyn/core/entity/proxying/ApplicationBuilderOverridingTest.java, utils/common/src/main/java/org/apache/brooklyn/util/collections/MutableList.java, utils/common/src/main/java/org/apache/brooklyn/util/collections/MutableSet.java, utils/common/src/test/java/org/apache/brooklyn/util/collections/MutableListTest.java, utils/common/src/test/java/org/apache/brooklyn/util/collections/MutableSetTest.java
And a few other very minor additions.
=> Fix brooklyn-225

core/src/main/java/org/apache/brooklyn/util/core/config/ResolvingConfigBag.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java
- Adds ResolvingConfigBag, which resolves deferred-supplier on get()
- Use that in jcloudsLocation.getComputeService(ConfigBag)
=> Fix external-config for jclouds credentials

core/src/test/java/org/apache/brooklyn/util/core/text/TemplateProcessorTest.java
=> add template test for attributeWhenReady within memberSpec

api/src/main/java/org/apache/brooklyn/api/location/LocationRegistry.java, core/src/main/java/org/apache/brooklyn/core/location/BasicLocationRegistry.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/EffectorUtils.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicClusterImpl.java, core/src/test/java/org/apache/brooklyn/core/effector/EffectorBasicTest.java, core/src/test/java/org/apache/brooklyn/core/effector/EffectorSayHiTest.java, core/src/test/java/org/apache/brooklyn/core/entity/lifecycle/ServiceStateLogicTest.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocationConfig.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsLocationTest.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ApplicationResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/transform/TaskTransformer.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/lifecycle/ScriptHelper.java, utils/common/src/main/java/org/apache/brooklyn/test/Asserts.java, utils/common/src/main/java/org/apache/brooklyn/util/exceptions/CanSkipInContext.java, utils/common/src/main/java/org/apache/brooklyn/util/exceptions/Exceptions.java, utils/common/src/test/java/org/apache/brooklyn/util/exceptions/ExceptionsTest.java
rendering errors more helpfully, and waiting for app to be STARTING when deploying
=> Misc server changes for nicer UI experience

test-framework/src/main/java/org/apache/brooklyn/test/framework/InfrastructureDeploymentTestCase.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/InfrastructureDeploymentTestCaseImpl.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/InfrastructureDeploymentTestCaseTest.java
Modified InfrastructureDeploymentTestCase changing the testSpecs config to Startable rather than SoftwareProcess
=> InfrastructureDeploymentTestCase update

utils/jmx/jmxmp-ssl-agent/src/main/license/DISCLAIMER.shaded
Missed one file in my earlier attempt to clean up DISCLAIMERs.
=> Remove DISCLAIMER remnant

core/src/main/java/org/apache/brooklyn/core/entity/AbstractEntity.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicMultiGroupImpl.java, core/src/test/java/org/apache/brooklyn/entity/group/DynamicMultiGroupRebindTest.java, core/src/test/java/org/apache/brooklyn/entity/group/DynamicMultiGroupTest.java
The `isRebindComplete()` is really hacky, but not sure how better to do this - @ahgittin any advice?
I'd like to merge this PR asap to fix the problem, and then improve on the impl in subsequent PRs. Unless you think the code changes are dangerous!
=> Fix DynamicMultiGroup rebind

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java
Longer term, we should look at how better to configure a startup script. Different clouds within jclouds seem to use userMetadata in different ways, making our code fiddly.
Note this change isn't enough to get Windows@GCE working. We also need to write some code for generating + retrieving a Windows password. See https://cloud.google.com/compute/docs/instances/automate-pw-generation
If testing, the following location config is also important for users, to avoid jclouds waiting for port 22 to be reachable (and thus failing): `templateOptions: { autoCreateKeyPair: false }`
=> Windows @ GCE: exec startup script to enable WinRM

core/src/main/java/org/apache/brooklyn/core/BrooklynVersion.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ServerResource.java, rest/rest-resources/src/main/resources/OSGI-INF/blueprint/service.xml
* Use the correct json serializer
* Make version files accessible
* Fix collecting version info from bundles - array should be mutable
=> [OSGi] Improve REST API behaviour in Karaf

core/src/main/java/org/apache/brooklyn/core/mgmt/ShutdownHandler.java, core/src/main/resources/org/apache/brooklyn/core/mgmt/persist/deserializingClassRenames.properties, karaf/init/pom.xml, karaf/init/src/main/java/org/apache/brooklyn/launcher/osgi/OsgiLauncher.java, karaf/init/src/main/java/org/apache/brooklyn/launcher/osgi/OsgiShutdownHandler.java, karaf/init/src/main/resources/OSGI-INF/blueprint/blueprint.xml, karaf/pom.xml, launcher-common/src/main/java/org/apache/brooklyn/launcher/common/BasicLauncher.java, launcher/src/main/java/org/apache/brooklyn/launcher/BrooklynLauncher.java, launcher/src/main/java/org/apache/brooklyn/launcher/BrooklynWebServer.java, pom.xml, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ServerResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/util/ShutdownHandler.java, rest/rest-resources/src/main/resources/OSGI-INF/blueprint/service.xml, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/util/TestShutdownHandler.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/util/NoOpRecordingShutdownHandler.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/util/ServerStoppingShutdownHandler.java, server-cli/src/main/java/org/apache/brooklyn/cli/Main.java, utils/common/src/main/java/org/apache/brooklyn/util/javalang/Threads.java
Implement shutdown handler, call shutdown hooks at the appropriate time.
Depends on (but not based on):
* #55
* #65
* #66
=> [OSGi] Graceful shutdown

launcher/src/main/java/org/apache/brooklyn/launcher/BrooklynWebServer.java, launcher/src/test/java/org/apache/brooklyn/rest/jsgui/BrooklynJavascriptGuiLauncher.java, rest/rest-server-jersey/src/test/java/org/apache/brooklyn/rest/BrooklynRestApiLauncherTest.java, rest/rest-server-jersey/src/test/java/org/apache/brooklyn/rest/test/entity/brooklynnode/DeployBlueprintTest.java, rest/rest-server/src/main/java/org/apache/brooklyn/rest/NopSecurityHandler.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/BrooklynRestApiLauncher.java
Also skip security by default for tests
=> Fix noConsoleSecurity option

karaf/apache-brooklyn/src/main/resources/etc/org.ops4j.pax.url.mvn.repositories.cfg, karaf/features/src/main/feature/feature.xml
Build fails, trying to resolve the http url as a file system path.
=> Fix build on Windows

camp/camp-brooklyn/pom.xml, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/JcloudsRebindWithExternalConfigTest.java, core/src/main/java/org/apache/brooklyn/core/location/LocationConfigUtils.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/BasicLocationRebindSupport.java, core/src/main/java/org/apache/brooklyn/util/core/config/ResolvingConfigBag.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindTestFixture.java, core/src/test/java/org/apache/brooklyn/location/byon/ByonLocationResolverRebindTest.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/AbstractJcloudsLiveTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsRebindStubTest.java
See more detailed descriptions in each commit message.
=> Fix BROOKLYN-249

software/base/src/main/java/org/apache/brooklyn/entity/java/JmxAttributeSensor.java, software/base/src/test/java/org/apache/brooklyn/feed/jmx/JmxFeedTest.java
- fix bug where period was wrongly taken from entity config
- fix add feed to entity 
- add unit test
=> Fix JmxAttributeSensor

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/BrooklynImageChooser.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/AbstractJcloudsStubbedLiveTest.java
Replaces https://github.com/apache/brooklyn-server/pull/128, which was opened against 0.9.x branch (see discussion in there).
=> jclouds.ImageChooser configurable

karaf/apache-brooklyn/src/main/filtered-resources/etc/branding.properties, karaf/features/src/main/feature/feature.xml, rest/rest-server/src/main/webapp/WEB-INF/web.xml
doesn't solve anything, but opening this to track outstanding problems
=> a few more OSGi fixes

launcher/src/main/java/org/apache/brooklyn/launcher/BrooklynLauncher.java
Keeps backwards compatibility - using AnyoneSecurityProvider wouldn't force brooklyn server to bind to loopback only, but then changed to being treated same as noSecurityProvider. Revert to initial behaviour.
/cc @johnmccabe
=> Don't force binding to 127.0.0.1 when using AnyoneSecurityProvider

software/base/src/main/java/org/apache/brooklyn/entity/software/base/VanillaWindowsProcessWinRmDriver.java
Some Windows Blueprints require restart.
That's why for the isRunning check,
I catched WinRM IO Exceptions which could happen because of the restart.
=> Suppress exceptions in the isRunning check for Windows

core/src/main/java/org/apache/brooklyn/core/entity/AbstractEntity.java, core/src/main/java/org/apache/brooklyn/core/mgmt/BrooklynTags.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/LocalEntityManager.java, core/src/main/java/org/apache/brooklyn/core/objs/proxy/InternalEntityFactory.java, core/src/test/java/org/apache/brooklyn/core/location/LocationManagementTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/persist/BrooklynMementoPersisterTestFixture.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsLocationTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/test/location/SoftwareProcessLocationUnmanageTest.java
This PR replaces https://github.com/apache/brooklyn-server/pull/148
=> Test and fix locations not being unmanaged [updated #148]

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/ComputeServiceRegistryImpl.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsImageChoiceStubbedLiveTest.java
As discussed in https://github.com/apache/brooklyn-server/pull/115 (for BROOKLYN-286)...
I've confirmed that the live tests in `JcloudsImageChoiceStubbedLiveTest` work for me.
=> JcloudsLocation: handle config null values

core/src/main/java/org/apache/brooklyn/core/sensor/ssh/SshCommandSensor.java, core/src/main/java/org/apache/brooklyn/feed/ssh/SshFeed.java
Removes surrounding whitespace which makes further transformation simpler.
=> Add configuration option to SSH sensor to trim output

api/src/main/java/org/apache/brooklyn/api/effector/ParameterType.java, core/src/main/java/org/apache/brooklyn/core/effector/BasicParameterType.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/EffectorUtils.java, core/src/test/java/org/apache/brooklyn/core/mgmt/internal/TestEntityWithEffectors.java, core/src/test/java/org/apache/brooklyn/core/mgmt/internal/TestEntityWithEffectorsImpl.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/domain/EffectorSummary.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/EffectorResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/transform/EffectorTransformer.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/EffectorUtilsRestTest.java
For review.
@ygy can you check it?
=> Hide sensitive parameters from effectors

core/src/main/java/org/apache/brooklyn/enricher/stock/AbstractTransformer.java, core/src/test/java/org/apache/brooklyn/enricher/stock/TransformingEnricherTest.java
If set to true, then allows the transformer to read and publish on the 
same sensor. This is needed for some use-cases in 
brooklyncentral/advanced-networking.
=> Add AbstractTransformer.ALLOW_CYCLIC_PUBLISHING

core/src/main/java/org/apache/brooklyn/core/effector/MethodEffector.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/AbstractManagementContext.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/EffectorUtils.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/ManagementContextInternal.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/NonDeploymentManagementContext.java, core/src/test/java/org/apache/brooklyn/core/mgmt/internal/TestEntityWithEffectors.java, core/src/test/java/org/apache/brooklyn/core/mgmt/internal/TestEntityWithEffectorsImpl.java
It is possible to show such parameters on other places.
=> Sanitize effector parameters when reporting an exception

core/src/test/java/org/apache/brooklyn/util/core/internal/ssh/RecordingSshTool.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/TestFrameworkAssertions.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/TestSshCommandImpl.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/TestSshCommandIntegrationTest.java, utils/common/src/main/java/org/apache/brooklyn/util/time/Duration.java
`TestSshCommand` test repeatedly runs its command and assertions until either all the assertions pass or the configured timeout expires. Previously the class ran the command once and then ran all the assertions repeatedly until either they passed or the timeout expired.
=> Repeat ssh tests

policy/src/main/resources/catalog.bom
Extracted from https://github.com/apache/brooklyn-server/pull/231
=> Fix policy catalog.bom (for running in karaf)

core/src/main/java/org/apache/brooklyn/core/entity/EntityAsserts.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/TestSshCommandTest.java
I am using the same code in
https://github.com/apache/brooklyn-server/pull/211/files#diff-a1f3deedd5b53826884793055b989b87R96
=> Expose assertServiceFailed(Entity) and assertServiceHealthy(Entity)

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlEntityTest.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/AbstractManagementContext.java
In addition to any libraries provided by the catalog item.
We are actually assigning the wrong catalog item ID to the entity (should be the inner-most instead of the outer-most). That's more of a workaround, than fixing the root cause.
=> Use entity's classpath when loading resources

karaf/apache-brooklyn/src/main/resources/etc/org.ops4j.pax.logging.cfg, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsPropertiesFromBrooklynProperties.java
Updates org.ops4j.pax.logging.cfg to be configured similarly to the logback.xml configuration with regular launcher.
=> Update Karaf logging configuration.

test-framework/src/main/java/org/apache/brooklyn/test/framework/TestFrameworkAssertions.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/TestFrameworkAssertionsTest.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/TestSshCommandTest.java
* Adds a `notEqual` assert type
* Includes the actual state in assert failures
=> Improve test entity asserts (notEqual, actual state in failure)

core/src/main/java/org/apache/brooklyn/core/effector/ssh/SshCommandEffector.java, core/src/main/java/org/apache/brooklyn/core/sensor/ssh/SshCommandSensor.java
Means behaviour of sensors and effectors can be controlled with more granularity
=> Add shell.env config for SSH sensor and effector

utils/common/src/main/java/org/apache/brooklyn/util/ssh/BashCommands.java
Prevent race condition with multiple entities (for example children of a `SoftwareProcess` or `SameServerEntity`) that share the same configuration, and could try to make this change at the same time. Still not fully resilient in the face of bad timing, but better than before. Perhaps some kind of lock file could be created using `flock` at the start of the script?
=> Make dontRequireTtyForSudo idempotent

core/src/main/java/org/apache/brooklyn/core/feed/Poller.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindTestFixture.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindTestUtils.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessEntityFeedRebindTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessEntityRebindTest.java
Fixes https://issues.apache.org/jira/browse/BROOKLYN-322. See the description in that jira issue.
=> BROOKLYN-322: feeds don’t poll if entity unmanaged

utils/common/src/main/java/org/apache/brooklyn/util/ssh/BashCommands.java
Addesses [BROOKLYN-320](https://issues.apache.org/jira/browse/BROOKLYN-320) by upgrading NSS on yum based systems after the install of Java.
Tested on AWS Centos6
=> Upgrade NSS on yum based systems

core/src/test/java/org/apache/brooklyn/core/effector/EffectorBasicTest.java, core/src/test/java/org/apache/brooklyn/core/entity/trait/FailingEntityImpl.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/TestCase.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/TestCaseImpl.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/TestCaseTest.java, utils/common/src/main/java/org/apache/brooklyn/util/exceptions/Exceptions.java, utils/common/src/test/java/org/apache/brooklyn/util/exceptions/ExceptionsTest.java
Instantiates and executes this entity if there is an error while executing the test-cases.
=> Add TestCase.ON_ERROR_SPEC

karaf/features/src/main/feature/feature.xml, karaf/pom.xml
@neykov can you take a look please?
Useful for any downstream projects that depend on brooklyn-rest-client and that want to run in Karaf.
=> Adds brooklyn-rest-client feature

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ConfigParametersYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/SshCommandSensorYamlTest.java, core/src/main/java/org/apache/brooklyn/core/objs/BasicSpecParameter.java, core/src/test/java/org/apache/brooklyn/location/byon/FixedListMachineProvisioningLocationTest.java, core/src/test/java/org/apache/brooklyn/util/core/internal/ssh/ExecCmdAsserts.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/VanillaSoftwareProcessTest.java
Mostly improvements to tests (including failing tests for BROOKLYN-328 and BROOKLYN-329). See individual commits for explanation and details.
=> Various minor things

core/src/main/java/org/apache/brooklyn/util/core/BrooklynNetworkUtils.java, utils/common/src/main/java/org/apache/brooklyn/util/net/Networking.java, utils/common/src/main/java/org/apache/brooklyn/util/text/Strings.java, utils/common/src/test/java/org/apache/brooklyn/util/net/NetworkingUtilsTest.java, utils/common/src/test/java/org/apache/brooklyn/util/text/StringsTest.java
This contains the first commit of https://github.com/apache/brooklyn-server/pull/276 and https://github.com/apache/brooklyn-server/pull/292. It includes some minor improvements to the code and the tests.
I propose we merge this PR asap, then rebase those two other PRs against master.
=> Add BrooklynNetworkUtils.portRulesToRanges(Collection<String>)

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/networking/InboundPortsJcloudsLocationCustomizer.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/networking/NetworkingEffectors.java, software/base/pom.xml, software/base/src/main/java/org/apache/brooklyn/entity/software/base/SoftwareProcess.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/SoftwareProcessImpl.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/location/NetworkEffectorsEc2LiveTests.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/location/NetworkingEffectorsLiveTests.java
Caveat: the effector will return error when called before machine location is provisioned
=> Effector for opening inbound ports in security group

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/BrooklynDslCommon.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/DslComponent.java, core/src/main/java/org/apache/brooklyn/core/effector/ssh/SshCommandEffector.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/QueueingSubscriptionManager.java, core/src/main/java/org/apache/brooklyn/entity/group/SshCommandMembershipTrackingPolicy.java, core/src/main/java/org/apache/brooklyn/policy/InvokeEffectorOnSensorChange.java
These fixes make https://github.com/brooklyncentral/brooklyn-dns work neatly.
=> Invoke on sensor and ssh to multiple

core/src/main/java/org/apache/brooklyn/core/entity/AbstractEntity.java, core/src/test/java/org/apache/brooklyn/core/entity/EntityNameTest.java
@aledsage could you review it.
=> Do not inherit entity config defaultDisplayName

core/src/main/java/org/apache/brooklyn/core/config/ConfigUtils.java, core/src/main/java/org/apache/brooklyn/core/location/cloud/CloudLocationConfig.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsUtil.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsLocationReachabilityPredicateInstantiationTest.java, utils/common/src/main/java/org/apache/brooklyn/util/net/Networking.java, utils/common/src/main/java/org/apache/brooklyn/util/net/ReachableSocketFinder.java
Ability to supply external implementation for the socket tester predicate.
=> JcloudsLocation: Ability to supply external implementation for the socket

core/src/test/java/org/apache/brooklyn/util/core/text/TemplateProcessorTest.java
Only adds tests, so pretty trivial and safe to merge once jenkins confirms it works.
=> Add more tests to TemplateProcessorTest

api/src/main/java/org/apache/brooklyn/api/mgmt/classloading/BrooklynClassLoadingContext.java, api/src/main/java/org/apache/brooklyn/api/typereg/BrooklynTypeRegistry.java, api/src/main/java/org/apache/brooklyn/api/typereg/RegisteredType.java, core/src/main/java/org/apache/brooklyn/core/typereg/BasicBrooklynTypeRegistry.java, core/src/main/java/org/apache/brooklyn/core/typereg/BrooklynTypePlanTransformer.java, core/src/main/java/org/apache/brooklyn/core/typereg/RegisteredTypes.java, core/src/main/java/org/apache/brooklyn/core/typereg/TypePlanTransformers.java, core/src/test/java/org/apache/brooklyn/core/typereg/JavaClassNameTypePlanTransformerTest.java, utils/common/src/main/java/org/apache/brooklyn/test/Asserts.java, utils/common/src/main/java/org/apache/brooklyn/util/exceptions/Exceptions.java, utils/common/src/main/java/org/apache/brooklyn/util/guava/Maybe.java, utils/common/src/main/java/org/apache/brooklyn/util/javalang/ClassLoadingContext.java
I've been working on a new way of reading types from yaml -- PR coming in the next couple weeks -- but found these small improvements to the existing codebase which seemed appropriate and would be good to get in sooner.
=> Minor tweaks to utils and new TypeRegistry process

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/networking/SharedLocationSecurityGroupCustomizer.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/networking/SharedLocationSecurityGroupCustomizerTest.java
This flag allows the shared sg to be disabled in yaml
=> Add disable flag to shared sg customizer

locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsByonLocationResolverStubbedTest.java
Was taking a very long time, because trying to find a reachable address
=> Fix JcloudsByonLocationResolverStubbedTest

core/src/main/java/org/apache/brooklyn/core/entity/Attributes.java
Create 2 new sensors: `main.uri.mapped.public` and `main.uri.mapped.subnet`
=> Add more sensors for main.uri, based on the context, i.e public or not

core/src/main/java/org/apache/brooklyn/core/objs/AbstractConfigurationSupportInternal.java, core/src/main/java/org/apache/brooklyn/enricher/stock/Transformer.java, core/src/main/java/org/apache/brooklyn/util/core/task/ValueResolver.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsByonLocationResolverStubbedRebindTest.java
@neykov can you take a look please?
=> BROOKLYN-356: workaround, by increasing timeout

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ProxyEffectorYamlTest.java, core/src/main/java/org/apache/brooklyn/core/effector/ProxyEffector.java, core/src/main/java/org/apache/brooklyn/policy/InvokeEffectorOnSensorChange.java, core/src/test/java/org/apache/brooklyn/core/effector/ProxyEffectorTest.java
Forwards effector invocations from one entity to another.
=> ProxyEffector

core/src/main/java/org/apache/brooklyn/core/entity/EntityTypeSnapshot.java, core/src/main/java/org/apache/brooklyn/core/sensor/Sensors.java, core/src/main/java/org/apache/brooklyn/policy/InvokeEffectorOnCollectionSensorChange.java, core/src/test/java/org/apache/brooklyn/policy/InvokeEffectorOnCollectionSensorChangeRebindTest.java, core/src/test/java/org/apache/brooklyn/policy/InvokeEffectorOnCollectionSensorChangeTest.java
Tracks a collection and invokes effectors when elements are added and removed.
=> InvokeEffectorOnCollectionSensorChange

core/src/main/java/org/apache/brooklyn/core/entity/AbstractApplication.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicGroup.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicGroupImpl.java, core/src/main/java/org/apache/brooklyn/entity/stock/BasicStartableImpl.java, core/src/test/java/org/apache/brooklyn/entity/stock/BasicStartableTest.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessDriver.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessRestartIntegrationTest.java, utils/common/src/main/java/org/apache/brooklyn/test/Asserts.java, utils/common/src/main/java/org/apache/brooklyn/util/collections/QuorumCheck.java
Fixes a handful of surprising behaviours in AbstractApplication, DynamicGroup and BasicStartable.
=> Lifecycle fixes

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynYamlLocationResolver.java, core/src/main/java/org/apache/brooklyn/core/location/BasicLocationRegistry.java, core/src/main/java/org/apache/brooklyn/core/mgmt/classloading/BrooklynClassLoadingContextSequential.java, core/src/main/java/org/apache/brooklyn/core/mgmt/ha/OsgiManager.java, core/src/main/java/org/apache/brooklyn/core/resolve/entity/JavaEntitySpecResolver.java, core/src/main/java/org/apache/brooklyn/location/byon/HostLocationResolver.java, core/src/main/java/org/apache/brooklyn/location/byon/SingleMachineLocationResolver.java, software/base/src/test/java/org/apache/brooklyn/entity/chef/ChefLiveTestSupport.java, utils/common/src/main/java/org/apache/brooklyn/test/Asserts.java, utils/common/src/main/java/org/apache/brooklyn/util/ShellUtils.java, utils/common/src/main/java/org/apache/brooklyn/util/guava/Maybe.java, utils/common/src/main/java/org/apache/brooklyn/util/http/HttpTool.java, utils/common/src/main/java/org/apache/brooklyn/util/io/FilePermissions.java, utils/common/src/main/java/org/apache/brooklyn/util/net/ReachableSocketFinder.java, utils/common/src/main/java/org/apache/brooklyn/util/os/Os.java, utils/common/src/main/java/org/apache/brooklyn/util/repeat/Repeater.java, utils/common/src/main/java/org/apache/brooklyn/util/stream/InputStreamSupplier.java, utils/common/src/main/java/org/apache/brooklyn/util/text/Identifiers.java, utils/common/src/test/java/org/apache/brooklyn/util/collections/MutableSetTest.java, utils/common/src/test/java/org/apache/brooklyn/util/text/IdentifiersTest.java
tiny tidies to utils, including deprecation making `Maybe` a bit easier to work with in a couple places
=> Utils tidy

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/DslComponent.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/EnrichersYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/dsl/DslTest.java, core/src/main/java/org/apache/brooklyn/core/objs/AbstractConfigurationSupportInternal.java, utils/common/src/main/java/org/apache/brooklyn/util/guava/Maybe.java
This extracts part of https://github.com/apache/brooklyn-server/pull/408, adding an additional test.
=> transformer config uses brooklyn param defaults

parent/pom.xml
Add -XX:SoftRefLRUPolicyMSPerMB=1 to testing params, see https://github.com/apache/brooklyn-dist/pull/58
=> Adds SoftRefLRUPolicyMSPerMB

core/src/main/java/org/apache/brooklyn/entity/group/DynamicFabric.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicFabricImpl.java, core/src/test/java/org/apache/brooklyn/entity/group/DynamicRegionsFabricTest.java
And adds tests for existing behaviour.
=> BROOKLYN-380: Adds DynamicFabric.includeInitialChildren config

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ConfigNestedYamlTest.java, camp/camp-brooklyn/src/test/resources/org/apache/brooklyn/camp/brooklyn/config-nested-test.bom, camp/camp-brooklyn/src/test/resources/org/apache/brooklyn/camp/brooklyn/config-nested-test.yaml, core/src/main/java/org/apache/brooklyn/core/config/internal/AbstractConfigMapImpl.java
fixes subtle bug which prevents some evaluation strategies for map subkeys
=> Fix key lookup

launcher-common/src/main/java/org/apache/brooklyn/launcher/common/BasicLauncher.java
handy with the docker one-line deployer
=> Show info after application start

utils/common/src/test/java/org/apache/brooklyn/util/javalang/MemoryUsageTrackerTest.java
Motivated by discussion in https://github.com/apache/brooklyn-server/pull/412 with @neykov (cc @ahgittin).
=> Improve robustness of MemoryUsageTrackerTest

core/src/main/java/org/apache/brooklyn/entity/group/DynamicClusterImpl.java, utils/common/src/main/java/org/apache/brooklyn/util/guava/Suppliers.java, utils/common/src/test/java/org/apache/brooklyn/util/guava/SuppliersTest.java, utils/common/src/test/java/org/apache/brooklyn/util/pool/BasicPoolTest.java
A simple useful class. I have a pull request coming for brooklyn-library that makes proper use of this.
=> Add Suppliers.incrementingSupplier

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ReferencedYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlRebindTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/persist/XmlMementoSerializerDelegatingClassLoaderTest.java
Ignore tests relying on binary files in the source distribution.
=> Fix the Apache Brooklyn source release build

core/src/test/java/org/apache/brooklyn/core/mgmt/internal/EntityExecutionManagerTest.java
All tasks hit the listener, including tasks for starting the application
etc, so before this change the test logged errors as below. These fail the
assertion on the name, giving the messages below.
Change the test to avoid the assertion on name and to explicitly check for
the two tasks we want to find.
Note had to add the synchronization on 'completedTasks' as without it the
test would occasionally fail (~ one time in a dozen); as the state in the
exec thread wouldn't necessarily be propagated to the main thread without
synchronization.
2016-11-24 10:02:33,097 INFO  TESTNG INVOKING: "Surefire test" - org.apache.brooklyn.core.mgmt.internal.EntityExecutionManagerTest.testOnDoneCallback()
2016-11-24 10:02:33,099 INFO  TESTNG PASSED: "Surefire test" - …
=> Avoid uncaught exceptions in testOnDoneCallback

core/src/main/java/org/apache/brooklyn/location/ssh/SshMachineLocation.java, core/src/main/java/org/apache/brooklyn/util/core/task/system/internal/ExecWithLoggingHelpers.java, core/src/test/java/org/apache/brooklyn/location/ssh/SshMachineLocationIntegrationTest.java, core/src/test/java/org/apache/brooklyn/location/ssh/SshMachineLocationTest.java, test-support/src/main/java/org/apache/brooklyn/test/LogWatcher.java
First commit just tidies up tests (allowing more of them to run as unit tests).
Second commit actually changes non-test code.
=> BROOKLYN-405: ssh doesn't log password environment variables

utils/common/src/main/java/org/apache/brooklyn/util/internal/BrooklynSystemProperties.java, utils/common/src/main/java/org/apache/brooklyn/util/yaml/Yamls.java, utils/common/src/test/java/org/apache/brooklyn/util/yaml/YamlsTest.java
Overridable by setting a system property.
=> Use SnakeYAML SafeConstructor by default

core/pom.xml, core/src/main/java/org/apache/brooklyn/core/location/LocationConfigUtils.java, core/src/main/java/org/apache/brooklyn/util/core/crypto/FluentKeySigner.java, core/src/main/java/org/apache/brooklyn/util/core/crypto/SecureKeys.java, core/src/main/java/org/apache/brooklyn/util/core/internal/ssh/sshj/SshjTool.java, core/src/test/java/org/apache/brooklyn/util/core/internal/ssh/sshj/SshjToolIntegrationTest.java, locations/jclouds/pom.xml, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/templates/AbstractPortableTemplateBuilder.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/templates/PortableTemplateBuilder.java, locations/jclouds/src/test/java/org/apache/brooklyn/core/mgmt/persist/jclouds/BlobStoreExpiryTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/DelegatingComputeService.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsByonLocationResolverStubbedRebindTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsByonLocationResolverStubbedTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/StubbedComputeServiceRegistry.java, parent/pom.xml, pom.xml, utils/common/src/test/java/org/apache/brooklyn/util/osgi/OsgisTest.java
it is built on top of #409 
It uses jclouds-2.0.0-SNAPSHOT just to verify what needs to be changed in brooklyn-server.
I think it would be good to set up a jenkins job that builds this branch continuously, but I can't set it up myself at https://builds.apache.org/view/Brooklyn/
=> [NOT MERGE] Jclouds2.0.0 snapshot

core/pom.xml, core/src/main/java/org/apache/brooklyn/core/location/LocationConfigUtils.java, core/src/main/java/org/apache/brooklyn/util/core/crypto/FluentKeySigner.java, core/src/main/java/org/apache/brooklyn/util/core/crypto/SecureKeys.java, core/src/main/java/org/apache/brooklyn/util/core/internal/ssh/ShellAbstractTool.java, core/src/main/java/org/apache/brooklyn/util/core/internal/ssh/sshj/SshjTool.java, core/src/test/java/org/apache/brooklyn/util/core/internal/ssh/sshj/SshjToolIntegrationTest.java, karaf/features/src/main/feature/feature.xml, locations/jclouds/pom.xml, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/templates/AbstractPortableTemplateBuilder.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/templates/PortableTemplateBuilder.java, locations/jclouds/src/test/java/org/apache/brooklyn/core/mgmt/persist/jclouds/BlobStoreExpiryTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/DelegatingComputeService.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsByonLocationResolverStubbedRebindTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsByonLocationResolverStubbedTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsStubTemplateBuilder.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/StubbedComputeServiceRegistry.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/UnsupportedComputeService.java, logging/logback-includes/src/main/resources/brooklyn/logback-logger-excludes.xml, parent/pom.xml, pom.xml, utils/common/src/test/java/org/apache/brooklyn/util/osgi/OsgisTest.java
Built on top of @andreaturli 's #415 
Compile with jclouds 2.0.0
- tweak karaf dependencies [WIP]
- small changes to accommodate new signatures
- sshj package rename throughout
TODO: 
- Fix karaf dependencies
- Fix failing unit tests
=> [WIP] [NOT MERGE] Jclouds 2.0.0

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogOsgiVersionMoreEntityRebindTest.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/RebindIteration.java
Builds on https://github.com/apache/brooklyn-server/pull/489 - please review and merge that first; then I'll rebase (which will make the first commit disappear).
=> Fix BROOKLYN-410: rebind locations from bundles

software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessSshDriver.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/lifecycle/ScriptHelperIntegrationTest.java
=> Use SIGTERM in stop script inside AbstractSoftwareProcessSshDriver

utils/common/src/main/java/org/apache/brooklyn/util/math/BitUtils.java, utils/common/src/test/java/org/apache/brooklyn/util/math/BitUtilsTest.java
Couldn't help it. All tests still pass.
=> Simplify BitUtils methods

core/src/main/java/org/apache/brooklyn/core/effector/MethodEffector.java, core/src/main/java/org/apache/brooklyn/core/entity/EntityFunctions.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/EffectorUtils.java, core/src/main/java/org/apache/brooklyn/core/objs/AbstractEntityAdjunct.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicFabricImpl.java, core/src/main/java/org/apache/brooklyn/location/byon/FixedListMachineProvisioningLocation.java, core/src/main/java/org/apache/brooklyn/location/localhost/LocalhostMachineProvisioningLocation.java, core/src/main/java/org/apache/brooklyn/location/ssh/SshMachineLocation.java, core/src/main/java/org/apache/brooklyn/util/core/flags/FlagUtils.java, core/src/main/java/org/apache/brooklyn/util/core/internal/ssh/sshj/SshjClientConnection.java, core/src/main/java/org/apache/brooklyn/util/core/task/ScheduledTask.java, utils/common/src/main/java/org/apache/brooklyn/util/JavaGroovyEquivalents.java, utils/common/src/test/java/org/apache/brooklyn/util/JavaGroovyEquivalentsTest.java, utils/groovy/src/main/java/org/apache/brooklyn/util/groovy/FromRunnableClosure.java, utils/groovy/src/main/java/org/apache/brooklyn/util/groovy/GroovyJavaMethods.java, utils/groovy/src/test/java/org/apache/brooklyn/util/groovy/GroovJavaMethodsTest.java
- Optimize performance and avoid locks used in groovy dynamic invocation
Should fix BROOKLYN-424
=> Use stripped version of ScriptBytecodeAdapter.isCase

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java
Use `getCreationString` rather than `setup.getDescription` throughout `JcloudsLocation`. 
Fixes the annoying nulls in log messages when locations are provisioned:
```
2017-01-10 10:54:17,954 INFO  Creating VM null in JcloudsLocation[...]
2017-01-10 11:00:34,114 ERROR Failed to start VM for null;
```
etc.
See  8405d8774a0380a99b9dd1fbd2daf7fc15265cb8 for the introduction of `getCreationString`.
=> Fix logging of creation string in JcloudsLocation

core/src/main/resources/org/apache/brooklyn/core/mgmt/persist/deserializingClassRenames.properties, core/src/test/java/org/apache/brooklyn/core/mgmt/persist/DeserializingClassRenamesProviderTest.java
See https://github.com/brooklyncentral/advanced-networking/pull/116
=> Class renames for advanced-networking vcloud-director

api/src/main/java/org/apache/brooklyn/api/entity/EntitySpec.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/BasicSubscriptionContext.java, core/src/main/java/org/apache/brooklyn/core/sensor/ssh/SshCommandSensor.java, core/src/test/java/org/apache/brooklyn/util/core/internal/ssh/RecordingSshTool.java, launcher/src/main/java/org/apache/brooklyn/launcher/WebAppContextProvider.java, launcher/src/test/java/org/apache/brooklyn/launcher/BrooklynLauncherTest.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/BasicJcloudsLocationCustomizer.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/AbstractJcloudsStubbedUnitTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsLocationReachabilityPredicateInstantiationTest.java, rest/rest-server/src/main/java/org/apache/brooklyn/rest/filter/BrooklynPropertiesSecurityFilter.java, software/winrm/src/test/java/org/apache/brooklyn/util/core/internal/winrm/RecordingWinRmTool.java
A bunch of things I've found useful.
=> Misc improvements

utils/common/src/test/java/org/apache/brooklyn/util/net/ReachableSocketFinderTest.java
Tests sometimes failed on apache Jenkins, because 100ms wasn’t long 
enough for the other thread(s) to complete.
e.g. see https://builds.apache.org/job/brooklyn-master-build/org.apache.brooklyn$brooklyn-utils-common/758/testReport/junit/org.apache.brooklyn.util.net/ReachableSocketFinderTest/testGetReachableSockets/
```
2017-01-26 16:54:15,390 INFO  TESTNG INVOKING CONFIGURATION: "Surefire test" - @BeforeMethod org.apache.brooklyn.util.net.ReachableSocketFinderTest.setUp()
2017-01-26 16:54:15,390 INFO  TESTNG PASSED CONFIGURATION: "Surefire test" - @BeforeMethod org.apache.brooklyn.util.net.ReachableSocketFinderTest.setUp() finished in 0 ms
2017-01-26 16:54:15,390 INFO  TESTNG INVOKING: "Surefire test" - org.apache.brooklyn.util.net.ReachableSocketFinderTest.testGetReachableSockets() …
```
=> Fix ReachableSocketFinderTest (so not time-sensitive)

core/src/test/java/org/apache/brooklyn/entity/group/DynamicClusterTest.java
@drigodwin mentioned that DynamicCluster's memberIds seemed to keep incrementing up when a second cluster was provisioned (i.e. the second cluster didn't start counting at 0). This adds a test to assert we start counting from 0 from each new cluster.
=> Adds DynamicCluster.testClustersHaveIndependentCounters

core/src/main/java/org/apache/brooklyn/core/location/Machines.java, core/src/main/java/org/apache/brooklyn/util/core/json/MultimapSerializer.java, core/src/test/java/org/apache/brooklyn/core/location/MachinesTest.java, core/src/test/java/org/apache/brooklyn/util/core/json/MultimapSerializerTest.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/networking/SecurityGroupEditor.java
MultimapSerializer works with non-String keys
=> MultimapSerializer works with non-String keys

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ConfigParametersYamlTest.java, core/src/main/java/org/apache/brooklyn/core/objs/BasicSpecParameter.java
Docs PR will follow, to update the constraints section in https://github.com/apache/brooklyn-docs/blob/master/guide/yaml/yaml-reference.md
=> BROOKLYN-433: regex/obj config key constraint in yaml

rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/ActivityApi.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ActivityResource.java
=> Activity api include background

utils/common/src/main/java/org/apache/brooklyn/util/time/DurationPredicates.java, utils/common/src/test/java/org/apache/brooklyn/util/time/DurationPredicatesTest.java
Adds `DurationPredicates` which contains `Predicate`s for common `Duration` comparison operations.
=> Add DurationPredicates

core/src/main/java/org/apache/brooklyn/core/mgmt/usage/LocationUsage.java
i think we want to make sure a record is generated, even if it is incomplete
=> don't NPE fail is application is GC'd at same time as location

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/EffectorResource.java
=> Log User info on effector invocation via REST API

rest/rest-api/src/main/java/org/apache/brooklyn/rest/domain/ApiError.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ApplicationResource.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/ErrorResponseTest.java
populate error field of `ApiError`, and better logging on REST errors
=> Better error reporting

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/BrooklynDslCommon.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ObjectsYamlTest.java, core/src/main/java/org/apache/brooklyn/util/core/flags/TypeCoercions.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/TestHttpCall.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/TestHttpCallImpl.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/TestHttpCallTest.java, utils/common/src/main/java/org/apache/brooklyn/util/javalang/Reflections.java, utils/common/src/main/java/org/apache/brooklyn/util/javalang/coerce/CommonAdaptorTypeCoercions.java, utils/common/src/test/java/org/apache/brooklyn/util/javalang/ReflectionsTest.java, utils/common/src/test/java/org/apache/brooklyn/util/javalang/coerce/TypeCoercionsTest.java
A few conveniences to make it easier to write my yaml blueprints! See individual commits for details.
If anything in here looks controversial to you then please let me know, and I'll split things out into separate PRs.
=> Conveniences for yaml

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/CompositeEffectorYamlRebindTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/HttpCommandEffectorYamlRebindTest.java
See https://github.com/apache/brooklyn-server/pull/599
=> Make a couple more tests be integration tests.

core/src/main/java/org/apache/brooklyn/core/effector/http/HttpCommandEffector.java, core/src/test/java/org/apache/brooklyn/core/effector/http/HttpCommandEffectorIntegrationTest.java, core/src/test/java/org/apache/brooklyn/core/effector/http/HttpCommandEffectorTest.java
Also fixed integration tests that failing due to https://httpbin
=> HttpCommandEffector allows string payload

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/CompositeEffectorYamlRebindTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/CompositeEffectorYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/HttpCommandEffectorYamlRebindTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/HttpCommandEffectorYamlTest.java, core/src/main/resources/org/apache/brooklyn/location/geo/external-ip-address-resolvers.txt, core/src/test/java/org/apache/brooklyn/core/effector/http/HttpCommandEffectorHttpBinTest.java, policy/src/test/java/org/apache/brooklyn/policy/ha/ServiceReplacerTest.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/util/json/BrooklynJacksonSerializerIntegrationTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessEntityTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/lifecycle/ScriptHelperIntegrationTest.java, software/winrm/src/test/java/org/apache/brooklyn/feed/windows/WinRmFeedLiveTest.java
=> Various integration test fixes

core/src/test/java/org/apache/brooklyn/util/core/http/HttpToolSNITest.java
See https://issues.apache.org/jira/browse/BROOKLYN-456.
=> Add test illustrating SNI connection problem.

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/CatalogResource.java
remove use of printStackTrace()
=> Remove leftover debugging statement.

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocationResolver.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsPropertiesFromBrooklynProperties.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsLocationResolverTest.java
See https://issues.apache.org/jira/browse/BROOKLYN-491
=> BROOKLYN-491: fix named jcloudsLocation

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/HttpRequestSensorYamlTest.java, core/src/main/java/org/apache/brooklyn/core/sensor/http/HttpRequestSensor.java
This now also tests rebind (which I added, based on @sjcorbett's comment in https://issues.apache.org/jira/browse/BROOKLYN-330?focusedCommentId=15421279&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15421279)
=> BROOKLYN-330: enable test, and test rebind

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ReloadBrooklynPropertiesTest.java, core/src/main/java/org/apache/brooklyn/core/entity/AbstractApplication.java, core/src/main/java/org/apache/brooklyn/core/entity/lifecycle/ServiceStateLogic.java, core/src/main/java/org/apache/brooklyn/core/location/cloud/CloudLocationConfig.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicClusterImpl.java, core/src/main/java/org/apache/brooklyn/util/core/task/ValueResolver.java, core/src/test/java/org/apache/brooklyn/core/entity/AbstractApplicationLegacyTest.java, core/src/test/java/org/apache/brooklyn/core/entity/trait/FailingEntityImpl.java, core/src/test/java/org/apache/brooklyn/core/mgmt/internal/LocalManagementContextTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindLocationTest.java, core/src/test/java/org/apache/brooklyn/core/network/OnPublicNetworkEnricherTest.java, core/src/test/java/org/apache/brooklyn/entity/group/DynamicClusterTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/DefaultConnectivityResolverTest.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/BaseTest.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/TestSensorImpl.java, test-framework/src/main/java/org/apache/brooklyn/test/framework/TestWinrmCommandImpl.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/LoopOverGroupMembersTestCaseTest.java, test-framework/src/test/java/org/apache/brooklyn/test/framework/TestWinrmCommandTest.java, utils/common/src/main/java/org/apache/brooklyn/test/Asserts.java, utils/common/src/main/java/org/apache/brooklyn/util/repeat/Repeater.java, utils/common/src/test/java/org/apache/brooklyn/util/stream/StreamGobblerTest.java
Lots of little things to make tests run faster.
Builds on #649 (so we get decent test results) so it's only the last several commits which are relevant.  Will rebase once that is merged.
=> Test speedups

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlEntityTest.java
https://issues.apache.org/jira/browse/BROOKLYN-343
=> Add additional test case for BROOKLYN-343.

core/src/main/java/org/apache/brooklyn/core/entity/BrooklynConfigKeys.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessSshDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/EmptySoftwareProcessSshDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/SoftwareProcess.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/lifecycle/SoftwareProcessDriverCopyResourcesTest.java
As discussed on the mailing list [here](https://lists.apache.org/thread.html/ed50f697a75992f24eda24a5c9c409fd0d08358a8173e274c15b75d8@%3Cdev.brooklyn.apache.org%3E)
=> Add resource copy for customize phase

core/src/main/java/org/apache/brooklyn/core/enricher/AbstractEnricher.java, core/src/test/java/org/apache/brooklyn/core/entity/ApplicationLifecycleStateStressTest.java, core/src/test/java/org/apache/brooklyn/core/entity/ApplicationLifecycleStateTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindTestUtils.java, core/src/test/java/org/apache/brooklyn/policy/InvokeEffectorOnCollectionSensorChangeTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/VanillaSoftwareProcessAndChildrenIntegrationTest.java
Either fixes or marks integration tests as Broken so the CI integration test runs reliably.
=> Integration tests fixes

core/src/main/java/org/apache/brooklyn/core/entity/AbstractEntity.java, core/src/main/java/org/apache/brooklyn/core/sensor/AttributeMap.java, core/src/main/java/org/apache/brooklyn/entity/group/AbstractGroupImpl.java
and now preserve happens-before for child add-remove
see: https://issues.apache.org/jira/browse/BROOKLYN-498
=> define canonical synch order to fix potential deadlock

core/src/main/java/org/apache/brooklyn/core/mgmt/internal/AbstractManagementContext.java, core/src/test/java/org/apache/brooklyn/core/effector/MethodEffectorTest.java
See https://issues.apache.org/jira/browse/BROOKLYN-449
=> BROOKLYN-449 don't use groovy for effector method calls

locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/DefaultConnectivityResolverTest.java
Was failing on apache Jenkins sometimes, due to a 1ms timeout!
Increased this to 100ms, which still feels low (but unfortunately
The test will take a minimum of `Math.min(timeout, gracePeriod)`.
=> Fix non-deterministic DefaultCOnnectivityResolverTest

karaf/features/src/main/feature/feature.xml
- Added 'jclouds-loadbalancer' bundle to 'brooklyn-locations-jclouds' feature
=> Updated feature.xml to include `jclouds-loadbalancer`

karaf/features/src/main/feature/feature.xml, pom.xml
This reverts commit 1259e2832829d67148a42cbbb07400cc94a06587.
Apologies, I did not intend to merge this.
=> Revert "Upgrade to jclouds 2.1.0-SNAPSHOT"

locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/AbstractJcloudsStubbedUnitTest.java
This allows sub-classes to better override the config values
(the `jcloudsLocationConfig` can contain keys of type ConfigKey or String).
Also fixes the log.debug, to say what the default value is overridden with.
The motivator for this change is my use of it in a downstream project, which failed because the overrides weren't being applied (when passed in as string keys).
=> jclouds stub test: better allow config to be overridden

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AbstractWindowsYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/WindowsYamlLiveTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/WindowsYamlTest.java, software/winrm/src/test/java/org/apache/brooklyn/util/core/internal/winrm/ExecCmdAsserts.java
Note the `AbstractWindowsYamlTest` is a straightforward move of code from `WindowsYamlLiveTest`.
=> Adds WindowsYamlTest (unit test)

karaf/features/src/main/feature/feature.xml
Added missing GCE dependency to features and moved to load order. Tested deployment on GCE (which was previously not working).
=> Updated GCE features

core/src/main/java/org/apache/brooklyn/entity/group/DynamicFabric.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicFabricImpl.java, core/src/test/java/org/apache/brooklyn/entity/group/AbstractDynamicClusterOrFabricTest.java, core/src/test/java/org/apache/brooklyn/entity/group/DynamicClusterTest.java, core/src/test/java/org/apache/brooklyn/entity/group/DynamicFabricTest.java, core/src/test/java/org/apache/brooklyn/entity/group/DynamicRegionsFabricTest.java
Just like DynamicCluster does.
=> DynamicFabric: add support for firstMemberSpec

locations/container/src/test/resources/generic-application.tests.bom, locations/container/src/test/resources/generic.tests.bom
Added two boms that can be used to test endpoints
=> Added endpoint test boms

core/src/main/java/org/apache/brooklyn/util/core/config/ConfigBag.java
Small follow-up to https://github.com/apache/brooklyn-server/pull/734.
=> Remove a bit of code duplication.

core/src/main/java/org/apache/brooklyn/core/mgmt/EntityManagementUtils.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/IdAlreadyExistsException.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/LocalEntityManager.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/NonDeploymentEntityManager.java, core/src/main/java/org/apache/brooklyn/core/objs/proxy/InternalEntityFactory.java, core/src/test/java/org/apache/brooklyn/core/entity/proxying/EntityManagerTest.java, core/src/test/java/org/apache/brooklyn/core/entity/proxying/InternalEntityFactoryTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/osgi/OsgiVersionMoreEntityTest.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/ApplicationApi.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ApplicationResource.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/ApplicationResourceTest.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/testing/BrooklynRestResourceTest.java
For deploying an app with a pre-defined app-id. This feature is marked as beta.
This has been discussed extensively on the mailing list: https://lists.apache.org/thread.html/8eb58818d3ba50cfa5d5111363258cfe8529a76d17d45dc01823e0ba@%3Cdev.brooklyn.apache.org%3E
=> Adds `PUT /applications/{appid}`

core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/RebindIteration.java
This is so as to avoid the side effect of the "getCatalog()" in the
validate step, which does an unofficial catalog load that takes up
unnecessary time on startup.
=> Don't validate an empty list of types.

core/src/main/java/org/apache/brooklyn/core/mgmt/internal/EntityManagementSupport.java
Reverts #206 incorrectly merged
=> Reverts #206

karaf/pom.xml, launcher/src/test/java/org/apache/brooklyn/launcher/BrooklynWebServerTest.java, pom.xml, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/security/jaas/BrooklynLoginModule.java
* Jetty update to 9.3.14.v20161028
=> Updates karaf to 4.1.2

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/CampTypePlanTransformer.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlAppOsgiTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlAppTest.java, camp/camp-brooklyn/src/test/resources/org/apache/brooklyn/camp/brooklyn/catalog/template-and-app.bom, core/src/main/java/org/apache/brooklyn/core/typereg/AbstractTypePlanTransformer.java, core/src/main/java/org/apache/brooklyn/core/typereg/BasicBrooklynTypeRegistry.java, core/src/main/java/org/apache/brooklyn/core/typereg/ReferencedUnresolvedTypeException.java, core/src/main/java/org/apache/brooklyn/core/typereg/RegisteredTypes.java
Tests for and fixes a bug found with auto-wrapping BOMs being too strict on template resolution requirements.
=> Fix template forward reference

core/src/main/java/org/apache/brooklyn/core/mgmt/internal/AbstractManagementContext.java, karaf/features/src/main/feature/feature.xml, karaf/init/src/main/java/org/apache/brooklyn/launcher/osgi/OsgiLauncher.java, karaf/init/src/main/java/org/apache/brooklyn/launcher/osgi/OsgiLauncherImpl.java, karaf/init/src/main/resources/OSGI-INF/blueprint/blueprint.xml, karaf/pom.xml, karaf/start/pom.xml, karaf/start/src/main/java/org/apache/brooklyn/launcher/osgi/start/OsgiLauncherCompleter.java, karaf/start/src/main/resources/OSGI-INF/blueprint/blueprint.xml, launcher-common/src/main/java/org/apache/brooklyn/launcher/common/BasicLauncher.java
See https://issues.apache.org/jira/browse/BROOKLYN-532. This implements the last of the suggestions in https://issues.apache.org/jira/browse/BROOKLYN-532?focusedCommentId=16161370&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16161370
=> BROOKLYN-532: karaf separate mgmt init and start

core/src/main/java/org/apache/brooklyn/core/config/BasicConfigKey.java, core/src/main/java/org/apache/brooklyn/core/sensor/BasicAttributeSensor.java, core/src/main/java/org/apache/brooklyn/core/sensor/BasicSensor.java, core/src/main/java/org/apache/brooklyn/core/sensor/Sensors.java, test-support/src/main/java/org/apache/brooklyn/test/performance/PerformanceTestUtils.java, utils/common/src/main/java/org/apache/brooklyn/util/guava/TypeTokens.java, utils/common/src/main/java/org/apache/brooklyn/util/javalang/coerce/TypeCoercerExtensible.java
Minor things I noticed which were chewing up CPU and could be easily fixed
=> Optimizations

api/src/main/java/org/apache/brooklyn/api/typereg/RegisteredType.java, core/src/main/java/org/apache/brooklyn/core/typereg/BasicBrooklynTypeRegistry.java, core/src/main/java/org/apache/brooklyn/core/typereg/BasicTypeImplementationPlan.java, core/src/main/java/org/apache/brooklyn/core/typereg/RegisteredTypeLoadingContexts.java
Fixes https://issues.apache.org/jira/browse/BROOKLYN-537
=> BROOKLYN-537: fix NPE listing catalog items

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/JcloudsCustomizerInstantiationYamlDslTest.java, core/src/main/java/org/apache/brooklyn/core/objs/BasicConfigurableObject.java, core/src/main/java/org/apache/brooklyn/location/byon/FixedListMachineProvisioningLocation.java, core/src/test/java/org/apache/brooklyn/util/core/internal/ssh/RecordingSshTool.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/LocationCustomizerDelegate.java
Previously, DSL values passed to the location/machine customizers would not be resolved.
Also includes a couple of other tiny changes (see individual commits)!
=> Fix machine customizers

rest/rest-resources/src/main/resources/OSGI-INF/blueprint/service.xml, rest/rest-server/src/main/webapp/WEB-INF/web.xml
enable endpoint done for #821 for karaf
=> add adjunct endpoint to karaf config

api/src/main/java/org/apache/brooklyn/api/entity/Entity.java, api/src/main/java/org/apache/brooklyn/api/mgmt/ExecutionContext.java, api/src/main/java/org/apache/brooklyn/api/mgmt/ExecutionManager.java, core/src/main/java/org/apache/brooklyn/core/entity/AbstractEntity.java, core/src/main/java/org/apache/brooklyn/core/entity/EntityInternal.java, core/src/main/java/org/apache/brooklyn/core/mgmt/BrooklynTaskTags.java, core/src/main/java/org/apache/brooklyn/core/mgmt/ha/OsgiBundleInstallationResult.java, core/src/main/java/org/apache/brooklyn/core/objs/AbstractEntityAdjunct.java, core/src/main/java/org/apache/brooklyn/core/policy/Policies.java, core/src/main/java/org/apache/brooklyn/core/typereg/RegisteredTypePredicates.java, core/src/main/java/org/apache/brooklyn/core/typereg/RegisteredTypes.java, core/src/main/java/org/apache/brooklyn/util/core/task/BasicExecutionContext.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/CatalogApi.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/PolicyApi.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/PolicyConfigApi.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/domain/CatalogEnricherSummary.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/domain/CatalogEntitySummary.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/domain/CatalogItemSummary.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/domain/CatalogLocationSummary.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/domain/CatalogPolicySummary.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/domain/EnricherConfigSummary.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/domain/EntityConfigSummary.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/domain/LocationConfigSummary.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/domain/PolicyConfigSummary.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/domain/PolicySummary.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/transform/CatalogTransformer.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/transform/EntityTransformer.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/transform/PolicyTransformer.java, utils/common/src/main/java/org/apache/brooklyn/util/osgi/VersionedName.java
Version 0.13.0 will be 1.0.0 this PR updates those references.
=> Update 0.13.0 versions to 1.0.0

api/src/main/java/org/apache/brooklyn/api/mgmt/ha/HighAvailabilityManager.java, core/src/main/java/org/apache/brooklyn/core/mgmt/ha/HighAvailabilityManagerImpl.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/ManagementNodeStateListenerManager.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/NonDeploymentManagementContext.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindTestFixture.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindTestUtils.java, core/src/test/java/org/apache/brooklyn/core/mgmt/usage/ManagementNodeStateListenerTest.java, launcher-common/src/main/java/org/apache/brooklyn/launcher/common/BasicLauncher.java, launcher/src/test/java/org/apache/brooklyn/entity/brooklynnode/BrooklynEntityMirrorIntegrationTest.java, launcher/src/test/java/org/apache/brooklyn/launcher/BrooklynLauncherRebindManagementNodeStateListenerTest.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/testing/BrooklynRestApiTest.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/BrooklynRestApiLauncher.java, software/base/src/test/java/org/apache/brooklyn/entity/AbstractMultiDistroLiveTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessRebindNotRunningEntityTest.java
Wait for rebind to complete before notifying of ‘MASTER’. Otherwise if the listener does things like listing the apps, it might get back an empty list.
=> Fix ManagementNodeStateListener

core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogInitialization.java, core/src/main/java/org/apache/brooklyn/core/typereg/BundleUpgradeParser.java, core/src/test/java/org/apache/brooklyn/core/typereg/BundleUpgradeParserTest.java, utils/common/src/main/java/org/apache/brooklyn/util/text/Strings.java
Builds on #866 - closes it and adds a few tweaks.
=> Tweaks on 866

parent/pom.xml
=> update maven-bundle-plugin to include headers for catalog bundles rebind after upgrade

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsRebindStubUnitTest.java, locations/jclouds/src/test/resources/org/apache/brooklyn/location/jclouds/persisted-no-semaphores-stubbed-machine-l27nwbyisk, locations/jclouds/src/test/resources/org/apache/brooklyn/location/jclouds/persisted-no-semaphores-stubbed-parent-afy79330h5
Fixes https://issues.apache.org/jira/browse/BROOKLYN-554
=> BROOKLYN-554: fix jclouds loc upgrade+rebind

core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, core/src/main/java/org/apache/brooklyn/core/mgmt/BrooklynTaskTags.java, core/src/main/java/org/apache/brooklyn/core/sensor/DependentConfiguration.java, core/src/main/java/org/apache/brooklyn/core/typereg/ReferencedUnresolvedTypeException.java
discovered in testing and usage
=>  minor tidies for better logging and comments

core/src/main/java/org/apache/brooklyn/core/mgmt/ha/OsgiManager.java
Previously, if you tried to delete a bundle that was pre-installed in brooklyn karaf then the REST pai call would return a 500 response:
```
curl -v -X DELETE -u xxxxxxxx:xxxxxxxx http://localhost:8081/v1/catalog/bundles/org.example.my-pre-installed-bundle/1.0.0
```
gave the exception:
```
"No such bundle installed in OSGi when uninstalling: BasicManagedBundle{symbolicName=org.example.my-pre-installed-bundle, version=1.0.0, url=mvn:org.example/my-pre-installed-bundle/1.0.0}"...
```
e.g. to reproduce, try removing a bundle like `http://localhost:8081/v1/catalog/bundles/org.apache.brooklyn.software-database/1.0.0.SNAPSHOT`
This PR changes our bundle-lookup so that we don't just use the `bundleMetadata.getOsgiUniqueUrl()`, but instead use lookup by url etc (in the same way as we use …
=> Delete bundle: handle pre-installed karaf bundles

core/src/main/java/org/apache/brooklyn/core/feed/PollConfig.java, core/src/main/java/org/apache/brooklyn/enricher/stock/Transformer.java, core/src/main/java/org/apache/brooklyn/util/core/task/DynamicTasks.java, core/src/main/java/org/apache/brooklyn/util/core/task/TaskBuilder.java, core/src/main/java/org/apache/brooklyn/util/core/task/Tasks.java
A few misc cleanups - especially `Tasks.of(name, body)` to facilitate simple task creation.
=> Misc cleanups

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynComponentTemplateResolver.java
I believe this fixes the issue.
Glad to do a little Sunday hiking in Apache Brooklyn.
=> BROOKLYN-567 Prevent mutating EntitySpecSupplier's flag field

core/src/main/java/org/apache/brooklyn/enricher/stock/aggregator/AggregationJob.java, core/src/main/java/org/apache/brooklyn/enricher/stock/aggregator/DashboardAggregator.java, core/src/test/java/org/apache/brooklyn/enricher/stock/aggregator/AggregationJobTest.java
Added a DashboardAggregator. This aggregator will pull together dashboard sensors from it's children and merge them together. This however, does not touch the owner or environment sensors as there is no good way to aggregate them.
=> Added a DashboardAggregator

core/src/test/java/org/apache/brooklyn/entity/group/DynamicClusterWithAvailabilityZonesTest.java
Prior to @drigodwin's fix in https://github.com/apache/brooklyn-server/pull/919, this test would have failed. The child clusters are each passed a sub-location (i.e. a `SimulatedLocation`). However, because they also re-inherited the ENABLE_AVAILABILITY_ZONES=true, it tried to get the availability zone extension for the location it was given. This failed because `SimulatedLocation` does not have that extension.
With the fix in #919, the config key is not re-inherited, so the child `DynamicCluster`s do nottry to lookup the availability zone extension, and instead just create their children in the given location.
=> Adds test for enableAvailabilityZones not re-inherited

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/EntitiesYamlTest.java, core/src/main/java/org/apache/brooklyn/core/entity/AbstractEntity.java
Fixes https://issues.apache.org/jira/browse/BROOKLYN-570
=> BROOKLYN-570: fix entity synchronizing on self

test-framework/src/main/java/org/apache/brooklyn/test/framework/LoopOverGroupMembersTestCaseImpl.java
See https://issues.apache.org/jira/browse/BROOKLYN-574
=> BROOKLYN-574: wait for child running

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynEntityMatcher.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/BrooklynDslDeferredSupplier.java, core/src/main/java/org/apache/brooklyn/core/location/access/BrooklynAccessUtils.java, core/src/main/java/org/apache/brooklyn/core/objs/proxy/InternalLocationFactory.java
See https://issues.apache.org/jira/browse/BROOKLYN-576
=> BROOKLYN-576: decrease amount of debug logging

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JCloudsPropertiesBuilder.java
Motivated by experience with a large customer doing scalability testing, where they were rate limited a lot (despite having agreed in advance with AWS to increase their permitted limits). That customer had been using a bunch of overrides. However, such discussions highlighted the need for us to change the default behaviour in Brooklyn so that small/medium size users don't normally need to think about such things.
=> jclouds polling/backoff: increase delays

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/FunctionSensorYamlTest.java, core/src/main/java/org/apache/brooklyn/location/localhost/LocalhostMachineProvisioningLocation.java, core/src/test/java/org/apache/brooklyn/core/entity/lifecycle/ServiceStateLogicTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/SoftwareProcessEntityLatchTest.java, test-support/src/main/java/org/apache/brooklyn/test/LogWatcher.java
See individual commits for more information
=> Fix non-deterministic tests

api/src/main/java/org/apache/brooklyn/api/mgmt/rebind/RebindManager.java, core/src/main/java/org/apache/brooklyn/core/location/AbstractMachineLocation.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/NonDeploymentManagementContext.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/RebindManagerImpl.java, software/base/src/main/java/org/apache/brooklyn/entity/machine/MachineEntityImpl.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/SoftwareProcessImpl.java, software/base/src/test/java/org/apache/brooklyn/entity/machine/MachineEntityJcloudsRebindTest.java
Fixes https://issues.apache.org/jira/browse/BROOKLYN-580
=> BROOKLYN-580 rebind machine entity feeds

locations/jclouds/pom.xml, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/AbstractComputeServiceRegistry.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocationConfig.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/domain/JcloudsContext.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/suppliers/LinkContextSupplier.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsAddressesLiveTest.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsLocationResolverTest.java
- add support for user-defined Guice modules
- add support for ContextLinking
=> [BROOKLYN-584] Add support for recent jclouds's ContextLinking

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/SshCommandSensorYamlTest.java
See my comments in PR #953 
This now uses the `RecordingSshTool` to execute the ssh command sensor, so the test is quicker. If you run it 100 times, the first time still takes 2 seconds (presumably due to classloading etc), and then it takes about 200ms per test after that.
Also fixes the final assertion, that it is the `newValue` in the sensor.
=> SshCommandSensor.testDslWithSshSensor: convert to non-integration

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlEntityOsgiTypeRegistryTest.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/domain/ConfigSummary.java
it has been supported in code and in rest api, but not possible to set from `catalog.bom` -- this fixes that
=> allow tags to be set on catalog items

core/src/main/java/org/apache/brooklyn/core/mgmt/persist/BrooklynPersistenceUtils.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ServerResource.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/ServerResourceTest.java
Fixes https://issues.apache.org/jira/browse/BROOKLYN-594
=> BROOKLYN-594: fix REST api /v1/server/ha/persist/export

core/src/main/java/org/apache/brooklyn/core/entity/AbstractEntity.java, core/src/test/java/org/apache/brooklyn/core/mgmt/DeployFailureTest.java
Fixes https://issues.apache.org/jira/browse/BROOKLYN-599
=> BROOKLYN-599: fix getApplication()

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/BrooklynDslDeferredSupplier.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/DslComponent.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/DslYamlTest.java
As per the code comment, I broke this in https://github.com/apache/brooklyn-server/pull/971. This PR fixes it.
=> Fix DSL recursive-reference detection

pom.xml
no evidence these affect brooklyn but good to stay current
=> bump jetty version in response to recent CVE's

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/VanillaSoftwareProcessYamlTest.java, core/src/test/java/org/apache/brooklyn/core/mgmt/rebind/RebindHistoricSshCommandSensorTest.java, core/src/test/resources/org/apache/brooklyn/core/mgmt/rebind/ssh-command-sensor-feed-a9ekg3cnu0
fix one non-det test
and speed up a ssh feed test, from 5s to 20ms
=> minor simple test fixes/improvements

camp/camp-brooklyn/pom.xml, pom.xml
See individual commits (the first one just moves stuff around).
=> Pom tidy, and version upgrades

utils/common/src/main/java/org/apache/brooklyn/util/collections/CollectionMerger.java, utils/common/src/test/java/org/apache/brooklyn/util/collections/CollectionMergerTest.java
simple extension but useful when lists need special treatment cc @aledsage
=> improve CollectionMerger to take a configurable list merge function

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ConfigParametersYamlTest.java, core/src/main/java/org/apache/brooklyn/core/config/ConfigConstraints.java
Previously this caused the entity’s startup to hang.
=> Fix requiredUnless config key constraint, with attributeWhenReady

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/transform/TypeTransformer.java
this includes that in the payload if different
=> REST API includes icon url source

core/src/main/java/org/apache/brooklyn/util/core/xstream/XmlSerializer.java
Added default security config for Xstream deserialization.
=> Added default security config for XStream

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AbstractYamlTest.java, core/src/main/java/org/apache/brooklyn/core/config/ConfigConstraints.java, core/src/main/java/org/apache/brooklyn/core/mgmt/EntityManagementUtils.java, core/src/main/java/org/apache/brooklyn/core/objs/BasicSpecParameter.java, core/src/main/java/org/apache/brooklyn/core/objs/BrooklynObjectInternal.java, core/src/main/java/org/apache/brooklyn/util/core/flags/TypeCoercions.java, locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsTypeCoercions.java, utils/common/src/main/java/org/apache/brooklyn/util/javalang/coerce/CommonAdaptorTryCoercions.java, utils/common/src/main/java/org/apache/brooklyn/util/javalang/coerce/CommonAdaptorTypeCoercions.java, utils/common/src/main/java/org/apache/brooklyn/util/javalang/coerce/TypeCoercerExtensible.java, utils/common/src/test/java/org/apache/brooklyn/util/javalang/coerce/TypeCoercerExtensibleTest.java
and misc comments to clarify some immediate resolution semantics
=> allow the types of parameters to be extended programmatically

core/src/main/java/org/apache/brooklyn/core/mgmt/entitlement/Entitlements.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/AdjunctResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ApplicationResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/BundleResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/EntityResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/LocationResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/PolicyConfigResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/PolicyResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ScriptResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ServerResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/UsageResource.java
Added new more granulated entitlements applied on rest resources
=> Granularity entitlement control

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/util/MultiSessionAttributeAdapter.java
- This marks as used all the session with the same ID on the different session handlers
- Fix bug on the loop for setting and removing attributes on all session detected by Denis
=> Fix session error

pom.xml
Previous version had known vulnerability CVE-2019-12402
=> Bumps commons-compress version

pom.xml
=> For fixing some karaf startup slowness

karaf/features/src/main/feature/feature.xml, software/base/src/main/java/org/apache/brooklyn/feed/jmx/JmxHelper.java
Fix for https://issues.apache.org/jira/browse/BROOKLYN-626
=> BROOKLYN-626: fix jmxmp

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AbstractYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/ReferencedOsgiYamlTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogOsgiYamlEntityTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogOsgiYamlLocationTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogOsgiYamlPolicyTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogOsgiYamlTemplateTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlAppTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlCombiTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlEntityOsgiTypeRegistryTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlEntityTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlLocationTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlPolicyTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlTemplateTest.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java
Improve #1111 with one fix and one more test case
=> Better errors on bean transforms

api/src/main/java/org/apache/brooklyn/api/internal/AbstractBrooklynObjectSpec.java, api/src/main/java/org/apache/brooklyn/api/objs/BrooklynObject.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynComponentTemplateResolver.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/CampResolver.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogOsgiVersionMoreEntityRebindTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogOsgiYamlEntityTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlEntityOsgiTypeRegistryTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/catalog/CatalogYamlEntityTest.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogUtils.java, core/src/main/java/org/apache/brooklyn/core/entity/Dumper.java, core/src/main/java/org/apache/brooklyn/core/mgmt/EntityManagementUtils.java, core/src/main/java/org/apache/brooklyn/core/mgmt/rebind/RebindIteration.java, core/src/test/java/org/apache/brooklyn/core/mgmt/osgi/OsgiStandaloneTest.java
See first commit for the failing tests, then second commit for the fix and clarifications.
=> Improve search path logic for edge cases

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/BrooklynDslCommon.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogUtils.java, core/src/main/java/org/apache/brooklyn/core/mgmt/ha/BrooklynBomOsgiArchiveInstaller.java, core/src/main/java/org/apache/brooklyn/core/mgmt/ha/OsgiManager.java, core/src/main/java/org/apache/brooklyn/core/resolve/jackson/WrappedValue.java, core/src/main/java/org/apache/brooklyn/core/resolve/jackson/WrappedValuesSerialization.java, core/src/main/java/org/apache/brooklyn/core/typereg/AbstractCatalogBundleResolver.java, core/src/main/java/org/apache/brooklyn/core/typereg/BrooklynBomBundleCatalogBundleResolver.java, core/src/main/java/org/apache/brooklyn/core/typereg/BrooklynCatalogBundleResolver.java, core/src/main/java/org/apache/brooklyn/core/typereg/BrooklynCatalogBundleResolvers.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/CatalogResourceTest.java, utils/common/src/main/java/org/apache/brooklyn/util/os/Os.java, utils/common/src/main/java/org/apache/brooklyn/util/text/WildcardGlobs.java
Introduces scoring conventions to reduce noise and to pick the best error(s)
=> Better error reporting for bad bundles, and fix some minor serialization errors revealed

camp/camp-base/src/main/java/org/apache/brooklyn/camp/BasicCampPlatform.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogInitialization.java, karaf/init/src/main/java/org/apache/brooklyn/launcher/osgi/OsgiLauncherImpl.java, utils/common/src/main/java/org/apache/brooklyn/util/osgi/OsgiActivator.java
More details will be in a docs PR which will come shortly and be advertised here
=> Option to delay catalog initialization / rebind until after required OSGi services are available

core/src/main/java/org/apache/brooklyn/core/location/BasicLocationRegistry.java
using osgi ServiceListener -- previously it loaded it once so wouldn't find things added after it was initialized
=> allow location registry to listen for resolvers

core/src/test/java/org/apache/brooklyn/util/core/task/ValueResolverTest.java
Wait until the result is present before continuing with test.
Signed-off-by: Andrew Donald Kennedy <andrew.international@gmail.com>
=> Fix race in testUnsubmittedTaskWithExecutionContextTimesOutWhenImmediate

api/src/main/java/org/apache/brooklyn/api/catalog/BrooklynCatalog.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynAssemblyTemplateInstantiator.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynEntityDecorationResolver.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynYamlTypeInstantiator.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/CampResolver.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/BrooklynDslCommon.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogBundleLoader.java, core/src/main/java/org/apache/brooklyn/core/location/BasicLocationRegistry.java, core/src/main/java/org/apache/brooklyn/core/plan/PlanToSpecFactory.java, core/src/main/java/org/apache/brooklyn/core/resolve/entity/DelegatingEntitySpecResolver.java, core/src/main/java/org/apache/brooklyn/core/typereg/AbstractTypePlanTransformer.java, core/src/main/java/org/apache/brooklyn/core/typereg/BasicBrooklynTypeRegistry.java, core/src/main/java/org/apache/brooklyn/core/typereg/RegisteredTypes.java, core/src/main/java/org/apache/brooklyn/core/typereg/TypePlanTransformers.java, core/src/main/java/org/apache/brooklyn/util/core/flags/BrooklynTypeNameResolution.java, utils/common/src/main/java/org/apache/brooklyn/util/javalang/coerce/TypeCoercerExtensible.java, utils/common/src/main/java/org/apache/brooklyn/util/text/Strings.java, utils/rt-felix/src/main/java/org/apache/brooklyn/rt/felix/EmbeddedFelixFramework.java, utils/test-support/src/main/resources/logback-test.xml
suppress benign warnings and debug messages, esp when guessing the resolved type; add debug logging for what is being analyzed; more coercion flexibility and logback customization
=> improve logging esp around catalog initialization and bundle load

core/src/main/java/org/apache/brooklyn/core/BrooklynFeatureEnablement.java, core/src/main/java/org/apache/brooklyn/core/entity/AbstractEntity.java, core/src/test/java/org/apache/brooklyn/core/entity/OwnedChildrenDeprecatedTest.java
this seems to work surprisingly nicely (through groovy scripting)
=> allow programmatic reparenting

core/src/main/java/org/apache/brooklyn/core/config/external/PropertiesFileExternalConfigSupplier.java, core/src/main/java/org/apache/brooklyn/core/config/external/UrlsExternalConfigSupplier.java, core/src/test/java/org/apache/brooklyn/core/config/external/PropertiesFileExternalConfigSupplierTest.java
for consistency ... java by default seems to fail on "file:///path/to/x" :(
=> use our routines for urls in PropertiesFileExternalConfigSupplier

core/src/main/java/org/apache/brooklyn/core/config/external/vault/VaultExternalConfigSupplier.java
Tested with Vault version 1.6.0.
Note: please see corresponding documentation updates: https://github.com/apache/brooklyn-docs/pull/313
=> Support newer versions of Hashicorp Vault

rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/ApplicationApi.java, rest/rest-resources/pom.xml, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ApplicationResource.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/ApplicationResourceTest.java
Fix the bug introduced by #1137
=> Fix /v1/applications REST endpoints

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/WindowsYamlLiveTest.java, core/src/main/java/org/apache/brooklyn/core/typereg/TypePlanTransformers.java, core/src/main/java/org/apache/brooklyn/util/core/task/ssh/internal/AbstractSshExecTaskFactory.java, core/src/main/java/org/apache/brooklyn/util/core/task/system/ProcessTaskWrapper.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/AbstractSoftwareProcessWinRmDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/lifecycle/WinRmExecuteHelper.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/test/location/WindowsTestFixture.java, software/winrm/src/main/java/org/apache/brooklyn/location/winrm/PlainWinRmExecTaskFactory.java, software/winrm/src/main/java/org/apache/brooklyn/util/core/internal/winrm/winrm4j/ErrorXmlWriter.java, software/winrm/src/main/java/org/apache/brooklyn/util/core/internal/winrm/winrm4j/FilteringXmlWriter.java, software/winrm/src/main/java/org/apache/brooklyn/util/core/internal/winrm/winrm4j/Winrm4jTool.java, software/winrm/src/test/java/org/apache/brooklyn/util/core/internal/winrm/winrm4j/ErrorXmlWriterTest.java, utils/common/src/main/java/org/apache/brooklyn/util/text/Strings.java
… and an exhaustive "xml" error stream
needs testing and want to make other streams available but for early review
=> split actual winrm "stderr" (xml) into a filtered "stderr" stream

rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/ApplicationApi.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/BundleApi.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/CatalogApi.java
Signed-off-by: Andrew Donald Kennedy <andrew.kennedy@cloudsoftcorp.com>
=> Set return type for deprecated CatalogApi methods

camp/camp-server/src/main/java/org/apache/brooklyn/camp/server/RestApiSetup.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ApidocResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/util/ScannerInjectHelper.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/ApidocResourceTest.java, rest/rest-server/src/main/java/org/apache/brooklyn/rest/RestApiSetup.java, utils/rest-swagger/src/main/java/org/apache/brooklyn/rest/apidoc/RestApiResourceScanner.java
so add'l projects can add classes to be documented
=> make swagger classes extensible

pom.xml
Detected with snyk:
https://snyk.io/vuln/SNYK-JAVA-ORGFREEMARKER-1076795
=> Bumping org.freemaker due a high severity vulnerability

core/src/main/java/org/apache/brooklyn/core/catalog/internal/BasicBrooklynCatalog.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/BundleApi.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/BundleResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/TypeResource.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/transform/TypeTransformer.java
support icons for type within a given bundle, and prefer icon set in the item over one inherited
=> for icons, support referencing the bundle and the type name not just the type name

core/src/main/java/org/apache/brooklyn/core/objs/BasicSpecParameter.java
=> Added comment to explain immutable log and demoted it to trace

core/src/main/java/org/apache/brooklyn/core/resolve/jackson/BrooklynJacksonSerializationUtils.java
makes it easier to track down the root cause
=> include deserialization trace when hitting deserialization problems

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/filter/BrooklynSecurityProviderFilterHelper.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/filter/BrooklynSecurityProviderFilterJavax.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/filter/BrooklynSecurityProviderFilterJersey.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/security/provider/LdapSecurityProvider.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/util/MultiSessionAttributeAdapter.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/security/provider/LdapSecurityProviderTest.java
This is a set of, what I hope are, improvements around using ldap / a domain controller for sign on.  It provides a login page, rather than the basic auth log in popup, handles multiple ldap realms, and fixes some odd issues in how we handle username/password based authentication.
=> Ldap login improvements

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/transform/TypeTransformer.java
Added code and explanatory comments.
=> Fixed implementation to re-order spec tag values

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/filter/BrooklynSecurityProviderFilterJavax.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/filter/BrooklynSecurityProviderFilterJersey.java
Logout was not redirecting correctly.  This adds a header to the
login form to the 401 api response so that it can be a) ignored by the
cli and b) followed by the UI.
=> Fix login form

core/src/main/java/org/apache/brooklyn/core/mgmt/entitlement/Entitlements.java, core/src/main/java/org/apache/brooklyn/util/core/logbook/DelegatingLogStore.java, core/src/main/java/org/apache/brooklyn/util/core/logbook/file/FileLogStore.java, core/src/test/java/org/apache/brooklyn/core/mgmt/entitlement/EntitlementsTest.java, core/src/test/java/org/apache/brooklyn/util/core/logbook/file/FileLogStoreTest.java, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/LogbookApi.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/LogbookResource.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/LogbookResourceTest.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/testing/BrooklynRestApiTest.java, rest/rest-resources/src/test/resources/logbook.test.log
Signed-off-by: Mykola Mandra <mykola.mandra@cloudsoftcorp.com>
=> Couple of unit-tests for the logbook resource and tidy up

core/src/main/java/org/apache/brooklyn/util/core/logbook/LogBookQueryParams.java, core/src/main/java/org/apache/brooklyn/util/core/logbook/file/FileLogStore.java, core/src/main/java/org/apache/brooklyn/util/core/logbook/opensearch/OpenSearchLogStore.java, core/src/test/java/org/apache/brooklyn/util/core/logbook/file/FileLogStoreTest.java, core/src/test/java/org/apache/brooklyn/util/core/logbook/opensearch/OpenSearchLogStoreTest.java, core/src/test/resources/brooklyn/util/core/logbook/file/log-sample.txt
Signed-off-by: Mykola Mandra <mykola.mandra@cloudsoftcorp.com>
=> Add search by phrase, use better parameter names; more unit-tests

core/src/main/java/org/apache/brooklyn/core/mgmt/ha/HighAvailabilityManagerImpl.java
=> Solved reference being discarded and not used issue

core/src/main/java/org/apache/brooklyn/util/core/logbook/LogBookQueryParams.java, core/src/main/java/org/apache/brooklyn/util/core/logbook/LogStore.java, core/src/main/java/org/apache/brooklyn/util/core/logbook/file/FileLogStore.java, core/src/main/java/org/apache/brooklyn/util/core/logbook/opensearch/OpenSearchLogStore.java, core/src/test/java/org/apache/brooklyn/util/core/logbook/file/FileLogStoreTest.java, core/src/test/java/org/apache/brooklyn/util/core/logbook/opensearch/OpenSearchLogStoreTest.java
=> Support logbook multi-phrase query

rest/rest-api/pom.xml, rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/ApplicationApi.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ApplicationResource.java, rest/rest-server/src/test/java/org/apache/brooklyn/rest/api/ApplicationApiTest.java
Specifically if posting a multipart form with %s then we would get an
error.
=> Fix disallowed characters in multipart form

pom.xml
Bumps vulnerable dependencies identified using snyk.io
=> Bumping vulnerable dependencies 

core/src/main/java/org/apache/brooklyn/util/core/task/system/internal/AbstractProcessTaskFactory.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/lifecycle/ScriptHelper.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/VanillaSoftwareProcessStreamsIntegrationTest.java, software/base/src/test/java/org/apache/brooklyn/entity/software/base/VanillaSoftwareProcessStreamsTest.java, software/winrm/src/main/java/org/apache/brooklyn/location/winrm/WinRmPutTaskStub.java
=> Found more ssh/scp mentions and removed them. 

core/src/main/java/org/apache/brooklyn/core/BrooklynLogging.java, core/src/main/java/org/apache/brooklyn/core/config/Sanitizer.java, core/src/main/java/org/apache/brooklyn/core/mgmt/BrooklynTaskTags.java, software/winrm/src/main/java/org/apache/brooklyn/location/winrm/WinRmMachineLocation.java
Adds to the debug log the WinRM `stdin`, `stdout`, `winrm` and `stderr` streams
=> Logging WinRm streams

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/transform/TaskTransformer.java
=> Encode stream type in the link as UTF-8

software/base/src/main/java/org/apache/brooklyn/feed/jmx/JmxHelper.java
Added references for this change
=> Added references for this change

karaf/features/src/main/feature/feature.xml, software/base/src/main/java/org/apache/brooklyn/feed/jmx/JmxHelper.java
Reverts apache/brooklyn-server#1097
=> Revert "BROOKLYN-626: fix jmxmp"

rest/rest-resources/src/main/java/org/apache/brooklyn/rest/filter/BrooklynSecurityProviderFilterHelper.java
=> allow static content if login form being used

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/AppGroupTraverser.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/BrooklynDslCommon.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/DslComponent.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/AppGroupTraverserTest.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/DslYamlTest.java
prefer those:
- crossing fewer application boundaries
- closer
=> be smarter about picking which component is referenced by DSL

utils/common/src/main/java/org/apache/brooklyn/util/ssh/BashCommands.java
Added method to use curl with a minimum TLS version specified as argument.
=> Added method to use curl with a minimum TLS version specified as

core/src/main/java/org/apache/brooklyn/entity/group/GroupsChangePolicy.java
Otherwise initializer config initialized against group not member
=> Use raw config for initializers

core/src/main/java/org/apache/brooklyn/core/location/Locations.java, locations/container/src/main/java/org/apache/brooklyn/container/entity/helm/HelmEntity.java, locations/container/src/main/java/org/apache/brooklyn/container/entity/helm/HelmEntityImpl.java, locations/container/src/main/java/org/apache/brooklyn/container/location/kubernetes/KubernetesLocation.java, locations/container/src/main/java/org/apache/brooklyn/container/location/openshift/OpenShiftLocation.java, pom.xml
Change to latest fabric8.io version and make `KubernetesLocation#getClient()` public
=> Update Kubernetes client

core/src/main/java/org/apache/brooklyn/core/effector/http/HttpCommandEffector.java, core/src/main/java/org/apache/brooklyn/core/sensor/DurationSinceSensor.java, core/src/main/java/org/apache/brooklyn/core/sensor/function/FunctionSensor.java, core/src/main/java/org/apache/brooklyn/core/sensor/http/HttpRequestSensor.java, core/src/main/java/org/apache/brooklyn/core/sensor/password/CreatePasswordSensor.java, core/src/main/java/org/apache/brooklyn/entity/group/GroupsChangePolicy.java, core/src/main/resources/catalog.bom, core/src/test/java/org/apache/brooklyn/core/test/BrooklynAppLiveTestSupport.java, core/src/test/java/org/apache/brooklyn/entity/group/GroupsChangePolicyTest.java, software/base/src/main/java/org/apache/brooklyn/entity/java/JmxAttributeSensor.java
In order to add initialisers to the catalog I've had to make them non-final and add public no-arg constructors.
=> Add useful initialisers to the catalog

rest/rest-api/src/main/java/org/apache/brooklyn/rest/api/ServerApi.java, rest/rest-resources/src/main/java/org/apache/brooklyn/rest/resources/ServerResource.java
=> Require Entitlements.HA_ADMIN for HA clear requests; tidy up

locations/jclouds/src/main/java/org/apache/brooklyn/location/jclouds/JcloudsLocation.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/JcloudsStubTemplateBuilder.java, locations/jclouds/src/test/java/org/apache/brooklyn/location/jclouds/provider/AwsEc2LocationLiveTest.java
Update to #1276 (see for more details)
=> Pragmatic fix for AWS default hardware image

core/src/main/java/org/apache/brooklyn/policy/InvokeEffectorOnSensorChange.java, core/src/test/java/org/apache/brooklyn/policy/InvokeEffectorOnSensorChangeIntegrationTest.java
=> Allow effector-on-sensor-change subscribing to any entity

core/src/main/java/org/apache/brooklyn/enricher/stock/PropagateToMembers.java, core/src/main/resources/catalog.bom, core/src/test/java/org/apache/brooklyn/enricher/stock/PropagateToMembersTest.java
=> New enricher PropagateToMembers

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/creation/BrooklynComponentTemplateResolver.java, core/src/main/java/org/apache/brooklyn/core/mgmt/persist/RetryingMementoSerializer.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicMultiGroupImpl.java, core/src/main/java/org/apache/brooklyn/util/core/xstream/MutableListConverter.java, core/src/main/java/org/apache/brooklyn/util/core/xstream/MutableSetConverter.java, core/src/main/java/org/apache/brooklyn/util/core/xstream/StringKeyMapConverter.java, core/src/main/java/org/apache/brooklyn/util/core/xstream/XmlSerializer.java, core/src/test/java/org/apache/brooklyn/core/mgmt/internal/EntityExecutionManagerTest.java, core/src/test/java/org/apache/brooklyn/util/core/xstream/XmlSerializerTest.java, policy/src/main/java/org/apache/brooklyn/policy/failover/ElectPrimaryPolicy.java
Reduce ConcurrentMod conflicts in persistence, nicer log when it does happen; clean up persistence of lists, supporting rebind to previous. Fix a few more guava maps that don't serialize nicely.
=> Misc logging and serialize improvements

utils/common/src/main/java/org/apache/brooklyn/util/stream/StreamGobbler.java, utils/common/src/test/java/org/apache/brooklyn/util/stream/StreamGobblerTest.java
=> Support UTF sequences in stream gobbler

Jenkinsfile
=> WIP: Fix docker image tag to match '^[a-zA-Z0-9_]([a-zA-Z0-9_.-]){0,127}'

Jenkinsfile
=> Print DOCKER_TAG as sh step

Jenkinsfile
=> Print dockerTag Jenkins var in echo step

core/src/main/java/org/apache/brooklyn/core/sensor/ssh/SshCommandSensor.java, core/src/test/java/org/apache/brooklyn/core/sensor/ssh/SshCommandSensorIntegrationTest.java, core/src/test/resources/ssh-command-sensor-command.sh
=> Support remote command via 'commandUrl' in SshCommandSensor

core/src/main/java/org/apache/brooklyn/core/catalog/internal/CatalogClasspathDo.java, core/src/main/java/org/apache/brooklyn/core/mgmt/ha/BrooklynBomOsgiArchiveInstaller.java, core/src/main/java/org/apache/brooklyn/core/typereg/AbstractCatalogBundleResolver.java, core/src/main/java/org/apache/brooklyn/core/typereg/BrooklynBomBundleCatalogBundleResolver.java, core/src/main/java/org/apache/brooklyn/core/typereg/BrooklynBomYamlCatalogBundleResolver.java, core/src/main/java/org/apache/brooklyn/core/typereg/BrooklynCatalogBundleResolvers.java, core/src/main/java/org/apache/brooklyn/util/core/file/ArchiveBuilder.java, core/src/main/java/org/apache/brooklyn/util/core/file/ArchiveUtils.java, software/base/src/main/java/org/apache/brooklyn/entity/brooklynnode/BrooklynNodeSshDriver.java, software/base/src/main/java/org/apache/brooklyn/entity/java/VanillaJavaAppSshDriver.java
catches leaks to /tmp file system if AMP is long-running or killed non-cleanly
=> fix most reliances on deleteOnExit, deleting when done with the file

utils/common/src/test/java/org/apache/brooklyn/util/io/FileUtilTest.java
Signed-off-by: Andrew Donald Kennedy <andrew.international@gmail.com>
=> Use toURI on resource URLs to fix Windows path issues

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/AbstractJcloudsStubYamlTest.java, camp/camp-brooklyn/src/test/resources/vanilla-bash-netcat-w-client-and-effector-ui.yaml, camp/camp-brooklyn/src/test/resources/vanilla-bash-netcat-w-client.yaml, core/src/main/java/org/apache/brooklyn/core/mgmt/BrooklynTaskTags.java, rest/rest-resources/src/test/java/org/apache/brooklyn/rest/resources/ActivityRestTest.java
=> include effector params in the tag on tasks, as returned by REST API

software/base/README.adoc, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/ContainerCommons.java, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/ContainerTaskFactory.java, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/JobBuilder.java, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/PullPolicy.java, software/base/src/test/java/org/apache/brooklyn/tasks/kubectl/DockerEffectorTest.java, software/base/src/test/java/org/apache/brooklyn/tasks/kubectl/DockerSensorTest.java, software/base/src/test/java/org/apache/brooklyn/tasks/kubectl/DockerTaskTest.java, software/base/src/test/java/org/apache/brooklyn/tasks/kubectl/JobBuilderTest.java, software/base/src/test/resources/org/apache/brooklyn/kubectl/sample-both.yaml, software/base/src/test/resources/org/apache/brooklyn/kubectl/sample-effector.yaml
=> Added support for pull policy and docs

software/base/README.adoc, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/ContainerEffector.java, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/ContainerSensor.java, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/ContainerTaskFactory.java, software/base/src/main/resources/catalog.bom, software/base/src/test/java/org/apache/brooklyn/tasks/kubectl/ContainerEffectorTest.java, software/base/src/test/java/org/apache/brooklyn/tasks/kubectl/ContainerSensorTest.java, software/base/src/test/java/org/apache/brooklyn/tasks/kubectl/ContainerTaskTest.java, software/base/src/test/resources/org/apache/brooklyn/kubectl/sample-both.yaml, software/base/src/test/resources/org/apache/brooklyn/kubectl/sample-effector-dev.yaml, software/base/src/test/resources/org/apache/brooklyn/kubectl/sample-effector.yaml, software/base/src/test/resources/org/apache/brooklyn/kubectl/sample-sensor.yaml
=> Renamed all classes and references from Docker to Container

software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/ContainerCommons.java, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/ContainerTaskFactory.java
=> Add kubectl job completion timeout config

core/src/main/java/org/apache/brooklyn/core/objs/ConstraintSerialization.java, core/src/test/java/org/apache/brooklyn/core/objs/ConstraintSerializationTest.java
=> Support arrays in string constraint parser

core/pom.xml, karaf/features/src/main/feature/feature.xml, pom.xml
Fix issues SSH'ing to recent OSs
=> Bump SSHJ versions

core/src/main/java/org/apache/brooklyn/core/effector/ssh/SshEffectorTasks.java, core/src/main/java/org/apache/brooklyn/util/core/task/system/internal/SystemProcessTaskFactory.java, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/ContainerCommons.java, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/ContainerEffector.java, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/ContainerSensor.java, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/ContainerTaskFactory.java, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/KubeJobFileCreator.java, software/base/src/test/java/org/apache/brooklyn/tasks/kubectl/ContainerEffectorTest.java, software/base/src/test/java/org/apache/brooklyn/tasks/kubectl/ContainerSensorTest.java, software/base/src/test/java/org/apache/brooklyn/tasks/kubectl/ContainerTaskTest.java, software/base/src/test/java/org/apache/brooklyn/tasks/kubectl/KubeJobSpecCreatorTest.java
* to track output, gather exit code, and clearer semantics
* also fix dirty detection across all processes
=> rejig container task

core/src/main/java/org/apache/brooklyn/util/core/internal/ssh/sshj/SshjTool.java, core/src/test/java/org/apache/brooklyn/util/core/internal/ssh/sshj/SshjToolIntegrationTest.java, utils/common/src/main/java/org/apache/brooklyn/util/exceptions/Exceptions.java
=> catch other case where interrupt might be swallowed

camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/AppGroupTraverser.java, camp/camp-brooklyn/src/main/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/methods/DslComponent.java, camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/spi/dsl/AppGroupTraverserTest.java, core/src/main/java/org/apache/brooklyn/core/feed/AbstractFeed.java, core/src/main/java/org/apache/brooklyn/core/feed/AttributePollHandler.java, core/src/main/java/org/apache/brooklyn/core/feed/PollConfig.java, core/src/main/java/org/apache/brooklyn/core/feed/Poller.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/AppGroupTraverser.java, core/src/main/java/org/apache/brooklyn/core/mgmt/internal/BrooklynGarbageCollector.java, core/src/main/java/org/apache/brooklyn/core/sensor/AbstractAddSensorFeed.java, core/src/main/java/org/apache/brooklyn/core/sensor/AbstractAddTriggerableSensor.java, core/src/main/java/org/apache/brooklyn/core/sensor/http/HttpRequestSensor.java, core/src/main/java/org/apache/brooklyn/core/sensor/ssh/SshCommandSensor.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicClusterImpl.java, core/src/main/java/org/apache/brooklyn/entity/group/DynamicMultiGroupImpl.java, core/src/main/java/org/apache/brooklyn/feed/AbstractCommandFeed.java, core/src/main/java/org/apache/brooklyn/feed/function/FunctionFeed.java, core/src/main/java/org/apache/brooklyn/feed/function/FunctionPollConfig.java, core/src/main/java/org/apache/brooklyn/feed/http/HttpFeed.java, core/src/main/java/org/apache/brooklyn/util/core/task/BasicExecutionManager.java, core/src/main/java/org/apache/brooklyn/util/core/task/Tasks.java, software/base/src/main/java/org/apache/brooklyn/entity/software/base/SoftwareProcessImpl.java, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/ContainerCommons.java, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/ContainerSensor.java, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/ContainerTaskFactory.java, software/base/src/test/java/org/apache/brooklyn/tasks/kubectl/ContainerSensorTest.java, software/winrm/src/main/java/org/apache/brooklyn/core/sensor/windows/WinRmCommandSensor.java
Allow common feeds, including containers, to be triggered (like enrichers) rather than only periodic.
Also improve display names of fields, unique tags, container task transience, and task GC.
=> Triggerable feeds, container and presentational improvements

core/src/main/java/org/apache/brooklyn/core/sensor/ssh/SshCommandSensor.java, core/src/main/java/org/apache/brooklyn/entity/group/GroupsChangePolicy.java, core/src/main/java/org/apache/brooklyn/feed/AbstractCommandFeed.java, core/src/main/java/org/apache/brooklyn/feed/ssh/SshFeed.java, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/ContainerTaskFactory.java, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/ContainerTaskResult.java, software/winrm/src/main/java/org/apache/brooklyn/feed/windows/CmdFeed.java
improve use of commandUrl with ssh-command-sensor
=> Tidy sensor feeds

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/WorkflowYamlTest.java, core/src/main/java/org/apache/brooklyn/core/workflow/steps/LogWorkflowStep.java, core/src/test/java/org/apache/brooklyn/core/workflow/WorkflowBasicTest.java
=> Workflow step to log messages

software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/ContainerTaskFactory.java, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/ContainerWorkflowStep.java
=> Added arguments splitting using QuotedStringTokenizer

core/src/main/java/org/apache/brooklyn/util/core/json/ConfigurableSerializerProvider.java, pom.xml, software/base/src/main/java/org/apache/brooklyn/tasks/kubectl/KubeJobFileCreator.java, utils/common/src/main/java/org/apache/brooklyn/util/yaml/Yamls.java, utils/common/src/test/java/org/apache/brooklyn/util/yaml/YamlsTest.java
same for jackson and cxf to use latest snakeyaml
=> update snakeyaml to latest version

DEPENDENCIES, server-cli/DEPENDENCIES
Updated licences ahead of release
=> Updated licenses

camp/camp-brooklyn/src/test/java/org/apache/brooklyn/camp/brooklyn/test/policy/failover/ElectPrimaryTest.java, core/src/main/java/org/apache/brooklyn/core/sensor/DependentConfiguration.java, utils/common/src/main/java/org/apache/brooklyn/util/time/Duration.java, utils/common/src/main/java/org/apache/brooklyn/util/time/Time.java, utils/common/src/test/java/org/apache/brooklyn/util/time/DurationTest.java
which could cause timeout forever to become timeout immediately
=> Fix Duration maths
